"use strict";
const crypto = require("crypto"); const { loadOperationsConfig } = require("./config"); const { createServiceRegistry } = require("./registry"); const { OperationsState } = require("./state"); const { OperationsAudit } = require("./audit"); const { LocalServiceAdapter } = require("./services/adapter"); const { HealthService } = require("./health"); const { recentLogs } = require("./monitoring/logs"); const { planOperation } = require("./planner"); const { BackupManager } = require("./backups/manager"); const { LocalDeploymentAdapter } = require("./deployment/local"); const { createRecoveryPolicies } = require("./recovery/policies");
function confirmationNeeded(plan, config) { return plan.risk === "CRITICAL" || plan.risk === "HIGH" && config.requireHighConfirmation; }
class CardinalOperationsService {
    constructor(options = {}) { this.config = loadOperationsConfig(options); this.registry = options.registry || createServiceRegistry(this.config.root, options.services); this.state = options.state || new OperationsState(this.config.statePath); this.audit = options.audit || new OperationsAudit(this.config.auditPath); this.adapters = options.adapters || Object.fromEntries(Object.entries(this.registry).map(([id, service]) => [id, new LocalServiceAdapter(service)])); this.database = options.database || require("../../packages/database"); this.health = options.health || new HealthService({ root: this.config.root, registry: this.registry, adapters: this.adapters, database: this.database }); this.authorize = options.authorize || (async () => true); this.developerStore = options.developerStore; this.git = options.git; this.backups = options.backups || new BackupManager({ config: this.config, state: this.state }); this.deployment = options.deployment || (this.git ? new LocalDeploymentAdapter({ git: this.git }) : null); this.reindex = options.reindex || null; this.policies = createRecoveryPolicies(this.registry); }
    plan(message) { return planOperation(message); }
    async systemStatus(actor) { await this.authorize(actor, "CARDINAL_OPS_READ"); return this.health.all(); }
    async serviceStatus(actor, id) { await this.authorize(actor, "CARDINAL_OPS_READ"); return this.health.service(id); }
    async logs(actor, id, lines) { await this.authorize(actor, "CARDINAL_OPS_READ"); this.assertService(id); return recentLogs(this.registry[id].logFile, lines); }
    async execute(actor, plan, options = {}) { const permission = { health: "CARDINAL_OPS_READ", logs: "CARDINAL_OPS_READ", start: "CARDINAL_OPS_RESTART", stop: "CARDINAL_OPS_RESTART", restart: "CARDINAL_OPS_RESTART", backup: "CARDINAL_OPS_BACKUP", deploy: "CARDINAL_OPS_DEPLOY", rollback: "CARDINAL_OPS_DEPLOY", restore: "CARDINAL_OPS_RESTORE" }[plan.intent]; if (!permission) throw new Error("Operação não registrada."); await this.authorize(actor, permission); if (plan.intent === "health") return plan.target && plan.target !== "all" ? this.serviceStatus(actor, plan.target) : this.systemStatus(actor); if (plan.intent === "logs") return this.logs(actor, plan.target, 100); this.assertEnabled(); const dryRun = options.dryRun ?? plan.dry_run; if (!dryRun && confirmationNeeded(plan, this.config) && !options.confirmed) return this.createConfirmation(actor, plan); const key = crypto.createHash("sha256").update(`${actor}:${plan.intent}:${plan.target}:${plan.change_id || ""}:${options.idempotencyKey || plan.operation_id}`).digest("hex"), data = await this.state.read(); if (data.idempotency[key]) return { ...data.idempotency[key], idempotent_replay: true }; const started = Date.now(), before = plan.target && this.registry[plan.target] ? await this.adapters[plan.target].status() : null; try { let result; if (dryRun) result = { dry_run: true, plan }; else if (plan.intent === "start") result = await this.start(plan.target); else if (plan.intent === "stop") result = await this.stop(plan.target); else if (plan.intent === "restart") result = await this.restart(plan.target, plan.reason); else if (plan.intent === "backup") result = await this.backups.create(plan.reason); else if (plan.intent === "deploy") result = await this.deploy(actor, plan.change_id); else if (plan.intent === "rollback") result = await this.rollbackDeployment(actor, plan.deployment_id || plan.change_id); else if (plan.intent === "restore") result = await this.backups.restore(plan.backup_id || plan.target); const after = plan.target && this.registry[plan.target] ? await this.adapters[plan.target].status() : null, response = { success: true, operation_id: plan.operation_id, intent: plan.intent, target: plan.target, before, after, result, duration_ms: Date.now() - started }; await this.state.mutate(state => { state.operations.push({ ...response, actor, timestamp: new Date().toISOString() }); state.idempotency[key] = response; }); await this.audit.record({ ...response, actor }); return response; } catch (error) { await this.state.add("operations", { operation_id: plan.operation_id, actor, intent: plan.intent, target: plan.target, before, status: "FAILED", duration_ms: Date.now() - started, error: { code: error.code, message: error.message } }); await this.audit.record({ operation_id: plan.operation_id, actor, intent: plan.intent, target: plan.target, before, result: "FAILED", duration_ms: Date.now() - started, error: error.message }); throw error; } }
    async start(id) { this.assertService(id); const lock = `service:${id}`; return this.withLock(lock, async () => { const before = await this.adapters[id].status(); if (before.status === "ONLINE") return { ...before, duplicate: true }; const started = await this.adapters[id].start(), health = await this.waitHealth(id); if (!health.online && health.status !== "ONLINE") await this.incident(id, "HIGH", "Health falhou após start", ["start", "health"]); return { started, health }; }); }
    async stop(id) { this.assertService(id); return this.withLock(`service:${id}`, () => this.adapters[id].stop()); }
    async restart(id, reason) { this.assertService(id); return this.withLock(`service:${id}`, async () => { await this.assertRestartBudget(id); await this.adapters[id].stop(); await this.adapters[id].start(); const health = await this.waitHealth(id); await this.recordRestart(id, health.status === "ONLINE"); if (health.status !== "ONLINE") { await this.incident(id, "HIGH", reason || "Restart sem recuperação", ["stop", "start", "health"]); const e = new Error(`Serviço ${id} permaneceu indisponível.`); e.code = "RECOVERY_FAILED"; throw e; } return health; }); }
    async waitHealth(id) { let last; for (let i = 0; i < 10; i++) { last = await this.health.service(id); if (last.status === "ONLINE") return last; await new Promise(resolve => setTimeout(resolve, 250)); } return last; }
    async assertRestartBudget(id) { const since = Date.now() - this.config.restartWindowMs, data = await this.state.read(), attempts = data.operations.filter(x => x.intent === "restart_attempt" && x.target === id && new Date(x.timestamp).getTime() >= since); if (attempts.length >= this.config.maxRestartAttempts) { const e = new Error("Limite de reinicializações atingido; serviço marcado FAILED."); e.code = "RESTART_LOOP_BLOCKED"; throw e; } }
    recordRestart(id, success) { return this.state.add("operations", { intent: "restart_attempt", target: id, timestamp: new Date().toISOString(), success }); }
    incident(service, severity, cause, actions) { return this.state.add("incidents", { incident_id: `incident_${crypto.randomUUID()}`, service, severity, started_at: new Date().toISOString(), cause, actions, status: "OPEN" }); }
    async deploy(actor, changeId) { if (!this.developerStore || !this.deployment) throw new Error("Deployment local não configurado."); if (!changeId) throw new Error("change_id obrigatório."); return this.withLock("deployment:local", async () => { const task = await this.developerStore.get(changeId); if (task.status !== "APPROVED" || !task.review?.passed || !task.commit || !(task.tests || []).length || task.tests.some(x => !x.success)) { const e = new Error("Somente mudança APPROVED, commitada e com validações aprovadas pode ser implantada."); e.code = "UNAPPROVED_CHANGE"; throw e; } const deployment = await this.state.add("deployments", { change_id: changeId, status: "PRECHECK", environment: "local", main_branch: task.mainBranch, branch: task.branch, tests: task.tests.map(x => ({ tool: x.tool, success: x.success })), files: task.files }); const system = await this.health.system(); if (system.disk_free_mb < this.config.minDiskFreeMb) throw Object.assign(new Error("Espaço em disco insuficiente."), { code: "DISK_LOW" }); await this.state.update("deployments", deployment.id, { status: "BACKUP" }); const backup = await this.backups.create(`Pre-deploy ${changeId}`, deployment.id); await this.state.update("deployments", deployment.id, { status: "DEPLOYING", backup_id: backup.id }); try { const applied = await this.deployment.deploy(task); await this.state.update("deployments", deployment.id, { status: "VERIFYING", merge_commit: applied.commit }); const health = await this.health.all(); const failed = [health.bot, health.site, health.database].some(x => x.status === "OFFLINE" || x.status === "FAILED"); if (failed) throw new Error("Health pós-deploy falhou."); const done = await this.state.update("deployments", deployment.id, { status: "SUCCESS", health, merge_commit: applied.commit }); await this.developerStore.update(changeId, { status: "MERGED", merge_commit: applied.commit }); if (this.reindex) await this.reindex(task.files); return done; } catch (error) { await this.state.update("deployments", deployment.id, { status: "FAILED", error: error.message }); throw error; } }); }
    async rollbackDeployment(actor, id) { if (!this.deployment) throw new Error("Rollback local não configurado."); return this.withLock("deployment:local", async () => { const data = await this.state.read(), deployment = data.deployments.find(x => x.id === id); if (!deployment || deployment.status !== "SUCCESS") throw new Error("Deployment válido não encontrado."); await this.state.update("deployments", id, { status: "ROLLING_BACK" }); const result = await this.deployment.rollback(deployment); return this.state.update("deployments", id, { status: "ROLLED_BACK", rollback_commit: result.commit }); }); }
    async createConfirmation(actor, plan) { const confirmation = await this.state.add("confirmations", { confirmation_id: `ops_confirm_${crypto.randomUUID()}`, actor, plan, expires_at: new Date(Date.now() + 10 * 60000).toISOString(), used: false }); return { confirmation_required: true, confirmation_id: confirmation.confirmation_id, risk: plan.risk, expires_at: confirmation.expires_at }; }
    async confirm(actor, id) { await this.authorize(actor, "CARDINAL_OPS_CRITICAL"); const data = await this.state.read(), row = data.confirmations.find(x => x.confirmation_id === id && x.actor === actor && !x.used); if (!row || new Date(row.expires_at) <= new Date()) throw new Error("Confirmação inválida ou expirada."); await this.state.mutate(state => { state.confirmations.find(x => x.confirmation_id === id).used = true; }); return this.execute(actor, row.plan, { confirmed: true }); }
    async history(actor) { await this.authorize(actor, "CARDINAL_OPS_READ"); return this.state.read(); }
    async withLock(key, work) { const owner = crypto.randomUUID(); if (!await this.state.lock(key, owner)) { const e = new Error(`Operação simultânea bloqueada: ${key}.`); e.code = "OPERATION_LOCKED"; throw e; } try { return await work(); } finally { await this.state.unlock(key, owner); } }
    assertService(id) { if (!id || !this.registry[id]) throw new Error(`Serviço não permitido: ${id || "ausente"}.`); } assertEnabled() { if (!this.config.enabled) { const e = new Error("Cardinal Operations está em modo somente leitura."); e.code = "OPERATIONS_DISABLED"; throw e; } }
}
module.exports = { CardinalOperationsService, confirmationNeeded };
