"use strict";
const { qualityGate, developerImpact } = require("../../balance");
function artifact(workflow, taskId) { const value = workflow.artifacts[taskId]; if (!value) throw Object.assign(new Error(`Artifact ausente: ${taskId}.`), { code: "LOGICAL_ERROR" }); return value; }
function createHandlers(modules) { return {
    knowledge: { async execute(task) { const rows = await modules.knowledge.searchKnowledge(task.parameters.query, { limit: 8 }); return { sources: rows.map(x => ({ id: x.id, file: x.file, category: x.category, entity: x.entity })), summary: rows.map(x => x.content).join("\n").slice(0, 12000) }; } },
    web: { async execute(task, workflow) { if (!modules.web) throw Object.assign(new Error("Web Research indisponível."), { code: "WEB_DEGRADED" }); const record = await modules.web.research(workflow.actor, task.parameters.query, { mode: task.parameters.mode || "RESEARCH_AND_DRAFT", review: task.parameters.mode === "RESEARCH_ONLY", intent: task.parameters.intent, refresh: task.action === "expand" }); if (record.confidence === "LOW" || (record.warnings || []).some(row => row.code === "SOURCE_CONFLICT")) throw Object.assign(new Error("Pesquisa externa exige revisão antes de criar conteúdo."), { code: "RESEARCH_REVIEW_REQUIRED", details: { external_record_id: record.record_id, confidence: record.confidence, warnings: record.warnings } }); return { artifact_type: "EXTERNAL_RESEARCH", external_record_id: record.record_id, record_version: record.updated_at || record.created_at || 1, query: record.query, entity: record.plan?.target_entity, facts: record.facts, core_traits: record.core_traits, citations: record.citations, confidence: record.confidence, adaptation: record.adaptation, record }; } },
    forge: { async execute(task, workflow) { const dependencies = (task.parameters.artifacts_from || []).map(id => artifact(workflow, id)); const research = task.parameters.external_record_task ? artifact(workflow, task.parameters.external_record_task) : null; const result = await modules.forge.generate(task.parameters.request, { type: task.parameters.type, author: workflow.actor, context: { artifacts: dependencies, external_record: research?.record } }); if (!result.draft?.validation?.valid && result.draft?.status !== "VALID") throw Object.assign(new Error("Forge retornou conteúdo inválido."), { code: "LOGICAL_ERROR" }); return { draft_id: result.draft.id, type: result.draft.type, status: result.draft.status, content: result.draft.content, external_record_id: research?.external_record_id || null, external_record_version: research?.record_version || null }; } },
    publisher: { async execute(task, workflow) { const draft = artifact(workflow, task.parameters.draft_task); const plan = modules.admin.plan(`publique o draft ${draft.draft_id}`); plan.intent = "publish_draft"; plan.parameters = { draft_id: draft.draft_id }; plan.idempotency_key = task.operation_id; return modules.admin.executePlan(workflow.actor, plan); }, async rollback(task, workflow) { const output = workflow.artifacts[task.id]; if (output?.operation_id) return modules.admin.rollback(workflow.actor, output.operation_id); } },
    admin: { async execute(task, workflow) { return modules.admin.executePlan(workflow.actor, { ...task.parameters.plan, idempotency_key: task.operation_id }); } },
    developer: { async execute(task, workflow) { const result = await modules.developer.plan(workflow.actor, task.parameters.request); return { change_id: result.task_id, status: result.status, balance_test_scopes: developerImpact(task.parameters.files || []) }; }, async rollback(task, workflow) { const out = workflow.artifacts[task.id]; if (out?.change_id) return modules.developer.rollback(workflow.actor, out.change_id); } },
    operations: { async execute(task, workflow) { if (task.action === "health_check") return modules.operations.systemStatus(workflow.actor); const change = artifact(workflow, task.parameters.change_task); const plan = modules.operations.plan(`deploy change ${change.change_id}`); plan.intent = "deploy"; plan.change_id = change.change_id; plan.risk = "HIGH"; return modules.operations.execute(workflow.actor, plan, { confirmed: true }); }, async rollback(task, workflow) { const out = workflow.artifacts[task.id], id = out?.result?.id; if (id) return modules.operations.rollbackDeployment(workflow.actor, id); } },
    world: { async execute(task, workflow) { if (!modules.world) throw Object.assign(new Error("World Director indisponível."), { code: "WORLD_DEGRADED" }); if (task.action === "overview") return modules.world.overview(); if (task.action === "weekly_dungeons") return modules.world.planWeeklyDungeons(); if (task.action === "event") return modules.world.createEvent(workflow.actor, task.parameters, { dryRun: Boolean(task.dry_run) }); if (task.action === "research_plan") { const research = artifact(workflow, task.parameters.external_record_task), overview = await modules.world.overview(), location = task.parameters.location || null, known = [...overview.dungeons, ...overview.events].map(row => row.location_id).filter(Boolean); if (location && known.length && !known.includes(location)) throw Object.assign(new Error("Local sugerido pela pesquisa não está disponível no estado mundial."), { code: "WORLD_LOCATION_INVALID" }); return { artifact_type: "WORLD_RESEARCH_PLAN", theme: task.parameters.theme || research.entity, locations: location ? [location] : [], entities: (research.core_traits || []).map(row => row.trait), event_components: task.parameters.components || [], external_record_ids: [research.external_record_id], external_record_versions: [research.record_version], world_phase: overview.phase, status: "DRAFT" }; } throw Object.assign(new Error("Ação mundial não permitida."), { code: "WORLD_ACTION_NOT_ALLOWED" }); } },
    balance: { async execute(task, workflow) { if (!modules.balance) throw Object.assign(new Error("Cardinal Balance indisponível."), { code: "BALANCE_DEGRADED" }); if (task.action === "simulate_banner") return modules.balance.simulateBanner(task.parameters.rewards || [], task.parameters); if (task.action === "simulate_economy") return modules.balance.simulateEconomy(task.parameters); if (task.action === "exploit_scan") return modules.balance.scanExploit(task.parameters.system || "unknown", task.parameters.payload || {}); const source = task.parameters.draft_task ? artifact(workflow, task.parameters.draft_task) : task.parameters, research = task.parameters.external_record_task ? artifact(workflow, task.parameters.external_record_task) : null, type = task.parameters.type || source.type, content = source.content || task.parameters.content; if (!type || !content) throw Object.assign(new Error("Tipo e conteúdo são obrigatórios para Quality Gate."), { code: "BALANCE_INPUT_INVALID" }); const result = await qualityGate({ engine: modules.balance, type, content, options: { ...task.parameters.options, inspiration_target: research?.entity } }); if (!result.passed) throw Object.assign(new Error("Quality Gate bloqueou o artefato."), { code: "BALANCE_BLOCKED", details: result }); return { ...result, draft_id: source.draft_id || null, external_record_id: research?.external_record_id || null, external_record_version: research?.record_version || null, balance_report_id: result.report?.id || null }; } },
    narrative: { async execute(task, workflow) { if (!modules.narrative) throw Object.assign(new Error("Cardinal Narrator indisponível."), { code: "NARRATIVE_DEGRADED" }); await modules.narrative.ready; const research = task.parameters.external_record_task ? artifact(workflow, task.parameters.external_record_task) : null, input = { ...task.parameters, external_research: research?.record ? { external_record_id: research.external_record_id, record_version: research.record_version, facts: research.facts, core_traits: research.core_traits, citations: research.citations, adaptation: research.adaptation } : null }; if (task.action === "npc_brief") return modules.narrative.npcBrief(workflow.actor, input); if (task.action === "revise") return modules.narrative.revise(workflow.actor, input.draft_id, input.changes); const result = await modules.narrative.generate(workflow.actor, input); return { ...result, external_record_id: research?.external_record_id || null, external_record_version: research?.record_version || null }; } },
    verify: { async execute(task, workflow) { const missing = task.depends_on.filter(id => !workflow.artifacts[id]); if (missing.length) throw Object.assign(new Error(`Artifacts ausentes: ${missing.join(", ")}`), { code: "LOGICAL_ERROR" }); return { verified: true, references: task.depends_on }; } }
}; }
module.exports = { createHandlers, artifact };
