"use strict";
const { loadOrchestratorConfig } = require("./config"); const { buildPlan } = require("./planner"); const { validateWorkflowPlan } = require("./dependencies/graph"); const { WorkflowStore } = require("./state/store"); const { PolicyEngine } = require("./policies"); const { OrchestratorAudit } = require("./audit"); const { WorkflowEngine } = require("./workflow/engine"); const { createHandlers } = require("./executor/handlers");
class CardinalOrchestratorService {
    constructor(options = {}) { this.config = loadOrchestratorConfig(options); this.store = options.store || new WorkflowStore(this.config.statePath); this.policy = options.policy || new PolicyEngine(this.config); this.audit = options.audit || new OrchestratorAudit(this.config.auditPath); this.authorize = options.authorize || (async () => true); this.identity = options.identity || (async actor => ({ actor, permissions: [] })); this.handlers = options.handlers || createHandlers(options.modules || {}); this.engine = options.engine || new WorkflowEngine({ config: this.config, store: this.store, policy: this.policy, handlers: this.handlers, authorize: this.authorize }); }
    preview(request, options = {}) { const plan = validateWorkflowPlan(buildPlan(request, options), this.config); this.policy.assertScope(plan); return { dry_run: true, goal: plan.goal, tasks: plan.tasks.map(({ output, error, ...task }) => task), dependencies: Object.fromEntries(plan.tasks.map(t => [t.id, t.depends_on])), affected_systems: plan.affected_systems, risk: plan.risk, approvals: plan.approvals, expected_outputs: plan.expected_outputs, rollback_plan: plan.rollback_plan }; }
    async create(actor, request, options = {}) { if (!actor) throw new Error("Actor autenticado obrigatório."); const plan = validateWorkflowPlan(buildPlan(request, options), this.config); this.policy.assertScope(plan); const identity = await this.identity(actor), workflow = await this.store.create({ actor, request_original: request, goal: plan.goal, goal_classification: plan.goal_classification, template: plan.template, tasks: plan.tasks, dependencies: Object.fromEntries(plan.tasks.map(t => [t.id, t.depends_on])), risk: plan.risk, priority: plan.priority, affected_systems: plan.affected_systems, expected_outputs: plan.expected_outputs, rollback_plan: plan.rollback_plan, permissions_snapshot: identity.permissions || [], mode: this.config.mode, depth: options.depth || 0, status: "READY" }); await this.audit.record({ event: "workflow_created", actor, workflow_id: workflow.workflow_id, request, plan }); return workflow; }
    async start(actor, id) { const workflow = await this.assertActor(actor, id); await this.audit.record({ event: "workflow_start_requested", actor, workflow_id: id }); return this.engine.run(workflow.workflow_id); }
    async resume(actor, id) { let workflow = await this.assertActor(actor, id); if (!new Set(["PAUSED", "WAITING_FOR_APPROVAL", "READY", "RUNNING"]).has(workflow.status)) throw new Error(`Workflow não pode continuar em ${workflow.status}.`); if (workflow.status === "WAITING_FOR_APPROVAL") return workflow; workflow = await this.store.update(id, { status: "READY" }, { event: "workflow_resumed" }); return this.engine.run(workflow.workflow_id); }
    async pause(actor, id) { await this.assertActor(actor, id); const result = await this.store.update(id, { status: "PAUSED", pause_reason: "Pausado pelo administrador." }, { event: "workflow_paused_by_actor", actor }); await this.store.release(id); return result; }
    async approveStage(actor, id, stage) { const workflow = await this.assertActor(actor, id), permission = stage === "deploy" ? "CARDINAL_OPS_DEPLOY" : "CARDINAL_PUBLISH"; await this.authorize(actor, permission); const gates = workflow.tasks.filter(t => t.type === "approval" && t.parameters.stage === stage && t.status === "WAITING_APPROVAL"); if (!gates.length) throw new Error("Etapa não está aguardando aprovação."); for (const gate of gates) { gate.status = "SUCCESS"; gate.output = { approved_by: actor, stage, at: new Date().toISOString() }; workflow.artifacts[gate.id] = gate.output; } workflow.approvals.push({ stage, actor, at: new Date().toISOString(), tasks: gates.map(x => x.id) }); await this.store.update(id, { tasks: workflow.tasks, artifacts: workflow.artifacts, approvals: workflow.approvals, status: "READY" }, { event: "approval_granted", stage, actor }); await this.audit.record({ event: "approval_granted", workflow_id: id, actor, stage }); return this.engine.run(id); }
    async cancel(actor, id, options = {}) { const workflow = await this.assertActor(actor, id), completed = [...workflow.tasks].reverse().filter(t => t.status === "SUCCESS" && this.handlers[t.type]?.rollback), rolled = [], partial = []; if (options.rollback) for (const task of completed) try { await this.handlers[task.type].rollback(task, workflow); task.status = "ROLLED_BACK"; rolled.push(task.id); } catch (e) { partial.push({ task: task.id, error: e.message }); } const result = await this.store.update(id, { tasks: workflow.tasks, status: "CANCELLED", cancellation: { rollback_requested: Boolean(options.rollback), rolled_back: rolled, not_rolled_back: partial } }, { event: "workflow_cancelled", actor }); await this.store.release(id); return result; }
    async replan(actor, id, revisedPlan, reason) { const workflow = await this.assertActor(actor, id); if ((workflow.plan_revisions || []).length >= this.config.maxReplans) throw new Error("Limite de replanning atingido."); validateWorkflowPlan(revisedPlan, this.config); this.policy.assertScope(revisedPlan); const completed = new Map(workflow.tasks.filter(t => t.status === "SUCCESS").map(t => [t.id, t])); for (const task of revisedPlan.tasks) if (completed.has(task.id)) Object.assign(task, completed.get(task.id)); const revision = { at: new Date().toISOString(), actor, reason, previous_task_count: workflow.tasks.length, new_task_count: revisedPlan.tasks.length }; return this.store.update(id, { tasks: revisedPlan.tasks, dependencies: Object.fromEntries(revisedPlan.tasks.map(t => [t.id, t.depends_on])), affected_systems: revisedPlan.affected_systems || workflow.affected_systems, status: "READY", plan_revisions: [...workflow.plan_revisions, revision] }, { event: "workflow_replanned", reason }); }
    async status(actor, id) { return this.assertActor(actor, id); } async history(actor) { await this.authorize(actor, "CARDINAL_READ"); return (await this.store.read()).workflows; } async setPreference(actor, patch) { await this.authorize(actor, "CARDINAL_READ"); return this.store.preference(actor, patch); }
    async assertActor(actor, id) { const workflow = await this.store.get(id); if (workflow.actor !== actor) await this.authorize(actor, "CARDINAL_CRITICAL"); return workflow; }
    explain(workflow) { return { workflow_id: workflow.workflow_id, goal: workflow.goal, status: workflow.status, completed: workflow.tasks.filter(x => ["SUCCESS", "ROLLED_BACK"].includes(x.status)).map(x => x.id), failed: workflow.tasks.filter(x => x.status === "FAILED").map(x => ({ id: x.id, error: x.error })), pending: workflow.tasks.filter(x => ["PENDING", "READY", "BLOCKED", "WAITING_APPROVAL"].includes(x.status)).map(x => x.id), approvals: workflow.approvals, next_step: workflow.status === "WAITING_FOR_APPROVAL" ? "Aprovação administrativa necessária." : workflow.pause_reason || null, metrics: workflow.metrics }; }
}
const approveStageBase = CardinalOrchestratorService.prototype.approveStage;
CardinalOrchestratorService.prototype.approveStage = async function approveStageProtected(actor, id, stage) {
    if (stage === "critical") await this.authorize(actor, "CARDINAL_CRITICAL");
    return approveStageBase.call(this, actor, id, stage);
};
module.exports = { CardinalOrchestratorService };
