"use strict";const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),{WorldDirector,WorldStore}=require("../world");
async function fx(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"world-")),store=new WorldStore(path.join(root,"w.db")),database={all:async()=>[],get:async()=>null,playerLocation:async id=>({player_id:id,city_id:"seoul"})},world=new WorldDirector({root,store,database,authorize:async()=>true});await world.ready;return{root,store,world};}
test("world state and phase",async t=>{const f=await fx();t.after(async()=>{await f.store.close();fs.rmSync(f.root,{recursive:true,force:true})});assert.equal((await f.world.overview()).timezone,"America/Sao_Paulo");assert.ok(["DAY","SUNSET","NIGHT"].includes(f.world.phase()));});
test("travel restriction and protected Seoul",async t=>{const f=await fx();t.after(async()=>{await f.store.close();fs.rmSync(f.root,{recursive:true,force:true})});assert.equal((await f.world.canInteract(1,"npc")).code,"WORLD_LOCATION_REQUIRED");assert.equal((await f.world.claimTerritory("adm",{territory:"Seoul",guild:"g"})).code,"WORLD_PROTECTED_TERRITORY");});
test("schedule survives restart and notification deduplicates",async t=>{const f=await fx(),row=await f.world.schedule("adm",{action:"activate",entity_type:"event",entity_id:"x",run_at:new Date(Date.now()+1000).toISOString()});assert.ok(row.schedule_id);assert.equal((await f.world.notify("event","x",{})).created,true);assert.equal((await f.world.notify("event","x",{})).deduplicated,true);await f.store.close();const again=new WorldStore(path.join(f.root,"w.db"));await again.init();assert.equal((await again.all("SELECT * FROM world_schedules")).length,1);await again.close();fs.rmSync(f.root,{recursive:true,force:true});});
test("undefined weekly rule is never invented",async t=>{const f=await fx();t.after(async()=>{await f.store.close();fs.rmSync(f.root,{recursive:true,force:true})});assert.equal((await f.world.planWeeklyDungeons()).status,"WORLD_RULE_PENDING");});
test("event lifecycle, conflict, audit and rollback",async t=>{const f=await fx();t.after(async()=>{await f.store.close();fs.rmSync(f.root,{recursive:true,force:true})});const input={name:"Halloween",location_id:"busan",start_at:"2030-10-01T00:00:00Z",end_at:"2030-10-02T00:00:00Z"},event=await f.world.createEvent("adm",input);assert.equal(event.status,"DRAFT");assert.equal((await f.world.transitionEvent("adm",event.id,"SCHEDULED","aprovado")).status,"SCHEDULED");const conflict=await f.world.createEvent("adm",{...input,name:"Outro"});assert.equal(conflict.status,"CONFLICT");assert.ok((await f.store.all("SELECT * FROM world_audit")).length>=2);});
test("world lock and NPC double location",async t=>{const f=await fx();t.after(async()=>{await f.store.close();fs.rmSync(f.root,{recursive:true,force:true})});assert.equal(await f.world.lock("event:x","a"),true);assert.equal(await f.world.lock("event:x","b"),false);await f.world.unlock("event:x","a");const first=await f.world.spawnNpc("adm",{npc_id:"npc",location_id:"seoul"}),second=await f.world.spawnNpc("adm",{npc_id:"npc",location_id:"busan"});assert.equal(first.status,"ACTIVE");assert.equal(second.code,"WORLD_NPC_DOUBLE_LOCATION");});
test("eligibility is deterministic",()=>{const {canPlayerJoinDungeon,canGuildClaimTerritory}=require("../world");assert.equal(canPlayerJoinDungeon({location:"seoul"},{status:"open",location_id:"busan"}).code,"WORLD_TRAVEL_REQUIRED");assert.equal(canGuildClaimTerritory({id:1},{name:"Seoul",protected:true}).code,"WORLD_PROTECTED_TERRITORY");});
