"use strict";
const test = require("node:test"); const assert = require("node:assert/strict"); const fs = require("fs/promises"); const os = require("os"); const path = require("path"); const { execFileSync } = require("child_process");
const { CardinalDeveloperService, ControlledEditor, CodeSearch, SafeRunner, createDeveloperPlan, scanDiff } = require("../developer");
async function fixture() { const parent = await fs.mkdtemp(path.join(os.tmpdir(), "cardinal-dev-")), root = path.join(parent, "repo"), worktreeRoot = path.join(parent, "worktrees"); await fs.mkdir(path.join(root, "apps/site"), { recursive: true }); await fs.mkdir(path.join(root, "src"), { recursive: true }); await fs.writeFile(path.join(root, "src/banner.js"), "function charge(value) { return value * 2; }\nmodule.exports = { charge };\n"); await fs.writeFile(path.join(root, ".env"), "TOKEN=secret\n"); await fs.writeFile(path.join(root, "package.json"), JSON.stringify({ scripts: { "cardinal:test": "node -e \"process.exit(0)\"" } })); await fs.writeFile(path.join(root, "apps/site/package.json"), JSON.stringify({ scripts: { lint: "node -e \"process.exit(0)\"", build: "node -e \"process.exit(0)\"" } })); execFileSync("git", ["init", "-b", "main"], { cwd: root }); execFileSync("git", ["config", "user.email", "cardinal@test.local"], { cwd: root }); execFileSync("git", ["config", "user.name", "Cardinal Test"], { cwd: root }); execFileSync("git", ["add", "."], { cwd: root }); execFileSync("git", ["commit", "-m", "test: base"], { cwd: root }); const options = { root, worktreeRoot, enabled: true, statePath: path.join(parent, "tasks.json"), auditPath: path.join(parent, "audit.jsonl"), projectMapPath: path.join(parent, "map.json"), authorize: async () => true }; return { parent, root, worktreeRoot, service: new CardinalDeveloperService(options) }; }
async function cleanup(ctx) { await fs.rm(ctx.parent, { recursive: true, force: true, maxRetries: 3 }); }
test("busca localiza arquivo correto por texto, símbolo e nome", async t => { const ctx = await fixture(); t.after(() => cleanup(ctx)); const search = new CodeSearch(ctx.root); assert.equal((await search.search("function charge"))[0].file, "src/banner.js"); assert.equal((await search.findSymbol("charge"))[0].file, "src/banner.js"); assert.match((await search.findFiles("banner"))[0], /banner\.js/); });
test("patch pequeno ocorre somente no worktree e main fica intacta", async t => { const ctx = await fixture(); t.after(() => cleanup(ctx)); let task = await ctx.service.plan("adm", "Corrija o bug no banner"); task = await ctx.service.start("adm", task.task_id); assert.notEqual(path.resolve(task.worktree), path.resolve(ctx.root)); assert.match(task.branch, /^cardinal\/bugfix\//); await ctx.service.edit("adm", task.task_id, { file: "src/banner.js", expected: "value * 2", replacement: "value", diagnosis: "Cobrança multiplicada por dois." }); assert.match(await fs.readFile(path.join(task.worktree, "src/banner.js"), "utf8"), /return value;/); assert.match(await fs.readFile(path.join(ctx.root, "src/banner.js"), "utf8"), /value \* 2/); });
test("arquivos protegidos e diff perigoso são bloqueados", async t => { const ctx = await fixture(); t.after(() => cleanup(ctx)); const editor = new ControlledEditor(ctx.root), search = new CodeSearch(ctx.root); await assert.rejects(editor.replace(".env", "secret", "changed"), error => error.code === "PROTECTED_FILE"); await assert.rejects(search.read(".env"), /protegido/); assert.throws(() => ctx.service.toolsFor().edit_source_file("src/banner.js", "x", "y"), /worktree/); assert.ok(scanDiff("+password='123456789'\n+DROP TABLE players").length >= 2); });
test("runner executa somente testes/build allowlisted", async t => { const ctx = await fixture(); t.after(() => cleanup(ctx)); const runner = new SafeRunner(ctx.root); assert.equal((await runner.run("cardinal_test")).success, true); assert.equal((await runner.run("site_build")).success, true); assert.throws(() => runner.run("shell"), error => error.code === "COMMAND_BLOCKED"); });
test("falha de teste impede review e rollback descarta worktree", async t => { const ctx = await fixture(); t.after(() => cleanup(ctx)); let task = await ctx.service.plan("adm", "Corrija o bug no banner"); task = await ctx.service.start("adm", task.task_id); await ctx.service.edit("adm", task.task_id, { file: "src/banner.js", expected: "value * 2", replacement: "value", diagnosis: "Multiplicação indevida." }); await fs.writeFile(path.join(task.worktree, "package.json"), JSON.stringify({ scripts: { "cardinal:test": "node -e \"process.exit(1)\"" } })); task = await ctx.service.test("adm", task.task_id, ["cardinal_test"]); assert.equal(task.status, "FAILED"); task = await ctx.service.review("adm", task.task_id); assert.equal(task.status, "FAILED"); await assert.rejects(ctx.service.approve("adm", task.task_id), error => error.code === "REVIEW_FAILED"); task = await ctx.service.rollback("adm", task.task_id); assert.equal(task.status, "ROLLED_BACK"); await assert.rejects(fs.access(path.join(ctx.worktreeRoot, task.task_id))); });
test("diff aprovado chega a READY_FOR_REVIEW sem merge automático", async t => { const ctx = await fixture(); t.after(() => cleanup(ctx)); let task = await ctx.service.plan("adm", "Corrija o bug no banner"); task = await ctx.service.start("adm", task.task_id); await ctx.service.edit("adm", task.task_id, { file: "src/banner.js", expected: "value * 2", replacement: "value", diagnosis: "Multiplicação indevida." }); task = await ctx.service.test("adm", task.task_id, ["cardinal_test"]); task = await ctx.service.review("adm", task.task_id); assert.equal(task.status, "READY_FOR_REVIEW"); assert.match(task.diff, /value \* 2/); task = await ctx.service.approve("adm", task.task_id); assert.equal(task.status, "APPROVED"); assert.equal(task.commit, undefined); });
test("pedido grande é decomposto e migration recebe risco alto", () => { const large = createDeveloperPlan("Reformule todo o sistema de Guildas completo"); assert.equal(large.large_request, true); assert.ok(large.stages.length >= 7); assert.equal(createDeveloperPlan("adicione uma nova coluna no banco").risk, "HIGH"); });
