"use strict";
const crypto = require("crypto");
function norm(v) { return String(v || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); }
function task(id, type, action, depends_on = [], parameters = {}) { return { id, type, action, depends_on, parameters, status: "PENDING", operation_id: `wfop_${crypto.randomUUID()}`, retries: 0, output: null, error: null }; }
function contentTypes(text) { const q = norm(text), out = []; for (const [rx, type] of [[/titulo/, "title"], [/passiva/, "passive"], [/dungeon|masmorra/, "dungeon"], [/missao|quest/, "mission"], [/banner/, "banner"], [/conjunto|set/, "set"], [/evento/, "event"], [/arma|espada|shikai|lanca/, "weapon"]]) if (rx.test(q) && !out.includes(type)) out.push(type); return out; }
function contentType(text) { return contentTypes(text)[0] || "weapon"; }
function hasResearch(text) { return /pesquise|pesquisar|pesquisa|referencia externa|mitologia|yokai|hallasan|zangetsu|neuvillette|gashadokuro/.test(norm(text)); }
function result(request, options, template, classification, tasks, affected, risk = "LOW") { return { workflow_schema_version: 1, goal: String(request).trim(), goal_classification: classification, template, tasks, affected_systems: [...new Set(affected)], risk, priority: options.priority || "NORMAL", approvals: tasks.filter(row => row.type === "approval").map(row => row.parameters.stage), expected_outputs: tasks.filter(row => ["web", "forge", "balance", "narrative", "world", "publisher", "developer", "operations"].includes(row.type)).map(row => row.id), rollback_plan: tasks.filter(row => row.type === "publisher").map(row => ({ task: row.id, strategy: "admin_transaction_rollback" })) }; }
function buildResearchPlan(request, options = {}) { const text = norm(request), review = /nao crie|so a pesquisa|mostre antes|somente pesquisa/.test(text), types = contentTypes(request), wantsNarrative = /lore|narrativ|historia|descricao|ambientacao/.test(text) || types.includes("dungeon"), wantsWorld = /evento|mundo|regiao|hallasan|local real|proxima semana/.test(text), wantsPublish = /publi|coloque.*(?:jogo|ar)/.test(text), tasks = [task("external_research", "web", "research", [], { query: request, mode: review ? "RESEARCH_ONLY" : "RESEARCH_AND_DRAFT" })], affected = ["external_research"];
    if (review || (!types.length && !wantsNarrative && !wantsWorld)) return result(request, options, "WEB_RESEARCH", "RESEARCH", tasks, affected);
    if (wantsWorld) { tasks.push(task("world_plan", "world", "research_plan", ["external_research"], { external_record_task: "external_research", theme: request, components: types })); affected.push("world"); }
    const drafts = []; for (const type of types) { const id = `draft_${type}`; tasks.push(task(id, "forge", "create_draft", ["external_research", ...(wantsWorld ? ["world_plan"] : [])], { type, request, external_record_task: "external_research", artifacts_from: wantsWorld ? ["world_plan"] : [] }), task(`balance_${type}`, "balance", "quality_gate", [id], { type, draft_task: id, external_record_task: "external_research" })); drafts.push(id); affected.push("content"); }
    if (wantsNarrative) { tasks.push(task("narrative_draft", "narrative", "generate", ["external_research", ...drafts, ...(wantsWorld ? ["world_plan"] : [])], { title: `Adaptação: ${request}`, objective: request, template: types.includes("dungeon") ? "DUNGEON_INTRO" : "SCENE_OPENING", external_record_task: "external_research" })); affected.push("narrative"); }
    const finalDeps = tasks.filter(row => ["balance", "narrative", "world"].includes(row.type)).map(row => row.id); tasks.push(task("verify_research_workflow", "verify", "verify_artifacts", finalDeps.length ? finalDeps : ["external_research"]));
    if (wantsPublish && drafts.length) { tasks.push(task("approve_publication", "approval", "approve_stage", ["verify_research_workflow"], { stage: "publication" })); for (const id of drafts) tasks.push(task(`publish_${id}`, "publisher", "publish_draft", ["approve_publication"], { draft_task: id })); }
    return result(request, options, wantsWorld ? "WEB_WORLD_RESEARCH" : "WEB_RESEARCH_CREATE", wantsPublish ? "ADMIN" : "CONTENT", tasks, affected, wantsPublish ? "HIGH" : "LOW"); }
function legacyEvent(request, options) { const text = norm(request), wantsPublish = /publi/.test(text), count = Math.min(Number(text.match(/(\d+)\s+itens?/)?.[1] || 1), 10), tasks = [], drafts = []; for (const type of ["event", "banner", "dungeon", "weapon", "title", "mission"]) tasks.push(task(`rules_${type}`, "knowledge", "search_rules", [], { query: `${type} ${request}` })); for (let i = 1; i <= count; i++) { const id = `draft_item_${i}`; tasks.push(task(id, "forge", "create_draft", ["rules_weapon"], { type: "weapon", request: `Item ${i}: ${request}` })); drafts.push(id); } for (const type of ["title", "dungeon", "mission"]) { const id = `draft_${type}`; tasks.push(task(id, "forge", "create_draft", [`rules_${type}`], { type, request })); drafts.push(id); } tasks.push(task("draft_banner", "forge", "create_draft", ["rules_banner", ...drafts], { type: "banner", request, artifacts_from: drafts }), task("draft_event", "forge", "create_draft", ["rules_event", "draft_banner", "draft_dungeon", "draft_title", "draft_mission"], { type: "event", request }), task("verify_drafts", "verify", "verify_artifacts", [...drafts, "draft_banner", "draft_event"])); if (wantsPublish) { tasks.push(task("approve_publication", "approval", "approve_stage", ["verify_drafts"], { stage: "publication" })); for (const id of [...drafts, "draft_banner", "draft_event"]) tasks.push(task(`publish_${id}`, "publisher", "publish_draft", ["approve_publication"], { draft_task: id })); } return result(request, options, "CREATE_EVENT", wantsPublish ? "ADMIN" : "CONTENT", tasks, ["content", "database"], wantsPublish ? "HIGH" : "LOW"); }
function buildPlan(request, options = {}) { const text = norm(request); if (hasResearch(request)) return buildResearchPlan(request, options); if (/bug|erro|quebrad|nao funciona|corrij|melhore|filtro|pagina|site/.test(text)) { const deploy = /deploy|coloque.*no ar/.test(text), tasks = [task("rules_code", "knowledge", "search_rules", [], { query: request }), task("developer", "developer", "plan_change", ["rules_code"], { request })]; if (deploy) tasks.push(task("approve_deploy", "approval", "approve_stage", ["developer"], { stage: "deploy" }), task("deploy", "operations", "deploy_change", ["approve_deploy"], { change_task: "developer" }), task("health", "operations", "health_check", ["deploy"])); return result(request, options, "FIX_BUG", deploy ? "MIXED" : "DEVELOPMENT", tasks, ["code", "site"], deploy ? "HIGH" : "LOW"); }
    if (/evento/.test(text) && /banner|dungeon|itens?|titulo|missao/.test(text)) return legacyEvent(request, options);
    const type = contentType(request), wantsPublish = /publi|coloque.*(?:jogo|ar)/.test(text), tasks = [task(`rules_${type}`, "knowledge", "search_rules", [], { query: request }), task(`draft_${type}`, "forge", "create_draft", [`rules_${type}`], { type, request }), task("verify_drafts", "verify", "verify_artifacts", [`draft_${type}`])]; if (wantsPublish) tasks.push(task("approve_publication", "approval", "approve_stage", ["verify_drafts"], { stage: "publication" }), task(`publish_${type}`, "publisher", "publish_draft", ["approve_publication"], { draft_task: `draft_${type}` })); return result(request, options, "CREATE_CONTENT", wantsPublish ? "ADMIN" : "CONTENT", tasks, ["content"], wantsPublish ? "HIGH" : "LOW"); }
module.exports = { buildPlan, buildResearchPlan, task, contentType, contentTypes, hasResearch };
