'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useState} from 'react';
import {X,MapPin,Users,UserRound,Shield,Coins,TrendingUp,Landmark,Building2,Sparkles,Mountain,Store,CircleDollarSign,Navigation,LockKeyhole} from 'lucide-react';
type Investment={name:string;price:number;effect:string}; type Person={name:string;status?:string;guild?:string;reason?:string}; type Guild={name:string;territory:string;level:number;note:string};
type PlaceData={id:string;name:string;type:'city'|'island';x:number;y:number;dangerLevel:string;image:string;description:string;marketPrice:number;weeklyIncome:number;dominantGuild:Guild;players:Person[];npcs:Person[];tourism:string[];specialLocations:string[];investments:Investment[];marketBasis:string;purchasable?:boolean;protected?:boolean};
type Props={place:{id:string;name:string;x:number;y:number}|null;onClose:()=>void;currentLocationId?:string;onTravel?:(id:string)=>void}; const won=(n:number)=>`${new Intl.NumberFormat('pt-BR').format(n)} Won`;
export default function CityPanel({place,onClose,currentLocationId='seoul',onTravel}:Props){const[data,setData]=useState<PlaceData|null>(null);useEffect(()=>{if(!place){setData(null);return}fetch('/data/places.json').then(r=>r.json()).then(p=>setData((p.places||[]).find((x:PlaceData)=>x.id===place.id)||null))},[place]); if(!place)return null; const here=currentLocationId===place.id;
 return <><div className="place-overlay" onClick={onClose}/><aside className="place-panel"><button className="place-close" onClick={onClose}><X/></button>{data&&<><div className="place-hero"><img src={data.image} alt={`Visão de ${data.name}`}/><div className="place-hero-shade"/><div className="place-hero-copy"><span className="place-kicker">{data.protected?'ZONA NEUTRA':data.type==='island'?'ILHA':'TERRITÓRIO'} · COREIA DO SUL</span><h2>{data.name}</h2><p><MapPin size={14}/> {here?'Você está neste local':'Destino disponível por viagem'}</p></div></div><div className="place-body"><p className="place-description">{data.description}</p>
 <div className="travel-box"><div><Navigation/><span>Sua localização</span><b>{here?data.name:'Outro local'}</b></div>{here?<button disabled>VOCÊ ESTÁ AQUI</button>:<button onClick={()=>{onTravel?.(data.id);onClose()}}>VIAJAR PARA {data.name.toUpperCase()}</button>}</div>
 {data.protected?<div className="protected-box"><LockKeyhole/><div><b>SEUL — ZONA PROTEGIDA</b><span>Não pode ser comprada, conquistada ou dominada por guildas.</span></div></div>:<section className="market-grid"><div className="market-card"><Coins/><span>Valor territorial</span><strong>{won(data.marketPrice)}</strong></div><div className="market-card"><TrendingUp/><span>Renda semanal base</span><strong>{won(data.weeklyIncome)}</strong></div></section>}
 <section className="panel-section"><div className="section-title"><Shield/><span>{data.protected?'Status territorial':'Guilda dominante'}</span></div><div className="guild-box"><div><strong>{data.dominantGuild.name}</strong><span>{data.dominantGuild.territory}</span></div></div><p className="section-note">{data.dominantGuild.note}</p></section>
 <section className="panel-section"><div className="section-title"><Users/><span>Players neste local</span></div>{here?<div className="people-list"><div><span className="presence-dot"/><strong>Irelia</strong><small>Você</small></div></div>:<p className="empty-state">Nenhum player registrado nesta demonstração.</p>}</section>
 <section className="panel-section"><div className="section-title"><UserRound/><span>NPCs registrados</span></div>{data.npcs.length?<div className="people-list npc-reasons">{data.npcs.map(n=><div key={n.name}><span className="npc-dot"/><strong>{n.name}</strong><small>{n.status||'Ativo'}</small>{n.reason&&<p>{n.reason}</p>}</div>)}</div>:<p className="empty-state">Nenhum NPC importante registrado neste local.</p>}<p className="section-note">Para criar uma cena com um NPC, o personagem precisa estar na mesma cidade/região.</p></section>
 {data.tourism.length>0&&<section className="panel-section"><div className="section-title"><Landmark/><span>Pontos turísticos</span></div><div className="tag-list">{data.tourism.map(t=><span key={t}>{t}</span>)}</div></section>}
 {data.specialLocations.length>0&&<section className="panel-section"><div className="section-title"><Mountain/><span>Locais especiais do RPG</span></div>{data.specialLocations.map(s=><div className="special-item" key={s}><Sparkles/><span>{s}</span></div>)}</section>}
 {!data.protected&&<section className="panel-section"><div className="section-title"><Building2/><span>Investimentos possíveis</span></div><div className="investment-list">{data.investments.map(inv=><article key={inv.name}><div className="investment-icon"><Store/></div><div className="investment-copy"><strong>{inv.name}</strong><p>{inv.effect}</p></div><div className="investment-price"><CircleDollarSign/><span>{won(inv.price)}</span></div></article>)}</div></section>}
 <p className="market-disclaimer">{data.marketBasis}</p></div></>}</aside></>}
