'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import {
  Activity, Backpack, BookOpen, ChevronRight, CircleDollarSign, Crown, DoorOpen,
  Gem, Home, Map, Menu, Package, ScrollText, Shield, ShoppingBag, Sparkles,
  Swords, Trophy, Upload, UserRound, Users, X, Zap, MapPin, Bell, Settings,
  HeartPulse, WandSparkles, Search
} from 'lucide-react';
import MapViewer from './MapViewer';

type Section='inicio'|'personagem'|'inventario'|'equipamentos'|'habilidades'|'missoes'|'mapa'|'dungeons'|'guilda'|'loja'|'npcs'|'titulos';
type LivePayload={player:any;inventory:any[];skills:any[];guild:any;location:any;titles:string[];passives:any[];slots:Record<string,number>};

const nav:[Section,string,any,string][]=[
 ['inicio','Início',Home,'/'],['personagem','Meu Personagem',UserRound,'/personagem'],['inventario','Inventário',Backpack,'/inventario'],
 ['equipamentos','Equipamentos',Shield,'/equipamentos'],['habilidades','Habilidades',Zap,'/habilidades'],['missoes','Missões',ScrollText,'/missoes'],
 ['mapa','Mapa',Map,'/mapa'],['dungeons','Dungeons',Swords,'/dungeons'],['guilda','Guilda',Crown,'/guilda'],['loja','Loja',ShoppingBag,'/loja'],
 ['npcs','NPCs',Users,'/npcs'],['titulos','Títulos',Trophy,'/titulos']
];

function fmt(n:any){return Number(n||0).toLocaleString('pt-BR')}
async function readJson(response:Response){const text=await response.text();if(!text.trim())throw new Error(response.ok?'O servidor respondeu sem dados.':`Falha no servidor (${response.status}).`);try{return JSON.parse(text)}catch{throw new Error(response.ok?'O servidor respondeu com dados invalidos.':`Falha no servidor (${response.status}).`)}}
const fetch:typeof globalThis.fetch=async(...args)=>{const response=await globalThis.fetch(...args);const read=response.text.bind(response);response.json=async()=>{const text=await read();if(!text.trim())return {};try{return JSON.parse(text)}catch{throw new Error(response.ok?'O servidor respondeu com dados invalidos.':`Falha no servidor (${response.status}).`)}};return response};
function Progress({value,max,label,tone='blue'}:{value:number,max:number,label:string,tone?:string}){const pct=Math.max(0,Math.min(100,max?value/max*100:0));return <div className={`sys-progress ${tone}`}><div><span>{label}</span><b>{fmt(value)} / {fmt(max)}</b></div><i><em style={{width:`${pct}%`}}/></i></div>}
function useAvatar(playerName?:string){const[key,setKey]=useState('');const[avatar,setAvatar]=useState<string|null>(null);useEffect(()=>{if(!playerName)return;const k=`slrpg-avatar:${playerName}`;setKey(k);setAvatar(localStorage.getItem(k))},[playerName]);const save=(f?:File)=>{if(!f||!key)return;const r=new FileReader();r.onload=()=>{const v=String(r.result);localStorage.setItem(key,v);setAvatar(v)};r.readAsDataURL(f)};return{avatar,save}}

function CharacterRender({avatar,name}:{avatar:string|null,name:string}){return <div className="character-render">{avatar?<img src={avatar} alt={`PNG de ${name}`}/>:<div className="character-placeholder"><UserRound/><b>SEU PERSONAGEM</b><span>Adicione um PNG para personalizar a interface.</span></div>}</div>}

function Shell({section,data,children}:{section:Section,data:LivePayload,children:React.ReactNode}){
 const[open,setOpen]=useState(false);const p=data.player;const current=nav.find(n=>n[0]===section);
 return <main className="hunter-app">
  <aside className={`hunter-sidebar ${open?'open':''}`}>
   <div className="sl-brand"><span>SOLO</span><b>LEVELING</b><small>RPG SYSTEM</small><button onClick={()=>setOpen(false)} aria-label="Fechar menu"><X/></button></div>
   <div className="hunter-mini"><div className="mini-avatar">{String(p.nome||'?').slice(0,1)}</div><div><small>CAÇADOR</small><b>{p.nome}</b><span>Rank {p.rank} • Nv. {p.nivel}</span></div></div>
   <nav>{nav.map(([id,label,Icon,href])=><Link key={id} href={href} className={section===id?'active':''} onClick={()=>setOpen(false)}><Icon/><span>{label}</span><ChevronRight/></Link>)}</nav>
   <div className="sidebar-foot"><Link href="/configuracoes"><Settings/>Configurações</Link><form action="/api/auth/logout" method="post"><button><DoorOpen/>Sair</button></form></div>
  </aside>
  {open&&<button className="nav-scrim" aria-label="Fechar menu" onClick={()=>setOpen(false)}/>} 
  <section className="hunter-main">
   <header className="hunter-topbar"><button className="hamb" onClick={()=>setOpen(true)}><Menu/></button><div className="page-title"><small>SISTEMA DO CAÇADOR</small><b>{current?.[1]}</b></div><div className="top-location"><MapPin/><div><small>LOCALIZAÇÃO</small><b>{data.location?.city_id||'seoul'}</b></div></div><div className="top-wallet"><Gem/><b>{fmt(p.maestria)}</b><CircleDollarSign/><b>{fmt(p.won)}</b></div><button className="bell"><Bell/></button></header>
   <div className={`hunter-content ${section==='mapa'?'map-page-content':''}`}>{children}</div>
   <nav className="mobile-bottom">{nav.filter(n=>['inicio','personagem','mapa','inventario'].includes(n[0])).map(([id,label,Icon,href])=><Link key={id} href={href} className={section===id?'active':''}><Icon/><span>{label}</span></Link>)}<button onClick={()=>setOpen(true)}><Menu/><span>Mais</span></button></nav>
  </section>
 </main>
}

function Dashboard({data}:{data:LivePayload}){const p=data.player;return <div className="dashboard-page">
 <section className="hero-system"><div className="hero-copy"><small>O SISTEMA RECONHECEU VOCÊ</small><h1>DESPERTE.<br/>EVOLUA.<br/><em>SOBREVIVA.</em></h1><p>Seu personagem, inventário e mundo agora vivem no mesmo Sistema.</p><Link href="/personagem" className="primary-cta">ENTRAR NO SISTEMA <ChevronRight/></Link></div><div className="hero-art"/><div className="event-card"><small>EVENTO ATIVO</small><b>GATES SEMANAIS</b><span>Viaje pelo mapa antes de participar.</span><Link href="/mapa">ABRIR MAPA</Link></div></section>
 <section className="dashboard-grid"><article className="profile-card sys-panel"><div className="mini-avatar big">{String(p.nome||'?').slice(0,1)}</div><div><small>CAÇADOR</small><h2>{p.nome}</h2><p>Rank {p.rank} • Nível {p.nivel}</p></div><div className="power"><span>PODER TOTAL</span><b>{fmt(Number(p.forca_total||0)+Number(p.resistencia_total||0)+Number(p.velocidade_total||0)+Number(p.sentidos_total||0)+Number(p.inteligencia_total||0)+Number(p.poder_magico_total||0))}</b></div><Progress value={p.vida_atual} max={p.vida_maxima} label="HP" tone="red"/><Progress value={p.mana_atual} max={p.mana_maxima} label="MP"/></article>
 <article className="quick-panel sys-panel"><h3>ATALHOS RÁPIDOS</h3><div className="quick-links">{nav.filter(n=>['inventario','equipamentos','habilidades','missoes','mapa','loja'].includes(n[0])).map(([id,label,Icon,href])=><Link href={href} key={id}><Icon/><span>{label}</span></Link>)}</div></article>
 <article className="notice-panel sys-panel"><h3>STATUS DO MUNDO</h3><div><span>Localização atual</span><b>{data.location?.city_id||'seoul'}</b></div><div><span>Guilda</span><b>{data.guild?.nome||'Nenhuma'}</b></div><div><span>Itens no inventário</span><b>{data.inventory.length}</b></div><div><span>Técnicas</span><b>{data.skills.length}</b></div></article></section>
 </div>}

function CharacterPage({data}:{data:LivePayload}){const p=data.player;const{avatar,save}=useAvatar(p.nome);const stats=[['Força','forca'],['Resistência','resistencia'],['Velocidade','velocidade'],['Sentidos','sentidos'],['Inteligência','inteligencia'],['Poder Mágico','poder_magico']];return <div className="system-page"><div className="section-heading"><div><small>STATUS DO CAÇADOR</small><h1>{p.nome}</h1><p>{p.classe} • {p.classe_avancada||'Sem classe avançada'} • Rank {p.rank}</p></div><div className="rank-badge">{p.rank}</div></div><div className="character-layout"><article className="sys-panel attribute-panel"><h3><Activity/> ATRIBUTOS</h3>{stats.map(([label,key])=><div className="stat-row" key={key}><span>{label}</span><b>{fmt(p[`${key}_total`])}</b><small>Base {fmt(p[`${key}_base`])} • Buff {fmt(p[`${key}_buff`])}</small></div>)}</article><article className="character-stage"><CharacterRender avatar={avatar} name={p.nome}/><label className="upload-character"><Upload/> ALTERAR PNG<input type="file" accept="image/png,image/webp" onChange={e=>save(e.target.files?.[0])}/></label></article><article className="sys-panel status-panel"><h3><HeartPulse/> STATUS</h3><div className="level-block"><b>{p.nivel}</b><span>LEVEL</span></div><div className="identity-list"><div><span>Classe</span><b>{p.classe}</b></div><div><span>Classe Avançada</span><b>{p.classe_avancada||'—'}</b></div><div><span>Título</span><b>{p.titulo||'Nenhum'}</b></div><div><span>Guilda</span><b>{data.guild?.nome||'Independente'}</b></div><div><span>Localização</span><b>{data.location?.city_id||'seoul'}</b></div></div><Progress value={p.vida_atual} max={p.vida_maxima} label="HP" tone="red"/><Progress value={p.mana_atual} max={p.mana_maxima} label="MP"/><Progress value={p.experiencia||0} max={Math.max(Number(p.experiencia||1),1)} label="EXP" tone="violet"/></article></div></div>}

function InventoryPage({data}:{data:LivePayload}){const[filter,setFilter]=useState('Todos');const cats=['Todos','Armas','Armaduras','Acessórios','Consumíveis','Materiais'];const items=useMemo(()=>data.inventory.filter(i=>{if(filter==='Todos')return true;const s=(i.slot||i.categoria||'').toLowerCase();if(filter==='Armas')return s.includes('arma');if(filter==='Armaduras')return ['cabeça','corpo','pernas','pés'].some(x=>s.includes(x.normalize('NFD').replace(/[\u0300-\u036f]/g,'')))||i.armadura;if(filter==='Acessórios')return s.includes('acess');if(filter==='Consumíveis')return i.consumivel;return !i.consumivel&&!i.arma&&!i.armadura&&!i.acessorio}),[data.inventory,filter]);return <div className="system-page"><div className="section-heading"><div><small>ARMAZENAMENTO</small><h1>Inventário</h1><p>{data.inventory.length} tipos de item registrados.</p></div><div className="wallet-pill"><CircleDollarSign/> ₩ {fmt(data.player.won)}</div></div><div className="filter-row">{cats.map(c=><button className={filter===c?'active':''} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><div className="inventory-page-grid"><article className="sys-panel item-grid">{items.map(item=><div className={`inventory-item rank-${String(item.tier||'').toLowerCase()}`} key={item.id}><span className="item-icon">{item.arma?'⚔':item.consumivel?'✦':item.acessorio?'◆':'⬢'}</span><b>{item.nome}</b><small>{item.slot||item.categoria}</small><em>x{item.quantidade}</em>{item.equipado&&<i>EQUIPADO</i>}</div>)}</article><aside className="sys-panel inventory-summary"><Backpack/><h3>Capacidade</h3><b>{data.inventory.reduce((a,i)=>a+Number(i.quantidade||0),0)} itens</b><p>Toque em um item para conferir detalhes e use a página de Equipamentos para alterar o loadout.</p></aside></div></div>}

function EquipmentPage({data}:{data:LivePayload}){const p=data.player;const{avatar,save}=useAvatar(p.nome);const[busy,setBusy]=useState<number|null>(null);const[error,setError]=useState('');const eq=data.inventory.filter(i=>i.equipado);const slots=[['Cabeça',1],['Corpo',1],['Pernas',2],['Pés',1],['Acessórios',4],['Item de Apoio',1],['Arma 1',2],['Arma 2',1]] as const;const equipped=(slot:string,index:number)=>eq.filter(i=>i.slot===slot)[index];const action=async(item:any)=>{setBusy(item.id);setError('');try{const r=await fetch('/api/equipment',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({itemId:item.id})});const d=await readJson(r);if(!r.ok)throw new Error(d.error||'Falha ao equipar.');location.reload()}catch(e){setError(e instanceof Error?e.message:'Falha ao equipar.')}finally{setBusy(null)}};return <div className="system-page"><div className="section-heading"><div><small>LOADOUT OFICIAL DO RPG</small><h1>Equipamentos</h1><p>Slots verificados no sistema do bot. Arma 2 (2FP) bloqueia os dois slots de Arma 1.</p></div></div>{error&&<div className="system-error">{error}</div>}<div className="equipment-layout"><div className="equipment-side left">{slots.slice(0,4).flatMap(([s,c])=>Array.from({length:c},(_,i)=><EquipSlot key={`${s}${i}`} name={s} index={i} item={equipped(s,i)}/>))}</div><div className="equipment-center"><CharacterRender avatar={avatar} name={p.nome}/><label className="upload-character small"><Upload/> PNG<input type="file" accept="image/png,image/webp" onChange={e=>save(e.target.files?.[0])}/></label><div className="weapon-slots">{slots.slice(6).flatMap(([s,c])=>Array.from({length:c},(_,i)=><EquipSlot key={`${s}${i}`} name={s} index={i} item={equipped(s,i)}/>))}</div></div><div className="equipment-side right">{slots.slice(4,6).flatMap(([s,c])=>Array.from({length:c},(_,i)=><EquipSlot key={`${s}${i}`} name={s} index={i} item={equipped(s,i)}/>))}</div></div><div className="equipment-inventory sys-panel"><h3>ITENS EQUIPÁVEIS</h3><div className="equip-actions">{data.inventory.filter(i=>!i.consumivel).map(item=><button className={item.equipado?'equipped':''} disabled={busy===item.id} onClick={()=>action(item)} key={item.id}><Shield/><span><b>{item.nome}</b><small>{item.slot}</small></span><em>{busy===item.id?'...':item.equipado?'DESEQUIPAR':'EQUIPAR'}</em></button>)}</div></div></div>}
function EquipSlot({name,index,item}:{name:string,index:number,item:any}){return <div className={`equip-slot-card ${item?'filled':''}`}><small>{name}{['Pernas','Acessórios','Arma 1'].includes(name)?` ${index+1}`:''}</small>{item?<><b>{item.nome}</b><span>Rank {item.tier||'—'}</span></>:<><Shield/><span>VAZIO</span></>}</div>}

function SkillsPage({data}:{data:LivePayload}){return <div className="system-page"><div className="section-heading"><div><small>ARSENAL DE COMBATE</small><h1>Habilidades & Técnicas</h1><p>Técnicas sincronizadas com o personagem real.</p></div><div className="wallet-pill mastery"><WandSparkles/> {fmt(data.player.maestria)} Maestria</div></div><div className="skill-grid">{data.skills.map(s=><article className="sys-panel skill-tile" key={s.id}><div className="skill-glyph"><Zap/></div><small>{s.classe} • Nv. {s.nivel}</small><h3>{s.nome}</h3><p>{s.descricao||'Sem descrição cadastrada.'}</p><footer><span>{s.custo_mana||0} MP</span><b>{s.equipada?'EQUIPADA':'DISPONÍVEL'}</b></footer></article>)}</div></div>}

function GenericListPage({section,data}:{section:Section,data:LivePayload}){const[items,setItems]=useState<any[]>([]);useEffect(()=>{const path=section==='missoes'?'/api/quests':section==='npcs'?'/api/npcs':section==='dungeons'?'/api/dungeons':null;if(path)fetch(path,{cache:'no-store'}).then(r=>r.json()).then(d=>setItems(d.quests||d.npcs||d.active||[])).catch(()=>{})},[section]);if(section==='guilda')return <div className="system-page"><div className="section-heading"><div><small>ORGANIZAÇÃO</small><h1>Guilda</h1></div></div><article className="sys-panel empty-feature"><Crown/><h2>{data.guild?.nome||'Nenhuma guilda'}</h2><p>{data.guild?'Seu vínculo de guilda está sincronizado com o RPG.':'Seu caçador ainda é independente. Seul continua neutra e não pode ser conquistada.'}</p></article></div>;if(section==='titulos')return <div className="system-page"><div className="section-heading"><div><small>CONQUISTAS</small><h1>Títulos & Passivas</h1></div></div><div className="skill-grid">{data.titles.map(t=><article className="sys-panel skill-tile" key={t}><Trophy/><h3>{t}</h3><p>Título persistido do personagem.</p></article>)}{data.passives.map((x:any,i)=><article className="sys-panel skill-tile" key={i}><Sparkles/><h3>{x.nome||String(x)}</h3><p>Passiva ativa.</p></article>)}</div></div>;const title=section==='missoes'?'Missões':section==='npcs'?'NPCs':'Dungeons';return <div className="system-page"><div className="section-heading"><div><small>{section==='dungeons'?'GATES ATIVOS':'ARQUIVOS DO SISTEMA'}</small><h1>{title}</h1></div></div><div className="mission-list">{items.map((x:any,i)=><article className="sys-panel mission-card" key={x.id||i}>{section==='missoes'?<ScrollText/>:section==='npcs'?<Users/>:<Swords/>}<div><small>{x.status||x.profissao||`Rank ${x.rank||'—'}`}</small><h3>{x.nome||x.name}</h3><p>{x.descricao||x.description||x.objetivo_texto||x.localizacao||'Sem descrição.'}</p></div>{x.recompensa_xp!=null&&<b>{fmt(x.recompensa_xp)} XP</b>}</article>)}{!items.length&&<article className="sys-panel empty-feature"><BookOpen/><h3>Nenhum registro disponível agora.</h3></article>}</div></div>}

function ShopPage({data}:{data:LivePayload}){const[shop,setShop]=useState<any[]>([]);const[busy,setBusy]=useState<any>(null);const[msg,setMsg]=useState('');useEffect(()=>{fetch('/api/shop').then(r=>r.json()).then(d=>setShop(d.items||[])).catch(()=>{})},[]);const buy=async(item:any)=>{setBusy(item.id);setMsg('');try{const r=await fetch('/api/shop',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({itemId:item.id})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMsg(`${item.nome} adquirido.`)}catch(e){setMsg(e instanceof Error?e.message:'Compra falhou.')}finally{setBusy(null)}};return <div className="system-page"><div className="section-heading"><div><small>MERCADO DA ASSOCIAÇÃO</small><h1>Loja</h1></div><div className="wallet-pill"><CircleDollarSign/> ₩ {fmt(data.player.won)}</div></div>{msg&&<div className="system-message">{msg}</div>}<div className="shop-grid">{shop.map(item=><article className="sys-panel shop-card" key={item.id}><div className="shop-icon"><Gem/></div><small>{item.tier||item.categoria}</small><h3>{item.nome}</h3><p>{item.descricao||'Item registrado no catálogo.'}</p><footer><b>₩ {fmt(item.preco||item.valor)}</b><button disabled={busy===item.id} onClick={()=>buy(item)}>{busy===item.id?'...':'COMPRAR'}</button></footer></article>)}</div></div>}

export default function HunterPortal({section}:{section:Section}){const[data,setData]=useState<LivePayload|null>(null);const[error,setError]=useState('');useEffect(()=>{fetch('/api/me',{cache:'no-store'}).then(async r=>{if(r.status===401){location.href='/login';return null}const d=await r.json();if(!r.ok)throw new Error(d.error);return d}).then(d=>d&&setData(d)).catch(e=>setError(e.message))},[]);if(!data)return <div className="system-loading"><div className="loading-rune"/><small>SYSTEM INITIALIZING</small><h1>{error||'Sincronizando dados do Caçador...'}</h1></div>;let page:React.ReactNode;if(section==='inicio')page=<Dashboard data={data}/>;else if(section==='personagem')page=<CharacterPage data={data}/>;else if(section==='inventario')page=<InventoryPage data={data}/>;else if(section==='equipamentos')page=<EquipmentPage data={data}/>;else if(section==='habilidades')page=<SkillsPage data={data}/>;else if(section==='mapa')page=<MapViewer/>;else if(section==='loja')page=<ShopPage data={data}/>;else page=<GenericListPage section={section} data={data}/>;return <Shell section={section} data={data}>{page}</Shell>}
