/**
 * TÉCNICAS DE ESTILO DE LUTA: Proficiência em Báculos
 * Catálogo com 9 técnicas exclusivas.
 */

const catalogo = {
    "nome": "Báculos",
    "descricao_classe": "Especialista em armas mágicas focadas em suporte e canalização.",
    "categoria": "Proficiencia",
    "arma": "Báculos ou semelhantes",
    "tecnicaInicial": {
        "nome": "Canal Arcano",
        "classe": "Báculos",
        "categoria": "Proficiencia",
        "tipo": "Física",
        "descricao": "O usuário segura o báculo verticalmente à frente do corpo, ambas as mãos próximas ao centro de gravidade, e o báculo se torna extensão natural do próprio corpo desde o primeiro movimento. Mantém passos curtos e comedidos, preservando a concentração necessária para canalizar, cada repetição do gesto entalhando a técnica um pouco mais fundo na memória muscular. No instante em que o báculo finalmente aponta a ponta entalhada do báculo e libera a mana acumulada em um jato direcionado, um zumbido grave de mana se acumulando na madeira antes da liberação marca o impacto — a base sobre a qual toda a proficiência em Báculos será construída.",
        "descricao_completa": "O usuário segura o báculo verticalmente à frente do corpo, ambas as mãos próximas ao centro de gravidade, e o báculo se torna extensão natural do próprio corpo desde o primeiro movimento. Mantém passos curtos e comedidos, preservando a concentração necessária para canalizar, cada repetição do gesto entalhando a técnica um pouco mais fundo na memória muscular. No instante em que o báculo finalmente aponta a ponta entalhada do báculo e libera a mana acumulada em um jato direcionado, um zumbido grave de mana se acumulando na madeira antes da liberação marca o impacto — a base sobre a qual toda a proficiência em Báculos será construída. O ganho é direto: +15% de eficácia no impacto com Báculos, e nada além disso muda.",
        "custo_mana": 600,
        "custo_qi": 10,
        "custo_qi_formatado": "10 de Maestria",
        "custo_maestria": 10,
        "custo_maestria_formatado": "10 de Maestria",
        "cooldown": 1,
        "nivel_desbloqueio": 1,
        "passiva": false
    },
    "tecnicas": [
        {
            "nome": "Báculo de Merlin",
            "classe": "Báculos",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Sem pressa e sem desperdício, o usuário lê a guarda do oponente antes de agir: mantém passos curtos e comedidos, preservando a concentração necessária para canalizar até o ângulo certo se abrir. É só então que o báculo aponta a ponta entalhada do báculo e libera a mana acumulada em um jato direcionado. Não é o golpe mais forte que essa técnica busca, mas o mais preciso — aquele que encontra a única fresta que realmente importa, ignorando o que a defesa do inimigo parecia garantir.",
            "descricao_completa": "Sem pressa e sem desperdício, o usuário lê a guarda do oponente antes de agir: mantém passos curtos e comedidos, preservando a concentração necessária para canalizar até o ângulo certo se abrir. É só então que o báculo aponta a ponta entalhada do báculo e libera a mana acumulada em um jato direcionado. Não é o golpe mais forte que essa técnica busca, mas o mais preciso — aquele que encontra a única fresta que realmente importa, ignorando o que a defesa do inimigo parecia garantir. Mecanicamente, um acerto limpo faz o ataque ignorar 15% da Resistência do inimigo, sem afetar os próximos turnos.",
            "custo_mana": 900,
            "custo_qi": 20,
            "custo_qi_formatado": "20 de Maestria",
            "custo_maestria": 20,
            "custo_maestria_formatado": "20 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 6,
            "passiva": false
        },
        {
            "nome": "Passo Rúnico",
            "classe": "Báculos",
            "categoria": "Proficiencia",
            "tipo": "Movimentação",
            "descricao": "Antes que o oponente perceba, o usuário já não está mais onde estava: mantém passos curtos e comedidos, preservando a concentração necessária para canalizar, cobrindo em um instante a distância que segundos antes parecia segura. O báculo acompanha cada passo sem quebrar o ritmo ofensivo, e o reposicionamento termina com o corpo já alinhado para o próximo golpe — a guarda inimiga sempre um passo atrás.",
            "descricao_completa": "Antes que o oponente perceba, o usuário já não está mais onde estava: mantém passos curtos e comedidos, preservando a concentração necessária para canalizar, cobrindo em um instante a distância que segundos antes parecia segura. O báculo acompanha cada passo sem quebrar o ritmo ofensivo, e o reposicionamento termina com o corpo já alinhado para o próximo golpe — a guarda inimiga sempre um passo atrás. Na prática, o usuário se reposiciona em até 5m sem perder a ação ofensiva do turno, e o próximo ataque deste estilo ganha +10% de Agilidade.",
            "custo_mana": 700,
            "custo_qi": 40,
            "custo_qi_formatado": "40 de Maestria",
            "custo_maestria": 40,
            "custo_maestria_formatado": "40 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 11,
            "passiva": false,
            "alcance": "5M"
        },
        {
            "nome": "Selo do Mago",
            "classe": "Báculos",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "O usuário força a entrada: mantém passos curtos e comedidos, preservando a concentração necessária para canalizar, testando a resistência do oponente até que ela cede. Um zumbido grave de mana se acumulando na madeira antes da liberação anuncia o instante em que o báculo aponta a ponta entalhada do báculo e libera a mana acumulada em um jato direcionado e a guarda inimiga racha — não se rompe de vez, mas fica visivelmente mais frágil, exposta para o que vier a seguir.",
            "descricao_completa": "O usuário força a entrada: mantém passos curtos e comedidos, preservando a concentração necessária para canalizar, testando a resistência do oponente até que ela cede. Um zumbido grave de mana se acumulando na madeira antes da liberação anuncia o instante em que o báculo aponta a ponta entalhada do báculo e libera a mana acumulada em um jato direcionado e a guarda inimiga racha — não se rompe de vez, mas fica visivelmente mais frágil, exposta para o que vier a seguir. Na prática, vencer a Resistência do oponente nesse confronto aplica -15% de Resistência nele por 1 turno.",
            "custo_mana": 1200,
            "custo_qi": 70,
            "custo_qi_formatado": "70 de Maestria",
            "custo_maestria": 70,
            "custo_maestria_formatado": "70 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 16,
            "passiva": false
        },
        {
            "nome": "Círculo de Ley",
            "classe": "Báculos",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Mantém passos curtos e comedidos, preservando a concentração necessária para canalizar, o usuário transforma toda a área ao redor em zona de perigo constante, o báculo alcançando tudo dentro do raio de ação enquanto aponta a ponta entalhada do báculo e libera a mana acumulada em um jato direcionado. Cada golpe encadeia com o anterior, e quem já foi tocado antes pela mesma proficiência em Báculos sente o dobro da dor quando a sequência retorna.",
            "descricao_completa": "Mantém passos curtos e comedidos, preservando a concentração necessária para canalizar, o usuário transforma toda a área ao redor em zona de perigo constante, o báculo alcançando tudo dentro do raio de ação enquanto aponta a ponta entalhada do báculo e libera a mana acumulada em um jato direcionado. Cada golpe encadeia com o anterior, e quem já foi tocado antes pela mesma proficiência em Báculos sente o dobro da dor quando a sequência retorna. O golpe alcança até 6m ao redor do usuário e causa +20% de dano a mais em alvos marcados pelo estilo no turno anterior.",
            "custo_mana": 1500,
            "custo_qi": 110,
            "custo_qi_formatado": "110 de Maestria",
            "custo_maestria": 110,
            "custo_maestria_formatado": "110 de Maestria",
            "cooldown": 4,
            "nivel_desbloqueio": 21,
            "passiva": false,
            "alcance": "6M"
        },
        {
            "nome": "Memória Arcana",
            "classe": "Báculos",
            "categoria": "Proficiencia",
            "tipo": "Passiva",
            "descricao": "Essa é uma vantagem silenciosa, construída golpe a golpe: cada vez que o báculo aponta a ponta entalhada do báculo e libera a mana acumulada em um jato direcionado com sucesso, o usuário sente o próprio corpo responder com mais naturalidade, como se revivesse cada hora de treino investida em Báculos. Mesmo nos intervalos entre um golpe e outro, quando o usuário mantém passos curtos e comedidos, preservando a concentração necessária para canalizar, esse estado se mantém — mas basta parar de atacar para que o encanto se desfaça rapidamente.",
            "descricao_completa": "Essa é uma vantagem silenciosa, construída golpe a golpe: cada vez que o báculo aponta a ponta entalhada do báculo e libera a mana acumulada em um jato direcionado com sucesso, o usuário sente o próprio corpo responder com mais naturalidade, como se revivesse cada hora de treino investida em Báculos. Mesmo nos intervalos entre um golpe e outro, quando o usuário mantém passos curtos e comedidos, preservando a concentração necessária para canalizar, esse estado se mantém — mas basta parar de atacar para que o encanto se desfaça rapidamente. Mecanicamente, 3 acertos consecutivos concedem +10% de eficiência nas técnicas deste estilo, mantido enquanto o ataque não parar.",
            "custo_mana": 0,
            "custo_qi": 160,
            "custo_qi_formatado": "160 de Maestria",
            "custo_maestria": 160,
            "custo_maestria_formatado": "160 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 26,
            "passiva": true
        },
        {
            "nome": "Retorno de Mana",
            "classe": "Báculos",
            "categoria": "Proficiencia",
            "tipo": "Defesa",
            "descricao": "Ao perceber o golpe se aproximando, o usuário não recua: mantém passos curtos e comedidos, preservando a concentração necessária para canalizar, posicionando o báculo exatamente onde o impacto será absorvido. O que seria dano vira apenas um custo menor, e antes que o oponente se recomponha, o báculo já responde — bloquear deixou de ser passivo há muito tempo para quem domina essa técnica.",
            "descricao_completa": "Ao perceber o golpe se aproximando, o usuário não recua: mantém passos curtos e comedidos, preservando a concentração necessária para canalizar, posicionando o báculo exatamente onde o impacto será absorvido. O que seria dano vira apenas um custo menor, e antes que o oponente se recomponha, o báculo já responde — bloquear deixou de ser passivo há muito tempo para quem domina essa técnica. Ao aparar ou evitar um ataque compatível, o dano recebido cai 25% e um contra-ataque com +10% de dano fica pronto para uso.",
            "custo_mana": 1200,
            "custo_qi": 230,
            "custo_qi_formatado": "230 de Maestria",
            "custo_maestria": 230,
            "custo_maestria_formatado": "230 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 31,
            "passiva": false
        },
        {
            "nome": "Estrela de Avalon",
            "classe": "Báculos",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "O usuário canaliza muito além do que o corpo pede, e o báculo carrega essa energia excedente até o limite. O corpo segura o báculo verticalmente à frente do corpo, ambas as mãos próximas ao centro de gravidade em um único instante de tensão máxima antes da liberação — um zumbido grave de mana se acumulando na madeira antes da liberação, seguido de um golpe brutal e vistoso. É um ataque tudo ou quase nada, e o próprio corpo cobra o preço logo em seguida, exigindo um intervalo antes de arriscar tudo outra vez.",
            "descricao_completa": "O usuário canaliza muito além do que o corpo pede, e o báculo carrega essa energia excedente até o limite. O corpo segura o báculo verticalmente à frente do corpo, ambas as mãos próximas ao centro de gravidade em um único instante de tensão máxima antes da liberação — um zumbido grave de mana se acumulando na madeira antes da liberação, seguido de um golpe brutal e vistoso. É um ataque tudo ou quase nada, e o próprio corpo cobra o preço logo em seguida, exigindo um intervalo antes de arriscar tudo outra vez. Na prática, são +35% de dano em um único golpe concentrado, que exige um turno de intervalo antes de ser usado de novo.",
            "custo_mana": 2200,
            "custo_qi": 320,
            "custo_qi_formatado": "320 de Maestria",
            "custo_maestria": 320,
            "custo_maestria_formatado": "320 de Maestria",
            "cooldown": 5,
            "nivel_desbloqueio": 36,
            "passiva": false
        },
        {
            "nome": "Jardim de Magia",
            "classe": "Báculos",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Esta é a técnica definitiva de Báculos: o usuário mantém passos curtos e comedidos, preservando a concentração necessária para canalizar até o instante exato, segura o báculo verticalmente à frente do corpo, ambas as mãos próximas ao centro de gravidade, e então um golpe da base do báculo no chão que libera toda a energia acumulada de uma vez. Um zumbido grave de mana se acumulando na madeira antes da liberação marca o golpe mais temido de toda a proficiência — capaz de romper defesas que segundos antes pareciam impossíveis de quebrar. Adversários experientes reconhecem a postura antes mesmo do movimento começar, e sabem exatamente o que ela significa. Por isso, o corpo só permite esse esforço uma única vez em cada combate.",
            "descricao_completa": "Esta é a técnica definitiva de Báculos: o usuário mantém passos curtos e comedidos, preservando a concentração necessária para canalizar até o instante exato, segura o báculo verticalmente à frente do corpo, ambas as mãos próximas ao centro de gravidade, e então um golpe da base do báculo no chão que libera toda a energia acumulada de uma vez. Um zumbido grave de mana se acumulando na madeira antes da liberação marca o golpe mais temido de toda a proficiência — capaz de romper defesas que segundos antes pareciam impossíveis de quebrar. Adversários experientes reconhecem a postura antes mesmo do movimento começar, e sabem exatamente o que ela significa. Por isso, o corpo só permite esse esforço uma única vez em cada combate. O efeito máximo: +50% de dano e 20% de Resistência ignorada, reservado para um único uso em toda a luta.",
            "custo_mana": 3500,
            "custo_qi": 450,
            "custo_qi_formatado": "450 de Maestria",
            "custo_maestria": 450,
            "custo_maestria_formatado": "450 de Maestria",
            "cooldown": 7,
            "nivel_desbloqueio": 41,
            "passiva": false,
            "alcance": "Até 12M conforme a arma"
        }
    ]
};

module.exports = catalogo;
