/**
 * TÉCNICAS DE ESTILO DE LUTA: Proficiência em Correntes com Foice
 * Catálogo com 9 técnicas exclusivas.
 */

const catalogo = {
    "nome": "Correntes com Foice",
    "descricao_classe": "Especialista em armas híbridas de corrente e foice.",
    "categoria": "Proficiencia",
    "arma": "Kusarigama ou semelhantes",
    "tecnicaInicial": {
        "nome": "Lua Acorrentada",
        "classe": "Correntes com Foice",
        "categoria": "Proficiencia",
        "tipo": "Física",
        "descricao": "O usuário segura a corrente enrolada em uma mão e a foice pronta na outra, o corpo em ângulo baixo, e a kusarigama se torna extensão natural do próprio corpo desde o primeiro movimento. Circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice, cada repetição do gesto entalhando a técnica um pouco mais fundo na memória muscular. No instante em que a kusarigama finalmente arremessa a foice presa à corrente para prender o alvo, puxando-o com força antes do golpe final da lâmina, o zunido da corrente girando seguido do corte seco da lâmina curva marca o impacto — a base sobre a qual toda a proficiência em Correntes com Foice será construída.",
        "descricao_completa": "O usuário segura a corrente enrolada em uma mão e a foice pronta na outra, o corpo em ângulo baixo, e a kusarigama se torna extensão natural do próprio corpo desde o primeiro movimento. Circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice, cada repetição do gesto entalhando a técnica um pouco mais fundo na memória muscular. No instante em que a kusarigama finalmente arremessa a foice presa à corrente para prender o alvo, puxando-o com força antes do golpe final da lâmina, o zunido da corrente girando seguido do corte seco da lâmina curva marca o impacto — a base sobre a qual toda a proficiência em Correntes com Foice será construída. Na prática, o golpe recebe +15% de eficácia no impacto ao usar Correntes com Foice, sem alterar nenhum outro atributo.",
        "custo_mana": 600,
        "custo_qi": 10,
        "custo_qi_formatado": "10 de Maestria",
        "custo_maestria": 10,
        "custo_maestria_formatado": "10 de Maestria",
        "cooldown": 1,
        "nivel_desbloqueio": 1,
        "passiva": false
    },
    "tecnicas": [
        {
            "nome": "Kusarigama de Hanzo",
            "classe": "Correntes com Foice",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Sem pressa e sem desperdício, o usuário lê a guarda do oponente antes de agir: circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice até o ângulo certo se abrir. É só então que a kusarigama arremessa a foice presa à corrente para prender o alvo, puxando-o com força antes do golpe final da lâmina. Não é o golpe mais forte que essa técnica busca, mas o mais preciso — aquele que encontra a única fresta que realmente importa, ignorando o que a defesa do inimigo parecia garantir.",
            "descricao_completa": "Sem pressa e sem desperdício, o usuário lê a guarda do oponente antes de agir: circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice até o ângulo certo se abrir. É só então que a kusarigama arremessa a foice presa à corrente para prender o alvo, puxando-o com força antes do golpe final da lâmina. Não é o golpe mais forte que essa técnica busca, mas o mais preciso — aquele que encontra a única fresta que realmente importa, ignorando o que a defesa do inimigo parecia garantir. Na prática, um acerto bem-sucedido ignora 15% da Resistência do oponente, só nesse instante.",
            "custo_mana": 900,
            "custo_qi": 20,
            "custo_qi_formatado": "20 de Maestria",
            "custo_maestria": 20,
            "custo_maestria_formatado": "20 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 6,
            "passiva": false
        },
        {
            "nome": "Passo do Shinobi",
            "classe": "Correntes com Foice",
            "categoria": "Proficiencia",
            "tipo": "Movimentação",
            "descricao": "Antes que o oponente perceba, o usuário já não está mais onde estava: circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice, cobrindo em um instante a distância que segundos antes parecia segura. A kusarigama acompanha cada passo sem quebrar o ritmo ofensivo, e o reposicionamento termina com o corpo já alinhado para o próximo golpe — a guarda inimiga sempre um passo atrás.",
            "descricao_completa": "Antes que o oponente perceba, o usuário já não está mais onde estava: circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice, cobrindo em um instante a distância que segundos antes parecia segura. A kusarigama acompanha cada passo sem quebrar o ritmo ofensivo, e o reposicionamento termina com o corpo já alinhado para o próximo golpe — a guarda inimiga sempre um passo atrás. Mecanicamente, são até 5m de deslocamento gratuito, seguidos de +10% de Agilidade no próximo ataque do estilo.",
            "custo_mana": 700,
            "custo_qi": 40,
            "custo_qi_formatado": "40 de Maestria",
            "custo_maestria": 40,
            "custo_maestria_formatado": "40 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 11,
            "passiva": false,
            "alcance": "5M"
        },
        {
            "nome": "Gancho da Lua",
            "classe": "Correntes com Foice",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "O usuário força a entrada: circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice, testando a resistência do oponente até que ela cede. O zunido da corrente girando seguido do corte seco da lâmina curva anuncia o instante em que a kusarigama arremessa a foice presa à corrente para prender o alvo, puxando-o com força antes do golpe final da lâmina e a guarda inimiga racha — não se rompe de vez, mas fica visivelmente mais frágil, exposta para o que vier a seguir.",
            "descricao_completa": "O usuário força a entrada: circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice, testando a resistência do oponente até que ela cede. O zunido da corrente girando seguido do corte seco da lâmina curva anuncia o instante em que a kusarigama arremessa a foice presa à corrente para prender o alvo, puxando-o com força antes do golpe final da lâmina e a guarda inimiga racha — não se rompe de vez, mas fica visivelmente mais frágil, exposta para o que vier a seguir. Mecanicamente, superar a defesa do inimigo aqui custa a ele -15% de Resistência pelo turno seguinte.",
            "custo_mana": 1200,
            "custo_qi": 70,
            "custo_qi_formatado": "70 de Maestria",
            "custo_maestria": 70,
            "custo_maestria_formatado": "70 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 16,
            "passiva": false
        },
        {
            "nome": "Círculo da Corrente",
            "classe": "Correntes com Foice",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice, o usuário transforma toda a área ao redor em zona de perigo constante, a kusarigama alcançando tudo dentro do raio de ação enquanto arremessa a foice presa à corrente para prender o alvo, puxando-o com força antes do golpe final da lâmina. Cada golpe encadeia com o anterior, e quem já foi tocado antes pela mesma proficiência em Correntes com Foice sente o dobro da dor quando a sequência retorna.",
            "descricao_completa": "Circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice, o usuário transforma toda a área ao redor em zona de perigo constante, a kusarigama alcançando tudo dentro do raio de ação enquanto arremessa a foice presa à corrente para prender o alvo, puxando-o com força antes do golpe final da lâmina. Cada golpe encadeia com o anterior, e quem já foi tocado antes pela mesma proficiência em Correntes com Foice sente o dobro da dor quando a sequência retorna. A técnica cobre até 6m ao redor ou à frente do usuário, causando +20% de dano contra alvos já atingidos por outra técnica deste estilo no turno anterior.",
            "custo_mana": 1500,
            "custo_qi": 110,
            "custo_qi_formatado": "110 de Maestria",
            "custo_maestria": 110,
            "custo_maestria_formatado": "110 de Maestria",
            "cooldown": 4,
            "nivel_desbloqueio": 21,
            "passiva": false,
            "alcance": "6M"
        },
        {
            "nome": "Pulso do Assassino",
            "classe": "Correntes com Foice",
            "categoria": "Proficiencia",
            "tipo": "Passiva",
            "descricao": "Essa é uma vantagem silenciosa, construída golpe a golpe: cada vez que a kusarigama arremessa a foice presa à corrente para prender o alvo, puxando-o com força antes do golpe final da lâmina com sucesso, o usuário sente o próprio corpo responder com mais naturalidade, como se revivesse cada hora de treino investida em Correntes com Foice. Mesmo nos intervalos entre um golpe e outro, quando o usuário circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice, esse estado se mantém — mas basta parar de atacar para que o encanto se desfaça rapidamente.",
            "descricao_completa": "Essa é uma vantagem silenciosa, construída golpe a golpe: cada vez que a kusarigama arremessa a foice presa à corrente para prender o alvo, puxando-o com força antes do golpe final da lâmina com sucesso, o usuário sente o próprio corpo responder com mais naturalidade, como se revivesse cada hora de treino investida em Correntes com Foice. Mesmo nos intervalos entre um golpe e outro, quando o usuário circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice, esse estado se mantém — mas basta parar de atacar para que o encanto se desfaça rapidamente. Na prática, acumular 3 acertos ativa +10% de eficiência nas técnicas do estilo, efeito que dura até um turno sem ataques.",
            "custo_mana": 0,
            "custo_qi": 160,
            "custo_qi_formatado": "160 de Maestria",
            "custo_maestria": 160,
            "custo_maestria_formatado": "160 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 26,
            "passiva": true
        },
        {
            "nome": "Retorno da Kusari",
            "classe": "Correntes com Foice",
            "categoria": "Proficiencia",
            "tipo": "Defesa",
            "descricao": "Ao perceber o golpe se aproximando, o usuário não recua: circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice, posicionando a kusarigama exatamente onde o impacto será absorvido. O que seria dano vira apenas um custo menor, e antes que o oponente se recomponha, a kusarigama já responde — bloquear deixou de ser passivo há muito tempo para quem domina essa técnica.",
            "descricao_completa": "Ao perceber o golpe se aproximando, o usuário não recua: circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice, posicionando a kusarigama exatamente onde o impacto será absorvido. O que seria dano vira apenas um custo menor, e antes que o oponente se recomponha, a kusarigama já responde — bloquear deixou de ser passivo há muito tempo para quem domina essa técnica. O efeito é duplo: -25% de dano recebido ao aparar ou evitar o ataque, mais um contra-ataque reforçado em +10% de dano.",
            "custo_mana": 1200,
            "custo_qi": 230,
            "custo_qi_formatado": "230 de Maestria",
            "custo_maestria": 230,
            "custo_maestria_formatado": "230 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 31,
            "passiva": false
        },
        {
            "nome": "Lua que Persegue",
            "classe": "Correntes com Foice",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "O usuário canaliza muito além do que o corpo pede, e a kusarigama carrega essa energia excedente até o limite. O corpo segura a corrente enrolada em uma mão e a foice pronta na outra, o corpo em ângulo baixo em um único instante de tensão máxima antes da liberação — o zunido da corrente girando seguido do corte seco da lâmina curva, seguido de um golpe brutal e vistoso. É um ataque tudo ou quase nada, e o próprio corpo cobra o preço logo em seguida, exigindo um intervalo antes de arriscar tudo outra vez.",
            "descricao_completa": "O usuário canaliza muito além do que o corpo pede, e a kusarigama carrega essa energia excedente até o limite. O corpo segura a corrente enrolada em uma mão e a foice pronta na outra, o corpo em ângulo baixo em um único instante de tensão máxima antes da liberação — o zunido da corrente girando seguido do corte seco da lâmina curva, seguido de um golpe brutal e vistoso. É um ataque tudo ou quase nada, e o próprio corpo cobra o preço logo em seguida, exigindo um intervalo antes de arriscar tudo outra vez. Mecanicamente, o golpe entrega +35% de dano de uma vez só, com um intervalo natural que impede o uso em turnos seguidos.",
            "custo_mana": 2200,
            "custo_qi": 320,
            "custo_qi_formatado": "320 de Maestria",
            "custo_maestria": 320,
            "custo_maestria_formatado": "320 de Maestria",
            "cooldown": 5,
            "nivel_desbloqueio": 36,
            "passiva": false
        },
        {
            "nome": "Prisão do Eclipse",
            "classe": "Correntes com Foice",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Esta é a técnica definitiva de Correntes com Foice: o usuário circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice até o instante exato, segura a corrente enrolada em uma mão e a foice pronta na outra, o corpo em ângulo baixo, e então um lançamento que prende, puxa e corta em uma única sequência ininterrupta. O zunido da corrente girando seguido do corte seco da lâmina curva marca o golpe mais temido de toda a proficiência — capaz de romper defesas que segundos antes pareciam impossíveis de quebrar. Adversários experientes reconhecem a postura antes mesmo do movimento começar, e sabem exatamente o que ela significa. Por isso, o corpo só permite esse esforço uma única vez em cada combate.",
            "descricao_completa": "Esta é a técnica definitiva de Correntes com Foice: o usuário circula o alvo mantendo distância variável, alternando entre o alcance da corrente e o corte da foice até o instante exato, segura a corrente enrolada em uma mão e a foice pronta na outra, o corpo em ângulo baixo, e então um lançamento que prende, puxa e corta em uma única sequência ininterrupta. O zunido da corrente girando seguido do corte seco da lâmina curva marca o golpe mais temido de toda a proficiência — capaz de romper defesas que segundos antes pareciam impossíveis de quebrar. Adversários experientes reconhecem a postura antes mesmo do movimento começar, e sabem exatamente o que ela significa. Por isso, o corpo só permite esse esforço uma única vez em cada combate. O golpe final causa +50% de dano e ignora 20% da Resistência do alvo, com uso limitado a 1 vez por luta.",
            "custo_mana": 3500,
            "custo_qi": 450,
            "custo_qi_formatado": "450 de Maestria",
            "custo_maestria": 450,
            "custo_maestria_formatado": "450 de Maestria",
            "cooldown": 7,
            "nivel_desbloqueio": 41,
            "passiva": false,
            "alcance": "Até 12M conforme a arma"
        }
    ]
};

module.exports = catalogo;
