/**
 * TÉCNICAS DE ESTILO DE LUTA: Proficiência em Correntes
 * Catálogo com 9 técnicas exclusivas.
 */

const catalogo = {
    "nome": "Correntes",
    "descricao_classe": "O usuário domina armas de movimento imprevisível, utilizando alcance, velocidade e controle.",
    "categoria": "Proficiencia",
    "arma": "Correntes ou armas flexíveis",
    "tecnicaInicial": {
        "nome": "Domínio das Correntes",
        "classe": "Correntes",
        "categoria": "Proficiencia",
        "tipo": "Física",
        "descricao": "O usuário segura uma extremidade firme junto ao corpo, deixando o restante da corrente solta e pronta, e a corrente se torna extensão natural do próprio corpo desde o primeiro movimento. Gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo, cada repetição do gesto entalhando a técnica um pouco mais fundo na memória muscular. No instante em que a corrente finalmente arremessa os elos em espiral, prendendo e golpeando o alvo à distância antes de recolher com um puxão seco, o tilintar metálico dos elos se chocando entre si em rotação constante marca o impacto — a base sobre a qual toda a proficiência em Correntes será construída.",
        "descricao_completa": "O usuário segura uma extremidade firme junto ao corpo, deixando o restante da corrente solta e pronta, e a corrente se torna extensão natural do próprio corpo desde o primeiro movimento. Gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo, cada repetição do gesto entalhando a técnica um pouco mais fundo na memória muscular. No instante em que a corrente finalmente arremessa os elos em espiral, prendendo e golpeando o alvo à distância antes de recolher com um puxão seco, o tilintar metálico dos elos se chocando entre si em rotação constante marca o impacto — a base sobre a qual toda a proficiência em Correntes será construída. O ganho é direto: +15% de eficácia no impacto com Correntes, e nada além disso muda.",
        "custo_mana": 600,
        "custo_qi": 10,
        "custo_qi_formatado": "10 de Maestria",
        "custo_maestria": 10,
        "custo_maestria_formatado": "10 de Maestria",
        "cooldown": 1,
        "nivel_desbloqueio": 1,
        "passiva": false
    },
    "tecnicas": [
        {
            "nome": "Laço de Andromeda",
            "classe": "Correntes",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Sem pressa e sem desperdício, o usuário lê a guarda do oponente antes de agir: gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo até o ângulo certo se abrir. É só então que a corrente arremessa os elos em espiral, prendendo e golpeando o alvo à distância antes de recolher com um puxão seco. Não é o golpe mais forte que essa técnica busca, mas o mais preciso — aquele que encontra a única fresta que realmente importa, ignorando o que a defesa do inimigo parecia garantir.",
            "descricao_completa": "Sem pressa e sem desperdício, o usuário lê a guarda do oponente antes de agir: gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo até o ângulo certo se abrir. É só então que a corrente arremessa os elos em espiral, prendendo e golpeando o alvo à distância antes de recolher com um puxão seco. Não é o golpe mais forte que essa técnica busca, mas o mais preciso — aquele que encontra a única fresta que realmente importa, ignorando o que a defesa do inimigo parecia garantir. Mecanicamente, um acerto limpo faz o ataque ignorar 15% da Resistência do inimigo, sem afetar os próximos turnos.",
            "custo_mana": 900,
            "custo_qi": 20,
            "custo_qi_formatado": "20 de Maestria",
            "custo_maestria": 20,
            "custo_maestria_formatado": "20 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 6,
            "passiva": false
        },
        {
            "nome": "Passo do Carcereiro",
            "classe": "Correntes",
            "categoria": "Proficiencia",
            "tipo": "Movimentação",
            "descricao": "Antes que o oponente perceba, o usuário já não está mais onde estava: gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo, cobrindo em um instante a distância que segundos antes parecia segura. A corrente acompanha cada passo sem quebrar o ritmo ofensivo, e o reposicionamento termina com o corpo já alinhado para o próximo golpe — a guarda inimiga sempre um passo atrás.",
            "descricao_completa": "Antes que o oponente perceba, o usuário já não está mais onde estava: gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo, cobrindo em um instante a distância que segundos antes parecia segura. A corrente acompanha cada passo sem quebrar o ritmo ofensivo, e o reposicionamento termina com o corpo já alinhado para o próximo golpe — a guarda inimiga sempre um passo atrás. Na prática, o usuário se reposiciona em até 5m sem perder a ação ofensiva do turno, e o próximo ataque deste estilo ganha +10% de Agilidade.",
            "custo_mana": 700,
            "custo_qi": 40,
            "custo_qi_formatado": "40 de Maestria",
            "custo_maestria": 40,
            "custo_maestria_formatado": "40 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 11,
            "passiva": false,
            "alcance": "5M"
        },
        {
            "nome": "Nó de Fenrir",
            "classe": "Correntes",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "O usuário força a entrada: gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo, testando a resistência do oponente até que ela cede. O tilintar metálico dos elos se chocando entre si em rotação constante anuncia o instante em que a corrente arremessa os elos em espiral, prendendo e golpeando o alvo à distância antes de recolher com um puxão seco e a guarda inimiga racha — não se rompe de vez, mas fica visivelmente mais frágil, exposta para o que vier a seguir.",
            "descricao_completa": "O usuário força a entrada: gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo, testando a resistência do oponente até que ela cede. O tilintar metálico dos elos se chocando entre si em rotação constante anuncia o instante em que a corrente arremessa os elos em espiral, prendendo e golpeando o alvo à distância antes de recolher com um puxão seco e a guarda inimiga racha — não se rompe de vez, mas fica visivelmente mais frágil, exposta para o que vier a seguir. Na prática, vencer a Resistência do oponente nesse confronto aplica -15% de Resistência nele por 1 turno.",
            "custo_mana": 1200,
            "custo_qi": 70,
            "custo_qi_formatado": "70 de Maestria",
            "custo_maestria": 70,
            "custo_maestria_formatado": "70 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 16,
            "passiva": false
        },
        {
            "nome": "Círculo de Grilhões",
            "classe": "Correntes",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo, o usuário transforma toda a área ao redor em zona de perigo constante, a corrente alcançando tudo dentro do raio de ação enquanto arremessa os elos em espiral, prendendo e golpeando o alvo à distância antes de recolher com um puxão seco. Cada golpe encadeia com o anterior, e quem já foi tocado antes pela mesma proficiência em Correntes sente o dobro da dor quando a sequência retorna.",
            "descricao_completa": "Gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo, o usuário transforma toda a área ao redor em zona de perigo constante, a corrente alcançando tudo dentro do raio de ação enquanto arremessa os elos em espiral, prendendo e golpeando o alvo à distância antes de recolher com um puxão seco. Cada golpe encadeia com o anterior, e quem já foi tocado antes pela mesma proficiência em Correntes sente o dobro da dor quando a sequência retorna. O golpe alcança até 6m ao redor do usuário e causa +20% de dano a mais em alvos marcados pelo estilo no turno anterior.",
            "custo_mana": 1500,
            "custo_qi": 110,
            "custo_qi_formatado": "110 de Maestria",
            "custo_maestria": 110,
            "custo_maestria_formatado": "110 de Maestria",
            "cooldown": 4,
            "nivel_desbloqueio": 21,
            "passiva": false,
            "alcance": "6M"
        },
        {
            "nome": "Memória dos Elos",
            "classe": "Correntes",
            "categoria": "Proficiencia",
            "tipo": "Passiva",
            "descricao": "Essa é uma vantagem silenciosa, construída golpe a golpe: cada vez que a corrente arremessa os elos em espiral, prendendo e golpeando o alvo à distância antes de recolher com um puxão seco com sucesso, o usuário sente o próprio corpo responder com mais naturalidade, como se revivesse cada hora de treino investida em Correntes. Mesmo nos intervalos entre um golpe e outro, quando o usuário gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo, esse estado se mantém — mas basta parar de atacar para que o encanto se desfaça rapidamente.",
            "descricao_completa": "Essa é uma vantagem silenciosa, construída golpe a golpe: cada vez que a corrente arremessa os elos em espiral, prendendo e golpeando o alvo à distância antes de recolher com um puxão seco com sucesso, o usuário sente o próprio corpo responder com mais naturalidade, como se revivesse cada hora de treino investida em Correntes. Mesmo nos intervalos entre um golpe e outro, quando o usuário gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo, esse estado se mantém — mas basta parar de atacar para que o encanto se desfaça rapidamente. Mecanicamente, 3 acertos consecutivos concedem +10% de eficiência nas técnicas deste estilo, mantido enquanto o ataque não parar.",
            "custo_mana": 0,
            "custo_qi": 160,
            "custo_qi_formatado": "160 de Maestria",
            "custo_maestria": 160,
            "custo_maestria_formatado": "160 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 26,
            "passiva": true
        },
        {
            "nome": "Retorno do Prisioneiro",
            "classe": "Correntes",
            "categoria": "Proficiencia",
            "tipo": "Defesa",
            "descricao": "Ao perceber o golpe se aproximando, o usuário não recua: gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo, posicionando a corrente exatamente onde o impacto será absorvido. O que seria dano vira apenas um custo menor, e antes que o oponente se recomponha, a corrente já responde — bloquear deixou de ser passivo há muito tempo para quem domina essa técnica.",
            "descricao_completa": "Ao perceber o golpe se aproximando, o usuário não recua: gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo, posicionando a corrente exatamente onde o impacto será absorvido. O que seria dano vira apenas um custo menor, e antes que o oponente se recomponha, a corrente já responde — bloquear deixou de ser passivo há muito tempo para quem domina essa técnica. Ao aparar ou evitar um ataque compatível, o dano recebido cai 25% e um contra-ataque com +10% de dano fica pronto para uso.",
            "custo_mana": 1200,
            "custo_qi": 230,
            "custo_qi_formatado": "230 de Maestria",
            "custo_maestria": 230,
            "custo_maestria_formatado": "230 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 31,
            "passiva": false
        },
        {
            "nome": "Queda da Âncora",
            "classe": "Correntes",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "O usuário canaliza muito além do que o corpo pede, e a corrente carrega essa energia excedente até o limite. O corpo segura uma extremidade firme junto ao corpo, deixando o restante da corrente solta e pronta em um único instante de tensão máxima antes da liberação — o tilintar metálico dos elos se chocando entre si em rotação constante, seguido de um golpe brutal e vistoso. É um ataque tudo ou quase nada, e o próprio corpo cobra o preço logo em seguida, exigindo um intervalo antes de arriscar tudo outra vez.",
            "descricao_completa": "O usuário canaliza muito além do que o corpo pede, e a corrente carrega essa energia excedente até o limite. O corpo segura uma extremidade firme junto ao corpo, deixando o restante da corrente solta e pronta em um único instante de tensão máxima antes da liberação — o tilintar metálico dos elos se chocando entre si em rotação constante, seguido de um golpe brutal e vistoso. É um ataque tudo ou quase nada, e o próprio corpo cobra o preço logo em seguida, exigindo um intervalo antes de arriscar tudo outra vez. Na prática, são +35% de dano em um único golpe concentrado, que exige um turno de intervalo antes de ser usado de novo.",
            "custo_mana": 2200,
            "custo_qi": 320,
            "custo_qi_formatado": "320 de Maestria",
            "custo_maestria": 320,
            "custo_maestria_formatado": "320 de Maestria",
            "cooldown": 5,
            "nivel_desbloqueio": 36,
            "passiva": false
        },
        {
            "nome": "Cárcere das Cem Correntes",
            "classe": "Correntes",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Esta é a técnica definitiva de Correntes: o usuário gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo até o instante exato, segura uma extremidade firme junto ao corpo, deixando o restante da corrente solta e pronta, e então um giro completo que faz a corrente inteira descrever um círculo antes de se fechar sobre o alvo. O tilintar metálico dos elos se chocando entre si em rotação constante marca o golpe mais temido de toda a proficiência — capaz de romper defesas que segundos antes pareciam impossíveis de quebrar. Adversários experientes reconhecem a postura antes mesmo do movimento começar, e sabem exatamente o que ela significa. Por isso, o corpo só permite esse esforço uma única vez em cada combate.",
            "descricao_completa": "Esta é a técnica definitiva de Correntes: o usuário gira em torno do próprio eixo, mantendo a corrente sempre em movimento circular ao redor do corpo até o instante exato, segura uma extremidade firme junto ao corpo, deixando o restante da corrente solta e pronta, e então um giro completo que faz a corrente inteira descrever um círculo antes de se fechar sobre o alvo. O tilintar metálico dos elos se chocando entre si em rotação constante marca o golpe mais temido de toda a proficiência — capaz de romper defesas que segundos antes pareciam impossíveis de quebrar. Adversários experientes reconhecem a postura antes mesmo do movimento começar, e sabem exatamente o que ela significa. Por isso, o corpo só permite esse esforço uma única vez em cada combate. O efeito máximo: +50% de dano e 20% de Resistência ignorada, reservado para um único uso em toda a luta.",
            "custo_mana": 3500,
            "custo_qi": 450,
            "custo_qi_formatado": "450 de Maestria",
            "custo_maestria": 450,
            "custo_maestria_formatado": "450 de Maestria",
            "cooldown": 7,
            "nivel_desbloqueio": 41,
            "passiva": false,
            "alcance": "Até 12M conforme a arma"
        }
    ]
};

module.exports = catalogo;
