/**
 * TÉCNICAS DE ESTILO DE LUTA: Proficiência em Floretes
 * Catálogo com 9 técnicas exclusivas.
 */

const catalogo = {
    "nome": "Floretes",
    "descricao_classe": "O usuário domina esgrima e ataques extremamente precisos.",
    "categoria": "Proficiencia",
    "arma": "Floretes ou semelhantes",
    "tecnicaInicial": {
        "nome": "Estocada Fantasma",
        "classe": "Floretes",
        "categoria": "Proficiencia",
        "tipo": "Física",
        "descricao": "O usuário mantém a lâmina fina esticada à frente, o corpo de perfil para reduzir o alvo exposto, e o florete se torna extensão natural do próprio corpo desde o primeiro movimento. Avança e recua em passos curtos e elásticos, típicos da esgrima clássica, cada repetição do gesto entalhando a técnica um pouco mais fundo na memória muscular. No instante em que o florete finalmente aplica estocadas leves e precisas, guiadas mais pelo pulso do que pelo braço inteiro, um tinido metálico fino toda vez que a lâmina encontra resistência marca o impacto — a base sobre a qual toda a proficiência em Floretes será construída.",
        "descricao_completa": "O usuário mantém a lâmina fina esticada à frente, o corpo de perfil para reduzir o alvo exposto, e o florete se torna extensão natural do próprio corpo desde o primeiro movimento. Avança e recua em passos curtos e elásticos, típicos da esgrima clássica, cada repetição do gesto entalhando a técnica um pouco mais fundo na memória muscular. No instante em que o florete finalmente aplica estocadas leves e precisas, guiadas mais pelo pulso do que pelo braço inteiro, um tinido metálico fino toda vez que a lâmina encontra resistência marca o impacto — a base sobre a qual toda a proficiência em Floretes será construída. O ganho é direto: +15% de eficácia no impacto com Floretes, e nada além disso muda.",
        "custo_mana": 600,
        "custo_qi": 10,
        "custo_qi_formatado": "10 de Maestria",
        "custo_maestria": 10,
        "custo_maestria_formatado": "10 de Maestria",
        "cooldown": 1,
        "nivel_desbloqueio": 1,
        "passiva": false
    },
    "tecnicas": [
        {
            "nome": "Agulha de Dantès",
            "classe": "Floretes",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Sem pressa e sem desperdício, o usuário lê a guarda do oponente antes de agir: avança e recua em passos curtos e elásticos, típicos da esgrima clássica até o ângulo certo se abrir. É só então que o florete aplica estocadas leves e precisas, guiadas mais pelo pulso do que pelo braço inteiro. Não é o golpe mais forte que essa técnica busca, mas o mais preciso — aquele que encontra a única fresta que realmente importa, ignorando o que a defesa do inimigo parecia garantir.",
            "descricao_completa": "Sem pressa e sem desperdício, o usuário lê a guarda do oponente antes de agir: avança e recua em passos curtos e elásticos, típicos da esgrima clássica até o ângulo certo se abrir. É só então que o florete aplica estocadas leves e precisas, guiadas mais pelo pulso do que pelo braço inteiro. Não é o golpe mais forte que essa técnica busca, mas o mais preciso — aquele que encontra a única fresta que realmente importa, ignorando o que a defesa do inimigo parecia garantir. Mecanicamente, um acerto limpo faz o ataque ignorar 15% da Resistência do inimigo, sem afetar os próximos turnos.",
            "custo_mana": 900,
            "custo_qi": 20,
            "custo_qi_formatado": "20 de Maestria",
            "custo_maestria": 20,
            "custo_maestria_formatado": "20 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 6,
            "passiva": false
        },
        {
            "nome": "Passo do Esgrimista",
            "classe": "Floretes",
            "categoria": "Proficiencia",
            "tipo": "Movimentação",
            "descricao": "Antes que o oponente perceba, o usuário já não está mais onde estava: avança e recua em passos curtos e elásticos, típicos da esgrima clássica, cobrindo em um instante a distância que segundos antes parecia segura. O florete acompanha cada passo sem quebrar o ritmo ofensivo, e o reposicionamento termina com o corpo já alinhado para o próximo golpe — a guarda inimiga sempre um passo atrás.",
            "descricao_completa": "Antes que o oponente perceba, o usuário já não está mais onde estava: avança e recua em passos curtos e elásticos, típicos da esgrima clássica, cobrindo em um instante a distância que segundos antes parecia segura. O florete acompanha cada passo sem quebrar o ritmo ofensivo, e o reposicionamento termina com o corpo já alinhado para o próximo golpe — a guarda inimiga sempre um passo atrás. Na prática, o usuário se reposiciona em até 5m sem perder a ação ofensiva do turno, e o próximo ataque deste estilo ganha +10% de Agilidade.",
            "custo_mana": 700,
            "custo_qi": 40,
            "custo_qi_formatado": "40 de Maestria",
            "custo_maestria": 40,
            "custo_maestria_formatado": "40 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 11,
            "passiva": false,
            "alcance": "5M"
        },
        {
            "nome": "Linha do Coração",
            "classe": "Floretes",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "O usuário força a entrada: avança e recua em passos curtos e elásticos, típicos da esgrima clássica, testando a resistência do oponente até que ela cede. Um tinido metálico fino toda vez que a lâmina encontra resistência anuncia o instante em que o florete aplica estocadas leves e precisas, guiadas mais pelo pulso do que pelo braço inteiro e a guarda inimiga racha — não se rompe de vez, mas fica visivelmente mais frágil, exposta para o que vier a seguir.",
            "descricao_completa": "O usuário força a entrada: avança e recua em passos curtos e elásticos, típicos da esgrima clássica, testando a resistência do oponente até que ela cede. Um tinido metálico fino toda vez que a lâmina encontra resistência anuncia o instante em que o florete aplica estocadas leves e precisas, guiadas mais pelo pulso do que pelo braço inteiro e a guarda inimiga racha — não se rompe de vez, mas fica visivelmente mais frágil, exposta para o que vier a seguir. Na prática, vencer a Resistência do oponente nesse confronto aplica -15% de Resistência nele por 1 turno.",
            "custo_mana": 1200,
            "custo_qi": 70,
            "custo_qi_formatado": "70 de Maestria",
            "custo_maestria": 70,
            "custo_maestria_formatado": "70 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 16,
            "passiva": false
        },
        {
            "nome": "Círculo de Prata",
            "classe": "Floretes",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Avança e recua em passos curtos e elásticos, típicos da esgrima clássica, o usuário transforma toda a área ao redor em zona de perigo constante, o florete alcançando tudo dentro do raio de ação enquanto aplica estocadas leves e precisas, guiadas mais pelo pulso do que pelo braço inteiro. Cada golpe encadeia com o anterior, e quem já foi tocado antes pela mesma proficiência em Floretes sente o dobro da dor quando a sequência retorna.",
            "descricao_completa": "Avança e recua em passos curtos e elásticos, típicos da esgrima clássica, o usuário transforma toda a área ao redor em zona de perigo constante, o florete alcançando tudo dentro do raio de ação enquanto aplica estocadas leves e precisas, guiadas mais pelo pulso do que pelo braço inteiro. Cada golpe encadeia com o anterior, e quem já foi tocado antes pela mesma proficiência em Floretes sente o dobro da dor quando a sequência retorna. O golpe alcança até 6m ao redor do usuário e causa +20% de dano a mais em alvos marcados pelo estilo no turno anterior.",
            "custo_mana": 1500,
            "custo_qi": 110,
            "custo_qi_formatado": "110 de Maestria",
            "custo_maestria": 110,
            "custo_maestria_formatado": "110 de Maestria",
            "cooldown": 4,
            "nivel_desbloqueio": 21,
            "passiva": false,
            "alcance": "6M"
        },
        {
            "nome": "Olho do Duelista",
            "classe": "Floretes",
            "categoria": "Proficiencia",
            "tipo": "Passiva",
            "descricao": "Essa é uma vantagem silenciosa, construída golpe a golpe: cada vez que o florete aplica estocadas leves e precisas, guiadas mais pelo pulso do que pelo braço inteiro com sucesso, o usuário sente o próprio corpo responder com mais naturalidade, como se revivesse cada hora de treino investida em Floretes. Mesmo nos intervalos entre um golpe e outro, quando o usuário avança e recua em passos curtos e elásticos, típicos da esgrima clássica, esse estado se mantém — mas basta parar de atacar para que o encanto se desfaça rapidamente.",
            "descricao_completa": "Essa é uma vantagem silenciosa, construída golpe a golpe: cada vez que o florete aplica estocadas leves e precisas, guiadas mais pelo pulso do que pelo braço inteiro com sucesso, o usuário sente o próprio corpo responder com mais naturalidade, como se revivesse cada hora de treino investida em Floretes. Mesmo nos intervalos entre um golpe e outro, quando o usuário avança e recua em passos curtos e elásticos, típicos da esgrima clássica, esse estado se mantém — mas basta parar de atacar para que o encanto se desfaça rapidamente. Mecanicamente, 3 acertos consecutivos concedem +10% de eficiência nas técnicas deste estilo, mantido enquanto o ataque não parar.",
            "custo_mana": 0,
            "custo_qi": 160,
            "custo_qi_formatado": "160 de Maestria",
            "custo_maestria": 160,
            "custo_maestria_formatado": "160 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 26,
            "passiva": true
        },
        {
            "nome": "Retorno da Ponta",
            "classe": "Floretes",
            "categoria": "Proficiencia",
            "tipo": "Defesa",
            "descricao": "Ao perceber o golpe se aproximando, o usuário não recua: avança e recua em passos curtos e elásticos, típicos da esgrima clássica, posicionando o florete exatamente onde o impacto será absorvido. O que seria dano vira apenas um custo menor, e antes que o oponente se recomponha, o florete já responde — bloquear deixou de ser passivo há muito tempo para quem domina essa técnica.",
            "descricao_completa": "Ao perceber o golpe se aproximando, o usuário não recua: avança e recua em passos curtos e elásticos, típicos da esgrima clássica, posicionando o florete exatamente onde o impacto será absorvido. O que seria dano vira apenas um custo menor, e antes que o oponente se recomponha, o florete já responde — bloquear deixou de ser passivo há muito tempo para quem domina essa técnica. Ao aparar ou evitar um ataque compatível, o dano recebido cai 25% e um contra-ataque com +10% de dano fica pronto para uso.",
            "custo_mana": 1200,
            "custo_qi": 230,
            "custo_qi_formatado": "230 de Maestria",
            "custo_maestria": 230,
            "custo_maestria_formatado": "230 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 31,
            "passiva": false
        },
        {
            "nome": "Rosário de Estocadas",
            "classe": "Floretes",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "O usuário canaliza muito além do que o corpo pede, e o florete carrega essa energia excedente até o limite. O corpo mantém a lâmina fina esticada à frente, o corpo de perfil para reduzir o alvo exposto em um único instante de tensão máxima antes da liberação — um tinido metálico fino toda vez que a lâmina encontra resistência, seguido de um golpe brutal e vistoso. É um ataque tudo ou quase nada, e o próprio corpo cobra o preço logo em seguida, exigindo um intervalo antes de arriscar tudo outra vez.",
            "descricao_completa": "O usuário canaliza muito além do que o corpo pede, e o florete carrega essa energia excedente até o limite. O corpo mantém a lâmina fina esticada à frente, o corpo de perfil para reduzir o alvo exposto em um único instante de tensão máxima antes da liberação — um tinido metálico fino toda vez que a lâmina encontra resistência, seguido de um golpe brutal e vistoso. É um ataque tudo ou quase nada, e o próprio corpo cobra o preço logo em seguida, exigindo um intervalo antes de arriscar tudo outra vez. Na prática, são +35% de dano em um único golpe concentrado, que exige um turno de intervalo antes de ser usado de novo.",
            "custo_mana": 2200,
            "custo_qi": 320,
            "custo_qi_formatado": "320 de Maestria",
            "custo_maestria": 320,
            "custo_maestria_formatado": "320 de Maestria",
            "cooldown": 5,
            "nivel_desbloqueio": 36,
            "passiva": false
        },
        {
            "nome": "Dernier Coup",
            "classe": "Floretes",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Esta é a técnica definitiva de Floretes: o usuário avança e recua em passos curtos e elásticos, típicos da esgrima clássica até o instante exato, mantém a lâmina fina esticada à frente, o corpo de perfil para reduzir o alvo exposto, e então uma estocada única e perfeitamente alinhada, guiada até o ponto exato antes calculado. Um tinido metálico fino toda vez que a lâmina encontra resistência marca o golpe mais temido de toda a proficiência — capaz de romper defesas que segundos antes pareciam impossíveis de quebrar. Adversários experientes reconhecem a postura antes mesmo do movimento começar, e sabem exatamente o que ela significa. Por isso, o corpo só permite esse esforço uma única vez em cada combate.",
            "descricao_completa": "Esta é a técnica definitiva de Floretes: o usuário avança e recua em passos curtos e elásticos, típicos da esgrima clássica até o instante exato, mantém a lâmina fina esticada à frente, o corpo de perfil para reduzir o alvo exposto, e então uma estocada única e perfeitamente alinhada, guiada até o ponto exato antes calculado. Um tinido metálico fino toda vez que a lâmina encontra resistência marca o golpe mais temido de toda a proficiência — capaz de romper defesas que segundos antes pareciam impossíveis de quebrar. Adversários experientes reconhecem a postura antes mesmo do movimento começar, e sabem exatamente o que ela significa. Por isso, o corpo só permite esse esforço uma única vez em cada combate. O efeito máximo: +50% de dano e 20% de Resistência ignorada, reservado para um único uso em toda a luta.",
            "custo_mana": 3500,
            "custo_qi": 450,
            "custo_qi_formatado": "450 de Maestria",
            "custo_maestria": 450,
            "custo_maestria_formatado": "450 de Maestria",
            "cooldown": 7,
            "nivel_desbloqueio": 41,
            "passiva": false,
            "alcance": "Até 12M conforme a arma"
        }
    ]
};

module.exports = catalogo;
