/**
 * TÉCNICAS DE ESTILO DE LUTA: Proficiência em Lanças
 * Catálogo com 9 técnicas exclusivas.
 */

const catalogo = {
    "nome": "Lanças",
    "descricao_classe": "O usuário domina uma das armas mais versáteis já criadas.",
    "categoria": "Proficiencia",
    "arma": "Lanças ou semelhantes",
    "tecnicaInicial": {
        "nome": "Investida de Randgriz",
        "classe": "Lanças",
        "categoria": "Proficiencia",
        "tipo": "Física",
        "descricao": "Executa a forma fundamental de alcance, estocada, varredura e investida.",
        "descricao_completa": "Executa a forma fundamental de alcance, estocada, varredura e investida. O golpe usa o domínio de Lanças ou semelhantes para receber +15% de eficácia no impacto, sem alterar outros atributos.",
        "custo_mana": 600,
        "custo_qi": 10,
        "custo_qi_formatado": "10 de Maestria",
        "custo_maestria": 10,
        "custo_maestria_formatado": "10 de Maestria",
        "cooldown": 1,
        "nivel_desbloqueio": 1,
        "passiva": false
    },
    "tecnicas": [
        {
            "nome": "Ponta de Gáe Bolg",
            "classe": "Lanças",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Condensa mana em Lanças ou semelhantes e força uma abertura específica da guarda inimiga.",
            "descricao_completa": "Condensa mana em Lanças ou semelhantes e força uma abertura específica da guarda inimiga. Se acertar, ignora 15% da Resistência apenas neste ataque.",
            "custo_mana": 900,
            "custo_qi": 20,
            "custo_qi_formatado": "20 de Maestria",
            "custo_maestria": 20,
            "custo_maestria_formatado": "20 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 6,
            "passiva": false
        },
        {
            "nome": "Passo da Valquíria",
            "classe": "Lanças",
            "categoria": "Proficiencia",
            "tipo": "Movimentação",
            "descricao": "Usa a técnica própria de Lanças ou semelhantes para reposicionar-se até 5m sem perder a ação ofensiva do turno.",
            "descricao_completa": "Usa a técnica própria de Lanças ou semelhantes para reposicionar-se até 5m sem perder a ação ofensiva do turno. O próximo ataque desse estilo recebe +10% de Agilidade.",
            "custo_mana": 700,
            "custo_qi": 40,
            "custo_qi_formatado": "40 de Maestria",
            "custo_maestria": 40,
            "custo_maestria_formatado": "40 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 11,
            "passiva": false,
            "alcance": "5M"
        },
        {
            "nome": "Linha de Longinus",
            "classe": "Lanças",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Explora alcance, estocada, varredura e investida para quebrar postura.",
            "descricao_completa": "Explora alcance, estocada, varredura e investida para quebrar postura. Se o atributo ofensivo usado pelo estilo superar a Resistência do alvo, aplica -15% de Resistência por 1 turno.",
            "custo_mana": 1200,
            "custo_qi": 70,
            "custo_qi_formatado": "70 de Maestria",
            "custo_maestria": 70,
            "custo_maestria_formatado": "70 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 16,
            "passiva": false
        },
        {
            "nome": "Círculo de Hrist",
            "classe": "Lanças",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Cria uma sequência em área usando Lanças ou semelhantes.",
            "descricao_completa": "Cria uma sequência em área usando Lanças ou semelhantes. A técnica cobre até 6m ao redor ou à frente do usuário e causa +20% de dano contra alvos já atingidos por outra técnica deste estilo no turno anterior.",
            "custo_mana": 1500,
            "custo_qi": 110,
            "custo_qi_formatado": "110 de Maestria",
            "custo_maestria": 110,
            "custo_maestria_formatado": "110 de Maestria",
            "cooldown": 4,
            "nivel_desbloqueio": 21,
            "passiva": false,
            "alcance": "6M"
        },
        {
            "nome": "Doutrina do Lanceiro",
            "classe": "Lanças",
            "categoria": "Proficiencia",
            "tipo": "Passiva",
            "descricao": "Passiva de domínio de Lanças ou semelhantes.",
            "descricao_completa": "Passiva de domínio de Lanças ou semelhantes. Após acertar 3 ataques deste estilo durante a mesma luta, o usuário ganha +10% de eficiência nas técnicas da proficiência até passar 1 turno sem atacar.",
            "custo_mana": 0,
            "custo_qi": 160,
            "custo_qi_formatado": "160 de Maestria",
            "custo_maestria": 160,
            "custo_maestria_formatado": "160 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 26,
            "passiva": true
        },
        {
            "nome": "Retorno de Brynhildr",
            "classe": "Lanças",
            "categoria": "Proficiencia",
            "tipo": "Defesa",
            "descricao": "Converte o domínio de Lanças ou semelhantes em resposta defensiva.",
            "descricao_completa": "Converte o domínio de Lanças ou semelhantes em resposta defensiva. Ao aparar ou evitar um ataque compatível, reduz o dano recebido em 25% e prepara um contra-ataque com +10% de dano.",
            "custo_mana": 1200,
            "custo_qi": 230,
            "custo_qi_formatado": "230 de Maestria",
            "custo_maestria": 230,
            "custo_maestria_formatado": "230 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 31,
            "passiva": false
        },
        {
            "nome": "Estocada do Destino",
            "classe": "Lanças",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Técnica avançada de alcance, estocada, varredura e investida: concentra mana em uma única execução e causa +35% de dano.",
            "descricao_completa": "Técnica avançada de alcance, estocada, varredura e investida: concentra mana em uma única execução e causa +35% de dano. Exige preparação narrativa curta e não pode ser repetida em turnos consecutivos.",
            "custo_mana": 2200,
            "custo_qi": 320,
            "custo_qi_formatado": "320 de Maestria",
            "custo_maestria": 320,
            "custo_maestria_formatado": "320 de Maestria",
            "cooldown": 5,
            "nivel_desbloqueio": 36,
            "passiva": false
        },
        {
            "nome": "Queda de Gungnir",
            "classe": "Lanças",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Assinatura máxima da proficiência em Lanças.",
            "descricao_completa": "Assinatura máxima da proficiência em Lanças. O usuário combina alcance, estocada, varredura e investida em uma execução decisiva de Lanças ou semelhantes, causando +50% de dano e ignorando 20% da Resistência. Uso limitado a 1 vez por luta.",
            "custo_mana": 3500,
            "custo_qi": 450,
            "custo_qi_formatado": "450 de Maestria",
            "custo_maestria": 450,
            "custo_maestria_formatado": "450 de Maestria",
            "cooldown": 7,
            "nivel_desbloqueio": 41,
            "passiva": false,
            "alcance": "Até 12M conforme a arma"
        }
    ]
};

module.exports = catalogo;
