/**
 * TÉCNICAS DE ESTILO DE LUTA: Proficiência em Manoplas
 * Catálogo com 9 técnicas exclusivas.
 */

const catalogo = {
    "nome": "Manoplas",
    "descricao_classe": "O usuário fortalece seus golpes corpo a corpo através de armas acopladas aos punhos.",
    "categoria": "Proficiencia",
    "arma": "Manoplas ou semelhantes",
    "tecnicaInicial": {
        "nome": "Punho Demolidor",
        "classe": "Manoplas",
        "categoria": "Proficiencia",
        "tipo": "Física",
        "descricao": "Executa a forma fundamental de golpes reforçados, combos e bloqueios com os punhos.",
        "descricao_completa": "Executa a forma fundamental de golpes reforçados, combos e bloqueios com os punhos. O golpe usa o domínio de Manoplas ou semelhantes para receber +15% de eficácia no impacto, sem alterar outros atributos.",
        "custo_mana": 600,
        "custo_qi": 10,
        "custo_qi_formatado": "10 de Maestria",
        "custo_maestria": 10,
        "custo_maestria_formatado": "10 de Maestria",
        "cooldown": 1,
        "nivel_desbloqueio": 1,
        "passiva": false
    },
    "tecnicas": [
        {
            "nome": "Impacto de Heracles",
            "classe": "Manoplas",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Condensa mana em Manoplas ou semelhantes e força uma abertura específica da guarda inimiga.",
            "descricao_completa": "Condensa mana em Manoplas ou semelhantes e força uma abertura específica da guarda inimiga. Se acertar, ignora 15% da Resistência apenas neste ataque.",
            "custo_mana": 900,
            "custo_qi": 20,
            "custo_qi_formatado": "20 de Maestria",
            "custo_maestria": 20,
            "custo_maestria_formatado": "20 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 6,
            "passiva": false
        },
        {
            "nome": "Passo do Boxer",
            "classe": "Manoplas",
            "categoria": "Proficiencia",
            "tipo": "Movimentação",
            "descricao": "Usa a técnica própria de Manoplas ou semelhantes para reposicionar-se até 5m sem perder a ação ofensiva do turno.",
            "descricao_completa": "Usa a técnica própria de Manoplas ou semelhantes para reposicionar-se até 5m sem perder a ação ofensiva do turno. O próximo ataque desse estilo recebe +10% de Agilidade.",
            "custo_mana": 700,
            "custo_qi": 40,
            "custo_qi_formatado": "40 de Maestria",
            "custo_maestria": 40,
            "custo_maestria_formatado": "40 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 11,
            "passiva": false,
            "alcance": "5M"
        },
        {
            "nome": "Quebra-Guarda",
            "classe": "Manoplas",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Explora golpes reforçados, combos e bloqueios com os punhos para quebrar postura.",
            "descricao_completa": "Explora golpes reforçados, combos e bloqueios com os punhos para quebrar postura. Se o atributo ofensivo usado pelo estilo superar a Resistência do alvo, aplica -15% de Resistência por 1 turno.",
            "custo_mana": 1200,
            "custo_qi": 70,
            "custo_qi_formatado": "70 de Maestria",
            "custo_maestria": 70,
            "custo_maestria_formatado": "70 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 16,
            "passiva": false
        },
        {
            "nome": "Círculo de Punhos",
            "classe": "Manoplas",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Cria uma sequência em área usando Manoplas ou semelhantes.",
            "descricao_completa": "Cria uma sequência em área usando Manoplas ou semelhantes. A técnica cobre até 6m ao redor ou à frente do usuário e causa +20% de dano contra alvos já atingidos por outra técnica deste estilo no turno anterior.",
            "custo_mana": 1500,
            "custo_qi": 110,
            "custo_qi_formatado": "110 de Maestria",
            "custo_maestria": 110,
            "custo_maestria_formatado": "110 de Maestria",
            "cooldown": 4,
            "nivel_desbloqueio": 21,
            "passiva": false,
            "alcance": "6M"
        },
        {
            "nome": "Motor de Combate",
            "classe": "Manoplas",
            "categoria": "Proficiencia",
            "tipo": "Passiva",
            "descricao": "Passiva de domínio de Manoplas ou semelhantes.",
            "descricao_completa": "Passiva de domínio de Manoplas ou semelhantes. Após acertar 3 ataques deste estilo durante a mesma luta, o usuário ganha +10% de eficiência nas técnicas da proficiência até passar 1 turno sem atacar.",
            "custo_mana": 0,
            "custo_qi": 160,
            "custo_qi_formatado": "160 de Maestria",
            "custo_maestria": 160,
            "custo_maestria_formatado": "160 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 26,
            "passiva": true
        },
        {
            "nome": "Retorno do Colosso",
            "classe": "Manoplas",
            "categoria": "Proficiencia",
            "tipo": "Defesa",
            "descricao": "Converte o domínio de Manoplas ou semelhantes em resposta defensiva.",
            "descricao_completa": "Converte o domínio de Manoplas ou semelhantes em resposta defensiva. Ao aparar ou evitar um ataque compatível, reduz o dano recebido em 25% e prepara um contra-ataque com +10% de dano.",
            "custo_mana": 1200,
            "custo_qi": 230,
            "custo_qi_formatado": "230 de Maestria",
            "custo_maestria": 230,
            "custo_maestria_formatado": "230 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 31,
            "passiva": false
        },
        {
            "nome": "Meteoros de Alcides",
            "classe": "Manoplas",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Técnica avançada de golpes reforçados, combos e bloqueios com os punhos: concentra mana em uma única execução e causa +35% de dano.",
            "descricao_completa": "Técnica avançada de golpes reforçados, combos e bloqueios com os punhos: concentra mana em uma única execução e causa +35% de dano. Exige preparação narrativa curta e não pode ser repetida em turnos consecutivos.",
            "custo_mana": 2200,
            "custo_qi": 320,
            "custo_qi_formatado": "320 de Maestria",
            "custo_maestria": 320,
            "custo_maestria_formatado": "320 de Maestria",
            "cooldown": 5,
            "nivel_desbloqueio": 36,
            "passiva": false
        },
        {
            "nome": "Nemeia Desperta",
            "classe": "Manoplas",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Assinatura máxima da proficiência em Manoplas.",
            "descricao_completa": "Assinatura máxima da proficiência em Manoplas. O usuário combina golpes reforçados, combos e bloqueios com os punhos em uma execução decisiva de Manoplas ou semelhantes, causando +50% de dano e ignorando 20% da Resistência. Uso limitado a 1 vez por luta.",
            "custo_mana": 3500,
            "custo_qi": 450,
            "custo_qi_formatado": "450 de Maestria",
            "custo_maestria": 450,
            "custo_maestria_formatado": "450 de Maestria",
            "cooldown": 7,
            "nivel_desbloqueio": 41,
            "passiva": false,
            "alcance": "Até 12M conforme a arma"
        }
    ]
};

module.exports = catalogo;
