/**
 * TÉCNICAS DE ESTILO DE LUTA: Proficiência em Pistolas
 * Catálogo com 9 técnicas exclusivas.
 */

const catalogo = {
    "nome": "Pistolas",
    "descricao_classe": "Especialista em armas de fogo curtas, saque rápido, precisão móvel e combate em curta e média distância.",
    "categoria": "Proficiencia",
    "arma": "Pistolas, revólveres e armas curtas",
    "tecnicaInicial": {
        "nome": "Réquiem do Saque Rápido",
        "classe": "Pistolas",
        "categoria": "Proficiencia",
        "tipo": "Física",
        "descricao": "Executa a forma fundamental de saque rápido, tiros precisos e combate móvel.",
        "descricao_completa": "Executa a forma fundamental de saque rápido, tiros precisos e combate móvel. O golpe usa o domínio de Pistolas, revólveres e armas curtas para receber +15% de eficácia no impacto, sem alterar outros atributos.",
        "custo_mana": 600,
        "custo_qi": 10,
        "custo_qi_formatado": "10 de Maestria",
        "custo_maestria": 10,
        "custo_maestria_formatado": "10 de Maestria",
        "cooldown": 1,
        "nivel_desbloqueio": 1,
        "passiva": false
    },
    "tecnicas": [
        {
            "nome": "Balada de Billy",
            "classe": "Pistolas",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Condensa mana em Pistolas, revólveres e armas curtas e força uma abertura específica da guarda inimiga.",
            "descricao_completa": "Condensa mana em Pistolas, revólveres e armas curtas e força uma abertura específica da guarda inimiga. Se acertar, ignora 15% da Resistência apenas neste ataque.",
            "custo_mana": 900,
            "custo_qi": 20,
            "custo_qi_formatado": "20 de Maestria",
            "custo_maestria": 20,
            "custo_maestria_formatado": "20 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 6,
            "passiva": false
        },
        {
            "nome": "Passo do Pistoleiro",
            "classe": "Pistolas",
            "categoria": "Proficiencia",
            "tipo": "Movimentação",
            "descricao": "Usa a técnica própria de Pistolas, revólveres e armas curtas para reposicionar-se até 5m sem perder a ação ofensiva do turno.",
            "descricao_completa": "Usa a técnica própria de Pistolas, revólveres e armas curtas para reposicionar-se até 5m sem perder a ação ofensiva do turno. O próximo ataque desse estilo recebe +10% de Agilidade.",
            "custo_mana": 700,
            "custo_qi": 40,
            "custo_qi_formatado": "40 de Maestria",
            "custo_maestria": 40,
            "custo_maestria_formatado": "40 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 11,
            "passiva": false,
            "alcance": "5M"
        },
        {
            "nome": "Tiro de Moeda",
            "classe": "Pistolas",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Explora saque rápido, tiros precisos e combate móvel para quebrar postura.",
            "descricao_completa": "Explora saque rápido, tiros precisos e combate móvel para quebrar postura. Se o atributo ofensivo usado pelo estilo superar a Resistência do alvo, aplica -15% de Resistência por 1 turno.",
            "custo_mana": 1200,
            "custo_qi": 70,
            "custo_qi_formatado": "70 de Maestria",
            "custo_maestria": 70,
            "custo_maestria_formatado": "70 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 16,
            "passiva": false
        },
        {
            "nome": "Círculo de Chumbo",
            "classe": "Pistolas",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Cria uma sequência em área usando Pistolas, revólveres e armas curtas.",
            "descricao_completa": "Cria uma sequência em área usando Pistolas, revólveres e armas curtas. A técnica cobre até 6m ao redor ou à frente do usuário e causa +20% de dano contra alvos já atingidos por outra técnica deste estilo no turno anterior.",
            "custo_mana": 1500,
            "custo_qi": 110,
            "custo_qi_formatado": "110 de Maestria",
            "custo_maestria": 110,
            "custo_maestria_formatado": "110 de Maestria",
            "cooldown": 4,
            "nivel_desbloqueio": 21,
            "passiva": false,
            "alcance": "6M"
        },
        {
            "nome": "Mão Mais Rápida",
            "classe": "Pistolas",
            "categoria": "Proficiencia",
            "tipo": "Passiva",
            "descricao": "Passiva de domínio de Pistolas, revólveres e armas curtas.",
            "descricao_completa": "Passiva de domínio de Pistolas, revólveres e armas curtas. Após acertar 3 ataques deste estilo durante a mesma luta, o usuário ganha +10% de eficiência nas técnicas da proficiência até passar 1 turno sem atacar.",
            "custo_mana": 0,
            "custo_qi": 160,
            "custo_qi_formatado": "160 de Maestria",
            "custo_maestria": 160,
            "custo_maestria_formatado": "160 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 26,
            "passiva": true
        },
        {
            "nome": "Ricochete do Xerife",
            "classe": "Pistolas",
            "categoria": "Proficiencia",
            "tipo": "Defesa",
            "descricao": "Converte o domínio de Pistolas, revólveres e armas curtas em resposta defensiva.",
            "descricao_completa": "Converte o domínio de Pistolas, revólveres e armas curtas em resposta defensiva. Ao aparar ou evitar um ataque compatível, reduz o dano recebido em 25% e prepara um contra-ataque com +10% de dano.",
            "custo_mana": 1200,
            "custo_qi": 230,
            "custo_qi_formatado": "230 de Maestria",
            "custo_maestria": 230,
            "custo_maestria_formatado": "230 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 31,
            "passiva": false
        },
        {
            "nome": "Seis Disparos",
            "classe": "Pistolas",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Técnica avançada de saque rápido, tiros precisos e combate móvel: concentra mana em uma única execução e causa +35% de dano.",
            "descricao_completa": "Técnica avançada de saque rápido, tiros precisos e combate móvel: concentra mana em uma única execução e causa +35% de dano. Exige preparação narrativa curta e não pode ser repetida em turnos consecutivos.",
            "custo_mana": 2200,
            "custo_qi": 320,
            "custo_qi_formatado": "320 de Maestria",
            "custo_maestria": 320,
            "custo_maestria_formatado": "320 de Maestria",
            "cooldown": 5,
            "nivel_desbloqueio": 36,
            "passiva": false
        },
        {
            "nome": "Last Encore",
            "classe": "Pistolas",
            "categoria": "Proficiencia",
            "tipo": "Física",
            "descricao": "Assinatura máxima da proficiência em Pistolas.",
            "descricao_completa": "Assinatura máxima da proficiência em Pistolas. O usuário combina saque rápido, tiros precisos e combate móvel em uma execução decisiva de Pistolas, revólveres e armas curtas, causando +50% de dano e ignorando 20% da Resistência. Uso limitado a 1 vez por luta.",
            "custo_mana": 3500,
            "custo_qi": 450,
            "custo_qi_formatado": "450 de Maestria",
            "custo_maestria": 450,
            "custo_maestria_formatado": "450 de Maestria",
            "cooldown": 7,
            "nivel_desbloqueio": 41,
            "passiva": false,
            "alcance": "Até 12M conforme a arma"
        }
    ]
};

module.exports = catalogo;
