const assassino = {
    nome: "Assassino",
    descricao_classe: "Especialista em combate furtivo e ataques precisos, domina adagas, kusarigama, foice e katanas. Possui alta mobilidade e técnicas de assassínio silencioso.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Ataque Furtivo",
        classe: "Assassino",
        categoria: "Inicial",
        tipo: "Passiva",
        descricao: "Ataques furtivos causam +10% de dano.",
        descricao_completa: "Ataques feitos pelo usuário enquanto estiver no estado de furtividade (ou seja, não detectado pelo inimigo alvo) tem um bônus de [10%] de dano em qualquer tipo de dano. Isso implica ataques que não sejam notados pelo atributo de Sentidos do alvo corretamente, ou seja, que sejam pelo menos [30%] menores que a Agilidade do assassino).",
        custo_mana: 0,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 0,
        nivel_desbloqueio: 1,
        passiva: true
    },
    tecnicas: [
        {
            nome: "Emboscada Fantasmagórica",
            classe: "Assassino",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Fica invisível por 1 turno e avança rapidamente.",
            descricao_completa: "O usuário se torna invisível por [1 turno] e avança rapidamente em direção a um inimigo [30% de agilidade], golpeando-o com uma adaga. Se o alvo for abatido, o usuário pode se mover novamente e ficando por mais um turno invisível.",
            custo_mana: 2000,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 2,
            nivel_desbloqueio: 3,
            passiva: false
        },
        {
            nome: "Fúria das Profundezas",
            classe: "Assassino",
            categoria: "Inicial",
            tipo: "Buff",
            descricao: "Aumenta AGI e ATK em 20% por 2 turnos.",
            descricao_completa: "O usuário canaliza energia das profundezas, ganhando um aumento temporário de agilidade [20%] e ataque [20%] por [2 turnos]. Durante este efeito, a cada dois golpes de adaga reduz o tempo de recarga das habilidades do usuário em [1 Turno] por acerto. Se o usuário abater um inimigo durante a duração, o efeito é estendido por mais 1 turno.",
            custo_mana: 3000,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 4,
            nivel_desbloqueio: 5,
            passiva: false
        },
        {
            nome: "Perfuramento de Assassino",
            classe: "Assassino",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Golpe preciso que ignora parte da defesa.",
            descricao_completa: "Uma habilidade combinada e vinculável que só pode ser ativada quando o assassino não é detectado pelo alvo ou quando o foco de ataque do inimigo está em outro lugar[0%]. Ao ativar a habilidade, o assassino canaliza uma poderosa energia azul profunda em sua adaga, aumentando drasticamente sua força de ataque e perfurando o alvo com um golpe preciso [+30%].",
            custo_mana: 1500,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 3,
            nivel_desbloqueio: 7,
            passiva: false
        },
        {
            nome: "Marca daExecução",
            classe: "Assassino",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Marca inimigo aumentando dano recebido.",
            descricao_completa: "O usuário marca um inimigo com uma adaga mágica, revelando sua localização e aumentando o dano recebido por ele em [30%]. Se o inimigo marcado for abatido dentro de [2 turnos], o usuário recupera a mana gasta da técnica e reduz o tempo de recarga de suas habilidades em [2 turnos].",
            custo_mana: 3000,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 3,
            nivel_desbloqueio: 9,
            passiva: false
        },
        {
            nome: "Morte das Profundezas",
            classe: "Assassino",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Corte mágico em X que executa inimigos.",
            descricao_completa: "O assassino conjura um corte mágico em formato de [X] no chão, com 2 metros de comprimento em cada direção. O corte causa dano massivo a todos os inimigos atingidos e executa aqueles com ferimentos graves. Se um inimigo for executado, o assassino pode reconjurar a técnica imediatamente, sem custo de mana, e com um aumento de [15%] no dano a cada reconjuração. O efeito de aumento de dano é acumulativo, mas a técnica só pode ser reconjurada até 3 vezes por turno.",
            custo_mana: 3000,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 6,
            nivel_desbloqueio: 11,
            passiva: false
        },
        {
            nome: "Ponto Fraco [Passivo]",
            classe: "Assassino",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Ataques cegos em pontos vitais causam dano dobrado.",
            descricao_completa: "Se atacando um ponto vital (como olhos e pescoço) e cego, (ou seja, não sendo notado de forma alguma antes do ataque ocorrer), o ataque do assassino terá seu dano multiplicado em 2x. Entretanto, é necessário que o alvo seja completamente incapaz de compreender sua ação até o momento do dano acontecer. Independente da sua natureza.",
            custo_mana: 0,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 0,
            nivel_desbloqueio: 13,
            passiva: true
        },
        {
            nome: "Célere",
            classe: "Assassino",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Corre por paredes e água com -30% agilidade.",
            descricao_completa: "Usando a mana em seu corpo junto a sua agilidade notável consegue correr por paredes e superfícies na vertical, podendo usar desse mesmo artificio para andar ou correr sobre a agua. [Se mover nesses cenários diminui 30% da agilidade].",
            custo_mana: 200,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 1,
            nivel_desbloqueio: 15,
            passiva: false,
            custo_mana_turno: 200
        },
        {
            nome: "Mãos Mágicas",
            classe: "Assassino",
            categoria: "Inicial",
            tipo: "Utilidade",
            descricao: "Rouba itens tocados por 2 turnos.",
            descricao_completa: "Pode fazer objetos tocados anteriormente aparecerem em suas mãos, sejam coisas comuns ou itens alheios. Ao tocar com sua mão em qualquer item equipado (como armaduras ou armas não empunhadas na posse do usuário), consegue 'roubar' o item por dois turnos, sendo necessário imbuir mana no objeto para isso. Necessário que a agilidade do usuário seja maior do que a sentidos do alvo. Se a força do alvo for [50%] maior que a agilidade do assassino, a habilidade não funcionará se ele estiver consciente da sua intenção. A habilidade não funciona em itens com [1 Rank] de diferença para cima.",
            custo_mana: 900,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 3,
            nivel_desbloqueio: 18,
            passiva: false
        },
        {
            nome: "Sede de Sangue",
            classe: "Assassino",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Reduz atributos de inimigos mais fracos.",
            descricao_completa: "O assassino canaliza sua sede de sangue, criando uma aura intimidante que se espalha ao seu redor. Inimigos dentro da área sofrem redução de até [50%] nos atributos dependendo de quanto ele é abaixo de seu nível. Caso ele tenha [5 níveis] abaixo, ele perde [10%] dos atributos, caso ele tenha [15 níveis] abaixo o debuff chega a [30%] e caso tenha [25 níveis] abaixo chegando em [50%] de redução nos atributos. Em inimigos superiores essa técnica funciona com base na agilidade do usuário. Caso o usuário tenha o dobro da velocidade do inimigo, essa técnica reduz [25%] e funcionando apenas e exclusivamente nesse caso. Dura por [2 Turnos].",
            custo_mana: 1500,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 3,
            nivel_desbloqueio: 20,
            passiva: false,
            alcance: "10m"
        },
        {
            nome: "Ligação de Sangue",
            classe: "Assassino",
            categoria: "Inicial",
            tipo: "Utilidade",
            descricao: "Puxa objetos tocados anteriormente.",
            descricao_completa: "Usando a Ligação de Sangue, criada ao utilizar um item de seu inventário, consegue criar uma linha de mana que se prende ao objeto designado e permite que este seja puxado para si, usando um dedo, se estando dentro dentro de um raio de [15 metros] e tendo formado a linha enquanto havia contato físico. Obs: Para notar as linhas invisíveis, o alvo precisa ter sentidos 30% superiores a PM do assassino. A força e velocidade das linhas são medidos pela força, mas a resistência delas é pela PM. Objetos maiores que [1,5x] o tamanho do usuário não podem ser puxados.",
            custo_mana: 700,
            custo_qi: 100000,
            custo_qi_formatado: "100000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 23,
            passiva: false,
            duracao: "3 turnos"
        }
    ]
};

module.exports = assassino;