const classe = {
    "nome": "Assassino",
    "descricao_classe": "Especialista em furtividade, execução e mobilidade; suas técnicas gerais independem da arma equipada.",
    "categoria": "Classe",
    "tecnicaInicial": {
        "nome": "Ataque Furtivo",
        "categoria": "Inicial",
        "tipo": "Física",
        "descricao": "Explora um ângulo cego para causar +15% de dano quando o alvo ainda não o percebeu ou está distraído.",
        "descricao_completa": "Explora um ângulo cego para causar +15% de dano quando o alvo ainda não o percebeu ou está distraído.",
        "custo_mana": 700,
        "custo_qi": 10,
        "custo_qi_formatado": "10 de Maestria",
        "custo_maestria": 10,
        "custo_maestria_formatado": "10 de Maestria",
        "cooldown": 2,
        "nivel_desbloqueio": 1,
        "passiva": false,
        "classe": "Assassino"
    },
    "tecnicas": [
        {
            "nome": "Emboscada Fantasmagórica",
            "categoria": "Inicial",
            "tipo": "Utilidade",
            "descricao": "Oculta a assinatura de mana por uma ação e recebe +15% Agilidade no primeiro avanço ofensivo após sair da ocultação.",
            "descricao_completa": "Oculta a assinatura de mana por uma ação e recebe +15% Agilidade no primeiro avanço ofensivo após sair da ocultação.",
            "custo_mana": 1000,
            "custo_qi": 20,
            "custo_qi_formatado": "20 de Maestria",
            "custo_maestria": 20,
            "custo_maestria_formatado": "20 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 5,
            "passiva": false,
            "classe": "Assassino"
        },
        {
            "nome": "Passo de Névoa",
            "categoria": "Inicial",
            "tipo": "Movimentação",
            "descricao": "Move-se até 5m entre pontos de cobertura ou ângulos mortos sem consumir todo o deslocamento normal.",
            "descricao_completa": "Move-se até 5m entre pontos de cobertura ou ângulos mortos sem consumir todo o deslocamento normal.",
            "custo_mana": 900,
            "custo_qi": 40,
            "custo_qi_formatado": "40 de Maestria",
            "custo_maestria": 40,
            "custo_maestria_formatado": "40 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 10,
            "passiva": false,
            "alcance": "5M",
            "classe": "Assassino"
        },
        {
            "nome": "Marca da Execução",
            "categoria": "Inicial",
            "tipo": "Física",
            "descricao": "Marca um alvo ferido por 2 turnos; ataques do assassino contra ele causam +10% de dano, sem acumular com nova marca.",
            "descricao_completa": "Marca um alvo ferido por 2 turnos; ataques do assassino contra ele causam +10% de dano, sem acumular com nova marca.",
            "custo_mana": 1200,
            "custo_qi": 70,
            "custo_qi_formatado": "70 de Maestria",
            "custo_maestria": 70,
            "custo_maestria_formatado": "70 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 15,
            "passiva": false,
            "classe": "Assassino"
        },
        {
            "nome": "Ponto Fraco",
            "categoria": "Inicial",
            "tipo": "Passiva",
            "descricao": "Após observar o mesmo alvo por um turno, o próximo ataque ignora 10% da Resistência.",
            "descricao_completa": "Após observar o mesmo alvo por um turno, o próximo ataque ignora 10% da Resistência.",
            "custo_mana": 0,
            "custo_qi": 110,
            "custo_qi_formatado": "110 de Maestria",
            "custo_maestria": 110,
            "custo_maestria_formatado": "110 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 20,
            "passiva": true,
            "classe": "Assassino"
        },
        {
            "nome": "Célere",
            "categoria": "Inicial",
            "tipo": "Passiva",
            "descricao": "Depois de esquivar com sucesso, recebe +15% Agilidade até o fim da próxima ação.",
            "descricao_completa": "Depois de esquivar com sucesso, recebe +15% Agilidade até o fim da próxima ação.",
            "custo_mana": 0,
            "custo_qi": 160,
            "custo_qi_formatado": "160 de Maestria",
            "custo_maestria": 160,
            "custo_maestria_formatado": "160 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 25,
            "passiva": true,
            "classe": "Assassino"
        },
        {
            "nome": "Sede de Sangue",
            "categoria": "Inicial",
            "tipo": "Passiva",
            "descricao": "Ao derrubar um inimigo, recupera 5% da vida e 5% da mana; ativa no máximo uma vez por turno.",
            "descricao_completa": "Ao derrubar um inimigo, recupera 5% da vida e 5% da mana; ativa no máximo uma vez por turno.",
            "custo_mana": 0,
            "custo_qi": 230,
            "custo_qi_formatado": "230 de Maestria",
            "custo_maestria": 230,
            "custo_maestria_formatado": "230 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 30,
            "passiva": true,
            "classe": "Assassino"
        },
        {
            "nome": "Desaparecer",
            "categoria": "Inicial",
            "tipo": "Utilidade",
            "descricao": "Quebra a leitura visual e de mana por uma ação se houver cobertura, fumaça, escuridão ou distração plausível.",
            "descricao_completa": "Quebra a leitura visual e de mana por uma ação se houver cobertura, fumaça, escuridão ou distração plausível.",
            "custo_mana": 1600,
            "custo_qi": 320,
            "custo_qi_formatado": "320 de Maestria",
            "custo_maestria": 320,
            "custo_maestria_formatado": "320 de Maestria",
            "cooldown": 4,
            "nivel_desbloqueio": 35,
            "passiva": false,
            "classe": "Assassino"
        },
        {
            "nome": "Golpe de Misericórdia",
            "categoria": "Inicial",
            "tipo": "Física",
            "descricao": "Contra alvos abaixo de 30% de vida, um ataque físico recebe +25% de dano.",
            "descricao_completa": "Contra alvos abaixo de 30% de vida, um ataque físico recebe +25% de dano. Uso limitado a uma vez por alvo.",
            "custo_mana": 2200,
            "custo_qi": 450,
            "custo_qi_formatado": "450 de Maestria",
            "custo_maestria": 450,
            "custo_maestria_formatado": "450 de Maestria",
            "cooldown": 5,
            "nivel_desbloqueio": 40,
            "passiva": false,
            "classe": "Assassino"
        },
        {
            "nome": "Instinto do Predador",
            "categoria": "Inicial",
            "tipo": "Passiva",
            "descricao": "Uma vez por luta, ao escolher um alvo, ganha +10% Sentidos e Agilidade contra ele por 3 turnos.",
            "descricao_completa": "Uma vez por luta, ao escolher um alvo, ganha +10% Sentidos e Agilidade contra ele por 3 turnos.",
            "custo_mana": 0,
            "custo_qi": 650,
            "custo_qi_formatado": "650 de Maestria",
            "custo_maestria": 650,
            "custo_maestria_formatado": "650 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 45,
            "passiva": true,
            "classe": "Assassino"
        }
    ]
};

module.exports = classe;
