const curador = {
    nome: "Curador",
    descricao_classe: "O Curador domina as artes de cura e suporte, utilizando energia sagrada para restaurar aliados e protegê-los de danos. Possui habilidades de cura em área, buffs de combate e ataques sagrados contra forças das trevas.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Toque Restaurador (Cura Leve)",
        classe: "Curador",
        categoria: "Inicial",
        tipo: "Cura",
        descricao: "Cura danos superficiais instantaneamente.",
        descricao_completa: "O usuário canaliza sua energia em suas mãos, emitindo um brilho esverdeado ao tocar um aliado ferido. Pequenos cortes, contusões e hematomas desaparecem lentamente. Cura danos superficiais instantaneamente e reduz a dor.",
        custo_mana: 750,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 1,
        nivel_desbloqueio: 1,
        passiva: false
    },
    tecnicas: [
        {
            nome: "Benção da Vida (Cura Moderada)",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Cura",
            descricao: "Regenera músculos parcialmente danificados.",
            descricao_completa: "Invocando um fluxo de energia vital em suas mãos e encostando no local do ferimento, o usuário consegue recuperar um alvo com um brilho dourado e intenso. O feitiço regenera músculos parcialmente danificados.",
            custo_mana: 1500,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 2,
            nivel_desbloqueio: 3,
            passiva: false
        },
        {
            nome: "Milagre da Luz (Cura Crítica)",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Cura",
            descricao: "Restaura até órgãos comprometidos e selamento de ferimentos fatais.",
            descricao_completa: "Erguendo as mãos ao céu, o usuário conjura um círculo sagrado abaixo de um aliado gravemente ferido, restaurando até mesmo órgãos comprometidos e selando ferimentos fatais. Cura danos críticos, estabiliza aliados à beira da morte e restaura membros do zero.",
            custo_mana: 4000,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 5,
            nivel_desbloqueio: 5,
            passiva: false
        },
        {
            nome: "Zona de Cura (Cura Leve)",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Cura",
            descricao: "Cria círculo dourado que recupera ferimentos leves e mana.",
            descricao_completa: "Ao expandir sua mana pelo ambiente, o usuário cria uma espécie de círculo dourado no solo, todo mundo que estiver dentro desse circulo acaba por recuperar ferimentos leves gradativamente + [10%] da mana por turno (o efeito de recuperação de mp não funciona no usuário).",
            custo_mana: 1500,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 4,
            nivel_desbloqueio: 7,
            passiva: false,
            custo_mana_turno: 1000,
            diametro: "10m"
        },
        {
            nome: "Reforço Sagrado",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Buff",
            descricao: "Aumenta FOR, AGI e RES em 15% por 3 turnos.",
            descricao_completa: "Colocando a mão em um aliado, o usuário começar a cobrir seu corpo com sua energia mágica dourada, agraciando-o com um Buff de 15% em Força, Agilidade e Resistência durante 3 Turnos. Monstros do tipo Demônio, Morto Vivo, Sombrio e Fantasma Recebem [30%] de dano a mais do aliado (essa habilidade também funciona no usuário).",
            custo_mana: 3000,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 3,
            nivel_desbloqueio: 9,
            passiva: false
        },
        {
            nome: "Onda Divina",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Cura/Combate",
            descricao: "Ataque em área 360° que cura aliados e mata demônios.",
            descricao_completa: "Ao canalizar uma grande quantidade de energia Durante 3 Turnos, o Healer solta toda a energia de uma vez com ele no epicentro do ataque, em um 360° completo. A onda divina é um ataque em área que atinge todos em volta. Todos os aliados atingidos pela onda terão cortes, contusões e hematomas curados instantaneamente enquanto os inimigos do tipo demônio, morto vivo, sombrio ou fantasma de Rank igualado ou inferior são automaticamente mortos ao serem atingidos pela Onda Divina.",
            custo_mana: 4000,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 6,
            nivel_desbloqueio: 11,
            passiva: false,
            area: "20m"
        },
        {
            nome: "Aura de Fortaleza",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Escudo que aumenta resistência em 25% do PM.",
            descricao_completa: "Um escudo translúcido envolve o aliado-alvo, fortalecendo sua resistência por um curto período de tempo em 25% do Poder Mágico do Healer. A aura brilha intensamente quando recebe efeitos negativos, dissipando-o do usuário e sucessivamente desfazendo o escudo.",
            custo_mana: 1500,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 3,
            nivel_desbloqueio: 13,
            passiva: false,
            custo_mana_turno: 750,
            duracao_maxima: "2 turnos"
        },
        {
            nome: "Benção da Serenidade",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Purifica toxinas e dissipa efeitos de medo.",
            descricao_completa: "O alvo é envolto por uma luz azulada que purifica toxinas, dissipa efeitos de medo e resistência mental, além de evitar novos debuffs temporariamente pelos próximos 2 turnos.",
            custo_mana: 2500,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 4,
            nivel_desbloqueio: 15,
            passiva: false
        },
        {
            nome: "Impulso do Guerreiro",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Buff",
            descricao: "Aumenta força física e velocidade em 20% por 2 turnos.",
            descricao_completa: "O usuário canaliza sua energia mágica e a transfere para um aliado, agraciando-o com uma aura avermelhada que aumenta temporariamente sua força física e velocidade de movimento em 20% por dois turnos.",
            custo_mana: 2500,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 3,
            nivel_desbloqueio: 17,
            passiva: false
        },
        {
            nome: "Esfera de Luz",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Utilidade",
            descricao: "Cega inimigos e revela presenças ocultas.",
            descricao_completa: "O usuário cria uma esfera luminosa que emparelha no campo de batalha, cegando temporariamente os inimigos próximos e iluminando áreas escuras. Efeito: Cega inimigos na área por 5 segundos (narrativo) e revela qualquer presença oculta.",
            custo_mana: 1500,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 2,
            nivel_desbloqueio: 19,
            passiva: false
        },
        {
            nome: "Esfera Sagrada",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Cura/Combate",
            descricao: "Esfera arremessável que cura aliados ou danifica inimigos.",
            descricao_completa: "O usuário cria uma esfera arremessável de coloração dourada que cabe em sua mão. Ao ser arremessada contra um aliado distante, recupera 5% da sua mana total e cura ferimentos de cortes, contusões e hematomas. Se jogada em um inimigo, ele sofre um dano equivalente ao PM do Healer, e caso o alvo seja uma criatura sombria ou derivado, recebe 25% a mais de dano.",
            custo_mana: 1500,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 2,
            nivel_desbloqueio: 22,
            passiva: false
        },
        {
            nome: "Redoma Sagrada",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Cúpula que reduz custo de mana e dissipa debuffs.",
            descricao_completa: "Ao concentrar sua energia sagrada, o usuário cria uma cúpula reluzente de luz dourada que se expande em um amplo raio ao seu redor. Dentro da Redoma, os protegidos recebem redução de 30% no gasto de mana para técnicas a longa distância. Além disso, a redoma purifica o ambiente, dissipando debuffs negativos que podem afetar os protegidos enquanto estiver ativo.",
            custo_mana: 2500,
            custo_qi: 20480,
            custo_qi_formatado: "20480 Qi",
            cooldown: 5,
            nivel_desbloqueio: 25,
            passiva: false,
            custo_mana_turno: 1000
        },
        {
            nome: "Olho Por Olho",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Cura/Combate",
            descricao: "Cura aliado e causa dano no último atacante.",
            descricao_completa: "Você canaliza sua energia mágica em um aliado que esteja dentro do alcance e ferido. Sua mana restaura os ferimentos do alvo tornando-o forte novamente, em contra partida, você causa dano na última criatura que atacou o alvo de sua técnica. O dano é condicionado a cura, se o alvo for curado, o inimigo sofre dano com base no seu PM total. Custo de mana: 6.OOO. Alcance: 2Om",
            custo_mana: 6000,
            custo_qi: 50000,
            custo_qi_formatado: "50000 Qi",
            cooldown: 4,
            nivel_desbloqueio: 28,
            passiva: false
        },
        {
            nome: "Cicatriz Ardente",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Cura/Buff",
            descricao: "Cura aliado e marca com aura de vingança.",
            descricao_completa: "Você canaliza seu poder mágico em um aliado, assim como na técnica 'Olho Por Olho' e o cura de ferimentos leves ou graves, inclusive regenerando partes pequenas do corpo como mãos, pés e órgãos menores. Com isso, você marca seu aliado com uma aura de vingança, concedendo a ele bônus para contra-atacar o inimigo que o feriu. Nesse caso, o aliado curado tem bônus de 50% em um ataque que faça contra o seu inimigo, até o final do seu próximo turno. Essa técnica pode ser usada em si próprio. Custo de Mana: 7.OOO. Alcance: 1Om. Cooldown: 2 Turnos",
            custo_mana: 7000,
            custo_qi: 100000,
            custo_qi_formatado: "100000 Qi",
            cooldown: 2,
            nivel_desbloqueio: 30,
            passiva: false
        },
        {
            nome: "Vínculo Divino",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Liga energia vital de aliado removendo limite de alcance.",
            descricao_completa: "Você liga a sua energia vital, com a energia vital de um aliado, previamente. Enquanto estiverem ligados um ao outro, as suas técnicas de alvo único não sofrem nenhum requisito de alncance. Paralelamente, a maior recuperação de mana, entre os dois, é mantida para ambos. Em outras palavras, o que tiver menos recuperação de mana por turno, passa a recuperar o mesmo valor do aliado. Custo de Mana: 12.OOO. Alcance: Toque [1 Aliado]. Duração: 5 Turnos. Cooldown: 2 Turnos",
            custo_mana: 12000,
            custo_qi: 250000,
            custo_qi_formatado: "250000 Qi",
            cooldown: 2,
            nivel_desbloqueio: 33,
            passiva: false
        },
        {
            nome: "Enxame Alado",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Combate",
            descricao: "Conjura pássaros de luz que atacam e carregam aliados.",
            descricao_completa: "Você conjura um enxame de pássaros feitos de luz que atacam seus inimigos em uma revoada. Os pássaros bicam causando dano enquanto carregam seu aliado para uma direção que você ordene, desde que mova apenas 5 metros. O dano causado pelos pássaros é equivalente ao seu PM. Se um aliado tiver morrido ou em estado de quase morte, seu dano aumenta em 20%. Custo de Mana: 5.OOO [+1.5OO/Turno]. Alcance: 15m",
            custo_mana: 5000,
            custo_qi: 500000,
            custo_qi_formatado: "500000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 35,
            passiva: false,
            custo_mana_turno: 1500
        },
        {
            nome: "Chama Sagrada",
            classe: "Curador",
            categoria: "Inicial",
            tipo: "Combate",
            descricao: "Causa dano sagrado com estalo de dedos.",
            descricao_completa: "Você canaliza a energia mágica sagrada que corre em suas veias e em um estalo é como se convocasse a combustão divina em um inimigo. Sempre que fizer o movimento de estalar de dedos, uma chama crepitante recai sobre seu inimigo através de um círculo mágico, causando dano com base no seu PM. Custo de Mana: 1.5OO. Alcance: 1Om",
            custo_mana: 1500,
            custo_qi: 1000000,
            custo_qi_formatado: "1000000 Qi",
            cooldown: 1,
            nivel_desbloqueio: 40,
            passiva: false
        }
    ]
};

module.exports = curador;