const foice = {
    nome: "Foice",
    descricao_classe: "Especialista em combate com foice, domina técnicas de corte circular, alcance e mobilidade. Possui ataques em área e técnicas de ceifador únicas.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Dança do Ceifador",
        classe: "Foice",
        categoria: "Inicial",
        tipo: "Mágica",
        descricao: "Amplia lâmina e gira causando dano em área.",
        descricao_completa: "O usuário amplia magicamente sua lâmina, aumentando seu alcance e poder. Em seguida, ele executa uma dança mortal, balançando a lâmina em um círculo perfeito e gerando cortes invisíveis que se propagam em todas as direções. Os cortes causam dano massivo a todos os inimigos no alcance.",
        custo_mana: 3000,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 3,
        nivel_desbloqueio: 1,
        passiva: false,
        alcance: "6M (raio ao redor do usuário)"
    },
    tecnicas: [
        {
            nome: "Roda de Foice",
            classe: "Foice",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Arremessa foice que retorna como bumerangue.",
            descricao_completa: "O assassino arremessa sua foice na forma de uma roda giratória vertical, que avança em linha reta e retorna como um bumerangue, causando dano a todos os inimigos no caminho. Se o assassino gastar o dobro de mana, o tamanho da foice aumenta em [100%] durante o arremesso, ampliando seu alcance e dano. Ao retornar, a foice volta ao tamanho normal.",
            custo_mana: 2000,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 2,
            nivel_desbloqueio: 3,
            passiva: false,
            alcance: "8M (A.P) / 12M (A.M)"
        },
        {
            nome: "Golpe da Foice Predatória",
            classe: "Foice",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Avança girando foice causando dano em linha.",
            descricao_completa: "O usuário avança rapidamente em linha reta, girando sua foice para causar dano a todos os inimigos no caminho. Se o golpe atingir um alvo isolado, causa dano adicional [+20%] e reduz o tempo de recarga desta habilidade [-1 turno de recarga].",
            custo_mana: 1500,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 3,
            nivel_desbloqueio: 5,
            passiva: false,
            alcance: "2M"
        },
        {
            nome: "Aparar Mágico",
            classe: "Foice",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Corta e bloqueia golpes mágicos.",
            descricao_completa: "O usuário usa sua agilidade para cortar e bloquear um golpe mágico lançado contra ele. A técnica só é bem-sucedida se a agilidade do usuário for maior do que a PM (Potência Mágica) do golpe inimigo. Após o uso, a técnica entra em tempo de recarga e só pode ser usada novamente após 3 turnos.",
            custo_mana: 1500,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 3,
            nivel_desbloqueio: 7,
            passiva: false
        },
        {
            nome: "Ataque Furtivo [Passivo]",
            classe: "Foice",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Ataques furtivos causam +10% de dano.",
            descricao_completa: "Ataques feitos pelo usuário enquanto estiver no estado de furtividade (ou seja, não detectado pelo inimigo alvo) tem um bônus de [10%] de dano em qualquer tipo de dano. Isso implica ataques que não sejam notados pelo atributo de Sentidos do alvo corretamente, ou seja, que sejam pelo menos [30%] menores que a Agilidade do assassino).",
            custo_mana: 0,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 0,
            nivel_desbloqueio: 9,
            passiva: true
        },
        {
            nome: "Segunda Marcha",
            classe: "Foice",
            categoria: "Inicial",
            tipo: "Buff",
            descricao: "Aumenta AGI e ATK progressivamente.",
            descricao_completa: "O assassino acelera seu fluxo sanguíneo, ganhando um aumento imediato de [20%] na agilidade e [10%] na força de ataque. Além disso, a [cada turno que permanece no campo de batalha], ele acumula [+10%] de agilidade e [+5%] de força de ataque, até um máximo de [50%] de agilidade e [25%] de força de ataque. O efeito de acumulação é resetado se o assassino sair do campo de batalha ou for derrotado. No entanto, o uso prolongado da técnica causa dano residual ao assassino, drenando [20%] de sua Mana por turno após o [2º turno de ativação].",
            custo_mana: 2500,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 7,
            nivel_desbloqueio: 12,
            passiva: false
        },
        {
            nome: "Ligação de Sangue",
            classe: "Foice",
            categoria: "Inicial",
            tipo: "Utilidade",
            descricao: "Puxa objetos para si com linha de mana.",
            descricao_completa: "Usando a Ligação de Sangue, criada ao utilizar um item de seu inventário, consegue criar uma linha de mana que se prende ao objeto designado e permite que este seja puxado para si, usando um dedo, se estando dentro dentro de um raio de [15 metros] e tendo formado a linha enquanto havia contato físico. Obs: Para notar as linhas invisíveis, o alvo precisa ter sentidos 30% superiores a PM do assassino. A força e velocidade das linhas são medidos pela força, mas a resistência delas é pela PM. Objetos maiores que [1,5x] o tamanho do usuário não podem ser puxados.",
            custo_mana: 700,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 3,
            nivel_desbloqueio: 15,
            passiva: false,
            duracao: "3 turnos",
            alcance: "15 metros"
        },
        {
            nome: "Ponto Fraco [Passivo]",
            classe: "Foice",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Ataques cegos em pontos vitais causam dano dobrado.",
            descricao_completa: "Se atacando um ponto vital (como olhos e pescoço) e cego, (ou seja, não sendo notado de forma alguma antes do ataque ocorrer), o ataque do assassino terá seu dano multiplicado em 2x. Entretanto, é necessário que o alvo seja completamente incapaz de compreender sua ação até o momento do dano acontecer. Independente da sua natureza.",
            custo_mana: 0,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 0,
            nivel_desbloqueio: 18,
            passiva: true
        },
        {
            nome: "Célere",
            classe: "Foice",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Corre por paredes e água com -30% agilidade.",
            descricao_completa: "Usando a mana em seu corpo junto a sua agilidade notável consegue correr por paredes e superfícies na vertical, podendo usar desse mesmo artificio para andar ou correr sobre a agua. [Se mover nesses cenários diminui 30% da agilidade].",
            custo_mana: 200,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 1,
            nivel_desbloqueio: 21,
            passiva: false,
            custo_mana_turno: 200
        },
        {
            nome: "Mãos Mágicas",
            classe: "Foice",
            categoria: "Inicial",
            tipo: "Utilidade",
            descricao: "Rouba itens tocados por 2 turnos.",
            descricao_completa: "Pode fazer objetos tocados anteriormente aparecerem em suas mãos, sejam coisas comuns ou itens alheios. Ao tocar com sua mão em qualquer item equipado (como armaduras ou armas não empunhadas na posse do usuário), consegue 'roubar' o item por dois turnos, sendo necessário imbuir mana no objeto para isso. Necessário que a agilidade do usuário seja maior do que a sentidos do alvo. Se a força do alvo for [50%] maior que a agilidade do assassino, a habilidade não funcionará se ele estiver consciente da sua intenção. A habilidade não funciona em itens com [1 Rank] de diferença para cima.",
            custo_mana: 900,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 3,
            nivel_desbloqueio: 24,
            passiva: false
        },
        {
            nome: "Sede de Sangue",
            classe: "Foice",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Aura que reduz atributos de inimigos mais fracos.",
            descricao_completa: "O assassino canaliza sua sede de sangue, criando uma aura intimidante que se espalha ao seu redor. Inimigos dentro da área sofrem redução de até [50%] nos atributos dependendo de quanto ele é abaixo de seu nível. Caso ele tenha [5 níveis] abaixo, ele perde [10%] dos atributos, caso ele tenha [15 níveis] abaixo o debuff chega a [30%] e caso tenha [25 níveis] abaixo chegando em [50%] de redução nos atributos. Em inimigos superiores essa técnica funciona com base na agilidade do usuário. Caso o usuário tenha o dobro da velocidade do inimigo, essa técnica reduz [25%] e funcionando apenas e exclusivamente nesse caso. Dura por [2 Turnos].",
            custo_mana: 1500,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 3,
            nivel_desbloqueio: 27,
            passiva: false,
            alcance: "10M"
        }
    ]
};

module.exports = foice;