const katana = {
    nome: "Katana",
    descricao_classe: "Especialista em combate com katana, domina técnicas de corte rápido, precisão e mobilidade. Possui ataques furtivos e técnicas de espada únicas.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Corte Veloz do Vento",
        classe: "Katana",
        categoria: "Inicial",
        tipo: "Mágica",
        descricao: "Desembainha rapidamente e ataca passando pelo inimigo.",
        descricao_completa: "O praticante coloca a sua espada embainhada na posição vertical e então escuta a 'respiração' de seu oponente. Em seguida, o praticante rapidamente desembainha a sua lâmina enquanto ataca passando por seu inimigo e, em seguida, embainha sua espada.[50% de Agilidade por 1 Turno/ 2M].",
        custo_mana: 1500,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 3,
        nivel_desbloqueio: 1,
        passiva: false
    },
    tecnicas: [
        {
            nome: "Dragão Voador",
            classe: "Katana",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Lança corte de vento em formato de dragão.",
            descricao_completa: "Usando uma espada empunhada em sua mão esquerda com a mão direita segurando a esquerda pulso de apoio. O usuário emana uma aura roxa sobre sua lâmina. Podendo lançar uma espécie de corte de vento pressurizado em formato de dragão em direção ao inimigo.",
            custo_mana: 2000,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 2,
            nivel_desbloqueio: 3,
            passiva: false,
            alcance: "5M"
        },
        {
            nome: "Grande Choque do Dragão",
            classe: "Katana",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Gira criando tempestade de cortes em área.",
            descricao_completa: "O espadachim gira rapidamente com sua katana, criando uma tempestade de cortes e um tornado em sua volta que causa dano em área ao redor dele. Inimigos atingidos são arremessados ao ar, permitindo que o espadachim use outras habilidades para combinar.",
            custo_mana: 2500,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 3,
            nivel_desbloqueio: 5,
            passiva: false,
            alcance: "1 metro"
        },
        {
            nome: "Aparar",
            classe: "Katana",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Bloqueia golpes físicos com agilidade.",
            descricao_completa: "Usando de sua agilidade consegue aparar um golpe lançado contra o usuário, apenas golpes fisicos, bloqueando danos de qualquer tipo de ataque, durante a execução da habilidade, após habilidade entra em tempo de recarga e só pode ser usado novamente após [3 turnos]. A agilidade do usuário precisa ser maior do que a força do golpe inimigo.",
            custo_mana: 1500,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 3,
            nivel_desbloqueio: 7,
            passiva: false
        },
        {
            nome: "Eclípse das Katanas",
            classe: "Katana",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Onda de cortes mágicos em todas as direções.",
            descricao_completa: "O espadachim canaliza mana para lançar uma onda de cortes mágicos em todas as direções. Cada corte causa dano e aplica um efeito de lentidão [10%]. Inimigos atingidos por múltiplos cortes [3] ficam atordoados por 1 turno.",
            custo_mana: 4000,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 8,
            nivel_desbloqueio: 10,
            passiva: false,
            alcance: "6M"
        },
        {
            nome: "Ataque Furtivo [Passivo]",
            classe: "Katana",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Ataques furtivos causam +10% de dano.",
            descricao_completa: "Ataques feitos pelo usuário enquanto estiver no estado de furtividade (ou seja, não detectado pelo inimigo alvo) tem um bônus de [10%] de dano em qualquer tipo de dano. Isso implica ataques que não sejam notados pelo atributo de Sentidos do alvo corretamente, ou seja, que sejam pelo menos [30%] menores que a Agilidade do assassino).",
            custo_mana: 0,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 0,
            nivel_desbloqueio: 12,
            passiva: true
        },
        {
            nome: "Célere",
            classe: "Katana",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Corre por paredes e água com -30% agilidade.",
            descricao_completa: "Usando a mana em seu corpo junto a sua agilidade notável consegue correr por paredes e superfícies na vertical, podendo usar desse mesmo artificio para andar ou correr sobre a agua. [Se mover nesses cenários diminui 30% da agilidade].",
            custo_mana: 500,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 1,
            nivel_desbloqueio: 14,
            passiva: false,
            custo_mana_turno: 500
        },
        {
            nome: "Mãos Mágicas",
            classe: "Katana",
            categoria: "Inicial",
            tipo: "Utilidade",
            descricao: "Rouba itens tocados por 2 turnos.",
            descricao_completa: "Pode fazer objetos tocados anteriormente aparecerem em suas mãos, sejam coisas comuns ou itens alheios. Ao tocar com sua mão em qualquer item equipado (como armaduras ou armas não empunhadas na posse do usuário), consegue 'roubar' o item por dois turnos, sendo necessário imbuir mana no objeto para isso. Necessário que a agilidade do usuário seja maior do que a sentidos do alvo. Se a força do alvo for [50%] maior que a agilidade do assassino, a habilidade não funcionará se ele estiver consciente da sua intenção. A habilidade não funciona em itens com [1 Rank] de diferença para cima.",
            custo_mana: 1000,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 3,
            nivel_desbloqueio: 17,
            passiva: false
        },
        {
            nome: "Prisão das Lâminas Arqueadas",
            classe: "Katana",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria prisão de lâminas que causa dano massivo.",
            descricao_completa: "O assassino balança sua katana com extrema precisão, criando três lâminas arqueadas de energia mágica que se fecham simultaneamente sobre o inimigo de todos os lados. As lâminas formam uma prisão inescapável, impedindo qualquer chance de defesa ou evasão. No momento em que as lâminas se fecham, o assassino conjura duas espadas mágicas adicionais, que se unem ao ataque principal, causando dano massivo.",
            custo_mana: 3500,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 4,
            nivel_desbloqueio: 20,
            passiva: false,
            alcance: "2M"
        },
        {
            nome: "Véu da Névoa Eterna",
            classe: "Katana",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Expande névoa que torna usuário invisível.",
            descricao_completa: "O usuário expande uma densa camada de névoa pelo ambiente, seja a partir de fontes de água próximas ou pela liberação de vapor pela boca. A névoa cobre uma grande área, obscurecendo a visão dos inimigos e tornando o usuário invisível e imune a qualquer efeito de habilidade localizável (como rastreamento, visão verdadeira ou habilidades de revelação). Enquanto estiver na névoa, o usuário ganha um aumento de velocidade de movimento de [10%].",
            custo_mana: 5000,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 8,
            nivel_desbloqueio: 23,
            passiva: false,
            custo_mana_turno: 2500,
            alcance: "10 metros (raio da névoa)"
        },
        {
            nome: "Sede de Sangue",
            classe: "Katana",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Aura que reduz atributos de inimigos mais fracos.",
            descricao_completa: "O assassino canaliza sua sede de sangue, criando uma aura intimidante que se espalha ao seu redor. Inimigos dentro da área sofrem redução de até [50%] nos atributos dependendo de quanto ele é abaixo de seu nível. Caso ele tenha [5 níveis abaixo], ele perde [10%] dos atributos, caso ele tenha [15 níveis] abaixo o debuff chega a [30%] e caso tenha [25 níveis] abaixo chegando em [50%] de redução nos atributos. Dura por [2 turnos].",
            custo_mana: 1500,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 3,
            nivel_desbloqueio: 25,
            passiva: false,
            alcance: "10M"
        }
    ]
};

module.exports = katana;