const kusarigama = {
    nome: "Kusarigama",
    descricao_classe: "Especialista em combate com kusarigama (foice com corrente), domina técnicas de alcance, puxão e controle. Possui alta versatilidade em combate corpo a corpo e à distância.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Gancho Enforcador",
        classe: "Kusarigama",
        categoria: "Inicial",
        tipo: "Mágica",
        descricao: "Prende alvo e aplica veneno que reduz atributos.",
        descricao_completa: "Você prende seu alvo com suas pequenas foices, causando dano em seu corpo e em seguida libera uma onda de veneno que percorre todo o sistema circulatório, fazendo com que o inimigo fique 25% menos capaz. Em outras palavras, todos os atributos do inimigo são reduzidos em comparação a 25% do seu NIR.",
        custo_mana: 6000,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 1,
        nivel_desbloqueio: 1,
        passiva: false,
        alcance: "6m",
        duracao: "1 Turno"
    },
    tecnicas: [
        {
            nome: "Avanço Letal",
            classe: "Kusarigama",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Puxa si mesmo com corrente e avança.",
            descricao_completa: "O usuário da técnica lança sua kusarigama atingindo uma superfície até 10 metros de distância e realiza um puxão envolvendo seu corpo em sua mana. Ao puxar a si próprio, ele avança com velocidade aumentada e realiza um segundo movimento, atacando o inimigo com um chute. O dano do seu ataque é calculado em 100% de seu NIR e sua velocidade neste ataque aumenta em 25% com base em seu NIR.",
            custo_mana: 1500,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 2,
            nivel_desbloqueio: 3,
            passiva: false,
            alcance: "10m"
        },
        {
            nome: "Marionete Assassina",
            classe: "Kusarigama",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Controla cadáver como marionete.",
            descricao_completa: "O usuário desta técnica aprende a comandar o corpo de outras criaturas com base em sua manipulação através das correntes de sua kusarigama. Você envolve suas correntes em uma criatura de rank inferior que esteja morta ou inconsciente e controla-a como uma marionete. Enquanto estiver fazendo isso, os atributos dessa criatura são idênticos ao seu NIR base [55% FOR sem itens e buffs + 55% AGI sem itens e buffs]. A marionete por portar até 1 único item de sua escolha, recebendo os benefícios ou penalidades, caso existam. Você só consegue usar técnicas da criatura, caso tenha visto e após a duração da técnica, você perde total controle sobre os efeitos e a própria criatura.",
            custo_mana: 6000,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 5,
            nivel_desbloqueio: 5,
            passiva: false,
            duracao: "5 Turnos",
            custo_mana_turno: 1500
        },
        {
            nome: "Acumulador das Sombras",
            classe: "Kusarigama",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Aumenta FOR após usar Avanço Letal.",
            descricao_completa: "A cada vez que você utilizar a técnica 'Avanço Letal' e o ataque for bem sucedido, sua FOR aumenta em 5%, tornando o seu próximo ataque ainda mais poderoso, independente da técnica que for usar. Você pode chegar a um incremento máximo no atributo base de 25% e quando atingir no nível 80 em 50%. Paralelamente, suas correntes não fazem barulho, se você estiver em penumbra ou escuridão total.",
            custo_mana: 0,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 0,
            nivel_desbloqueio: 8,
            passiva: true,
            duracao: "2 Turnos"
        },
        {
            nome: "Pesadelo Insistente",
            classe: "Kusarigama",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Causa dano mental baseado em SEN.",
            descricao_completa: "O usuário da técnica canaliza sua mana em sua arma, aplicando a ela uma energia escura, quase semelhante ao elemento escuridão, porém, ainda distinto de mais. Quando você atingir uma criatura com o próximo ataque, ela não sofrerá quaisquer danos físicos, mas a sua mente será brutalmente agredida por suas lâminas. Você causa dano com base em 40% do seu NIR + 40% de seu PM, no seu inimigo. Porém, ao invés de resistência, o atributo de comparação do adversário é sentidos [SEN].",
            custo_mana: 6000,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 3,
            nivel_desbloqueio: 11,
            passiva: false,
            alcance: "6m",
            dano: "40% NIR + 40% PM"
        },
        {
            nome: "Receptáculo de Monstros",
            classe: "Kusarigama",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Captura núcleo de boss para usar skills.",
            descricao_completa: "Você aprendeu que a melhor forma de se fortalecer é utilizando o que aprende em campo de batalha. Quando você enfrenta uma criatura de rank E ou D [Boss ou Miniboss] em um evento narrado [masmorra, missão, DLC, GvG], caso ela possua um núcleo, você pode capturar esse núcleo e infundir na sua própria arma, ganhando uma habilidade que outrora era da criatura. O núcleo concede uma skill de uso único e após este uso, o cristal se quebra, dando vaga para o próximo núcleo.",
            custo_mana: 8000,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 5,
            nivel_desbloqueio: 14,
            passiva: false,
            estoque: "Apenas 1 núcleo por vez"
        },
        {
            nome: "Mestre de Ilusões",
            classe: "Kusarigama",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Cria ilusões que negam esquiva.",
            descricao_completa: "O usuário movimenta suas kurasigamas tão rápido que outras pessoas sentem dificuldades para poder vê-las. Isso acontece pois você forma ilusões diversas não só da arma, mas também de seus braços, impedindo o inimigo de distinguir qual é verdadeira e qual é ilusão. Fazendo isso, você pode realizar um ataque — incluindo usar técnicas que não exijam seu deslocamento — contra a criatura negando a chance de qualquer esquiva. A criatura ainda poderá resistir fisicamente, mas não terá chance de esquivar, a menos que o valor de SEN seja igual ou maior a 60% do seu NIR.",
            custo_mana: 4000,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 2,
            nivel_desbloqueio: 17,
            passiva: false
        },
        {
            nome: "Pêndulo Invisível",
            classe: "Kusarigama",
            categoria: "Inicial",
            tipo: "Movimentação",
            descricao: "Move-se pendurando a kusarigama no ar.",
            descricao_completa: "Mover-se no campo de batalha é algo crucial para aqueles que se aproveitam do posicionamento. Você aprendeu a mover-se como em um pêndulo, mesmo que não haja local para prender a lâmina de sua kusarigama. isto é, você aprisiona, pelo menos uma de suas kusarigamas em pleno ar e se move com deslocamento igual a sua AGI, como se estivesse se pendurando.",
            custo_mana: 300,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 1,
            nivel_desbloqueio: 20,
            passiva: false,
            custo_por_pendulo: "300MP"
        },
        {
            nome: "Tecelão de Corpos",
            classe: "Kusarigama",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Usa cadáveres como escudo.",
            descricao_completa: "Você é capaz de costurar cadáveres e utilizá-los como um escudo. Em um único movimento as suas lâminas e correntes se movem no campo de batalha prendendo todos os cadáveres — independente de raça e rank — reunindo-os em um grande escudo à sua frente. O escudo, mesmo que com 1 único cadáver possui naturalmente uma capacidade de resistência equivalente a 50% de seu NIR + 60% de seu PM. Para cada corpo, além do primeiro, você adiciona +20% de seu PM como um adicional.",
            custo_mana: 4000,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 3,
            nivel_desbloqueio: 23,
            passiva: false
        },
        {
            nome: "Entre Tecidos",
            classe: "Kusarigama",
            categoria: "Inicial",
            tipo: "Movimentação",
            descricao: "Teleporta entre realidades por 5m.",
            descricao_completa: "Como outra forma de se defender ou ainda se mover de forma a surpreender o inimigo, você consegue 'descosturar' rapidamente o tecido que separa uma realidade da outra. Você desaparece de um ponto específico passando por outra realidade — totalmente vazia — e ressurge em um ponto de sua escolha até 5 metros de distância do local onde estava. Você pode usar isso para escapar de um ataque ou então para realizar um ataque. Na segunda opção, você ganha 10% de chance de um dano crítico.",
            custo_mana: 6000,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 5,
            nivel_desbloqueio: 26,
            passiva: false
        }
    ]
};

module.exports = kusarigama;