const lutador = {
    nome: "Lutador",
    descricao_classe: "O Lutador utiliza diferentes formas de combate corpo a corpo, cada uma com suas próprias técnicas e estilos de luta. Possui quatro formas de jogo: Espadão, Manopla, Punhos e Kanabo.",
    tipos_luta: ["Punhos", "Kanabo", "Manopla", "Espadão"],
    tecnicaInicial: {
        nome: "Soco Potente",
        classe: "Lutador",
        categoria: "Inicial",
        tipo: "Física",
        descricao: "Um soco carregado de mana que causa dano extra.",
        descricao_completa: "Um golpe básico mas poderoso que concentra mana no punho para causar dano adicional ao impacto. Técnica fundamental de todo lutador.",
        custo_mana: 20,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 1,
        nivel_desbloqueio: 1,
        passiva: false
    },
    tecnicas: [
        {
            nome: "Golpe Rápido",
            classe: "Lutador",
            categoria: "Inicial",
            tipo: "Física",
            descricao: "Um golpe rápido que atinge primeiro.",
            descricao_completa: "Um golpe veloz e direto, treinado para ser mais rápido que o reflexo do oponente, garantindo o primeiro ataque.",
            custo_mana: 15,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 0,
            nivel_desbloqueio: 3,
            passiva: false
        },
        {
            nome: "Postura de Combate",
            classe: "Lutador",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Aumenta a defesa em combate corpo a corpo.",
            descricao_completa: "Uma postura básica de combate que o lutador assume automaticamente, aumentando sua resistência a golpes físicos em 10%.",
            custo_mana: 0,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 0,
            nivel_desbloqueio: 5,
            passiva: true
        }
    ],
    formas_jogo: {
        "Espadão": {
            nome: "Espadão",
            descricao: "O espadão do lutador é uma arma colossal que exige força sobre-humana para ser manuseada. Ao bloquear um ataque com o espadão, o lutador absorve parte do impacto, reduzindo o dano recebido em 30%. A cada turno, ele ganha 2% em FOR até o fim da batalha.",
            tecnicas: [
                {
                    nome: "Impacto do Espadão",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Causa dano massivo com o espadão.",
                    descricao_completa: "Um golpe devastador que utiliza todo o peso e força do espadão para causar dano massivo. A cada turno de batalha, o dano aumenta em 2%.",
                    custo_mana: 30,
                    custo_qi: 80,
                    custo_qi_formatado: "80 Qi",
                    cooldown: 2,
                    nivel_desbloqueio: 5,
                    passiva: false
                },
                {
                    nome: "Semblante do Cavaleiro",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Buff",
                    descricao: "Cria aura esverdeada que aumenta ataque e resistência.",
                    descricao_completa: "O usuário canaliza sua energia, criando uma aura esverdeada que o envolve e aumenta seu ataque e resistência em 20% por 3 turnos. Além disso, a aura também reduz o dano recebido de ataques à distância em 15% e concede imunidade a efeitos de lentidão durante a duração.",
                    custo_mana: 1500,
                    custo_qi: 320,
                    custo_qi_formatado: "320 Qi",
                    cooldown: 3,
                    nivel_desbloqueio: 10,
                    passiva: false
                },
                {
                    nome: "Soberba de Balmung",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Mágica",
                    descricao: "Corte poderoso com onda de energia esverdeada.",
                    descricao_completa: "O usuário canaliza sua mana e força em um corte poderoso com sua espada, criando uma onda de energia esverdeada que avança em linha reta. A cada 1.000MP de mana, o alcance aumenta em 2 metros, e a cada 50 de força a Altura em 2M.",
                    custo_mana: 1000,
                    custo_qi: 640,
                    custo_qi_formatado: "640 Qi",
                    cooldown: 3,
                    nivel_desbloqueio: 15,
                    passiva: false
                },
                {
                    nome: "Balmung Liberar",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Mágica",
                    descricao: "Aura verde que expande a lâmina da espada.",
                    descricao_completa: "O usuário canaliza sua mana na lâmina, criando uma aura verde que se expande ao seu redor. Essa aura faz uma espada esverdeada energizada surgir em torno da lâmina já existente, ampliando seu tamanho e alcance. A cada 1.000 de mana, o tamanho da lâmina aumenta em +2 metros, e o dano adicional aumenta em 15% do PM do usuário.",
                    custo_mana: 1000,
                    custo_qi: 1280,
                    custo_qi_formatado: "1280 Qi",
                    cooldown: 2,
                    nivel_desbloqueio: 20,
                    passiva: false
                },
                {
                    nome: "Investida do Amanhã",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Avanço rápido com imunidade a efeitos de controle.",
                    descricao_completa: "O usuário canaliza uma aura verde que o envolve, concedendo um aumento de 40% na agilidade por 1 Turno e impulsionando-o rapidamente na direção de um inimigo ou local de sua escolha. Durante o impulso, o usuário é imune a efeitos de controle (como lentidão, atordoamento ou enraizamento).",
                    custo_mana: 2500,
                    custo_qi: 2560,
                    custo_qi_formatado: "2560 Qi",
                    cooldown: 4,
                    nivel_desbloqueio: 25,
                    passiva: false
                },
                {
                    nome: "Escudo de Akhilleus",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Defesa",
                    descricao: "Cria escudo mágico verde para defender feitiços.",
                    descricao_completa: "O usuário cria uma rajada de pura energia a partir de sua lâmina criando um escudo mágico verde para segurar feitiços. Caso o PM da técnica seja maior que seu Ataque, o escudo se partira.",
                    custo_mana: 2500,
                    custo_qi: 5120,
                    custo_qi_formatado: "5120 Qi",
                    cooldown: 4,
                    nivel_desbloqueio: 30,
                    passiva: false
                },
                {
                    nome: "Eclípse da Espada",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Mágica",
                    descricao: "Onda de energia massiva que avança em linha reta.",
                    descricao_completa: "O usuário canaliza toda sua energia em um único golpe poderoso, criando uma onda de energia que avança em linha reta e causa dano massivo a todos os inimigos no caminho +50%. A onda também destrói estruturas no ambiente.",
                    custo_mana: 4000,
                    custo_qi: 10000,
                    custo_qi_formatado: "10000 Qi",
                    cooldown: 5,
                    nivel_desbloqueio: 35,
                    passiva: false
                },
                {
                    nome: "A sensação do Dragão",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Buff",
                    descricao: "Corpo pega fogo internamente gerando queimaduras.",
                    descricao_completa: "O corpo do lutador pega fogo internamente, aquecendo muito e ativando todo sistema imunológico juntamente da adrenalina. Golpes acertados com corpo a espada em chamas gera queimaduras de terceiro grau além de dano de queimadura extra [queimadura= 50% da força.] ao final do turno o corpo do lutador volta ao normal.",
                    custo_mana: 1300,
                    custo_qi: 15000,
                    custo_qi_formatado: "15000 Qi",
                    cooldown: 3,
                    nivel_desbloqueio: 40,
                    passiva: false
                },
                {
                    nome: "Golpe do Abismo",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Mágica",
                    descricao: "Golpe poderoso que causa explosão massiva.",
                    descricao_completa: "O lutador desfere um golpe com espada tão poderoso que parece abrir um abismo na superfície, criando uma área de efeito devastadora ao redor do alvo atingido. Esse ataque cria uma explosão ao redor do alvo, que causa dano nos que estiverem próximos. O Dano da explosão e a sua Força [x2]",
                    custo_mana: 5000,
                    custo_qi: 25000,
                    custo_qi_formatado: "25000 Qi",
                    cooldown: 4,
                    nivel_desbloqueio: 45,
                    passiva: false
                },
                {
                    nome: "Investida Frenética",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Investida furiosa com aumento de velocidade e poder.",
                    descricao_completa: "O lutador canaliza sua força em uma investida furiosa contra um alvo específico. Ele se lança em direção ao inimigo, aumentando sua velocidade e poder de ataque momentaneamente por utilizar de um impulso inicial. [Soma Força{Base} +50% de agilidade{Base} para avançar no inimigo]",
                    custo_mana: 2000,
                    custo_qi: 50000,
                    custo_qi_formatado: "50000 Qi",
                    cooldown: 1,
                    nivel_desbloqueio: 50,
                    passiva: false
                }
            ]
        },
        "Manopla": {
            nome: "Manopla",
            descricao: "As manoplas do lutador são reforçadas com metal pesado, transformando seus punhos em armas letais. Cada ataque bem-sucedido aumenta a força do próximo golpe em 10%, acumulando até 5 vezes. Além disso, o lutador ganha resistência a interrupções enquanto ataca.",
            tecnicas: [
                {
                    nome: "Combo de Punhos",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Sequência rápida de golpes com manopla.",
                    descricao_completa: "Uma sequência de golpes rápidos e precisos com a manopla. Cada golpe acertado acumula 10% de dano no próximo, até 5x.",
                    custo_mana: 25,
                    custo_qi: 80,
                    custo_qi_formatado: "80 Qi",
                    cooldown: 1,
                    nivel_desbloqueio: 5,
                    passiva: false
                },
                {
                    nome: "Impacto Esmagador",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Avanço rápido que golpeia e atordoa o alvo.",
                    descricao_completa: "O usuário avança rapidamente em linha reta [20% AGILIDADE], golpeando o primeiro inimigo no caminho com um soco poderoso que causa dano e atordoa o alvo por 1 turno. Se o alvo for atingido contra uma parede ou obstáculo, o dano é aumentado em 50%.",
                    custo_mana: 1500,
                    custo_qi: 320,
                    custo_qi_formatado: "320 Qi",
                    cooldown: 2,
                    nivel_desbloqueio: 10,
                    passiva: false
                },
                {
                    nome: "Golpe do Colosso",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Golpe devastador no chão que causa dano em área.",
                    descricao_completa: "O usuário canaliza energia em seus punhos [+30% AT], desferindo um golpe devastador no chão que causa dano em área. Inimigos no centro do impacto são arremessados ao ar.[necessário ter Força maior para resistir ao levantamento]",
                    custo_mana: 2500,
                    custo_qi: 640,
                    custo_qi_formatado: "640 Qi",
                    cooldown: 2,
                    nivel_desbloqueio: 15,
                    passiva: false
                },
                {
                    nome: "Fúria dos Punhos Implacáveis",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Buff",
                    descricao: "Aumenta agilidade e dano por 3 turnos.",
                    descricao_completa: "O usuário entra em um estado de fúria, aumentando sua agilidade em 20% e causando dano adicional 10% com cada golpe por 3 turnos [Max:30%]. A Cada 2 golpes também reduz o tempo de recarga dessa habilidade do usuário em 1 turno.",
                    custo_mana: 3000,
                    custo_qi: 1280,
                    custo_qi_formatado: "1280 Qi",
                    cooldown: 6,
                    nivel_desbloqueio: 20,
                    passiva: false
                },
                {
                    nome: "Eclípse dos Punhos",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Golpe poderoso com explosão em área.",
                    descricao_completa: "O usuário canaliza toda sua energia em um único golpe poderoso com seus punhos, causando dano massivo ao primeiro inimigo atingido e criando uma explosão de energia que causa dano em área. Inimigos atingidos pela explosão ficam atordoados por 1 turno.",
                    custo_mana: 4000,
                    custo_qi: 2560,
                    custo_qi_formatado: "2560 Qi",
                    cooldown: 8,
                    nivel_desbloqueio: 25,
                    passiva: false
                },
                {
                    nome: "Contra-Ataque Equivalente",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Absorve dano e devolve em onda de choque.",
                    descricao_completa: "O lutador absorve o dano sofrido parcialmente de um ataque [50%] e o coloca em seu próximo ataque. A próxima vez que atacar, naquele turno, o seu ataque gera uma onda de choque acertando todas as criaturas que estiverem até 10M de você. Se a força do usuário for 80% ou mais da resistência do adversário, ele causa fissura nos ossos, inutilizando o membro.",
                    custo_mana: 2000,
                    custo_qi: 5120,
                    custo_qi_formatado: "5120 Qi",
                    cooldown: 5,
                    nivel_desbloqueio: 30,
                    passiva: false
                },
                {
                    nome: "Quebra ossos",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Ignora resistência causando rachaduras nos ossos.",
                    descricao_completa: "O lutador aprende bater não só nos pontos fracos, agora mirando nos pontos frágeis dos ossos, quando desferir um golpe usando essa habilidade, gera uma rachadura no osso acertado [ignora 30% da resistência]. Caso a diferença seja muito alta, quebra o osso acertado.",
                    custo_mana: 1800,
                    custo_qi: 10000,
                    custo_qi_formatado: "10000 Qi",
                    cooldown: 3,
                    nivel_desbloqueio: 35,
                    passiva: false
                },
                {
                    nome: "Pancada Certeira",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Golpes precisos que reduzem armadura do oponente.",
                    descricao_completa: "O usuário de manopla desfere uma série de golpes precisos e poderosos. A cada golpe, a armadura do oponente é reduzida em 10%, acumulando até 30% após 3 golpes. No quarto golpe, o usuário converte sua força em agilidade golpeando mais rápido o oponente.",
                    custo_mana: 1500,
                    custo_qi: 15000,
                    custo_qi_formatado: "15000 Qi",
                    cooldown: 2,
                    nivel_desbloqueio: 40,
                    passiva: false
                },
                {
                    nome: "Impacto Crescente",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Ataque em arco que ignora resistência de múltiplos inimigos.",
                    descricao_completa: "O lutador concentra sua energia em um golpe devastador que se assemelha à trajetória da lua crescente, desferindo um ataque em arco que pode atravessar a defesa do oponente.[Consegue acertar no máximo até cinco inimigos, ignorando 40% da resistência deles]",
                    custo_mana: 2500,
                    custo_qi: 25000,
                    custo_qi_formatado: "25000 Qi",
                    cooldown: 3,
                    nivel_desbloqueio: 45,
                    passiva: false
                },
                {
                    nome: "Não Morrerei Aqui",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Passiva",
                    descricao: "Ativa à beira da morte, concedendo +60% em todos atributos.",
                    descricao_completa: "Quando atingir um percentual baixo de vida que seja crítico e a beira da morte essa passiva se ativa uma vez por evento ou luta, impedindo o lutador de morrer apenas na sua ativação. O lutador ganha força, velocidade e resistência [+60%] além de inutilizar qualquer debuff existente nele, seja por título ou passiva, tornando ele no seu prime (melhor momento) por 2 turnos. Quando esses dois turnos acabam, o lutador desmaia.",
                    custo_mana: 0,
                    custo_qi: 50000,
                    custo_qi_formatado: "50000 Qi",
                    cooldown: 0,
                    nivel_desbloqueio: 50,
                    passiva: true
                }
            ]
        },
        "Punhos": {
            nome: "Punhos",
            descricao: "Os punhos do lutador são armas naturais que refletem sua resistência física. Ao receber dano, o lutador acumula mana, reduzindo o dano recebido em 5% por acúmulo, até um máximo de 5 vezes. Quando atingido com o máximo de acúmulos, o lutador libera uma explosão de vento de seu punho que afasta inimigos.",
            tecnicas: [
                {
                    nome: "Explosão de Vento",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Libera explosão de vento após acumular dano.",
                    descricao_completa: "Após acumular 5 acúmulos de dano recebido, o lutador libera uma poderosa explosão de vento que afasta todos os inimigos próximos.",
                    custo_mana: 35,
                    custo_qi: 80,
                    custo_qi_formatado: "80 Qi",
                    cooldown: 3,
                    nivel_desbloqueio: 5,
                    passiva: false
                },
                {
                    nome: "Impacto das Areias",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Onda de areia que arremessa inimigos e reduz velocidade.",
                    descricao_completa: "O usuário canaliza mana em seu punho e golpeia o chão, criando uma onda de areia que arremessa os inimigos para trás e esconde sua presença por alguns segundos. A técnica causa dano em área e reduz a velocidade dos alvos em 30% por 3 Turnos.",
                    custo_mana: 800,
                    custo_qi: 320,
                    custo_qi_formatado: "320 Qi",
                    cooldown: 2,
                    nivel_desbloqueio: 10,
                    passiva: false
                },
                {
                    nome: "Punho Revolucionário",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Explosão de energia que quebra armaduras e rouba resistência.",
                    descricao_completa: "O usuário libera uma explosão de energia mágica ao golpear o chão, causando dano e quebrando armaduras. A técnica também rouba 25% da resistência dos inimigos atingidos, transferindo-a para o usuário por 2 turnos.",
                    custo_mana: 1200,
                    custo_qi: 640,
                    custo_qi_formatado: "640 Qi",
                    cooldown: 3,
                    nivel_desbloqueio: 15,
                    passiva: false
                },
                {
                    nome: "Fúria do Colosso",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Avanço em linha reta derrubando inimigos com soco poderoso.",
                    descricao_completa: "O usuário avança em linha reta, derrubando todos os inimigos no caminho. Ao final do avanço, ele desfere um soco poderoso que causa dano adicional com base na mana perdida do usuário.[10% a cada 1000 de mana gasto]",
                    custo_mana: 1500,
                    custo_qi: 1280,
                    custo_qi_formatado: "1280 Qi",
                    cooldown: 4,
                    nivel_desbloqueio: 20,
                    passiva: false
                },
                {
                    nome: "Golpe do Faraó",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Soco carregado que aumenta ataque e zera cooldown se abater inimigo.",
                    descricao_completa: "O usuário desfere um soco carregado com mana, causando dano único e aumentando seu próprio ataque em 20% por 2 turnos. Caso um inimigo seja abatido neste soco, o tempo de recarga é zera e pode utilizar novamente essa técnica.[até 5x]",
                    custo_mana: 800,
                    custo_qi: 2560,
                    custo_qi_formatado: "2560 Qi",
                    cooldown: 1,
                    nivel_desbloqueio: 25,
                    passiva: false
                },
                {
                    nome: "Dominância do Chefe",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Arremessa inimigo no chão causando dano em área e atordoando.",
                    descricao_completa: "O usuário agarra um inimigo e o arremessa no chão, causando dano em área e atordoando os alvos por 2 Turnos. A técnica também gera um escudo temporário com base no dano causado.",
                    custo_mana: 2500,
                    custo_qi: 5120,
                    custo_qi_formatado: "5120 Qi",
                    cooldown: 4,
                    nivel_desbloqueio: 30,
                    passiva: false
                },
                {
                    nome: "Quebra ossos",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Ignora resistência causando rachaduras nos ossos.",
                    descricao_completa: "O lutador aprende bater não só nos pontos fracos, agora mirando nos pontos frágeis dos ossos, quando desferir um golpe usando essa habilidade, gera uma rachadura no osso acertado [ignora 35% da resistência]. Caso a diferença seja muito alta, quebra o osso acertado.",
                    custo_mana: 1000,
                    custo_qi: 10000,
                    custo_qi_formatado: "10000 Qi",
                    cooldown: 3,
                    nivel_desbloqueio: 35,
                    passiva: false
                },
                {
                    nome: "Contra-Ataque Equivalente",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Absorve dano e devolve em onda de choque.",
                    descricao_completa: "O lutador absorve o dano sofrido parcialmente de um ataque [50%] e o coloca em seu próximo ataque. A próxima vez que atacar, naquele turno, o seu ataque gera uma onda de choque acertando todas as criaturas que estiverem até 10 metros de você. Se a força do usuário for 80% ou mais da resistência do adversário, ele causa fissura nos ossos, inutilizando o membro.",
                    custo_mana: 1200,
                    custo_qi: 15000,
                    custo_qi_formatado: "15000 Qi",
                    cooldown: 5,
                    nivel_desbloqueio: 40,
                    passiva: false
                },
                {
                    nome: "Não Morrerei Aqui",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Passiva",
                    descricao: "Ativa à beira da morte, concedendo +60% em todos atributos.",
                    descricao_completa: "Quando atingir um percentual baixo de vida que seja crítico e a beira da morte essa passiva se ativa uma vez por evento ou luta, impedindo o lutador de morrer apenas na sua ativação. O lutador ganha força, velocidade e resistência [+60%] além de inutilizar qualquer debuff existente nele, seja por título ou passiva, tornando ele no seu prime (melhor momento) por 2 turnos. Quando esses dois turnos acabam, o lutador desmaia.",
                    custo_mana: 0,
                    custo_qi: 25000,
                    custo_qi_formatado: "25000 Qi",
                    cooldown: 0,
                    nivel_desbloqueio: 45,
                    passiva: true
                },
                {
                    nome: "Golpes decisivos",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Passiva",
                    descricao: "25% de chance de acerto crítico +35% de dano.",
                    descricao_completa: "O lutador se concentra na batalha, analisando friamente o alvo, desferindo golpes devastadores, mirando nos pontos vitais do inimigo para causar um dano massivo.[Ganha 25% de chance de acerto crítico além de causar +35% de dano]",
                    custo_mana: 0,
                    custo_qi: 50000,
                    custo_qi_formatado: "50000 Qi",
                    cooldown: 0,
                    nivel_desbloqueio: 50,
                    passiva: true
                }
            ]
        },
        "Kanabo": {
            nome: "Kanabo",
            descricao: "O kanabo do lutador é uma arma pesada e brutal, capaz de esmagar até os inimigos mais resistentes. Cada ataque bem-sucedido reduz a velocidade de movimento do alvo em 10%, acumulando até 3 vezes. Se o inimigo estiver com o máximo de acúmulos, o próximo golpe quebra a armadura, ignorando 30% da defesa do alvo.",
            tecnicas: [
                {
                    nome: "Esmagamento",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Golpe esmagador com o kanabo.",
                    descricao_completa: "Um golpe brutal que utiliza todo o peso do kanabo para esmagar o inimigo. Acumula até 3x de redução de velocidade e quebra armadura no máximo.",
                    custo_mana: 28,
                    custo_qi: 80,
                    custo_qi_formatado: "80 Qi",
                    cooldown: 2,
                    nivel_desbloqueio: 5,
                    passiva: false
                },
                {
                    nome: "Trovão Esmagador",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Avanço veloz com golpe de força avassaladora.",
                    descricao_completa: "O usuário avança em direção ao oponente a uma velocidade impressionante, balançando o kanabo horizontalmente com uma ou duas mãos para desferir um golpe de força avassaladora.[30% de AT]",
                    custo_mana: 1200,
                    custo_qi: 320,
                    custo_qi_formatado: "320 Qi",
                    cooldown: 1,
                    nivel_desbloqueio: 10,
                    passiva: false
                },
                {
                    nome: "Vento Demolidor",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Mágica",
                    descricao: "Lâminas de ar em forma de crescente que cortam o inimigo.",
                    descricao_completa: "O usuário balança o kanabo com força descomunal [30% de AT], gerando lâminas de ar em forma de crescente que cortam em ar pressurizado em direção ao inimigo. Essa técnica pode ser usada para ataques à distância ou para desviar adversários próximos.",
                    custo_mana: 3000,
                    custo_qi: 640,
                    custo_qi_formatado: "640 Qi",
                    cooldown: 4,
                    nivel_desbloqueio: 15,
                    passiva: false
                },
                {
                    nome: "Exército de Dragões Prósperos",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Série de golpes de alta velocidade com kanabo.",
                    descricao_completa: "O usuário gira o kanabo para ganhar impulso, imbui-o com energia poderosa e desfere uma série de golpes de alta velocidade [30% de AGI], bombardeando o inimigo com ataques consecutivos e devastadores.",
                    custo_mana: 3000,
                    custo_qi: 1280,
                    custo_qi_formatado: "1280 Qi",
                    cooldown: 4,
                    nivel_desbloqueio: 20,
                    passiva: false
                },
                {
                    nome: "Impacto Revestido",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Buff",
                    descricao: "Aura que aumenta ataque e resistência da arma.",
                    descricao_completa: "O usuário concentra sua energia na arma, envolvendo-a com uma aura poderosa que aumenta sua resistência e dano. Ao atacar, libera um choque de energia que pode causar dano adicional e quebrar defesas inimigas. Diferente de outras técnicas, essa amplia o Ataque e Resistência do Kanabo, de acordo com a mana gasta na arma. Aumentando em 10% ambos os atributos a cada 2.000MP mana gasto.",
                    custo_mana: 3000,
                    custo_qi: 2560,
                    custo_qi_formatado: "2560 Qi",
                    cooldown: 3,
                    nivel_desbloqueio: 25,
                    passiva: false
                },
                {
                    nome: "Lâmina de Diamante",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Mágica",
                    descricao: "Projétil cortante de longo alcance com dano massivo.",
                    descricao_completa: "O usuário balança sua arma com força descomunal, liberando uma onda de choque de longo alcance que se projeta como um projétil cortante e devastador. A técnica é carregada com mana pura, que concentra-se na lâmina da arma antes de ser liberada em um ataque de alcance massivo. O projétil gerado é uma manifestação densa de energia mágica, capaz de atravessar obstáculos e causar destruição em uma área ampla. Seu poder é comparado ao de uma explosão elemental, combinando força bruta e precisão para aniquilar inimigos à distância. [100% de Dano Adicional de Ataque] [Necessário carregar por 2 turnos]",
                    custo_mana: 9000,
                    custo_qi: 5120,
                    custo_qi_formatado: "5120 Qi",
                    cooldown: 5,
                    nivel_desbloqueio: 30,
                    passiva: false
                },
                {
                    nome: "Ragnarok dos Três Reinos Infernais",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Mágica",
                    descricao: "Salto massivo com golpe devastador que causa explosão.",
                    descricao_completa: "Empunha sua arma com ambas as mãos e salta a grandes alturas [30M]. Enquanto está no ar, ele gira a arma rapidamente acima de sua cabeça, canalizando uma imensa quantidade de mana pura que se manifesta como raios escuros e reluzentes ao redor da arma [10.000 mana]. Esses raios simbolizam a energia infernal do ataque. Ao descer em alta velocidade, o usuário balança a arma com força colossal, esmagando o alvo contra o chão com um impacto que gera uma onda de choque capaz de devastar a área ao redor [20M]. O golpe é tão poderoso que pode abrir crateras no solo e deixar marcas de destruição que ecoam a fúria de um verdadeiro dragão. [Essa técnica é um acúmulo do poder entre Ataque+Poder Mágico+Agilidade.]",
                    custo_mana: 10000,
                    custo_qi: 10000,
                    custo_qi_formatado: "10000 Qi",
                    cooldown: 10,
                    nivel_desbloqueio: 35,
                    passiva: false
                },
                {
                    nome: "Investida Frenética",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Investida furiosa com aumento de velocidade e poder.",
                    descricao_completa: "O lutador canaliza sua força em uma investida furiosa contra um alvo específico. Ele se lança em direção ao inimigo, aumentando sua velocidade e poder de ataque momentaneamente por utilizar de um impulso inicial. [Soma Força{Base} +50% de agilidade{Base} para avançar no inimigo]",
                    custo_mana: 2000,
                    custo_qi: 25000,
                    custo_qi_formatado: "25000 Qi",
                    cooldown: 1,
                    nivel_desbloqueio: 40,
                    passiva: false
                },
                {
                    nome: "Contra-Ataque Equivalente",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Física",
                    descricao: "Absorve dano e devolve em onda de choque.",
                    descricao_completa: "O lutador absorve o dano sofrido parcialmente de um ataque [50%] e o coloca em seu próximo ataque. A próxima vez que atacar, naquele turno, o seu ataque gera uma onda de choque acertando todas as criaturas que estiverem até 10 metros de você. Se a força do usuário for 80% ou mais da resistência do adversário, ele causa fissura nos ossos, inutilizando o membro.",
                    custo_mana: 1200,
                    custo_qi: 50000,
                    custo_qi_formatado: "50000 Qi",
                    cooldown: 5,
                    nivel_desbloqueio: 45,
                    passiva: false
                },
                {
                    nome: "Golpe do Abismo",
                    classe: "Lutador",
                    categoria: "Inicial",
                    tipo: "Mágica",
                    descricao: "Golpe poderoso que causa explosão massiva.",
                    descricao_completa: "O lutador desfere um golpe tão poderoso que parece abrir um abismo na superfície, criando uma área de efeito devastadora ao redor do alvo atingido. Esse ataque cria uma explosão ao redor do alvo, que causa dano nos que estiverem próximos. O Dano da explosão e a sua Força [x2]",
                    custo_mana: 5000,
                    custo_qi: 100000,
                    custo_qi_formatado: "100000 Qi",
                    cooldown: 4,
                    nivel_desbloqueio: 50,
                    passiva: false
                }
            ]
        }
    }
};

module.exports = lutador;