const classe = {
    "nome": "Lutador",
    "descricao_classe": "Combatente físico versátil cujas técnicas gerais independem da arma equipada.",
    "categoria": "Classe",
    "tecnicaInicial": {
        "nome": "Soco Potente",
        "categoria": "Inicial",
        "tipo": "Física",
        "descricao": "O lutador concentra mana no corpo e descarrega um golpe direto, independente da arma equipada, causando +10% de dano físico.",
        "descricao_completa": "O lutador concentra mana no corpo e descarrega um golpe direto, independente da arma equipada, causando +10% de dano físico.",
        "custo_mana": 700,
        "custo_qi": 10,
        "custo_qi_formatado": "10 de Maestria",
        "custo_maestria": 10,
        "custo_maestria_formatado": "10 de Maestria",
        "cooldown": 1,
        "nivel_desbloqueio": 1,
        "passiva": false,
        "classe": "Lutador"
    },
    "tecnicas": [
        {
            "nome": "Rugido de Guerra",
            "categoria": "Inicial",
            "tipo": "Suporte",
            "descricao": "Um brado carregado de mana intimida inimigos próximos, aplicando -10% de Ataque por 2 turnos.",
            "descricao_completa": "Um brado carregado de mana intimida inimigos próximos, aplicando -10% de Ataque por 2 turnos.",
            "custo_mana": 1200,
            "custo_qi": 20,
            "custo_qi_formatado": "20 de Maestria",
            "custo_maestria": 20,
            "custo_maestria_formatado": "20 de Maestria",
            "cooldown": 4,
            "nivel_desbloqueio": 5,
            "passiva": false,
            "alcance": "8M",
            "classe": "Lutador"
        },
        {
            "nome": "Instinto de Combate",
            "categoria": "Inicial",
            "tipo": "Passiva",
            "descricao": "Ao sofrer um ataque físico, possui 10% de chance de reduzir o dano recebido em 20% por reação instintiva.",
            "descricao_completa": "Ao sofrer um ataque físico, possui 10% de chance de reduzir o dano recebido em 20% por reação instintiva.",
            "custo_mana": 0,
            "custo_qi": 40,
            "custo_qi_formatado": "40 de Maestria",
            "custo_maestria": 40,
            "custo_maestria_formatado": "40 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 10,
            "passiva": true,
            "classe": "Lutador"
        },
        {
            "nome": "Passo Firme",
            "categoria": "Inicial",
            "tipo": "Movimentação",
            "descricao": "Reposiciona-se até 3m sem consumir o deslocamento normal do turno; o próximo ataque físico ignora 5% da Resistência.",
            "descricao_completa": "Reposiciona-se até 3m sem consumir o deslocamento normal do turno; o próximo ataque físico ignora 5% da Resistência.",
            "custo_mana": 700,
            "custo_qi": 70,
            "custo_qi_formatado": "70 de Maestria",
            "custo_maestria": 70,
            "custo_maestria_formatado": "70 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 15,
            "passiva": false,
            "alcance": "3M",
            "classe": "Lutador"
        },
        {
            "nome": "Fôlego de Aço",
            "categoria": "Inicial",
            "tipo": "Suporte",
            "descricao": "Estabiliza o corpo e recupera 5% do vigor/vida máxima, sem remover debuffs.",
            "descricao_completa": "Estabiliza o corpo e recupera 5% do vigor/vida máxima, sem remover debuffs.",
            "custo_mana": 1000,
            "custo_qi": 110,
            "custo_qi_formatado": "110 de Maestria",
            "custo_maestria": 110,
            "custo_maestria_formatado": "110 de Maestria",
            "cooldown": 4,
            "nivel_desbloqueio": 20,
            "passiva": false,
            "classe": "Lutador"
        },
        {
            "nome": "Marca do Combatente",
            "categoria": "Inicial",
            "tipo": "Física",
            "descricao": "Ao acertar um alvo, memoriza sua abertura; o próximo ataque físico contra ele em até 2 turnos causa +10% de dano.",
            "descricao_completa": "Ao acertar um alvo, memoriza sua abertura; o próximo ataque físico contra ele em até 2 turnos causa +10% de dano.",
            "custo_mana": 900,
            "custo_qi": 160,
            "custo_qi_formatado": "160 de Maestria",
            "custo_maestria": 160,
            "custo_maestria_formatado": "160 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 25,
            "passiva": false,
            "classe": "Lutador"
        },
        {
            "nome": "Vigor de Batalha",
            "categoria": "Inicial",
            "tipo": "Passiva",
            "descricao": "Cada ataque físico recebido concede uma carga de +3% Resistência, até 3 cargas; perde as cargas após um turno sem receber dano.",
            "descricao_completa": "Cada ataque físico recebido concede uma carga de +3% Resistência, até 3 cargas; perde as cargas após um turno sem receber dano.",
            "custo_mana": 0,
            "custo_qi": 230,
            "custo_qi_formatado": "230 de Maestria",
            "custo_maestria": 230,
            "custo_maestria_formatado": "230 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 30,
            "passiva": true,
            "classe": "Lutador"
        },
        {
            "nome": "Quebra de Postura",
            "categoria": "Inicial",
            "tipo": "Física",
            "descricao": "Golpe calculado que desequilibra o alvo; se a Força do usuário superar a Resistência do alvo, ele perde a próxima ação ofensiva.",
            "descricao_completa": "Golpe calculado que desequilibra o alvo; se a Força do usuário superar a Resistência do alvo, ele perde a próxima ação ofensiva.",
            "custo_mana": 1500,
            "custo_qi": 320,
            "custo_qi_formatado": "320 de Maestria",
            "custo_maestria": 320,
            "custo_maestria_formatado": "320 de Maestria",
            "cooldown": 4,
            "nivel_desbloqueio": 35,
            "passiva": false,
            "classe": "Lutador"
        },
        {
            "nome": "Última Investida",
            "categoria": "Inicial",
            "tipo": "Física",
            "descricao": "Reúne as forças restantes em um golpe com até +20% de dano conforme a vida perdida; só pode ser usado uma vez por luta.",
            "descricao_completa": "Reúne as forças restantes em um golpe com até +20% de dano conforme a vida perdida; só pode ser usado uma vez por luta.",
            "custo_mana": 2500,
            "custo_qi": 450,
            "custo_qi_formatado": "450 de Maestria",
            "custo_maestria": 450,
            "custo_maestria_formatado": "450 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 40,
            "passiva": false,
            "classe": "Lutador"
        },
        {
            "nome": "Coração do Gladiador",
            "categoria": "Inicial",
            "tipo": "Passiva",
            "descricao": "Uma vez por luta, ao cair abaixo de 25% de vida, recebe +15% Força e Resistência por 2 turnos; depois o bônus termina sem cura adicional.",
            "descricao_completa": "Uma vez por luta, ao cair abaixo de 25% de vida, recebe +15% Força e Resistência por 2 turnos; depois o bônus termina sem cura adicional.",
            "custo_mana": 0,
            "custo_qi": 650,
            "custo_qi_formatado": "650 de Maestria",
            "custo_maestria": 650,
            "custo_maestria_formatado": "650 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 45,
            "passiva": true,
            "classe": "Lutador"
        }
    ]
};

module.exports = classe;
