const magoGelo = {
    nome: "Mago de Gelo",
    descricao_classe: "Mago que manipula o gelo e o frio, criando barreiras, aprisionando inimigos e causando dano congelante. Possui técnicas defensivas e ofensivas.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Toque congelante",
        classe: "Mago de Gelo",
        categoria: "Inicial",
        tipo: "Mágica",
        descricao: "Congela área de 15m ao redor.",
        descricao_completa: "Congela uma área de 15 metros do que suas Mãos ou pés estejam tocando. Diminuindo a velocidade em 30%.",
        custo_mana: 700,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 2,
        nivel_desbloqueio: 1,
        passiva: false
    },
    tecnicas: [
        {
            nome: "Cópia de gelo",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Deixa cópia de gelo que congela ao ser atacada.",
            descricao_completa: "Se move, deixando uma cópia de gelo do seu próprio corpo que congela por 1 turno caso o ataque/toque.",
            custo_mana: 800,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 3,
            nivel_desbloqueio: 3,
            passiva: false
        },
        {
            nome: "Gelo quebradiço",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Resfria ar reduzindo resistência inimiga.",
            descricao_completa: "Resfria o ar à sua Volta em um alcance de 25 metros, esfriando a matéria de armaduras reduzindo assim a resistência de inimigos em [-35% de resistência].",
            custo_mana: 1200,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 3,
            nivel_desbloqueio: 5,
            passiva: false
        },
        {
            nome: "Gelo moldável",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Molda gelo em formatos desejados.",
            descricao_completa: "Utiliza de áreas congeladas para dobrar e moldar o gelo no formato que quiser por [2 turnos]. Possui limite para tamanhos podendo chegar a 10m² por rank e 1t de gelo.",
            custo_mana: 1500,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 4,
            nivel_desbloqueio: 7,
            passiva: false
        },
        {
            nome: "Feixe glacial",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Dispara feixe de neve que perfura alvo.",
            descricao_completa: "Dispara um feixe luminoso de neve que ao atingir algo, congela caso a resistência seja menor que o pm. e cresce em forma de estalagmite de gelo, perfurando o alvo no local atingido.",
            custo_mana: 1000,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 2,
            nivel_desbloqueio: 9,
            passiva: false
        },
        {
            nome: "Patinação",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Aumenta agilidade com placa de gelo.",
            descricao_completa: "Forma uma placa de gelo sobre os pés podendo patinar e criar gelo abaixo dos pés [+30% de agilidade].",
            custo_mana: 500,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 1,
            nivel_desbloqueio: 11,
            passiva: false
        },
        {
            nome: "Absolute Zero",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria globo de ar frio que congela inimigos.",
            descricao_completa: "Cria um globo de ar frio em um diâmetro de 10 metros em Volta do MAGO, congelando instantaneamente inimigos e projéteis por 2 turnos. Necessita canalizar por um turno para ter efeito no próximo.",
            custo_mana: 7000,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 6,
            nivel_desbloqueio: 13,
            passiva: false
        },
        {
            nome: "Acupuntura fria",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Dispara 100 agulhas de gelo que congelam alvo.",
            descricao_completa: "Cria 100 Agulhas de gelo que avançam em direção ao alvo ao comando do mago, o congelando de dentro para fora caso o oponente seja perfurado. Demora dois turnos pra fazer efeito.",
            custo_mana: 1800,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 4,
            nivel_desbloqueio: 15,
            passiva: false
        },
        {
            nome: "Tempestade de Neve",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria tempestade que reduz visão inimiga.",
            descricao_completa: "Cria uma tempestade de Neve em Volta de si, em um diâmetro de 25 metros do MAGO, reduzindo a visão do inimigo (-30% sentidos).",
            custo_mana: 1400,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 3,
            nivel_desbloqueio: 18,
            passiva: false
        },
        {
            nome: "Espelho de gelo",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Cria espelhos de gelo impenetráveis.",
            descricao_completa: "Cria perfeitos espelhos de vidro impenetráveis do qual aliados podem atravessar e inimigos também. Só pode atravessar seres.",
            custo_mana: 1300,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 4,
            nivel_desbloqueio: 20,
            passiva: false
        },
        {
            nome: "Nitrogênio líquido",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Assopra onda que congela e causa queimadura.",
            descricao_completa: "Assopra uma onda de nitrogênio liquido que avança e congela os atingidos quase que imediatamente e queimando a Pele em queimaduras de segundo grau. As partes congeladas recebem o efeito fraqueza, que recebe o dobro do dano ao ser atacada mais uma vez.",
            custo_mana: 2500,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 5,
            nivel_desbloqueio: 25,
            passiva: false
        },
        {
            nome: "Mimetismo do dragão de gelo",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Buff",
            descricao: "Cria garras, asas e cauda de gelo com buffs.",
            descricao_completa: "O gelo envolve os braços e pernas do MAGO, criando garras de gelo perfurantes, além de asas e uma enorme cauda similar a de um dragão. [+40% força +40% resistência]",
            custo_mana: 3000,
            custo_qi: 15000,
            custo_qi_formatado: "15000 Qi",
            cooldown: 4,
            nivel_desbloqueio: 28,
            passiva: false
        },
        {
            nome: "Globo de gelo",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Cria domo de gelo que protege e revida com espinhos.",
            descricao_completa: "Cria um Domo de 4 metros em Volta de si, podendo ser dobrado de resistência e tamanho caso gaste o dobro de mana. Esse domo envolve o MAGO, protegendo de ataques externos e revidando ao projetar espinhos de gelo em direções aleatórias. Golpes físicos causam +100 dano na barreira de neve caso tenha camadas finas e caso tenha camadas grossas (dobro do gasto) causam 75% a mais. se superar a resistência da barreira, a quebra. Gasto de mana: 2.000. Alcance: 15 metros. Tamanho: 4 metros+",
            custo_mana: 2000,
            custo_qi: 25000,
            custo_qi_formatado: "25000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 30,
            passiva: false
        },
        {
            nome: "Imitação da Fênix",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Resurge em neve ao receber ataque mortal.",
            descricao_completa: "1 vez a cada 2 semanas, o MAGO de gelo caso leve um ataque mortal/fatal que o deixe a beira da morte ou além disso, se desfaz em neve, perde a consciência enquanto o ar frio e a neve é guiada à alguém de sua confiança, formando seu corpo ao seu lado, restaurando em seu melhor estado.",
            custo_mana: 0,
            custo_qi: 50000,
            custo_qi_formatado: "50000 Qi",
            cooldown: 0,
            nivel_desbloqueio: 33,
            passiva: true
        },
        {
            nome: "Ice weapon",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Molda arma de gelo que paralisa ao toque.",
            descricao_completa: "Molda uma arma ou objeto de gelo que congela ao toque, paralisando a região atingida até o descongelamento que pode durar 2 turnos. A região congelada se torna um Ponto fraco, caso atingida, o inimigo leva o dobro de dano. Gasto de mana: 1.600MP.",
            custo_mana: 1600,
            custo_qi: 50000,
            custo_qi_formatado: "50000 Qi",
            cooldown: 2,
            nivel_desbloqueio: 35,
            passiva: false
        },
        {
            nome: "Ice berg",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Libera onda de frio que cria iceberg causando dano massivo.",
            descricao_completa: "O Usuário ao balançar as Mãos libera uma onda de sr frio que cria rapidamente um enorme iceberg que, causa dano de impacto [+40% de dano adicional.] ao ser jogado em alguém, o dano e baseado na soma de 60% de seu PM com sua 45% de sua força. Gasto de mana: 1.3OOMP. Alcance: 20m². Diâmetro: 4m²",
            custo_mana: 1300,
            custo_qi: 100000,
            custo_qi_formatado: "100000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 38,
            passiva: false
        },
        {
            nome: "Clones de gelo",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Cria clones de gelo com atributos do mago.",
            descricao_completa: "Cria 10 clones de gelo que agem como personalidades próprias, com metade de todos os atributos do mago original ou cria um clone único com todos atributos do original, exceto pela suas magias que terão apenas 80% do PM do mago. Gasto de mana: 3.OOO MP.",
            custo_mana: 3000,
            custo_qi: 150000,
            custo_qi_formatado: "150000 Qi",
            cooldown: 5,
            nivel_desbloqueio: 40,
            passiva: false
        },
        {
            nome: "Avalasca",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria nevasca que potencializa ataques de gelo.",
            descricao_completa: "Cria uma quantidade de Neve que durante 3 turnos, a nevasca passa ser controlado Gerando poderosos [+20% do tipo do elemento] ataques que além de atingir o exterior, diminui a temperatura interna causando tremedeira pelo frio. [-15% de agilidade é -15% de resistência ao frio.] Gasto de mana: 1.700MP. Alcance: 25m². Diâmetro: 8m²",
            custo_mana: 1700,
            custo_qi: 250000,
            custo_qi_formatado: "250000 Qi",
            cooldown: 4,
            nivel_desbloqueio: 43,
            passiva: false
        },
        {
            nome: "Reflexo gélido",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Controle",
            descricao: "Cria labirinto de espelhos que distorce realidade.",
            descricao_completa: "Ergue uma cortina de Neve e vento em um diâmetro de 40 metros, criando diversos espelhos de vidro enormes como um perfeito labirinto. Os espelhos podem distorcer imagens e até refletir coisas das memórias do mago de gelo as tornando reais. Nada exagero, isso vai levar em base o Rank do mago. Custo de mana: 5.000",
            custo_mana: 5000,
            custo_qi: 500000,
            custo_qi_formatado: "500000 Qi",
            cooldown: 6,
            nivel_desbloqueio: 45,
            passiva: false
        },
        {
            nome: "Absolute Zero",
            classe: "Mago de Gelo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Congela área de 10m por 2 turnos.",
            descricao_completa: "Cria um globo de ar frio em um diâmetro de 10 metros em Volta do MAGO, congelando instantaneamente inimigos e projéteis por 2 turnos. Necessita canalizar por um turno para ter efeito no próximo. Gasto de mana: 7.000MP",
            custo_mana: 7000,
            custo_qi: 1000000,
            custo_qi_formatado: "1000000 Qi",
            cooldown: 8,
            nivel_desbloqueio: 50,
            passiva: false
        }
    ]
};

module.exports = magoGelo;