const magoInvocador = {
    nome: "Mago Invocador",
    descricao_classe: "Mago que invoca criaturas mágicas para lutar ao seu lado. Possui um vasto arsenal de invocações, desde elementais até seres místicos, cada uma com habilidades únicas.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Sombra Lunar",
        classe: "Mago Invocador",
        categoria: "Inicial",
        tipo: "Invocação",
        descricao: "Invoca criatura etérea que manipula sombras.",
        descricao_completa: "Uma criatura etérea que manipula sombras, obscurecendo áreas e enfraquecendo inimigos com ilusões. Está invocação permite que o usuário cria uma área escura tirando a visão daqueles que estiverem dentro de 5m. A criatura tem 2m. Contém 90% dos atributos relacionados PM do invocador no próprio PM e 30% em resistência.",
        custo_mana: 700,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 3,
        nivel_desbloqueio: 1,
        passiva: false,
        gasto_turno: "40%",
        tipo_invocacao: "Ativo"
    },
    tecnicas: [
        {
            nome: "Poison Slime",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca slime venenoso que pode criar curas.",
            descricao_completa: "O Mago consegue invocar uma criatura gosmenta, um slime com propriedades venenosas. Tal pode comer qualquer tipo de veneno e criar uma cura(Demora 3 turnos para criar a cura, só funciona caso a criatura/Player for do mesmo rank que o seu) ou reter seus efeitos(Consegue diminuir as capacidades do veneno em até 20%, porém demora 2 turnos para criar isso. Pode reter veneno de qualquer rank) após isso, assim como até mesmo gerar aquele tipo de veneno(Só funciona caso você consiga curar o veneno). O slime tem 1.5m e pode lançar o veneno em uma área de até 10m como um jato, na qual ao atingir o inimigo, causa o efeito do veneno. pode ficar em uma área de até 10m longe do invocador. O slime tem 90% do PM do invocador em sentidos obrigatoriamente e os outros 30% em velocidade.",
            custo_mana: 700,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 3,
            nivel_desbloqueio: 3,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Metal Slime",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca slime metálico que pode mudar de forma.",
            descricao_completa: "O Mago consegue invocar uma criatura gosmenta, um slime com propriedades metálicas. Tal pode mudar sua forma para o que for, possuindo as propriedades de metal. O slime tem 2m. pode ficar em uma área de até 10m longe do invocador. O slime tem 90% do PM do mago obrigatoriamente em resistência e os outros 30% em velocidade.",
            custo_mana: 700,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 3,
            nivel_desbloqueio: 5,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Espectro Flamejante",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca espectro de chamas verdes que causa pânico.",
            descricao_completa: "Um espectro envolto em chamas verdes, capaz de queimar inimigos e causar pânico, espalhando o terror nas linhas adversárias. Esse espectro permite o usuário criar um chama esverdeada que queima inimigos em 5% por turno causando feridas corrosivas. O espectro tem 3m de altura. pode ficar em uma área de até 15m longe do invocador. Contém 90% do PM do invocador direto no próprio PM e os outros 30% em resistência.",
            custo_mana: 700,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 3,
            nivel_desbloqueio: 7,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Guardião de Cristal",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca guardião que reflete ataques mágicos.",
            descricao_completa: "Uma entidade feita de cristal que fornece proteção sólida e reflete ataques mágicos, tornando-se um escudo poderoso. Este pequeno animal é para a proteção do mago, onde ataques mágicos que o atingirem que são pelo menos 70% abaixo de seu PM, podem ser refletidos. Tem 5m. pode ficar em uma área de até 20m longe do invocador. Contém 90% do PM do invocador diretamente no próprio PM e ficando com 30% em velocidade.",
            custo_mana: 1800,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 3,
            nivel_desbloqueio: 9,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Quimera Arcana",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca quimera com resistência elemental elevada.",
            descricao_completa: "Uma quimera composta por partes de diferentes animais mágicos, possuindo habilidades variadas e adaptando-se às situações. Está quimera é criada para ter uma resistência elemental elevada, boa para enfrentar inimigos que controlam elementos.(40% de resistência a golpes elementais). Tem 4m. pode ficar em uma área de até 15m longe do invocador. Contém 90% do PM do invocador diretamente na resistência e 30% em sentidos.",
            custo_mana: 1000,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 3,
            nivel_desbloqueio: 11,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Fênix da Renovação",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca fênix que cura aliados.",
            descricao_completa: "Uma fênix que cura aliados caídos e irradia chamas curativas, trazendo vida renovada ao campo de batalha(cura até 3 aliados além do usuário). Está fênix permite que o usuário cure ferimentos medianos, como cortes, sangramentos e etc, mas nada tão profundo, podendo usá-la apenas uma vez a cada 3 turnos. A fênix tem 3m e pode se mover em uma área de até 20m do usuário. Contém 90% do PM do invocador diretamente em velocidade e 30% em resistência.",
            custo_mana: 2000,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 3,
            nivel_desbloqueio: 13,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Estátua de pedra",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca estátua que controla terra em 10m.",
            descricao_completa: "Uma estátua de pedra que controla a terra abaixo de seus pés(10m), ela pode canalizar sua magia para criar barreiras ou atacar utilizando a terra. A estrutura tem 5m, e não pode se mover. Contém obrigatoriamente 90% do PM do mago em resistência e ficando com 30% em velocidade.",
            custo_mana: 700,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 3,
            nivel_desbloqueio: 15,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Entidade Vampírica",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca vampiro que drena vitalidade.",
            descricao_completa: "Uma entidade que drena a vitalidade dos inimigos, curando o invocador e enfraquecendo os adversários com toques vampíricos(-10% nos status físicos dos inimigos. Cura ferimentos moderados, mas nada tão grave)(Necessário terminar uma Dungeon de vampiro sendo um invocador). O vampiro tem 2m e pode se mover em uma área de até 20m do usuário. Contém 90% de agilidade vindo diretamente do PM do invocador, ficando com 30% em sentidos.",
            custo_mana: 2700,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 3,
            nivel_desbloqueio: 17,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Espirito Elemental",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca espírito que alterna entre elementos.",
            descricao_completa: "Um espírito ligado aos elementos, podendo alternar entre fogo, água, terra e ar, adaptando-se para causar danos ou fornecer suporte(pode lançar bolas elementais, feixes elementais e etc). O espírito tem 5m, e pode se mover em uma área de até 20m do usuário. Contém 90% do PM do invocador em seu PM ficando com 30% em resistência.",
            custo_mana: 1800,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 3,
            nivel_desbloqueio: 19,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Mecanismo Auto-mágico",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca autômato mágico com força e resistência.",
            descricao_completa: "Um autômato mágico construído para cumprir tarefas específicas, seja atacar, defender, ou lançar feitiços especializados. Esse autômato pode ser modificado por ferreiro ou arcanista para realizar novas funções de acordo com a tecnologia que nele foi posta. O mecanismo tem 5m de altura e um Buff de +20% em força e resistente, mas em troca disso, tem um debuff de -20% em velocidade. Contém 90% do PM do mago diretamente em força ou resistência, ficando com 30% em sentidos.",
            custo_mana: 3000,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 3,
            nivel_desbloqueio: 22,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Flora Senciente",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca planta consciente que controla o ambiente.",
            descricao_completa: "Uma planta consciente que pode controlar o ambiente ao redor, criando obstáculos naturais e enredando inimigos(controla uma área de até 15m). Uma invocação que controla vinhas podendo trazer plantas carnívoras entre outras coisas. Ela tem 3m de e pode se mover em uma área de até 15m do usuário. Contém 90% do PM do invocador diretamente em seu PM, ficando com 30% em força.",
            custo_mana: 1000,
            custo_qi: 20480,
            custo_qi_formatado: "20480 Qi",
            cooldown: 3,
            nivel_desbloqueio: 25,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Serpente",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca serpente gigante que cresce com mana.",
            descricao_completa: "Uma serpente gigante que pode se deslocar por dentro da terra, surgindo inesperadamente para surpreender inimigos e causar confusão. Está serpente diferente de outras invocações cresce 10M a cada 3000 de mana imposto nela, chegando no máximo de 45m. A serpente tem um Buff de +30% em força e velocidade. Contém diretamente 90% do MP do mago diretamente em força ou velocidade, ficando com 30% em PM.",
            custo_mana: 7000,
            custo_qi: 40960,
            custo_qi_formatado: "40960 Qi",
            cooldown: 3,
            nivel_desbloqueio: 28,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Sapo",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca sapo que salta alturas e captura objetos.",
            descricao_completa: "Um sapo que pode saltar grandes alturas, surgindo inesperadamente para surpreender inimigos e causar confusão. Este Sapo diferente de outras invocações cresce 10M a cada 3000 de mana imposta nela, chegando no máximo de 45m. Sua língua pode ser usada para pegar objetos a distância, podendo ir em até 15m(+5m a cada 3OOO de mana). Contém obrigatoriamente 90% de força vindo diretamente do PM do invocador, ficando com 30% em PM.",
            custo_mana: 7000,
            custo_qi: 81920,
            custo_qi_formatado: "81920 Qi",
            cooldown: 3,
            nivel_desbloqueio: 30,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Lesma",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca lesma que cura feridas profundas.",
            descricao_completa: "Uma lesma que pode curar feridas profundas(Hemorragias internas, ferimentos graves e etc, mas não pode regenerar membros). Esta lesma diferente de outras invocações cresce 10M a cada 3000 de mana imposta nela, chegando no máximo de 45m. Ela pode cuspir ácido corrosivo que dá dano de 10% por turno em players(dano baseado na força da criatura). Contém 90% dos PM do invocador em força ou resistência, ficando com 30% em velocidade.",
            custo_mana: 7000,
            custo_qi: 100000,
            custo_qi_formatado: "100000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 32,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Lobo Lunar",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca lobo que ganha força com a luz da lua.",
            descricao_completa: "Um lobo que ganha força com a luz da lua, tornando-se mais veloz e feroz durante a noite, caçando inimigos implacavelmente. (50% a mais de atributos em Agi e força durante a noite)(necessário terminar uma Dungeon do tipo lunar). Tem 2m e pode se mover em uma área de até 18m do usuário. Contém 90% do PM do invocador em força ou agilidade, sobrando 30% em PM.",
            custo_mana: 1900,
            custo_qi: 150000,
            custo_qi_formatado: "150000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 34,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Estrategista Etéreo",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Invoca entidade que localiza inimigos ocultos.",
            descricao_completa: "Uma entidade que concede sabedoria estratégica, analisando o campo de batalha e fornecendo conselhos táticos ao invocador. Está invocação funciona como um sonar vivo para o invocador, ela trabalha na localização de inimigos escondidos que emitem som, através de uma ecolocalização. (30m) Contém obrigatoriamente 90% do PM do invocador em sentidos, sobrando 30% em PM.",
            custo_mana: 5000,
            custo_qi: 200000,
            custo_qi_formatado: "200000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 36,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Estrutura Arcana",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Construção que fortalece aliados e invocações.",
            descricao_completa: "Uma construção mágica que fortalece aliados/invocações próximas, concedendo bônus temporários de resistência e poder mágico. A construção concede aos aliados/invocações próximos dela um Buff de 20% de adicional em PM e Resistência. A estrutura tem 7m. Sua resistência representa 150% do poder mágico do invocador. Não sobra nada pra distribuição.",
            custo_mana: 1200,
            custo_qi: 250000,
            custo_qi_formatado: "250000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 38,
            passiva: false,
            gasto_turno: "30%"
        },
        {
            nome: "Guardião Elemental-2",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Evolução de guardião elemental com tamanho variável.",
            descricao_completa: "Um guardião ligado a um elemento específico (terra, fogo, água, ar), defendendo o invocador e causando danos correspondentes. Diferente das outras invocações essa é apenas uma evolução das dos respectivos elementos acima, que permite o invocador após passar do nível 40, evoluir essas invocações para aumentar o tamanho. (10M a cada 6k gasto. Máximo de 30M). Essa invocação tem mais pontos para se gastar, diferente das outras. Contém 90% do PM do mago em seu próprio PM. Diferente das outras, essa tem 90% em mais um atributo a sua escolha, dois de 70% e um de 50%. No nível 40 são três de 90% e duas de 70%. No nível 40 ao invés de duplicar, triplica.",
            custo_mana: 10000,
            custo_qi: 500000,
            custo_qi_formatado: "500000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 40,
            passiva: false,
            gasto_turno: "40%"
        },
        {
            nome: "Transposição Elemental",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Troca instantânea entre invocações.",
            descricao_completa: "Troca instantânea de uma invocação por outra, adaptando-se dinamicamente às necessidades da batalha.",
            custo_mana: 3000,
            custo_qi: 500000,
            custo_qi_formatado: "500000 Qi",
            cooldown: 2,
            nivel_desbloqueio: 42,
            passiva: false
        },
        {
            nome: "Vínculo Místico",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Redireciona dano do invocador para invocação.",
            descricao_completa: "Fortalece a conexão entre o invocador e suas invocações, um dano que seria direcionado ao invocador iria direto para a invocação (qual esteja invocada) a desfazendo até o fim da batalha se caso o PM for maior que a resistência do próprio.",
            custo_mana: 5000,
            custo_qi: 750000,
            custo_qi_formatado: "750000 Qi",
            cooldown: 4,
            nivel_desbloqueio: 44,
            passiva: false
        },
        {
            nome: "Ritual de Amplificação",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Buff",
            descricao: "Aumenta poder de invocação em 20% por 3 turnos.",
            descricao_completa: "Aumenta temporariamente o poder de uma invocação, concedendo habilidades aprimoradas por um curto período. (20% adicional mas técnicas), só funciona em 3 incrições por vez, e dura 3 turnos com recarga de 3 turnos.",
            custo_mana: 1000,
            custo_qi: 1000000,
            custo_qi_formatado: "1000000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 46,
            passiva: false
        },
        {
            nome: "Desencadeio Caótico",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Controle",
            descricao: "Libera invocações para agir autonomamente.",
            descricao_completa: "Libera o controle sobre todas as invocações simultaneamente, criando um caos mágico que confunde e dispersa os inimigos. Está técnica permite que o invocador deixe suas invocações decidirem por si própria quem atacar ou defender, além de tomarem suas próprias decisões para auxiliar o invocador na batalha. Dura 2 turnos.",
            custo_mana: 4000,
            custo_qi: 1500000,
            custo_qi_formatado: "1500000 Qi",
            cooldown: 6,
            nivel_desbloqueio: 48,
            passiva: false
        },
        {
            nome: "Círculo de Reversão",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Reflete dano de invocação para o usuário.",
            descricao_completa: "Inverte temporariamente a direção dos danos causados à invocação, refletindo parte dos ataques diretamente para o usuário.",
            custo_mana: 2000,
            custo_qi: 2000000,
            custo_qi_formatado: "2000000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 50,
            passiva: false
        },
        {
            nome: "Canalização Sinfônica",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Combate",
            descricao: "Ataque conjunto sincronizado de todas invocações.",
            descricao_completa: "Harmoniza todas as invocações para realizar um ataque conjunto sincronizado, maximizando o impacto em um alvo específico. (Uma vez por batalha. O ataque em conjunto só poderá ser de um único elemento ou de vários.) (O Dano será com base em 10% de adicional de PM por cada invocação)( O custo será de acordo com o gasto de cada criatura )",
            custo_mana: 5000,
            custo_qi: 5000000,
            custo_qi_formatado: "5000000 Qi",
            cooldown: 10,
            nivel_desbloqueio: 52,
            passiva: false
        },
        {
            nome: "Nexo Espiritual",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Compartilha conhecimentos entre invocações.",
            descricao_completa: "Cria um vínculo espiritual entre todas as invocações eo usuário, compartilhando conhecimentos e táticas para uma coordenação mais eficiente.",
            custo_mana: 1000,
            custo_qi: 1000000,
            custo_qi_formatado: "1000000 Qi",
            cooldown: 5,
            nivel_desbloqueio: 54,
            passiva: false
        },
        {
            nome: "Feitiço de Contenção",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Aprisiona invocação para liberar depois.",
            descricao_completa: "Aprisiona temporariamente uma invocação em um espaço separado mágico dentro de algum local que o usuário tocou, canalizando seus poderes para serem liberados estrategicamente mais tarde.",
            custo_mana: 5000,
            custo_qi: 2000000,
            custo_qi_formatado: "2000000 Qi",
            cooldown: 8,
            nivel_desbloqueio: 56,
            passiva: false
        },
        {
            nome: "Formação Espectral",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Buff",
            descricao: "Amplifica habilidades de invocações em área.",
            descricao_completa: "Cria um campo mágico que amplifica as habilidades defensivas e ofensivas de todas as invocações dentro de uma área específica. ( Até 10m do invocador)(30% de força/Pm e resistencia das incrições). Dura 3 turnos com recarga de 4 turnos.",
            custo_mana: 8000,
            custo_qi: 3000000,
            custo_qi_formatado: "3000000 Qi",
            cooldown: 4,
            nivel_desbloqueio: 58,
            passiva: false,
            gasto_turno: "50%"
        },
        {
            nome: "Dissolução Ancestral",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Combate",
            descricao: "Sacrifica invocação para explosão massiva.",
            descricao_completa: "Sacrifica temporariamente uma invocação para desencadear uma explosão de energia mágica, afetando adversários próximos com danos devastadores. (2x o PM da invocação)(30m)",
            custo_mana: 10000,
            custo_qi: 5000000,
            custo_qi_formatado: "5000000 Qi",
            cooldown: 8,
            nivel_desbloqueio: 60,
            passiva: false
        },
        {
            nome: "Evolução e adaptação (Passiva)",
            classe: "Mago Invocador",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Invocações ganham 5% atributos por turno.",
            descricao_completa: "Para cada turno que uma invocação permanecer invocada, seus atributos são aperfeiçoados em 5% do PM do invocador. Não existe um limite para isso. Quando a criatura é destruída ou desinvocada, reseta.",
            custo_mana: 0,
            custo_qi: 10000000,
            custo_qi_formatado: "10000000 Qi",
            cooldown: 0,
            nivel_desbloqueio: 62,
            passiva: true
        }
    ]
};

module.exports = magoInvocador;