const magoVento = {
    nome: "Mago de Vento",
    descricao_classe: "Mago que manipula o vento e o ar, criando tempestades, tornados e lâminas cortantes. Possui técnicas de mobilidade, controle de área e dano cortante.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Vento Cortante",
        classe: "Mago de Vento",
        categoria: "Inicial",
        tipo: "Mágica",
        descricao: "Cria lâmina de vento em forma de meia lua.",
        descricao_completa: "O usuário cria uma lâmina de dois metros de comprimento em forma de meia lua e a envia na direção do alvo, desferindo dano cortante e ignorando 15% da resistência.",
        custo_mana: 800,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 2,
        nivel_desbloqueio: 1,
        passiva: false,
        alcance: "40 metros",
        tamanho: "2 metros"
    },
    tecnicas: [
        {
            nome: "Escudo de Zéfiro",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Cria escudo de ar que redireciona ataques.",
            descricao_completa: "Correntes de ar formam um escudo de 5 metros em um local dentro do alcance, podendo redirecionar ataques e magias. Para que haja o redirecionamento, o usuário precisa ter 80% do PM da magia ou da Força do ataque.",
            custo_mana: 3000,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 3,
            nivel_desbloqueio: 3,
            passiva: false,
            alcance: "15 metros",
            tamanho: "5 metros (raio)"
        },
        {
            nome: "Passos Sibilantes",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Aumenta agilidade em 30% do PM.",
            descricao_completa: "O usuário envolve seu corpo com os ventos que cria e assim altera sua velocidade temporariamente. Sua agilidade é incrementada com 30% do PM enquanto a magia estiver durando.",
            custo_mana: 2000,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 2,
            nivel_desbloqueio: 5,
            passiva: false,
            custo_mana_turno: 1000
        },
        {
            nome: "Transporte Via Vento",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Utilidade",
            descricao: "Teleporta até 3 pessoas em 20m.",
            descricao_completa: "Até 3 pessoas, você incluso, desaparecem em um redemoinho que os faz ressurgir em um espaço dentro do alcance.",
            custo_mana: 3000,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 3,
            nivel_desbloqueio: 7,
            passiva: false,
            alcance: "20 metros"
        },
        {
            nome: "Tornado de Bóreas",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria tornado gélido que causa dano contínuo.",
            descricao_completa: "O usuário forma um tornado de ventos gélidos que causam dano continuo nos inimigos com base no PM do usuário enquanto os dilacera e prende no meio do tornado. Pela duração, o tornado resfria a temperatura ambiente ao ponto de congelar criaturas e objetos em seu interior. O dano causado em cada turno é baseado no PM do conjurador, enquanto é necessário 2 turnos dentro do alcance para que uma criatura seja congelada.",
            custo_mana: 2000,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 4,
            nivel_desbloqueio: 9,
            passiva: false,
            custo_mana_turno: 1000,
            alcance: "30 metros",
            tamanho: "15 metros"
        },
        {
            nome: "Turbilhão de Lâminas",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria lâminas minúsculas que causam dano contínuo.",
            descricao_completa: "O usuário cria inúmeras lâminas minúsculas que formam uma lâmina maior, mas não é possível separar as pequenas lâminas para formar um número maior do que 2 lâminas. Essas lâminas podem ter seu trajeto alterado uma única vez e causam dano cortante continuamente equivalente ao PM do usuário +25%.",
            custo_mana: 3000,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 3,
            nivel_desbloqueio: 11,
            passiva: false,
            alcance: "20 metros",
            tamanho: "4 metros ou 2 de 2 metros",
            duracao: "2 turnos após acertar o alvo"
        },
        {
            nome: "Véu Assassino",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Movimentação",
            descricao: "Se transforma em corrente de vento silenciosa.",
            descricao_completa: "O usuário se transforma em uma corrente de vento silenciosa que pode se deslocar pelo ambiente, dentro do alcance. Enquanto estiver nessa forma, o usuário causa dano cortante ao passar pelo alvo, desde que termine seu turno até 10 metros do último alvo.",
            custo_mana: 3500,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 2,
            nivel_desbloqueio: 13,
            passiva: false,
            duracao: "1 Turno",
            deslocamento_maximo: "20 metros (+10 do último alvo)"
        },
        {
            nome: "Armamento de Vento",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Cria arma de vento com buff de atributo.",
            descricao_completa: "O usuário é capaz de criar uma arma feita de puro vento e usá-la durante o combate. Essa arma pode ser um arco e flecha, espadas, lanças, alabardas ou pistolas e possuem a tonalidade verde além de poder escolher o atributo principal que a arma irá buffer [+25%] necessitando ter sentido.",
            custo_mana: 1000,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 3,
            nivel_desbloqueio: 15,
            passiva: false,
            custo_mana_turno: 500,
            alcance_projeteis: "40 metros",
            tamanho: "Até 2 metros"
        },
        {
            nome: "Agulhas Invisíveis",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Lança agulhas quase imperceptíveis.",
            descricao_completa: "O usuário cria até 10 agulhas que podem ser arremessadas em direção a múltiplos alvos. Cada agulha possui 8 centímetros e são quase imperceptíveis, exceto por sua leve alteração ao seu redor, é necessário Sentidos equivalente a 80% do PM do usuário para ver.",
            custo_mana: 1000,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 2,
            nivel_desbloqueio: 17,
            passiva: false,
            alcance: "30 metros"
        },
        {
            nome: "Lufada de Vento",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Corrente de ar que carrega e esmaga alvos.",
            descricao_completa: "Uma corrente de ar poderosa é invocada pelo usuário em uma direção que ele deseja. Pode ser na vertical, diagonal ou horizontal. Essa lufada carrega todos os objetos dentro da área e aqueles cujo o usuário tenha um valor de 80% da Força ou PM (para magias e invocações), em complemento, quando o alvo é pressionado contra uma superfície, é possível que haja esmagamento se o PM do usuário for maior que a Resistência ou PM do alvo.",
            custo_mana: 2000,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 3,
            nivel_desbloqueio: 19,
            passiva: false,
            alcance: "20 metros",
            tamanho: "10 m² (diâmetro)"
        },
        {
            nome: "Bolha de ar",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria onda de choque que arremessa inimigos.",
            descricao_completa: "Condensado várias bolhas de ar a frente do corpo, quando essa estourar gera uma onda de choque em área que vem com um impacto bruto de ar diretamente contra os inimigos na área das bolhas. O dano é [PM] mas o impacto causado é [PM+40%] que faz os inimigos serem arremessados para trás caso não possuam defesa suficiente para se manterem ativos.",
            custo_mana: 800,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 2,
            nivel_desbloqueio: 22,
            passiva: false,
            quantidade: "infinito",
            raio: "5m²"
        },
        {
            nome: "Letalidade veloz (Passivo)",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Acrescenta 50% do PM na velocidade.",
            descricao_completa: "Um tanto quanto simples mas não deixa de ser letal. O mago de vento pode acrescentar passivamente [50%] do seu PM na velocidade de forma adicional e não base. Isso se dá por conta do mago sempre estar conectado aos ventos.",
            custo_mana: 0,
            custo_qi: 20480,
            custo_qi_formatado: "20480 Qi",
            cooldown: 0,
            nivel_desbloqueio: 25,
            passiva: true
        },
        {
            nome: "Desvio de trajeto",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Desvia ataques com correntes de vento.",
            descricao_completa: "O mago de vento consegue direcionar correntes de vento aéreas que tiram trajetos diretamente nestes desde que seu PM seja maior ao ataque proporcionado. Mas o gasto sempre será o dobro do valor baseado no ataque do oponente. As correntes também desviam ataques mágicos.",
            custo_mana: 0,
            custo_qi: 40960,
            custo_qi_formatado: "40960 Qi",
            cooldown: 4,
            nivel_desbloqueio: 28,
            passiva: false
        },
        {
            nome: "Deturbador aéreo",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria furacão de 60m² que causa dano massivo.",
            descricao_completa: "Canalizando uma grande quantidade de mana, torra ela num único estalar de dedos formando um enorme furacão [60m²] que causa dano baseado em [PM+50%] porém o diferencial dessa técnica é a destruição em massa gerada que dentro do furacão aqueles que forem puxados tem que estar pelo menos no dobro do range e ter resistência maior que o [PM] em pelo menos [40%]. Os puxados para dentro sofrem danos cortantes ignorando [50%] da resistência total num total de dez ataques antes de serem jogados longe.",
            custo_mana: 10000,
            custo_qi: 81920,
            custo_qi_formatado: "81920 Qi",
            cooldown: 7,
            nivel_desbloqueio: 30,
            passiva: false,
            duracao: "2 turnos"
        },
        {
            nome: "Conversão de ar (Passivo)",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Ataques de vento potencializam dano em 25%.",
            descricao_completa: "O mago consegue converter o próprio vento em ataques. Isso é, ele pode usar 1x sim e uma não. Cada ataque de vento usando de correntes aéreas aumenta e potencializa o dano em [25%] além de ter custo reduzido pela metade.",
            custo_mana: 0,
            custo_qi: 500000,
            custo_qi_formatado: "500000 Qi",
            cooldown: 0,
            nivel_desbloqueio: 32,
            passiva: true
        },
        {
            nome: "Propulsor elétrico",
            classe: "Mago de Vento",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Aumenta velocidade em +50% do PM para locomoção.",
            descricao_completa: "o usuário cria pequenas explosões elétricas nas mãos ou pés que o impulsionam sua velocidade (+50% do Pm total como agilidade). Entretanto serve somente para locomoção. [limite de 3 movimentos por turno]. Custo de mana: 1.000. Recarga: 1 turno.",
            custo_mana: 1000,
            custo_qi: 1000000,
            custo_qi_formatado: "1000000 Qi",
            cooldown: 1,
            nivel_desbloqueio: 35,
            passiva: false
        }
    ]
};

module.exports = magoVento;