const magoElemental = {
    nome: "Mago Elemental",
    descricao_classe: "O Mago Elemental domina os quatro elementos da natureza (Fogo, Água, Gelo, Terra, Raio e Vento) para causar dano e controlar o campo de batalha.",
    elementos: ["Fogo", "Água", "Gelo", "Terra", "Raio", "Vento"],
    tecnicaInicial: {
        nome: "Bola de Fogo",
        classe: "Mago Elemental",
        categoria: "Inicial",
        tipo: "Mágica",
        descricao: "Dispara uma bola de fogo que causa dano elemental e queima o alvo.",
        descricao_completa: "O mago conjura uma esfera flamejante de 60cm de diâmetro que avança em linha reta até 25m. Ao atingir o alvo, explode em chamas causando dano baseado no PM do mago e deixando o alvo em chamas por 3 turnos, causando dano adicional de queimadura de 5% do PM por turno.",
        custo_mana: 35,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 1,
        nivel_desbloqueio: 1,
        passiva: false
    },
    tecnicas: [
        {
            nome: "Rajada de Gelo",
            classe: "Mago Elemental",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Uma rajada de gelo que reduz a velocidade do inimigo em 30%.",
            descricao_completa: "O mago canaliza energia gélida e a libera em uma rajada de estilhaços de gelo em cone de 15m. O ataque causa dano baseado no PM e reduz a velocidade do alvo em 30%, além de ter 20% de chance de congelar o alvo por 1 turno caso sua resistência seja inferior ao PM do mago.",
            custo_mana: 30,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 2,
            nivel_desbloqueio: 3,
            passiva: false
        },
        {
            nome: "Afinidade Elemental",
            classe: "Mago Elemental",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Aumenta o dano de ataques elementais em 20%.",
            descricao_completa: "A conexão do mago com os elementos se aprofunda, permitindo que sua mana flua mais livremente através de ataques elementais. Esta passiva aumenta permanentemente o dano de todas as magias elementais em 20% e reduz o custo de mana em 10% para feitiços do elemento escolhido como especialidade.",
            custo_mana: 0,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 0,
            nivel_desbloqueio: 5,
            passiva: true
        },
        {
            nome: "Tempestade Elemental",
            classe: "Mago Elemental",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Combina múltiplos elementos em área.",
            descricao_completa: "O mago combina dois elementos diferentes para criar uma tempestade elemental em área de 10m de raio. A combinação causa dano massivo e aplica efeitos de ambos os elementos (ex: Fogo + Gelo = queimadura + lentidão). O dano base é 150% do PM.",
            custo_mana: 5000,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 5,
            nivel_desbloqueio: 7,
            passiva: false,
            alcance: "20 metros",
            tamanho: "10 metros (raio)"
        },
        {
            nome: "Escudo Elemental",
            classe: "Mago Elemental",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Cria escudo que absorve dano elemental.",
            descricao_completa: "O mago cria um escudo elemental que absorve dano de um elemento específico. O escudo pode absorver até 200% do PM do mago em dano do elemento escolhido. Se o escudo for atingido por um elemento diferente, ele se quebra imediatamente.",
            custo_mana: 2000,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 3,
            nivel_desbloqueio: 9,
            passiva: false,
            duracao: "3 turnos"
        },
        {
            nome: "Círculo dos Elementos",
            classe: "Mago Elemental",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria círculo que alterna elementos automaticamente.",
            descricao_completa: "O mago desenha um círculo mágico no chão com 8m de diâmetro. A cada turno, o elemento do círculo muda automaticamente (Fogo, Água, Gelo, Terra, Raio, Vento), causando dano e efeitos diferentes a inimigos dentro da área. O círculo dura 5 turnos.",
            custo_mana: 4000,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 6,
            nivel_desbloqueio: 11,
            passiva: false,
            tamanho: "8 metros (diâmetro)",
            duracao: "5 turnos"
        },
        {
            nome: "Dominador Elemental",
            classe: "Mago Elemental",
            categoria: "Inicial",
            tipo: "Buff",
            descricao: "Aumenta poder de um elemento em 50%.",
            descricao_completa: "O mago escolhe um elemento e canaliza seu poder, aumentando temporariamente o poder desse elemento em 50%. Durante 3 turnos, todas as magias desse elemento causam +50% de dano e têm custo de mana reduzido em 20%.",
            custo_mana: 3000,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 4,
            nivel_desbloqueio: 13,
            passiva: false,
            duracao: "3 turnos"
        },
        {
            nome: "Convergência Elemental",
            classe: "Mago Elemental",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Dispara feixe que combina todos os elementos.",
            descricao_completa: "O mago canaliza todos os seis elementos simultaneamente em um único feixe devastador. O feixe causa dano baseado em 200% do PM e aplica todos os efeitos elementais ao alvo. Esta técnica só pode ser usada uma vez por batalha.",
            custo_mana: 10000,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 10,
            nivel_desbloqueio: 15,
            passiva: false,
            alcance: "30 metros"
        },
        {
            nome: "Resistência Elemental",
            classe: "Mago Elemental",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Ganha resistência a todos os elementos.",
            descricao_completa: "O mago desenvolve resistência natural a todos os elementos. Recebe -30% de dano de todos os elementos e ganha imunidade a efeitos de status elementais (queimadura, congelamento, envenenamento, etc).",
            custo_mana: 0,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 0,
            nivel_desbloqueio: 18,
            passiva: true
        },
        {
            nome: "Manipulação Ambiental",
            classe: "Mago Elemental",
            categoria: "Inicial",
            tipo: "Utilidade",
            descricao: "Altera o ambiente para favorecer elementos.",
            descricao_completa: "O mago altera o ambiente ao seu redor, criando condições que favorecem seus elementos. Pode criar: área de fogo (dano contínuo), área de gelo (lentidão), área de vento (empurra inimigos), área de terra (reduz agilidade), área de raio (paralisia), ou área de água (dificulta movimento). Dura 4 turnos.",
            custo_mana: 3500,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 5,
            nivel_desbloqueio: 20,
            passiva: false,
            alcance: "15 metros",
            duracao: "4 turnos"
        },
        {
            nome: "Mestre dos Elementos",
            classe: "Mago Elemental",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Pode usar todos os elementos simultaneamente.",
            descricao_completa: "O mago atinge o domínio completo de todos os elementos. Pode conjurar até 3 magias elementais diferentes simultaneamente, cada uma com seu efeito independente. Cada magia adicional gasta 50% do custo base.",
            custo_mana: 0,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 0,
            nivel_desbloqueio: 23,
            passiva: true
        },
        {
            nome: "Cataclismo",
            classe: "Mago Elemental",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Causa desastre natural combinando elementos.",
            descricao_completa: "O mago conjura um cataclismo que combina todos os elementos em uma área de 20m de raio. A área sofre: terremoto (dano físico), chuva ácida (dano contínuo), tempestade de raios (paralisia), ondas de gelo (congelamento), ventos cortantes (dano contínuo) e chuva de meteoros (dano massivo). Esta técnica só pode ser usada uma vez por dia.",
            custo_mana: 15000,
            custo_qi: 20480,
            custo_qi_formatado: "20480 Qi",
            cooldown: 20,
            nivel_desbloqueio: 25,
            passiva: false,
            alcance: "30 metros",
            tamanho: "20 metros (raio)"
        },
        {
            nome: "Avatar Elemental",
            classe: "Mago Elemental",
            categoria: "Inicial",
            tipo: "Transformação",
            descricao: "Transforma em ser elemental por 3 turnos.",
            descricao_completa: "O mago se transforma em um ser elemental puro, ganhando +100% em todos os atributos e podendo usar todas as magias elementais sem custo de mana. Durante a transformação, o mago é imune a dano físico e mágico, mas não pode usar técnicas não-elementais. Dura 3 turnos.",
            custo_mana: 8000,
            custo_qi: 40960,
            custo_qi_formatado: "40960 Qi",
            cooldown: 10,
            nivel_desbloqueio: 28,
            passiva: false,
            duracao: "3 turnos"
        }
    ]
};

module.exports = magoElemental;