const magoMaldicao = {
    nome: "Mago Maldição",
    descricao_classe: "O Mago Maldição domina as artes obscuras, enfraquecendo inimigos com maldições e causando dano espiritual.",
    tecnicaInicial: {
        nome: "Enfraquecer",
        classe: "Mago Maldição",
        categoria: "Inicial",
        tipo: "Mágica",
        descricao: "Reduz os atributos do inimigo por alguns turnos.",
        descricao_completa: "O mago pronuncia palavras ancestrais de poder, criando uma maldição que drena a força vital do alvo, reduzindo seus atributos físicos e mágicos em 15% por 3 turnos.",
        custo_mana: 25,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 2,
        nivel_desbloqueio: 1,
        passiva: false
    },
    tecnicas: [
        {
            nome: "Maldição Sombria",
            classe: "Mago Maldição",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Amaldiçoa o inimigo causando dano ao longo do tempo.",
            descricao_completa: "O mago invoca energia sombria para marcar o inimigo com uma maldição que causa dano contínuo de 10% do PM do mago por turno durante 4 turnos. A maldição também reduce a regeneração do alvo.",
            custo_mana: 35,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 2,
            nivel_desbloqueio: 3,
            passiva: false
        },
        {
            nome: "Olhar Maligno",
            classe: "Mago Maldição",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Suas maldições têm chance de causar medo no alvo.",
            descricao_completa: "O olhar do Mago Maldição carrega tal poder maligno que suas maldições têm 25% de chance de causar efeito de medo, fazendo o alvo fugir por 1 turno se sua resistência mental for menor que o PM do mago.",
            custo_mana: 0,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 0,
            nivel_desbloqueio: 5,
            passiva: true
        },
        {
            nome: "Roubo de Vida",
            classe: "Mago Maldição",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Drena vida do alvo e cura o usuário.",
            descricao_completa: "O mago toca o alvo e drena sua energia vital, causando dano de 20% do PM e curando-se com a mesma quantidade. A técnica não funciona em construtos ou mortos-vivos.",
            custo_mana: 1500,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 3,
            nivel_desbloqueio: 7,
            passiva: false
        },
        {
            nome: "Maldição da Fraqueza",
            classe: "Mago Maldição",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Reduz FOR e AGI do alvo em 40%.",
            descricao_completa: "O mago amaldiçoa o alvo, reduzindo sua força e agilidade em 40% por 3 turnos. A maldição é mais forte se o PM do mago for superior à resistência do alvo.",
            custo_mana: 2000,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 4,
            nivel_desbloqueio: 9,
            passiva: false,
            duracao: "3 turnos"
        },
        {
            nome: "Cadeia de Almas",
            classe: "Mago Maldição",
            categoria: "Inicial",
            tipo: "Controle",
            descricao: "Prende alvo com correntes espirituais.",
            descricao_completa: "O mago invoca correntes espirituais que prendem o alvo, impedindo seu movimento por 2 turnos. O alvo pode tentar quebrar as correntes, mas precisa de FOR 50% maior que o PM do mago.",
            custo_mana: 3000,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 5,
            nivel_desbloqueio: 11,
            passiva: false,
            duracao: "2 turnos"
        },
        {
            nome: "Maldição da Morte",
            classe: "Mago Maldição",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Aplica dano contínuo que aumenta por 5 turnos.",
            descricao_completa: "O mago amaldiçoa o alvo com morte lenta. A maldição causa dano de 5% do PM por turno, aumentando em 5% cumulativamente a cada turno (máximo 50% no 5º turno). A maldição não pode ser dissipada.",
            custo_mana: 4000,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 6,
            nivel_desbloqueio: 13,
            passiva: false,
            duracao: "5 turnos"
        },
        {
            nome: "Sacrifício Maldito",
            classe: "Mago Maldição",
            categoria: "Inicial",
            tipo: "Buff",
            descricao: "Troca HP por aumento de poder mágico.",
            descricao_completa: "O mago sacrifica 30% de seu HP atual para ganhar +80% de PM e +50% de dano em maldições por 3 turnos. Durante este período, o mago não pode se curar.",
            custo_mana: 2500,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 7,
            nivel_desbloqueio: 15,
            passiva: false,
            duracao: "3 turnos"
        },
        {
            nome: "Maldição do Esquecimento",
            classe: "Mago Maldição",
            categoria: "Inicial",
            tipo: "Controle",
            descricao: "Faz alvo esquecer habilidades por 2 turnos.",
            descricao_completa: "O mago amaldiçoa a mente do alvo, fazendo-o esquecer temporariamente suas habilidades. O alvo não pode usar técnicas por 2 turnos. A maldição é quebrada se o alvo receber dano massivo (mais de 50% do HP).",
            custo_mana: 5000,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 8,
            nivel_desbloqueio: 18,
            passiva: false,
            duracao: "2 turnos"
        },
        {
            nome: "Vínculo Sombrio",
            classe: "Mago Maldição",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Compartilha dano recebido com alvo amaldiçoado.",
            descricao_completa: "O mago cria um vínculo sombrio com um alvo amaldiçoado. Qualquer dano recebido pelo mago é reduzido em 40% e transferido para o alvo amaldiçoado. O vínculo dura enquanto a maldição estiver ativa.",
            custo_mana: 3500,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 5,
            nivel_desbloqueio: 20,
            passiva: false
        },
        {
            nome: "Maldição da Loucura",
            classe: "Mago Maldição",
            categoria: "Inicial",
            tipo: "Controle",
            descricao: "Alucinações que fazem alvo atacar aliados.",
            descricao_completa: "O mago amaldiçoa a mente do alvo, causando alucinações vívidas. O alvo ataca aliados aleatórios por 2 turnos, acreditando que são inimigos. A maldição é mais forte se o PM do mago for 2x maior que a resistência mental do alvo.",
            custo_mana: 6000,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 8,
            nivel_desbloqueio: 23,
            passiva: false,
            duracao: "2 turnos"
        },
        {
            nome: "Mestre das Maldições",
            classe: "Mago Maldição",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Pode manter até 3 maldições simultâneas.",
            descricao_completa: "O mago atinge domínio completo das artes malditas. Pode manter até 3 maldições ativas simultaneamente em diferentes alvos. Cada maldição adicional reduz o custo de mana em 15%.",
            custo_mana: 0,
            custo_qi: 20480,
            custo_qi_formatado: "20480 Qi",
            cooldown: 0,
            nivel_desbloqueio: 25,
            passiva: true
        },
        {
            nome: "Maldição da Destruição",
            classe: "Mago Maldição",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Explosão de energia sombria que causa dano massivo.",
            descricao_completa: "O mago concentra toda sua energia sombria e a libera em uma explosão de 10m de raio. A explosão causa dano de 200% do PM e aplica todas as maldições menores simultaneamente. Inimigos com 3 ou mais maldições recebem dano dobrado.",
            custo_mana: 10000,
            custo_qi: 40960,
            custo_qi_formatado: "40960 Qi",
            cooldown: 10,
            nivel_desbloqueio: 28,
            passiva: false,
            alcance: "15 metros",
            tamanho: "10 metros (raio)"
        }
    ]
};

module.exports = magoMaldicao;