const magoPlanta = {
    nome: "Mago de Planta",
    descricao_classe: "Mago que manipula plantas e a natureza, criando obstáculos, invocando criaturas florais e causando dano com espinhos e esporos. Possui técnicas de suporte, controle e dano em área.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Torreta de Girassol",
        classe: "Mago de Planta",
        categoria: "Inicial",
        tipo: "Mágica",
        descricao: "Invoca girassol que lança rajadas de energia.",
        descricao_completa: "O usuário Conjura um girassol em sua frente, esse girassol pode lançar rajadas de energia no inimigo em linha reta de forma contínua caso o usuário queira, além de poder rodar a cabeça em um ângulo de 360°. Pode manter até 10 torretas de girassol ao mesmo tempo. O dano é baseado em [PM].",
        custo_mana: 1000,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 2,
        nivel_desbloqueio: 1,
        passiva: false,
        custo_mana_turno: 500,
        tamanho: "1.5m",
        alcance: "10m²"
    },
    tecnicas: [
        {
            nome: "Solo de Vinhas",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Invoca vinhas que protegem e barram inimigos.",
            descricao_completa: "O usuário pode conjurar vinhas dentro do solo que podem proteger a todos em uma certa área[15 vinhas], podendo ser usadas tanto para defender como barrar os inimigos em volta ou prender eles. As vinhas também possuem vários espinhos pelos seus corpos, então sempre que protegem o alvo, diminuem em 15% impactos recebidos.",
            custo_mana: 2000,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 2,
            nivel_desbloqueio: 3,
            passiva: false,
            alcance: "20m²"
        },
        {
            nome: "Pétalas de cerejeira",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria enxurrada de pétalas que cortam tudo.",
            descricao_completa: "O usuário Conjura uma grande quantidade de pétalas que protegem o usuário, as pétalas são tão afiadas quanto lâminas de espadas, então qualquer coisa que se aproxima do usuário é cortado pela enxurrada de pétalas [PM e ignora 20% res]. Pode usar para proteger aliados próximos também.",
            custo_mana: 2000,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 2,
            nivel_desbloqueio: 5,
            passiva: false,
            custo_mana_turno: 1000,
            tamanho: "5m"
        },
        {
            nome: "Pólen Psicodélico",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Espalha pólen que causa alucinações.",
            descricao_completa: "O usuário Conjura uma grande flor de coloração roxa que ao desabrochar revela suas pétalas, e, delas, um pólen se espalha no ar cobrindo o campo de batalha. O pólen possui um efeito psicodélico que causa alucinações em quem o respira. As alucinações são tão realistas que impedem que os alvos afetados saibam distinguir o que é real e o que é apenas ilusão, mas apenas aqueles que possuírem sentidos inferior a 40% do PM do usuário são, de fato, afetados.",
            custo_mana: 3500,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 5,
            nivel_desbloqueio: 7,
            passiva: false,
            alcance: "15 m²",
            duracao: "3 Turnos"
        },
        {
            nome: "Crescimento celular",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Cura",
            descricao: "Regenera membros perdidos.",
            descricao_completa: "Tocando em qualquer parte do aliado ou a si mesmo, regenera um membro perdido através do crescimento celular imbuído em várias plantas, fazendo com que a regeneração seja praticamente semi instantânea. Não pode regenerar ninguém morto, somente pessoas vivas.",
            custo_mana: 7000,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 6,
            nivel_desbloqueio: 9,
            passiva: false,
            alcance: "Corpo"
        },
        {
            nome: "Madeiras alternativas",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Invoca raízes que perseguem e atacam inimigos.",
            descricao_completa: "O usuário invoca várias raízes que se extendem em madeiras, essas madeiras perseguem o alvo dentro dos limites possíveis e podem ter formatos ligeiros e personalizáveis, podendo ser usada não só para perseguição e ataque mas pra defesa, estruturar e afins. A madeira tem base em resistência baseado no [PM] e dano e são personalizáveis vindo da mente do mago.",
            custo_mana: 1500,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 3,
            nivel_desbloqueio: 11,
            passiva: false,
            custo_mana_turno: 1000,
            tamanho_alcance: "25m²"
        },
        {
            nome: "Árvore da concentração",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Cria árvore que buffa aliados e protege com barreira.",
            descricao_completa: "O usuário cria uma grande Árvore (aparência personalizável) que pode aplicar um grande buff de 10% em todos atributos dos aliados próximos além de conceder barreiras uma barreira mágica moldada pela árvore que reduz um único ataque em [50%] do dano.",
            custo_mana: 8000,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 4,
            nivel_desbloqueio: 13,
            passiva: false,
            custo_mana_turno: 2000,
            tamanho: "50m²"
        },
        {
            nome: "Flor de Canhão Mágico Benígno",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Dispara feixe de energia floral que cura e causa dano.",
            descricao_completa: "Usando de sua magia, o mago faz com que cresça um grande número de vinhas e na ponta brote e cresça uma flor gigante. A flor então, a partir de uma abertura entre as pétalas, reúne Mana e a dispara em um feixe concentrado, que ao acertar o alvo explode. Dando um buff adicional de [40%] de poder Mágico do mago em resistência além de curar. Quando o usuário usa esse suplementar para todos alvos atingidos podendo aumentar de 5 em 5% a cada 1.000 de mana adicional além do alcance em 1 em 1.",
            custo_mana: 5000,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 3,
            nivel_desbloqueio: 15,
            passiva: false,
            tamanho: "35m²",
            alcance_explosao: "15m²"
        },
        {
            nome: "Esporo Paralisante",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Libera esporos que paralisam inimigos.",
            descricao_completa: "O usuário invoca uma flor azul escura no campo de batalha, a flor então logo começa a desabrochar. Após isso, um esporo é liberado por todo o Campo de Batalha que pode paralisar tanto o oponente quanto os aliados, os paralisando por 2 turnos. Para paralisar o inimigo, a defesa do oponente tem que ser menor que [60%] do PM do Mago.",
            custo_mana: 2000,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 3,
            nivel_desbloqueio: 18,
            passiva: false,
            alcance: "20m²"
        },
        {
            nome: "Brotos de Mana",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Lança brotos que sugam mana do inimigo.",
            descricao_completa: "O usuário pode lançar brotos no inimigo, caso os brotos acertem, eles se prendem no corpo do Oponente e começa a sugar sua mana de pouco em pouco. Os brotos só sugam a mana do oponente caso a resistência dele for menor que [90%] do PM do usuário. Consome 750 de mana do Oponente por turno por broto colocado.",
            custo_mana: 1000,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 3,
            nivel_desbloqueio: 20,
            passiva: false,
            quantidade: "10 por pessoa",
            duracao: "2 turnos"
        },
        {
            nome: "Conexão das plantas",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Plantes conectadas potencializam feitiços.",
            descricao_completa: "Cada feitiço lançado pelo mago faz com que pequenas vinhas brotem de forma o oculta por baixo do solo se conectando as plantas criadas. Cada vinha potencializa em [5%] feitiços lançados pelo mago que já estejam no campo. As vinhas se conectam em múltiplos feitiços também, não existindo um limite em si.",
            custo_mana: 0,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 0,
            nivel_desbloqueio: 25,
            passiva: true
        },
        {
            nome: "Erva radiante",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Cura/Buff",
            descricao: "Cura aliados e buffa atributos em área.",
            descricao_completa: "Dentro de uma área, o usuário faz crescer pequenas ervas pelo solo que sacudem continuamente sem parar liberando pequenas partes de si além da fotossíntese rápida mesmo em ambientes escuros, assim curando aliados dentro dessa área e dando um pequeno buff nos dois atributos principais [15%] e reestrutura seus corpos os estabilizando caso estejam em estado grave. Custo de Mana: 2.500 por buff. Alcance: 15m². Recarga: 4 turnos. Duração: 2 turnos",
            custo_mana: 2500,
            custo_qi: 50000,
            custo_qi_formatado: "50000 Qi",
            cooldown: 4,
            nivel_desbloqueio: 28,
            passiva: false
        },
        {
            nome: "Interligação afetiva",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Liga aliados distribuindo dano mágico.",
            descricao_completa: "O mago de planta liga até quatro aliados com um vínculo através de uma única vinha, todos são ligados por uma 'corda' que se conecta. Quando um destes receber dano mágico, o dano mágico é distribuído para os 4 aliados e distribuindo igualmente em 25% além de aumentar a resistência destes em 10% da PM do mago. Pode usar em si mesmo e se ligar a plantas também. Custo de Mana: 5.000. Alcance: 40m². Duração: 3 turnos. Recarga: 4 turnos",
            custo_mana: 5000,
            custo_qi: 100000,
            custo_qi_formatado: "100000 Qi",
            cooldown: 4,
            nivel_desbloqueio: 30,
            passiva: false
        },
        {
            nome: "Semear e crescer",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Invocação",
            descricao: "Duplica plantas e remove limite por 2 turnos.",
            descricao_completa: "O mago faz com que suas plantas germinem uma semente de si mesmas e essas sementes crescem rapidamente se moldando numa nova planta idêntica e com mesmas características [1 semente por planta]. Também possibilita estourar limites de plantas por dois turnos, se uma planta tem limite de 3 e você tem 3 em campo e usa, se tornam 6 por dois turnos e n pode ser aumentado de forma alguma. [Skill sem possibilidade de token] Custo de Mana: 1.250 por planta. Recarga: 5 turnos",
            custo_mana: 1250,
            custo_qi: 250000,
            custo_qi_formatado: "250000 Qi",
            cooldown: 5,
            nivel_desbloqueio: 33,
            passiva: false
        },
        {
            nome: "Corrupção do verde",
            classe: "Mago de Planta",
            categoria: "Inicial",
            tipo: "Transformação",
            descricao: "Transforma habilidades de cura em dano.",
            descricao_completa: "Quando ativar essa habilidade, o mago transformará todas suas skill de cura em skills de dano, skills de retirar debuffs em aplicar debuffs e skills de redução de dano e afins no oposto. Suas plantas vão receber um aspecto sombrio e melancólico num tom preto alaranjado como se estivessem mortas e corrompidas além do seu dano base aumentar em 100%. Esse modo só pode ser ativado 3x em vida, pois a quarta se torna permanente e neste momento ninguém sabe o que acontece. Existem condições para aplicação deste modo. Obs: caso tenha dúvidas, só inverter tudo nas skills. Algumas não são afetadas por já causarem dano ou serem supleneh. Ter 20 plantas em campo [raízes não contam nem vinhas]. Ter pelo menos 500 de PM base sem buff de classe. Custo: nada. Duração: até o final da batalha. Recarga: até ser usado novamente com estas condições.",
            custo_mana: 0,
            custo_qi: 500000,
            custo_qi_formatado: "500000 Qi",
            cooldown: 0,
            nivel_desbloqueio: 35,
            passiva: false
        }
    ]
};

module.exports = magoPlanta;