const magoTerra = {
    nome: "Mago de Terra",
    descricao_classe: "Mago que manipula a terra e minerais, criando muralhas de cristal, espinhos de pedra e terremotos. Pode moldar diferentes tipos de minerais para obter efeitos variados.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Erupção",
        classe: "Mago de Terra",
        categoria: "Inicial",
        tipo: "Mágica",
        descricao: "Causa erupção de rochas em área de 12m.",
        descricao_completa: "Você imbui o solo em uma raio de 12 metros em um espaço que você possa ver há 30 metros e usa sua mana para desestabilizar o solo da região. Dentro da área, uma erupção de rochas é formada similar a um vulcão. Quem estiver na área é desestabilizado recebendo [-30% agilidade] e atingido por uma chuva de rochas magmáticas que além de dar dano causam queimaduras.",
        custo_mana: 3000,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 4,
        nivel_desbloqueio: 1,
        passiva: false,
        alcance: "30 metros",
        tamanho: "12 metros (diâmetro)"
    },
    tecnicas: [
        {
            nome: "Areia Movediça",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Transforma solo em areia movediça que prende inimigos.",
            descricao_completa: "Você altera as propriedades do solo local para que ele se iguale às propriedades de areia movediça. Se não houver grama ou plantas na região, o local é visualmente idêntico, quase imperceptível [comparar sentidos com seu PM] aos olhos. Uma vez que pisar no local, a criatura é puxada a uma taxa de 90 centímetros em cada um dos turnos do usuário. Além de receber [-25% agilidade] e ficar preso no solo.",
            custo_mana: 2500,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 3,
            nivel_desbloqueio: 3,
            passiva: false,
            alcance: "30 metros",
            tamanho: "8 metros (diâmetro)"
        },
        {
            nome: "Muralha de Cristal",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Cria muralha de cristal com resistência.",
            descricao_completa: "Você cria uma muralha de cristal que tem seu PM + 15% de resistência, com a mesma ficando 2 turnos ativa após utilizar a habilidade.",
            custo_mana: 1200,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 2,
            nivel_desbloqueio: 5,
            passiva: false,
            alcance: "2 metros",
            tamanho: "5 metros"
        },
        {
            nome: "Cristal Espelhado",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Espelho que redireciona ataques para o lançador.",
            descricao_completa: "Você cria um espelho que tem uma área total de 10x10 usando sua mana e consegue fazer com que ele redirecione um ataque para o local de onde foi originado, entretanto, apenas ataques que tenham pontuação superior ao seu PM. Uma vez que refletido, o espelho se torna areia e cai ao chão, formando um campo de areia movediça de 2x2 até o início de sua próxima cena.",
            custo_mana: 3000,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 3,
            nivel_desbloqueio: 7,
            passiva: false,
            alcance: "10 metros"
        },
        {
            nome: "Antecipação terrestre",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Defesa automática que bloqueia qualquer ataque por 1 turno.",
            descricao_completa: "O mago está em constante conexão com a sua natureza, sentindo vibrações e alterações terrenas como se fossem um só. Sua mana flui conectando-se na terra. Durante esse turno, qualquer ataque que tenha como o alvo o mago, será automaticamente defendido pela própria terra domada pela mana do emissor, ignorando condições e feitos.",
            custo_mana: 6000,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 1,
            nivel_desbloqueio: 9,
            passiva: false,
            duracao: "1 turno"
        },
        {
            nome: "Pequena Chuva de ouro",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Chuva de areia dourada que cega e causa dano.",
            descricao_completa: "Você espalha sua mana no ar, em uma área que possa ver dentro do alcance e neste local uma chuva de areia dourada recai sobre os alvos. Enquanto a areia toma um formato de furacão em area, alvos dentro sofrem com cegueira e perda do equilíbrio. Além de serem dilacerados pelo ouro na sua forma primordial, o pó. Tendo bônus de 30% de sua PM no ataque.",
            custo_mana: 3500,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 3,
            nivel_desbloqueio: 11,
            passiva: false,
            alcance: "15 metros",
            tamanho: "10 metros"
        },
        {
            nome: "Conhecimento terrestre (passiva)",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Permite modificar habilidades com diferentes minerais.",
            descricao_completa: "O mago de terra agora tem total conhecimento de seu potencial, entendendo que terra não está associada somente a pedras e solo movediço. Agora ganha conhecimento amplo podendo modificar e adicionar descrição das habilidades por qualquer minério desejado entre os listados a qualquer momento. Ouro [+30% resistência]/ Diamante[+30% dano]/ Ferro [+15% dano e resistência] obsidiana [+55% resistência porém dobra o custo].",
            custo_mana: 1000,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 0,
            nivel_desbloqueio: 13,
            passiva: true,
            alcance: "20 metros"
        },
        {
            nome: "Deserto Pesado",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Areia densa que atrai e explode com gases tóxicos.",
            descricao_completa: "Ao começar a concentrar uma grande quantidade de Areia em suas mãos você começa a criar uma grande quantidade de Areia que começa a condensar ficando mais densa e pesada até que gases esverdeados começam a sair da mesma, ao final de tudo ao disparar ela implode atraindo tudo para o seu meio que tenha uma resistência 70% menor que PM para o meio e logo explodindo em gases tóxicos com a força de 2x seu PM.",
            custo_mana: 4000,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 4,
            nivel_desbloqueio: 15,
            passiva: false,
            alcance: "30 Metros",
            tamanho: "10 metros"
        },
        {
            nome: "Estacas de pedra",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Invoca estacas de pedra que ignoram resistência.",
            descricao_completa: "O mago de terra pode forjar quantas estacas de pedra quiser e arremessar contra um inimigo ou manifestar no chão dentro da área limite. As estacas causam dano baseado no [PM] e ignoram [5% da resistência].",
            custo_mana: 750,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 2,
            nivel_desbloqueio: 18,
            passiva: false,
            alcance: "30m²"
        },
        {
            nome: "Robustez terrena",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Dobra quantidade de materiais usados nas skills.",
            descricao_completa: "O mago de terra consegue exercer aumento de material usado nas suas skill, isso é, melhora a quantidade do qual for usar, duplicando seu valor base citados na passiva. Entretanto gastará o dobro nas suas skill.",
            custo_mana: 5000,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 3,
            nivel_desbloqueio: 20,
            passiva: false,
            duracao: "2 turnos",
            max_uso: "2 num único turno"
        },
        {
            nome: "Coluna de Gaia",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Invoca coluna de rocha que lança inimigos ao ar.",
            descricao_completa: "Com um gesto firme, o mago invoca uma colossal coluna de rocha que explode do subsolo, lançando inimigos ao ar e causando dano massivo[PM+50% de dano]. A energia da terra reverbera no impacto, causando tremores que desestabilizam inimigos ao redor, reduzindo a velocidade por alguns segundos [15%].",
            custo_mana: 7000,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 4,
            nivel_desbloqueio: 23,
            passiva: false
        },
        {
            nome: "Corpo de granito",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Reveste corpo com granito reduzindo danos.",
            descricao_completa: "O mago reveste seu corpo com granito, fazendo com que danos físicos e mágicos sejam reduzidos em 30% por um único turno. Essa habilidade também permite revestir granito nas barreiras feitas como 'Muralha de cristal' reduzindo impactos em 30%",
            custo_mana: 4000,
            custo_qi: 20480,
            custo_qi_formatado: "20480 Qi",
            cooldown: 2,
            nivel_desbloqueio: 25,
            passiva: false
        },
        {
            nome: "Chamado do ferro",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Invoca armadura de ferro que aumenta resistência.",
            descricao_completa: "O mago invoca do mais profundo subsolo grandes quantidades de ferro, esse ferro se molda numa armadura para quem estiver próximo sendo aliado e ao mago também, aumentando sua resistência em [50%] do valor base do PM do mago.",
            custo_mana: 4000,
            custo_qi: 40960,
            custo_qi_formatado: "40960 Qi",
            cooldown: 5,
            nivel_desbloqueio: 28,
            passiva: false,
            custo_mana_turno: 3000,
            duracao: "3 turnos"
        },
        {
            nome: "Benção do ouro vivo",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Buff",
            descricao: "Reveste equipamentos com ouro que ignora resistência.",
            descricao_completa: "Quando utilizar essa técnica, entrelaça equipamentos com fios dourados maleáveis, aplicando a passiva automaticamente nestes utensílios revestidos pelo ouro, além de os tornarem fugazes. Fugaz faz com que ataques físicos ignorem [25%] da resistência e ataques mágicos apliquem uma marca dourada no inimigo da qual potencializa o dano recebido em [10%. Custo de mana: 5.000. Duração geral: 3 turnos. Recarga: 4 turnos.",
            custo_mana: 5000,
            custo_qi: 500000,
            custo_qi_formatado: "500000 Qi",
            cooldown: 4,
            nivel_desbloqueio: 30,
            passiva: false
        },
        {
            nome: "Súplica de Gaia",
            classe: "Mago de Terra",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Braço gigante de rocha que causa dano massivo.",
            descricao_completa: "Condensando ouro, obsidiana e ferro além de terra, areia e barro o mago cria um braço gigante que saí do solo aos céus ainda conectado ao solo, crescendo igualmente uma árvore. Esse braço sobe sessenta metros aéreos e abre sua mão que bate no solo com tudo. O impacto lança todos minérios e materiais usados para todas direções além de causar dano [+100%PM]. Os materiais espalhados na composição da mão que se desfaz ficam espalhados no solo, possibilitando uso destes sem gasto de mana. [1x cada material]. Gasto de mana: 10.000. Recarga: 7 turnos.",
            custo_mana: 10000,
            custo_qi: 1000000,
            custo_qi_formatado: "1000000 Qi",
            cooldown: 7,
            nivel_desbloqueio: 33,
            passiva: false
        }
    ]
};

module.exports = magoTerra;