const magoRaio = {
    nome: "Mago de Raio",
    descricao_classe: "Mago que manipula eletricidade e raios, criando descargas elétricas, tempestades e rajadas. Possui técnicas de dano massivo e controle com paralisia.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Esfera de Raio",
        classe: "Mago de Raio",
        categoria: "Inicial",
        tipo: "Mágica",
        descricao: "Cria esfera elétrica que explode em área.",
        descricao_completa: "O usuário conjura uma esfera elétrica de cerca de 60 cm de diâmetro próxima ao corpo, a qual emite rastros elétricos decorativos. Ao atingir um inimigo, explode, causando dano em uma área de 5 metros de raio. É possível conjurar várias esferas simultaneamente.",
        custo_mana: 1000,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 1,
        nivel_desbloqueio: 1,
        passiva: false,
        alcance: "Base de 15m, aumentando +1m para cada 1.000 de mana adicional",
        tamanho: "5 metros (raio)"
    },
    tecnicas: [
        {
            nome: "Zakeru",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Dispara feixe que paralisa por 1 turno.",
            descricao_completa: "O usuário canaliza energia elétrica em um ponto e dispara um feixe veloz contra o inimigo. Ao atingir, paralisa o alvo por 1 turno. A energia pode ser canalizada para armas, causando +50% do PM como dano extra.",
            custo_mana: 2000,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 2,
            nivel_desbloqueio: 3,
            passiva: false,
            alcance: "20m"
        },
        {
            nome: "Traço Relâmpago",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Movimentação",
            descricao: "Se converte em eletricidade para teleporte.",
            descricao_completa: "O corpo do usuário se converte em eletricidade por 5 segundos, permitindo deslocamento quase instantâneo por materiais condutores. O deslocamento tem limite de 10 metros e ignora obstáculos físicos condutivos.",
            custo_mana: 1000,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 3,
            nivel_desbloqueio: 5,
            passiva: false,
            alcance: "10m"
        },
        {
            nome: "Baou Zakeruga",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria dragão de raio com dano massivo.",
            descricao_completa: "O usuário cria uma grande manifestação de raio em forma de dragão com enormes presas que emitem eletricidade e olhos vermelhos brilhantes. O Dano base é de 100% do pm total do mago. O Baou Zakeruga dá um dano adicional de 100% do pm base em dano, caso gaste 8.000 de mana extra, sendo acumulado até um máximo de [500%]. Deixa um rastro elétrico pelo caminho, em áreas que possuem afinidade com eletricidade, nos quais geram correntes elétricas que paralisam o alvo por um turno.",
            custo_mana: 2000,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 6,
            nivel_desbloqueio: 8,
            passiva: false,
            tamanho: "15m"
        },
        {
            nome: "Railgun",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Dispara feixe contínuo de eletricidade.",
            descricao_completa: "Um feixe de eletricidade é disparado da ponta dos dedos do usuário em alta velocidade. Pode ser disparado por todos os dedos sem limite de uso.",
            custo_mana: 700,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 0,
            nivel_desbloqueio: 10,
            passiva: false,
            alcance: "20m"
        },
        {
            nome: "Prisão de Raios",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Aprisionamento",
            descricao: "Cria cúpula de raios que prende inimigos.",
            descricao_completa: "O usuário cria uma grande cúpula feita totalmente de raios que prende ele é o inimigo, caso o oponente tente fugir, ele terá que passar pela cúpula de raios que os prende, no qual da dano a qualquer pessoa que tocar nela. A prisão dura 3 Turnos.",
            custo_mana: 5000,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 3,
            nivel_desbloqueio: 12,
            passiva: false,
            tamanho: "10m"
        },
        {
            nome: "Tempestade",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria tempestade de relâmpagos em área.",
            descricao_completa: "O usuário cria uma grande tempestade de relâmpagos no céu que atingem todos os adversários, a área da tempestade é um quadrado de 40m por 40m, ou seja a partir do usuário (ele representa o meio da área) qualquer inimigo que esteja até 20m dele será contabilizado. O usuário pode concentrar raios lançados em si mesmo para condensar uma grande quantidade elétrica e dispersar numa rajada única amarelada que segue reto (com um alcance de 40m) causando uma explosão elétrica baseado no [PM total +20% do pm base por raio]. 1 raio por cada inimigo dentro da área.",
            custo_mana: 4000,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 3,
            nivel_desbloqueio: 14,
            passiva: false,
            alcance: "40m"
        },
        {
            nome: "El Thor",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Raio colossal do céu que causa dano massivo.",
            descricao_completa: "O usuário concentra um grande aglomerado de eletricidade no céu, então usa-o para enviar um enorme e poderoso raio para baixo do céu, destruindo e fritando tudo que estiver embaixo (Pm total+30%). Ao atingir o solo, o raio se dispersa em 10m², paralisando alvos por 1 turno.",
            custo_mana: 6000,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 2,
            nivel_desbloqueio: 16,
            passiva: false,
            alcance: "50m",
            area: "10m²"
        },
        {
            nome: "Proteção de Raio",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Cria esfera de raio que protege e causa dano.",
            descricao_completa: "O usuário cria uma de Esfera de raio em volta de si, essa Esfera protege o usuário de qualquer ataque externo e da dano a qualquer coisa que toque na esfera. A esfera pode ser destruída caso seja acertada por um Ataque muito forte [1,5x do PM para destruir].",
            custo_mana: 7000,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 4,
            nivel_desbloqueio: 18,
            passiva: false,
            duracao: "2 turnos",
            tamanho: "2.5m"
        },
        {
            nome: "Baou Kurou Disugurugu",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Braço de dragão de eletricidade que ataca.",
            descricao_completa: "O usuário cria um grande braço de dragão feito totalmente de eletricidade, o usuário pode usar esse braço para atacar os inimigos a longa distância batendo neles. Também pode Criar bolas de energia elétrica e lança nos inimigos (500 mp por volta). O braço também dispara rajadas elétricas que atingem 5m² em área com alcance de 30m (1.000 por rajada).",
            custo_mana: 3000,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 3,
            nivel_desblolveio: 21,
            passiva: false,
            custo_mana_turno: 1500,
            tamanho: "10m",
            alcance: "30m"
        },
        {
            nome: "Deus dos raios [Passiva]",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Altera cor da eletricidade com efeitos únicos.",
            descricao_completa: "O verdadeiro mestre dos raios desperta a capacidade de alterar a coloração e essência de sua eletricidade, tornando seus relâmpagos únicos, imbuídos de efeitos elementares e propriedades místicas. Apenas um usuário pode deter cada cor por vez uma escolha que define seu estilo de combate e identidade mágica. Obs: Archon não usa a cor amarelada. Azul [+40% dano + congelamento em área], Vermelho [+120% dano, custo duplicado], Verde [+50% dia/+40% noite], Laranja [+70% dano, stun 2 turnos], Super raio [+130% dano, ignora 10% resistência], Amarelada [+30% dano, -1 turno cooldown].",
            custo_mana: 0,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 0,
            nivel_desbloqueio: 25,
            passiva: true
        },
        {
            nome: "Onda de raio",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Ataque em linha reta de 5m x 20m.",
            descricao_completa: "O usuário cria um mega relâmpago em mãos e o bate no chão como uma clava. Quando acertar o solo explode em área acertando todos dentro, exceto o próprio usuário. A área é uma linha reta de 5m de largura e 20m de alcance.",
            custo_mana: 5000,
            custo_qi: 20480,
            custo_qi_formatado: "20480 Qi",
            cooldown: 3,
            nivel_desbloqueio: 28,
            passiva: false,
            area: "100m²"
        },
        {
            nome: "Círculo de Descargas",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria círculo de raios que causa dano contínuo.",
            descricao_completa: "O usuário cria um círculo de raios no chão com 8m de diâmetro. Qualquer criatura dentro do círculo recebe dano elétrico contínuo baseado no PM do usuário a cada turno. O círculo dura 3 turnos e pode ser usado para controlar área ou impedir fuga.",
            custo_mana: 4000,
            custo_qi: 50000,
            custo_qi_formatado: "50000 Qi",
            cooldown: 5,
            nivel_desbloqueio: 30,
            passiva: false,
            tamanho: "8m (diâmetro)",
            duracao: "3 turnos"
        },
        {
            nome: "Choque do Trovão",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Ataque concentrado que ignora 40% da resistência.",
            descricao_completa: "O usuário concentra eletricidade em um único ponto e libera em forma de choque direto. Este ataque ignora 40% da resistência do alvo e causa dano baseado no PM + 50% do PM base. Se o alvo estiver molhado ou em área com água, o dano é dobrado.",
            custo_mana: 3500,
            custo_qi: 100000,
            custo_qi_formatado: "100000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 32,
            passiva: false,
            alcance: "25m"
        },
        {
            nome: "Ressonância Elétrica (Passiva)",
            classe: "Mago de Raio",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Ataques elétricos causam dano adicional por 3 turnos.",
            descricao_completa: "Cada ataque elétrico bem-sucedido aplica uma marca de ressonância no alvo. A marca causa dano adicional de 10% do PM do usuário por 3 turnos. Se o alvo for atingido por outro ataque elétrico durante a duração, a duração é renovada e o dano acumulado aumenta em 5% por acerto.",
            custo_mana: 0,
            custo_qi: 250000,
            custo_qi_formatado: "250000 Qi",
            cooldown: 0,
            nivel_desbloqueio: 35,
            passiva: true
        }
    ]
};

module.exports = magoRaio;