const magoAgua = {
    nome: "Mago de Água",
    descricao_classe: "Mago que manipula a água em suas diversas formas, desde jatos pressurizados até tsunamis devastadores. Possui técnicas de combate, controle e invocação de criaturas marinhas.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Reflexo d'água",
        classe: "Mago de Água",
        categoria: "Inicial",
        tipo: "Mágica",
        descricao: "Reflete ação inimiga criando um círculo d'água.",
        descricao_completa: "Necessitando de uma superfície como base, o mago de água realiza um movimento circular criando um círculo d'água médio, do qual reflete a ação inimiga, fazendo com que ela seja idêntica e se choquem, podendo ser o próprio inimigo e suas habilidades respectivas. O dano da ação refletida equivale a 100% do PM do mago.",
        custo_mana: 3000,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 1,
        nivel_desbloqueio: 1,
        passiva: false
    },
    tecnicas: [
        {
            nome: "Tsunami",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Invoca onda gigantesca que varre tudo no caminho.",
            descricao_completa: "O mago d'água invoca uma tremenda onda gigantesca que sai varrendo tudo e todos pelo caminho. O tamanho da onda varia com a quantidade de mana gasto, a cada 1.000 de mana depositado aumenta o tamanho em 1m e seu respectivo dano em +10%.",
            custo_mana: 1500,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 3,
            nivel_desbloqueio: 3,
            passiva: false
        },
        {
            nome: "Mar Morto",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria área de água que corrói e debuffa inimigos.",
            descricao_completa: "O mago faz com que uma pequena quantidade de água se estabeleça na área de 40m² igualmente uma piscina rasa. Cada turno que quem estiver na área permaneça, perde 10% de resistência e velocidade com máximo de 5 turnos. O sal da água corrói as pernas lentamente. No último turno caso exista alguém ainda dentro da área, receberá um aumento de debuff em +20% nos respectivos listados.",
            custo_mana: 2000,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 4,
            nivel_desbloqueio: 5,
            passiva: false
        },
        {
            nome: "Sarcófago marítimo",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Prende inimigo com fios aquáticos e sela em sarcófago.",
            descricao_completa: "Emergindo um sarcófago aberto a frente do mago, fios aquáticos [max = 15] emergem de dentro de si indo em direção ao alvo que ao ser acertado por um desses fios [fio= 50% PM]. Se prende ao alvo imobilizando a área atingida fazendo força contrária [puxando pro sarcófago]. Caso o oponente seja puxado pro sarcófago será selado, ficando recoberto por correntes aquáticas impossibilitando movimentos hostis. Os fios percorrem até 30m.",
            custo_mana: 3000,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 5,
            nivel_desbloqueio: 7,
            passiva: false
        },
        {
            nome: "Entendedor das profundezas",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Controla águas profundas e invoca criaturas marinhas.",
            descricao_completa: "Treinando na área marítima, aperfeiçoou os conhecimentos com muito estudo e dedicação fiel aos livros. Agora pode controlar águas marítimas mais profundas e trazer criaturas profundas em habilidade. Qualquer habilidade pode te trazer uma criatura das profundezas dos listados [tubarão branco/lula gigante/peixe diabo e arraiá gigante]. Estes respondem fielmente seu chamado e tem atributos com base em 20% do seu mp. Além dos respectivos efeitos únicos (tubarão: +30% dano/lula gigante: oito tentáculos com +4% do mp em atributos cada um, totalizando +32%/peixe diabo : +30% agilidade/ arraiá gigante: causa dano elétrico ao agarrar um alvo]. 1x por turno.",
            custo_mana: 0,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 0,
            nivel_desbloqueio: 10,
            passiva: true
        },
        {
            nome: "Correntes Marítimas",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Invoca 4 correntes de água que prendem o alvo.",
            descricao_completa: "O mago invoca quatro correntes feita de água sólida que perseguem o alvo o prendendo e restringindo. As correntes possuem resistência igual MP do mago +25%.",
            custo_mana: 1200,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 3,
            nivel_desbloqueio: 12,
            passiva: false
        },
        {
            nome: "Chuva",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria chuva que inunda área e potencializa ataques aquáticos.",
            descricao_completa: "O mago consegue invocar água onde não existe, criando uma chuva mesmo que não exista nuvens ou sequer dê para vê-las. A chuva inunda até a altura de 90cm d'água em 40m². O mago também pode usar da própria água existente no lugar para realizar seus ataques sem tempo de castar e potencializar seus ataques. [+30% dano ataques potencializados] [pode fazer um único feitiço com metade do auxílio de mana por turno e só usando a água gerada]",
            custo_mana: 4000,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 4,
            nivel_desbloqueio: 15,
            passiva: false
        },
        {
            nome: "Jatos pressurizados",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Dispara jato de água pressurizada que ignora resistência.",
            descricao_completa: "O mago dispara um jato pressurizado de pura mana aquática em direção do alvo, esse pode ignorar resistência [20%] e quebrar armaduras que tenham rank abaixo ao mago.",
            custo_mana: 1500,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 2,
            nivel_desbloqueio: 18,
            passiva: false
        },
        {
            nome: "Barreira D'água",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Cria barreira de água sólida resistente.",
            descricao_completa: "O mago invoca uma barreira vertical moldada puramente por água em seu estado sólido, que contém resistência aprimorada [+35%] além de conseguir resistir a golpes físicos com até [+25% do MP do mago].",
            custo_mana: 2500,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 3,
            nivel_desbloqueio: 20,
            passiva: false
        },
        {
            nome: "Mandíbula do abismo",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Abre fenda marinha que abocanha área causando dano massivo.",
            descricao_completa: "Numa área [até 20m] da distância do mago, este pode condensar sua magia e conhecimento, fazendo com que de qualquer direção dentro dessa área uma fenda marítima abrir-se num formato circular [cada 750 de mana extra imposto aumenta tamanho da fenda em 1m com máximo de 10 extras/começa com 5]. Dentro dessa fenda uma boca enorme se manifesta sendo cuspida pra fora e abocanhando a área de efeito sob sua frente destruindo o que estiver no caminho. Para cada metro extra imposto aumenta o dano causado em 5% começando com 25%.",
            custo_mana: 2500,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 2,
            nivel_desbloqueio: 25,
            passiva: false
        },
        {
            nome: "Sussurro dos afundados",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Controle",
            descricao: "Vozes imperceptíveis que causam atordoamento.",
            descricao_completa: "Curtas brisas marítimas ecoam pela região trazendo consigo vozes imperceptíveis. Aqueles que forem afetados [PM= 100% a mais que sentidos e resistência] entram num transe iminente sendo distraídos pelas palavras, buscando entender e com isso ficam impossibilitados de reagir por um único turno. O gatilho desta habilidade não é instantâneo, ou seja, leva certos segundos até existir tal atordoamento. Gasto de mana : 3.000 por personagem afetado. Duração : 1 turno. Recarga : 3 turnos.",
            custo_mana: 3000,
            custo_qi: 15000,
            custo_qi_formatado: "15000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 30,
            passiva: false
        },
        {
            nome: "Lágrimas de izzith",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Cura",
            descricao: "Regenera membros e invoca projeção de monstro abissal.",
            descricao_completa: "Izzith é uma criatura marinha de todo conhecimento dos magos d'água, este chora por seus filhos destinados ao fadado perecer dos seus filhos. Em circunstâncias comuns, essa habilidade permite o mago regenerar um membro perdido por tempo limitado [2 turnos] de si próprio e melhorar a próxima habilidade aquática em [+30%]. Porém, seu uso mais efetivo é a beira da morte, onde Izzith se torna uma projeção, um reflexo do poder do mago, surgindo como um monstro abissal [é uma projeção, não a própria.] Que desfere um ataque único vindo como um maremoto negro [50m²] atingindo todos dentro desse raio causando dano igual 4x o PM do mago e para cada 3.000 de mana restante aumenta área em 5m. Entretanto este perecerá e Izzith o levará para as profundezas junto a todos os mortos. Gasto de mana habilidade tradicional: 4.000. Gasto de mana de Izzith : Tudo.",
            custo_mana: 4000,
            custo_qi: 25000,
            custo_qi_formatado: "25000 Qi",
            cooldown: 7,
            nivel_desbloqueio: 35,
            passiva: false
        },
        {
            nome: "Bolhas de artilharia",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "15 bolhas que causam dano em área.",
            descricao_completa: "Quinze bolhas são criadas ao redor do usuário rodando como órbitas, estas saem ao comando em direção retas. Quando encostam em qualquer superfície, estouram causando pequenas erupções no ar e abrindo micro crateras de 20cm. O dano de cada bolha é equivalente 50% do PM. Gasto de mana : 2.000. Tempo de duração: até acabar. Recarga : 2 turnos.",
            custo_mana: 2000,
            custo_qi: 50000,
            custo_qi_formatado: "50000 Qi",
            cooldown: 2,
            nivel_desbloqueio: 40,
            passiva: false
        },
        {
            nome: "Prisão de Krivor",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Controle",
            descricao: "Jaula de água que aprisiona o alvo.",
            descricao_completa: "Krivor, uma criatura conhecida pela tamanho resistência interna, tudo aquilo que ela come, nunca escapa. Buscando espelhar um reflexo do que seria Krivor, os magos d'água aprenderam a 'prisão' onde caso exista água no solo, essa pode tomar forma de uma jaula quadrilátera azulada molenga com textura ríspida. Importante ressaltar que dificilmente atinge um inimigo em movimento, é um adendo para aprisionamentos ou selamento. Quando estiver dentro da jaula, é necessário ter o dobro do PM do mago pra sair causando dano. Gasto de mana : 4.000. Tempo de duração : 3 turnos. Tempo de recarga : 5 turnos.",
            custo_mana: 4000,
            custo_qi: 100000,
            custo_qi_formatado: "100000 Qi",
            cooldown: 5,
            nivel_desbloqueio: 45,
            passiva: false
        },
        {
            nome: "O abismo",
            classe: "Mago de Água",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Leva inimigo para dimensão aquática com buffs.",
            descricao_completa: "O mago condensa energia sólida na ponta dos dedos ou objeto condutor e abre uma área circular [30m]. Tudo dentro dessa área é levado para as 'profundezas' e protegido por uma cúpula d'água sólida atuando como uma bolha. No abismo as habilidades do mago ganham +50% de efetividade [PM] e seus tempos de recarga são zerados para todas habilidades aquáticas. Nada pode sair dessa área, entretanto o mago só pode usar para levar 1 inimigo para as profundezas, pois essa magia reside a lei da equidade : 'Aquele que cria e aquele que atinge'. Nas paredes criaturas abissais passam, olhos enormes fitando, é quase como ambos estarem num terreno perigoso com um único furo para morrerem. Gasto de mana: 10.000. Tempo de duração: 4 turnos + 2.500 por turno. Tempo de recarga : 1x por luta.",
            custo_mana: 10000,
            custo_qi: 500000,
            custo_qi_formatado: "500000 Qi",
            cooldown: 0,
            nivel_desbloqueio: 50,
            passiva: false
        }
    ]
};

module.exports = magoAgua;