const magoBarreira = {
    nome: "Mago de Barreira",
    descricao_classe: "O Mago de Barreira especializa-se em defesa mágica, criando barreiras impenetráveis e domos protetores. Pode refletir ataques, absorver magia e proteger múltiplos aliados simultaneamente.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Barreira Elemental",
        classe: "Mago de Barreira",
        categoria: "Inicial",
        tipo: "Defesa",
        descricao: "Cria barreira elemental que oferece proteção.",
        descricao_completa: "O usuário cria uma barreira feita de um dos 4 elementos base: Água, Terra, Fogo ou Vento. A barreira oferece proteção a todos os tipos de dano, mas àqueles equivalentes ao elemento escolhido enfrentam uma barreira 30% mais poderosa.",
        custo_mana: 1000,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 2,
        nivel_desbloqueio: 1,
        passiva: false,
        custo_mana_turno: 500,
        alcance: "20 metros",
        tamanho: "8 metros (raio)"
    },
    tecnicas: [
        {
            nome: "Escudo da Réplica",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Reflete ataque de volta para o atacante.",
            descricao_completa: "O mago de barreira consegue criar um escudo circular que, apesar de não ser um espelho, é capaz de refletir a aparência de quem se põe do outro lado. Ao ser atingido uma vez, o escudo é quebrado e uma réplica do atacante surge desferindo o mesmo ataque contra àquele que havia atacado o conjurador. O dano, porém, é com base no PM do usuário da barreira.",
            custo_mana: 1500,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 1,
            nivel_desbloqueio: 3,
            passiva: false,
            alcance: "30 metros"
        },
        {
            nome: "Barreira de Tranquilidade",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Acalma inimigos reduzindo agressividade.",
            descricao_completa: "O usuário ergue uma cúpula que engloba uma extensa área. Todos os Mobs dentro dessa área, são emocionalmente induzidos à calmaria, reduzindo a agressividade e vontade de lutar. Essa redução leva em consideração os Sentidos do alvo, contra o PM do mago de barreira.",
            custo_mana: 2000,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 2,
            nivel_desbloqueio: 5,
            passiva: false,
            duracao: "3 Turnos",
            alcance: "15 metros",
            tamanho: "8 metros (raio)"
        },
        {
            nome: "Barreira Sensitiva",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Utilidade",
            descricao: "Detecta criaturas que atravessam a barreira.",
            descricao_completa: "O usuário cria uma barreira totalmente inofensiva e invisível, entretanto, uma vez que uma criatura atravessar ela, sua localização automaticamente será denunciada para o conjurador. Esse aviso não causa nenhum tipo de som ou alteração no ambiente, então não pode ser percebido, a menos que os sentidos do alvo sejam 70% do PM do usuário.",
            custo_mana: 2000,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 3,
            nivel_desbloqueio: 7,
            passiva: false,
            duracao: "5 Turnos",
            tamanho: "50 metros"
        },
        {
            nome: "Barreira Arcana",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Escudo mágico que impede entrada e saída.",
            descricao_completa: "O mago ergue uma barreira mágica que funciona como um simples escudo, impedindo que qualquer coisa entre ou saia, sem que a barreira seja quebrada ou dissipada. Barreira é quebrada caso seja superada em algum ataque, além de cada turno custear para mantê-la ativa.",
            custo_mana: 1300,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 3,
            nivel_desbloqueio: 9,
            passiva: false,
            custo_mana_turno: 1000,
            duracao_maxima: "3 Turnos",
            alcance: "15 metros",
            tamanho: "6 metros (raio)"
        },
        {
            nome: "Guardião da Barreira",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Cria guardião que absorve dano e invoca barreiras.",
            descricao_completa: "O usuário cria um guardião que toma todo dano direcionado a ao conjurador. Quando o impacto do ataque for 50% superior ao do usuário, o guardião é destruído após absorver tudo. Além disso, o constructo de energia possui os seus atributos físicos equivalente a 50% dos seus pontos em PM e pode invocar barreiras igualmente seu mestre, utilizando das mesmas habilidades que este tenha.",
            custo_mana: 2000,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 5,
            nivel_desbloqueio: 11,
            passiva: false,
            tamanho: "Tamanho do usuário",
            alcance: "3 metros"
        },
        {
            nome: "Barreira da Absorção",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Absorve mana de feitiços e converte para si.",
            descricao_completa: "O usuário ergue uma barreira que o protege enquanto absorve a mana usada em feitiços direcionados a ele, convertendo-a para si. Golpes mágicos têm um valor equivalente a 25% da mana gasto, absorvido pela barreira e redirecionada a mana do usuário, sem ultrapassar o total que ele possui. Não consegue absorver ataques que gastem mais de 120% que o gasto de mana dessa defesa, a quebrando e recebendo todo dano.",
            custo_mana: 5000,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 2,
            nivel_desbloqueio: 13,
            passiva: false,
            duracao: "1 Turno",
            tamanho: "8 metros (raio)"
        },
        {
            nome: "Barreira da Distorção",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Redireciona projéteis para o lançador.",
            descricao_completa: "O usuário cria uma barreira que redireciona projéteis lançados contra ela, no sentido horário. Ou seja, o projétil dá uma volta completa e é redirecionado para o seu lançador, desde que o PM do usuário seja pelo menos 80% da Força ou PM do projétil. Caso o projétil supere em [120% o PM do mago], a barreira se quebra e o dano que este irá receber é reduzido em [50%].",
            custo_mana: 4000,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 3,
            nivel_desbloqueio: 15,
            passiva: false,
            tamanho: "6 metros (raio)"
        },
        {
            nome: "Barreira Prismática",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Ilusão",
            descricao: "Cria ilusões que confundem inimigos.",
            descricao_completa: "O usuário cria uma série de pequenas barreiras dentro do alcance que refratam a luz, fazendo com que ilusões extremamente realistas surjam, assim confundindo aqueles que possuem sentidos menor do que 50% do PM do usuário.",
            custo_mana: 4000,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 2,
            nivel_desbloqueio: 18,
            passiva: false,
            duracao: "2 Turnos",
            tamanho_ilussoes: "Até 3 metros"
        },
        {
            nome: "Abraço da Escuridão",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Suprime luz em área de 6m de raio.",
            descricao_completa: "O usuário forma uma cúpula onde a luz é toda suprimida, deixando assim um completo escuro, em seu interior. Magias de Luz dentro dessa área são 25% mais custosas e, não é possível enxergar dentro da área sem que haja uma magia de luz possibilitando.",
            custo_mana: 4500,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 4,
            nivel_desbloqueio: 20,
            passiva: false,
            duracao: "2 Turnos",
            alcance: "15 metros",
            tamanho: "6 metros (raio)"
        },
        {
            nome: "Barreira Piramidal",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Aprisionamento",
            descricao: "Prende inimigo em pirâmide que esmaga após 2 turnos.",
            descricao_completa: "Manifesta uma barreira no formato de piramidal ao redor de um inimigo, prendendo-o. Caso passe um turno e esse não consiga destruir a pirâmide [70%pm do mago]. A pirâmide começa se fechar até prensar o inimigo dentro e esmagar-lo.",
            custo_mana: 3000,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 2,
            nivel_desbloqueio: 23,
            passiva: false,
            custo_mana_turno: 1000
        },
        {
            nome: "Cilindro expansivo",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Defesa/Combate",
            descricao: "Armazena ataque e dispare posteriormente.",
            descricao_completa: "Formando uma barreira cilíndrica em pé, quando sofrer algum ataque esse ataque é armazenado dentro da barreira [até 100% PM do usuário]. No próximo turno o mago pode optar por deitar a barreira de cilindro e disparar esse ataque armazenado de forma mais pura e bruta de mana causando dano equivalente ao do usuário em PM + oponentePM.",
            custo_mana: 4500,
            custo_qi: 20480,
            custo_qi_formatado: "20480 Qi",
            cooldown: 3,
            nivel_desbloqueio: 25,
            passiva: false,
            custo_mana_turno: 1250
        },
        {
            nome: "Maníaco do Perfeccionismo (Passiva)",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Barreiras perfeitas ganham +30% PM e MP.",
            descricao_completa: "Como um verdadeiro amante de barreiras, você odeia irregularidades, nada pode estar fora da posição por milímetros que sejam. Suas barreiras se tornam perfeitas em simetria, fazendo com que qualquer efeito relacionado a barreiras seja melhorado minimamente [+30%PM e 30%MP ao usar barreiras] porém a insanidade da imperfeição te levou perder [-25% atributos físicos]. Para poder obter essa passiva, necessita de 'Barreira prismática, Cilindro e piramidal'.",
            custo_mana: 0,
            custo_qi: 40960,
            custo_qi_formatado: "40960 Qi",
            cooldown: 0,
            nivel_desbloqueio: 28,
            passiva: true
        },
        {
            nome: "Camada extra",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Adiciona camada interna fortalecendo barreira.",
            descricao_completa: "O mago de barreira pode gerar uma camada interna dentro de suas barreiras, essa camada recobre a força da barreira e melhora ela em [10%] por cada barreira [limite 5]. Gasto de mana por camada: 2.500. Direção: 1 turno. Recarga: 1 turno.",
            custo_mana: 2500,
            custo_qi: 100000,
            custo_qi_formatado: "100000 Qi",
            cooldown: 1,
            nivel_desbloqueio: 30,
            passiva: false
        },
        {
            nome: "Selamento",
            classe: "Mago de Barreira",
            categoria: "Inicial",
            tipo: "Controle",
            descricao: "Sela inimigo dentro da barreira reduzindo atributos.",
            descricao_completa: "Quando um mago de barreira conseguir prender um inimigo dentro da barreira poderá ativar essa skill caso o inimigo tenha ficado pelo menos um turno dentro da barreira. Ativando a skill, o inimigo será selado dentro da barreira e terá atributos reduzidos em 50% por dois turnos, além de ficar com capacidades impossibilitadas para usar magias. O selamento vem com uma silhueta mágica que aparece no corpo do inimigo automaticamente. Custo de mana : 10.000. Duração: 2 turnos. Recarga: 6 turnos.",
            custo_mana: 10000,
            custo_qi: 250000,
            custo_qi_formatado: "250000 Qi",
            cooldown: 6,
            nivel_desbloqueio: 33,
            passiva: false
        }
    ]
};

module.exports = magoBarreira;