const magoFogo = {
    nome: "Mago de Fogo",
    descricao_classe: "Mago que manipula o fogo e as chamas, criando explosões, rajadas e muralhas incandescentes. Possui técnicas ofensivas devastadoras e buffs de dano.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Sopro Ardente",
        classe: "Mago de Fogo",
        categoria: "Inicial",
        tipo: "Mágica",
        descricao: "Assopra espiral de fogo que avança 6m.",
        descricao_completa: "Assopra pela boca uma quantidade enorme de fogo em espiral, que avança em até [6m em área] queimando os inimigos no caminho e deixando um rastro de fogo por três turnos, diminuindo a resistencia deles em [10%] a cada turno dentro do fogo, totalizando no máximo [20%].",
        custo_mana: 1200,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 2,
        nivel_desbloqueio: 1,
        passiva: false,
        alcance: "6 metros",
        tamanho: "6 metros"
    },
    tecnicas: [
        {
            nome: "Espalhar fogo",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Aumenta área de fogo existente pelo dobro.",
            descricao_completa: "O mago de fogo ao seu comando, onde existir resquícios de fogo, este pode aumentar a área flamejante pelo dobro que essa abrange, deixando seu espaço pessoal maior e queimando inimigos no processo, causando dano equivalente 50% PM e causando queimadura que reduz 10% resistência.",
            custo_mana: 2000,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 2,
            nivel_desbloqueio: 3,
            passiva: false
        },
        {
            nome: "Flecha Flamejante",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Dispara 10 flechas de fogo que perfuram alvos.",
            descricao_completa: "Dispara 10 flechas feita de chamas, precisas e rápidas, perfurando alvos a longa distância ignorando [25%] resistência, além de deixar o alvo em queimaduras, que reduz sua resistência em [10%] por três turnos.",
            custo_mana: 1800,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 3,
            nivel_desbloqueio: 5,
            passiva: false,
            alcance: "50 metros",
            tamanho: "40cm"
        },
        {
            nome: "Escudo Ígneo",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Cria escudo de fogo que absorve ataques.",
            descricao_completa: "Cria um escudo de fogo defensivo, onde consegue absorver ataques que contenham até [25%] a mais de PM que o mago. O golpe absorvido é convertido em uma rajada de fogo direcionada para o alto, onde ao estourar faz uma chuva de fogo que tem como principal função queimar terreno e aumentar área de controle do mago.",
            custo_mana: 1500,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 3,
            nivel_desbloqueio: 7,
            passiva: false,
            alcance_chuva: "20 metros",
            tamanho_escudo: "5 metros"
        },
        {
            nome: "Rei do fogo (Passiva)",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Potencializa ataques de fogo em +30%.",
            descricao_completa: "Quando estiver em uma área com fogo, consegue utilizar do fogo dessa área para gerar ataques potencializados [+30% dano]. Mas o uso de ataques potencializados não permite que esses ataques em si incendeiem áreas, pois estes explodem no contato de forma concentrada e a área utilizada para potencialização some.",
            custo_mana: 0,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 0,
            nivel_desbloqueio: 9,
            passiva: true
        },
        {
            nome: "Muralha Infernal",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Cria muralha impenetrável de fogo.",
            descricao_completa: "Ergue uma muralha impenetrável de fogo que protege contra ataques físicos e mágicos por um curto período. [A barreira tem 50% a mais do PM].",
            custo_mana: 3500,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 4,
            nivel_desbloqueio: 11,
            passiva: false,
            alcance: "15 metros",
            tamanho: "5 metros"
        },
        {
            nome: "Bola de fogo",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Lança bola de fogo que explode causando dano em área.",
            descricao_completa: "Uma bola de fogo se expande nas mãos do mago, aumentando consequentemente com base no gasto de MP [cada 500 = 1m]. Quando lança a bola de fogo, está explode em chamas no primeiro contato, queimando a área onde atingiu e diminuindo resistência de todos aqueles que estiverem no fogo [10%].",
            custo_mana: 2800,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 3,
            nivel_desbloqueio: 13,
            passiva: false,
            alcance: "25 metros",
            tamanho_base: "1 metro"
        },
        {
            nome: "Grande bola de fogo",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Versão maior e mais poderosa da bola de fogo.",
            descricao_completa: "Uma versão aperfeiçoada da bola de fogo, essa muito maior e causa muito mais dano. Agora, a bola de fogo é concentrada na frente do mago, seu dano bruto é PM+50% e seu tamanho base é 10m. Quando depositar mana, aumenta seu tamanho [1000mp= 1.5m] e também seu raio de explosão que gera fogo na área atingida que diminui a resistência do alvo em chamas por [10%].",
            custo_mana: 5000,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 5,
            nivel_desbloqueio: 15,
            passiva: false,
            alcance: "50 metros",
            tamanho_base: "10 metros"
        },
        {
            nome: "Torrente",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Lança torrente de chamas reta.",
            descricao_completa: "Esticando as mãos pra frente, o mago lança uma torrente de chamas reta, que incendeia a área atingida e aqueles que estiverem no caminho.",
            custo_mana: 1500,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 2,
            nivel_desbloqueio: 17,
            passiva: false,
            alcance: "10 metros"
        },
        {
            nome: "Lava incandescente",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Abre fissura que cuspe lava derretendo equipamentos.",
            descricao_completa: "O mago esquente o solo, abrindo uma fissura abaixo de si, que cresce aos poucos totalizando três turnos canalizando. No terceiro turno uma boca de vulcão se expõe, cuspindo lava pelo solo que toma a área completa. A lava possuí o dobro do PM do mago e derrete equipamentos ao toque.",
            custo_mana: 10000,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 6,
            nivel_desbloqueio: 19,
            passiva: false,
            alcance: "100",
            tamanho: "5 metros",
            custo_mana_turno: 10000
        },
        {
            nome: "Efeito Fênix",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Sacrifica vida para explosão avassaladora de 5x PM.",
            descricao_completa: "Sacrifica a vida do mago para criar uma explosão avassaladora, ressurgindo em cinzas após a explosão. Esta técnica causa 5x o PM, e ficará impedido de realizar qualquer função por duas semanas. Isso inclui treinar.",
            custo_mana: 999999,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 999,
            nivel_desbloqueio: 22,
            passiva: false,
            alcance: "30 metros",
            tamanho: "30 metros"
        },
        {
            nome: "Rajadas ígneas",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Dispara 20 rajadas de fogo que explodem.",
            descricao_completa: "Das pontas dos dedos o mago dispara 20 rajadas de fogo que seguem em linha reta e explodem [1m]. As rajadas não causam queimaduras na área mas incendeiem o alvo.",
            custo_mana: 2000,
            custo_qi: 20480,
            custo_qi_formatado: "20480 Qi",
            cooldown: 2,
            nivel_desbloqueio: 24,
            passiva: false,
            alcance: "30m"
        },
        {
            nome: "Dança do Fogo",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Dança que cria ondas de fogo ao redor.",
            descricao_completa: "Executa uma dança fluida que cria ondas de fogo ao redor, queimando inimigos próximos durante a performance. Em movimentos ágeis, levando seu corpo como uma extensão das chamas, o usuário consegue lançar rajadas de fogo pelos pés, mão, cotovelo e boca.",
            custo_mana: 750,
            custo_qi: 40960,
            custo_qi_formatado: "40960 Qi",
            cooldown: 1,
            nivel_desbloqueio: 26,
            passiva: false,
            alcance: "15m"
        },
        {
            nome: "Lâmina Incandescente",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Forja lâmina de fogo que causa dano extra.",
            descricao_completa: "Forja uma lâmina de fogo na mão do mago, aumentando seu poder de ataque em combate corpo a corpo. [+10% em PM].",
            custo_mana: 1200,
            custo_qi: 81920,
            custo_qi_formatado: "81920 Qi",
            cooldown: 2,
            nivel_desbloqueio: 28,
            passiva: false,
            alcance: "Toque",
            tamanho: "1 metro"
        },
        {
            nome: "Nevoeiro Flamejante",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria nevoeiro abrasador que causa queimaduras.",
            descricao_completa: "Cria um nevoeiro denso e abrasador, prejudicando a visibilidade dos inimigos e causando queimaduras leves pelo corpo caso fique mais de dois turnos dentro do nevoeiro.",
            custo_mana: 2700,
            custo_qi: 163840,
            custo_qi_formatado: "163840 Qi",
            cooldown: 4,
            nivel_desbloqueio: 30,
            passiva: false,
            alcance: "20 metros",
            tamanho: "8 metros"
        },
        {
            nome: "Arauto do Fogo (Passivo)",
            classe: "Mago de Fogo",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Altera coloração e essência do fogo com efeitos únicos.",
            descricao_completa: "O mago após obter 6 ataques flamejantes pode optar por dar uma coloração ao seu fogo, a coloração se baseia nos fogos existentes. Vermelho, azul, verde, branco, laranja, roxo, preto e manter amarelo. Cada cor possui seus respectivos buffs e suas habilidades vão passar a ser dessa coloração. Verde: chama química, queimadura stacka até 60%. Azul: +35% PM e queimadura 15%. Roxo: tóxico, envenenamento + redução 15% atributos. Preto: aura preta, +15% dano e recupera 5% mana por queimadura. Branco: +10% PM e -10% custo MP. Vermelho: combustão instantânea, ignora 20% resistência. Laranja: -20% custo MP, pode canalizar para dobrar dano. Amarelo: propagação, pode usar fogo existente no cenário.",
            custo_mana: 0,
            custo_qi: 500000,
            custo_qi_formatado: "500000 Qi",
            cooldown: 0,
            nivel_desbloqueio: 35,
            passiva: true
        }
    ]
};

module.exports = magoFogo;