const ranger = {
    nome: "Ranger",
    descricao_classe: "Especialista em combate à distância, domina diversas armas como arcos, facas, pistolas, escopetas, fuzis e snipers. Possui alta mobilidade e precisão.",
    categoria: "Classe",
    formas_jogo: ["Arco", "Faca", "Pistola", "Escopeta", "Fuzil", "Sniper"],
    tecnicaInicial: {
        nome: "Disparo Básico",
        classe: "Ranger",
        categoria: "Inicial",
        tipo: "Física",
        descricao: "Disparo básico com arma de longo alcance.",
        descricao_completa: "Disparo fundamental que serve de base para todas as técnicas de ranger. O dano e alcance variam conforme a forma de jogo escolhida.",
        custo_mana: 100,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 1,
        nivel_desbloqueio: 1,
        passiva: false
    },
    tecnicas: [
        {
            nome: "Precisão Arcana",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Aumenta precisão e dano com arco.",
            descricao_completa: "Com um olho treinado e mão firme, você aprende a calcular distâncias, vento e movimento do alvo. Seus ataques à distância recebem um bônus de penetração e causa +15% de dano adicional. O alcance efetivo do arco é ampliado.",
            custo_mana: 0,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 0,
            nivel_desbloqueio: 3,
            passiva: true
        },
        {
            nome: "Chuva de Flechas",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Dispara múltiplas flechas em área.",
            descricao_completa: "O usuário dispara uma chuva de flechas que cai em uma área de 5m de raio, causando dano a todos os inimigos dentro dela. Cada flecha causa dano baseado no ataque do usuário.",
            custo_mana: 800,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 3,
            nivel_desbloqueio: 5,
            passiva: false,
            alcance: "30 metros",
            tamanho: "5 metros (raio)"
        },
        {
            nome: "Flecha Explosiva",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Flecha que explode ao atingir o alvo.",
            descricao_completa: "O usuário imbuí uma flecha com mana, fazendo com que ela exploda ao impactar. A explosão causa dano em área de 3m de raio e adiciona +20% de dano baseado no PM.",
            custo_mana: 1200,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 4,
            nivel_desbloqueio: 7,
            passiva: false,
            alcance: "40 metros",
            tamanho: "3 metros (raio)"
        },
        {
            nome: "Mira Precisão",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Aumenta precisão e ignora parte da defesa.",
            descricao_completa: "O usuário canaliza sua energia em sua arma, aumentando sua precisão mortal. Próximo ataque ignora 30% da defesa do alvo e causa +25% de dano crítico.",
            custo_mana: 500,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 2,
            nivel_desbloqueio: 9,
            passiva: false
        },
        {
            nome: "Tiro de Eficácia",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Tiro que causa dano massivo em alvo único.",
            descricao_completa: "O usuário concentra toda sua energia em um único tiro, causando dano massivo ao primeiro alvo atingido. Se o alvo for atingido em ponto vital (cabeça, coração), o dano é dobrado.",
            custo_mana: 2000,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 5,
            nivel_desbloqueio: 11,
            passiva: false,
            alcance: "100 metros"
        },
        {
            nome: "Disparo Múltiplo",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Dispara 5 projéteis simultaneamente.",
            descricao_completa: "O usuário dispara 5 projéteis mágicos simultaneamente em diferentes direções ou alvos. Cada projétil causa 60% do dano normal, mas todos juntos podem causar dano massivo em área.",
            custo_mana: 1500,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 4,
            nivel_desbloqueio: 13,
            passiva: false,
            alcance: "50 metros"
        },
        {
            nome: "Arco-Estrela",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Cria estrela de energia que percorre área.",
            descricao_completa: "O usuário canaliza energia em seu arco, criando uma estrela de energia que percorre uma área de 10m de raio, causando dano contínuo a todos os inimigos dentro dela por 3 turnos.",
            custo_mana: 3000,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 6,
            nivel_desbloqueio: 15,
            passiva: false,
            alcance: "40 metros",
            tamanho: "10 metros (raio)",
            duracao: "3 turnos"
        },
        {
            nome: "Visão de Águia",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Aumenta alcance de visão e detecta inimigos.",
            descricao_completa: "O usuário ativa sua visão aguçada, conseguindo enxergar a longas distâncias e detectar inimigos ocultos ou invisíveis dentro de um raio de 100m. A visão é ampliada em 200%.",
            custo_mana: 800,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 3,
            nivel_desbloqueio: 18,
            passiva: false,
            alcance: "100 metros",
            duracao: "5 turnos"
        },
        {
            nome: "Tiro Preciso",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Física",
            descricao: "Disparo que ignora 30% da defesa do alvo.",
            descricao_completa: "O usuário concentra-se em um ponto vital do alvo, disparando uma flecha que ignora 30% da defesa do inimigo. O dano é aumentado em +20% se o alvo estiver a mais de 20 metros de distância.",
            custo_mana: 1500,
            custo_qi: 50000,
            custo_qi_formatado: "50000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 22,
            passiva: false,
            alcance: "100 metros"
        },
        {
            nome: "Flecha Venenosa",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Mágica",
            descricao: "Flecha que aplica veneno no alvo.",
            descricao_completa: "O usuário imbui sua flecha com veneno, causando dano adicional de 5% do PM por turno durante 3 turnos. O veneno também reduz a velocidade do alvo em 15%.",
            custo_mana: 2000,
            custo_qi: 100000,
            custo_qi_formatado: "100000 Qi",
            cooldown: 4,
            nivel_desbloqueio: 25,
            passiva: false,
            alcance: "60 metros",
            duracao: "3 turnos"
        },
        {
            nome: "Chuva de Facas",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Física",
            descricao: "Arremessa múltiplas facas em área.",
            descricao_completa: "O usuário arremessa 10 facas simultaneamente em diferentes direções, cobrindo uma área de 5m de raio. Cada faca causa dano físico e tem 50% de chance de acerto crítico.",
            custo_mana: 1800,
            custo_qi: 250000,
            custo_qi_formatado: "250000 Qi",
            cooldown: 3,
            nivel_desbloqueio: 28,
            passiva: false,
            alcance: "15 metros",
            tamanho: "5 metros (raio)"
        },
        {
            nome: "Disparo Perfurante",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Física",
            descricao: "Tiro que atravessa múltiplos inimigos.",
            descricao_completa: "O usuário dispara um projétil de alta velocidade que perfura até 3 inimigos em linha reta. Cada alvo após o primeiro recebe 20% a menos de dano. O projétil ignora 40% da resistência dos alvos.",
            custo_mana: 2500,
            custo_qi: 500000,
            custo_qi_formatado: "500000 Qi",
            cooldown: 5,
            nivel_desbloqueio: 30,
            passiva: false,
            alcance: "80 metros"
        },
        {
            nome: "Mira Estável",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Aumenta dano crítico em 50%.",
            descricao_completa: "O usuário desenvolve uma mira extremamente estável, conseguindo acertar pontos vitais com precisão cirúrgica. Aumenta a chance de acerto crítico em 25% e o dano crítico em 50%.",
            custo_mana: 0,
            custo_qi: 1000000,
            custo_qi_formatado: "1000000 Qi",
            cooldown: 0,
            nivel_desbloqueio: 33,
            passiva: true
        },
        {
            nome: "Rajada de Balas",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Física",
            descricao: "Dispara 15 balas em rápida sequência.",
            descricao_completa: "O usuário dispara 15 balas em rápida sequência contra um único alvo. Cada bala causa dano reduzido, mas o total pode ser devastador. A precisão aumenta a cada bala, concedendo +5% de chance de crítico por acerto consecutivo.",
            custo_mana: 3000,
            custo_qi: 2500000,
            custo_qi_formatado: "2500000 Qi",
            cooldown: 4,
            nivel_desbloqueio: 35,
            passiva: false,
            alcance: "50 metros"
        },
        {
            nome: "Tiro de Longo Alcance",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Física",
            descricao: "Disparo preciso a até 300 metros.",
            descricao_completa: "O usuário prepara um tiro de extrema precisão, capaz de atingir alvos a até 300 metros de distância. O dano é baseado na soma do Ataque e PM do usuário. Se o alvo estiver a mais de 150 metros, o dano é dobrado.",
            custo_mana: 4000,
            custo_qi: 5000000,
            custo_qi_formatado: "5000000 Qi",
            cooldown: 6,
            nivel_desbloqueio: 38,
            passiva: false,
            alcance: "300 metros"
        },
        {
            nome: "Olho do Falcão",
            classe: "Ranger",
            categoria: "Inicial",
            tipo: "Suporte",
            descricao: "Detecta fraquezas do alvo aumentando dano.",
            descricao_completa: "O usuário ativa sua visão especial, identificando pontos fracos no corpo do alvo. Durante 3 turnos, todos os ataques do usuário causam +35% de dano e ignoram 15% da resistência do alvo.",
            custo_mana: 3500,
            custo_qi: 10000000,
            custo_qi_formatado: "10000000 Qi",
            cooldown: 5,
            nivel_desbloqueio: 40,
            passiva: false,
            duracao: "3 turnos"
        }
    ]
};

module.exports = ranger;