const classe = {
    "nome": "Ranger",
    "descricao_classe": "Especialista em leitura de campo, rastreamento e posicionamento; suas técnicas gerais independem da arma equipada.",
    "categoria": "Classe",
    "tecnicaInicial": {
        "nome": "Leitura de Campo",
        "categoria": "Inicial",
        "tipo": "Suporte",
        "descricao": "Analisa terreno e linhas de visão; por 2 turnos recebe +10% Sentidos para rastrear ameaças e rotas.",
        "descricao_completa": "Analisa terreno e linhas de visão; por 2 turnos recebe +10% Sentidos para rastrear ameaças e rotas.",
        "custo_mana": 600,
        "custo_qi": 10,
        "custo_qi_formatado": "10 de Maestria",
        "custo_maestria": 10,
        "custo_maestria_formatado": "10 de Maestria",
        "cooldown": 2,
        "nivel_desbloqueio": 1,
        "passiva": false,
        "classe": "Ranger"
    },
    "tecnicas": [
        {
            "nome": "Passo do Batedor",
            "categoria": "Inicial",
            "tipo": "Movimentação",
            "descricao": "Reposiciona-se até 6m sem penalidade de terreno leve e recebe +10% Agilidade durante o deslocamento.",
            "descricao_completa": "Reposiciona-se até 6m sem penalidade de terreno leve e recebe +10% Agilidade durante o deslocamento.",
            "custo_mana": 800,
            "custo_qi": 20,
            "custo_qi_formatado": "20 de Maestria",
            "custo_maestria": 20,
            "custo_maestria_formatado": "20 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 5,
            "passiva": false,
            "alcance": "6M",
            "classe": "Ranger"
        },
        {
            "nome": "Marca do Caçador",
            "categoria": "Inicial",
            "tipo": "Suporte",
            "descricao": "Marca um alvo visível por 3 turnos; o Ranger recebe +10% precisão narrativa e Sentidos contra ele.",
            "descricao_completa": "Marca um alvo visível por 3 turnos; o Ranger recebe +10% precisão narrativa e Sentidos contra ele.",
            "custo_mana": 1000,
            "custo_qi": 40,
            "custo_qi_formatado": "40 de Maestria",
            "custo_maestria": 40,
            "custo_maestria_formatado": "40 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 10,
            "passiva": false,
            "alcance": "30M",
            "classe": "Ranger"
        },
        {
            "nome": "Cobertura Instintiva",
            "categoria": "Inicial",
            "tipo": "Defesa",
            "descricao": "Ao ser alvo de um ataque à distância, pode reduzir o dano em 20% se houver cobertura alcançável em até 3m.",
            "descricao_completa": "Ao ser alvo de um ataque à distância, pode reduzir o dano em 20% se houver cobertura alcançável em até 3m.",
            "custo_mana": 900,
            "custo_qi": 70,
            "custo_qi_formatado": "70 de Maestria",
            "custo_maestria": 70,
            "custo_maestria_formatado": "70 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 15,
            "passiva": false,
            "classe": "Ranger"
        },
        {
            "nome": "Rastreamento Persistente",
            "categoria": "Inicial",
            "tipo": "Passiva",
            "descricao": "Passiva: rastros recentes, mana residual e mudanças no ambiente são 20% mais fáceis de perceber.",
            "descricao_completa": "Passiva: rastros recentes, mana residual e mudanças no ambiente são 20% mais fáceis de perceber.",
            "custo_mana": 0,
            "custo_qi": 110,
            "custo_qi_formatado": "110 de Maestria",
            "custo_maestria": 110,
            "custo_maestria_formatado": "110 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 20,
            "passiva": true,
            "classe": "Ranger"
        },
        {
            "nome": "Janela de Oportunidade",
            "categoria": "Inicial",
            "tipo": "Física",
            "descricao": "Depois que um aliado atingir o alvo, o próximo ataque do Ranger contra ele causa +10% de dano se ocorrer no mesmo turno.",
            "descricao_completa": "Depois que um aliado atingir o alvo, o próximo ataque do Ranger contra ele causa +10% de dano se ocorrer no mesmo turno.",
            "custo_mana": 900,
            "custo_qi": 160,
            "custo_qi_formatado": "160 de Maestria",
            "custo_maestria": 160,
            "custo_maestria_formatado": "160 de Maestria",
            "cooldown": 2,
            "nivel_desbloqueio": 25,
            "passiva": false,
            "classe": "Ranger"
        },
        {
            "nome": "Reposicionamento Tático",
            "categoria": "Inicial",
            "tipo": "Movimentação",
            "descricao": "Troca de posição com um aliado voluntário a até 5m ou move-se para uma posição livre equivalente.",
            "descricao_completa": "Troca de posição com um aliado voluntário a até 5m ou move-se para uma posição livre equivalente.",
            "custo_mana": 1200,
            "custo_qi": 230,
            "custo_qi_formatado": "230 de Maestria",
            "custo_maestria": 230,
            "custo_maestria_formatado": "230 de Maestria",
            "cooldown": 3,
            "nivel_desbloqueio": 30,
            "passiva": false,
            "alcance": "5M",
            "classe": "Ranger"
        },
        {
            "nome": "Olho do Explorador",
            "categoria": "Inicial",
            "tipo": "Suporte",
            "descricao": "Por 2 turnos, ignora até 15% de penalidades de visão causadas por distância, neblina, fumaça ou baixa luminosidade.",
            "descricao_completa": "Por 2 turnos, ignora até 15% de penalidades de visão causadas por distância, neblina, fumaça ou baixa luminosidade.",
            "custo_mana": 1400,
            "custo_qi": 320,
            "custo_qi_formatado": "320 de Maestria",
            "custo_maestria": 320,
            "custo_maestria_formatado": "320 de Maestria",
            "cooldown": 4,
            "nivel_desbloqueio": 35,
            "passiva": false,
            "classe": "Ranger"
        },
        {
            "nome": "Zona de Caça",
            "categoria": "Inicial",
            "tipo": "Buff",
            "descricao": "Delimita uma área de 12m por 3 turnos; dentro dela recebe +10% Agilidade e Sentidos enquanto perseguir um alvo marcado.",
            "descricao_completa": "Delimita uma área de 12m por 3 turnos; dentro dela recebe +10% Agilidade e Sentidos enquanto perseguir um alvo marcado.",
            "custo_mana": 2200,
            "custo_qi": 450,
            "custo_qi_formatado": "450 de Maestria",
            "custo_maestria": 450,
            "custo_maestria_formatado": "450 de Maestria",
            "cooldown": 5,
            "nivel_desbloqueio": 40,
            "passiva": false,
            "alcance": "12M",
            "classe": "Ranger"
        },
        {
            "nome": "Sobrevivente de Fronteira",
            "categoria": "Inicial",
            "tipo": "Passiva",
            "descricao": "Uma vez por luta, ao cair abaixo de 25% de vida, remove uma penalidade de movimento e recebe +15% Resistência por 2 turnos.",
            "descricao_completa": "Uma vez por luta, ao cair abaixo de 25% de vida, remove uma penalidade de movimento e recebe +15% Resistência por 2 turnos.",
            "custo_mana": 0,
            "custo_qi": 650,
            "custo_qi_formatado": "650 de Maestria",
            "custo_maestria": 650,
            "custo_maestria_formatado": "650 de Maestria",
            "cooldown": 0,
            "nivel_desbloqueio": 45,
            "passiva": true,
            "classe": "Ranger"
        }
    ]
};

module.exports = classe;
