const tanker = {
    nome: "Tanker",
    descricao_classe: "O Tanker é especializado em defesa e resistência, capaz de absorver enormes quantidades de dano e proteger aliados. Possui escudos, muralhas e habilidades de provocação.",
    categoria: "Classe",
    tecnicaInicial: {
        nome: "Escudo Imponente",
        classe: "Tanker",
        categoria: "Inicial",
        tipo: "Defesa",
        descricao: "Invoca escudo circular de mana no antebraço.",
        descricao_completa: "Invoca um escudo circular feito de mana com 60 cm em seu antebraço. A resistência do escudo é igual a 80% da resistência do usuário. Enquanto essa técnica estiver ativa, qualquer técnica que tenha o pré-requisito de estar usando um escudo pode ser habilitada. O escudo de mana, por estar equipado no antebraço, não ocupa espaço de uma arma, porém não soma nenhum atributo ao usuário.",
        custo_mana: 1700,
        custo_qi: 10,
        custo_qi_formatado: "10 Qi",
        cooldown: 1,
        nivel_desbloqueio: 1,
        passiva: false
    },
    tecnicas: [
        {
            nome: "Escudo do Guardião",
            classe: "Tanker",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Arremessa escudo para defender aliado a 30m.",
            descricao_completa: "Consegue arremessar qualquer escudo que esteja usando em direção a um aliado que esteja dentro do raio de 30m² para defendê-lo de um ataque. Após 1 turno, o escudo retorna para o usuário.",
            custo_mana: 500,
            custo_qi: 20,
            custo_qi_formatado: "20 Qi",
            cooldown: 2,
            nivel_desbloqueio: 3,
            passiva: false
        },
        {
            nome: "Contra-ataque Vigoroso",
            classe: "Tanker",
            categoria: "Inicial",
            tipo: "Defesa/Combate",
            descricao: "Reflete 30% do dano recebido após bloquear.",
            descricao_completa: "Após bloquear um ataque inimigo utilizando um escudo, caso o adversário que realizou o ataque esteja dentro do raio de 2m², realiza um contra-ataque refletindo 30% do dano recebido em direção ao alvo.",
            custo_mana: 1000,
            custo_qi: 40,
            custo_qi_formatado: "40 Qi",
            cooldown: 3,
            nivel_desbloqueio: 5,
            passiva: false
        },
        {
            nome: "Guarda-costas",
            classe: "Tanker",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Absorve dano de aliado protegido a até 40m.",
            descricao_completa: "Realizando um pacto de mana com uma pessoa por vez, tornando-o seu protegido. Consegue absorver o dano recebido pelo seu protegido desde que ele esteja a pelo menos 40m² do usuário da técnica. Recarga de 2 turnos.",
            custo_mana: 1000,
            custo_qi: 80,
            custo_qi_formatado: "80 Qi",
            cooldown: 2,
            nivel_desbloqueio: 7,
            passiva: false
        },
        {
            nome: "Intransponível (Passiva)",
            classe: "Tanker",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Não pode ser empurrado ou puxado por técnicas.",
            descricao_completa: "Usando de sua resistência, ganha a capacidade de não ser puxado ou empurrado. Logo, não é possível mover seu corpo através de técnicas ou ataques que não ultrapassem sua resistência.",
            custo_mana: 0,
            custo_qi: 160,
            custo_qi_formatado: "160 Qi",
            cooldown: 0,
            nivel_desbloqueio: 9,
            passiva: true
        },
        {
            nome: "Aura do Defensor",
            classe: "Tanker",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Reduz dano de aliados em 25% em área 5m².",
            descricao_completa: "Emite uma aura protetora ao redor do usuário, cobrindo 5m², que reduz o dano recebido por todos os aliados próximos em 25%.",
            custo_mana: 1500,
            custo_qi: 320,
            custo_qi_formatado: "320 Qi",
            cooldown: 3,
            nivel_desbloqueio: 11,
            passiva: false
        },
        {
            nome: "Golpe de Escudo",
            classe: "Tanker",
            categoria: "Inicial",
            tipo: "Combate",
            descricao: "Causa dano com o escudo baseado na resistência.",
            descricao_completa: "Consegue arremessar ou bater com o escudo, causando dano equivalente a 80% de sua resistência. A área de impacto é de 1m² para cada 5 pontos em força.",
            custo_mana: 1500,
            custo_qi: 640,
            custo_qi_formatado: "640 Qi",
            cooldown: 2,
            nivel_desbloqueio: 13,
            passiva: false
        },
        {
            nome: "Fortaleza de Pedra",
            classe: "Tanker",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Transforma pele em pedra dobrando resistência física.",
            descricao_completa: "Transforma temporariamente a pele do usuário em pedra por 1 turno, forçando-o a ficar imóvel enquanto o efeito durar. Aumenta em 100% a resistência a danos físicos. Tem um turnos de recarga.",
            custo_mana: 1000,
            custo_qi: 1280,
            custo_qi_formatado: "1280 Qi",
            cooldown: 1,
            nivel_desbloqueio: 15,
            passiva: false
        },
        {
            nome: "Pele de Golias",
            classe: "Tanker",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Enrijece partes do corpo aumentando resistência.",
            descricao_completa: "Consegue enrijecer partes do corpo em até 30cm, aumentando a resistência da parte em 30%. Golpes realizados com partes enrijecidas causam 15% a mais de dano, baseado na resistência do usuário.",
            custo_mana: 750,
            custo_qi: 2560,
            custo_qi_formatado: "2560 Qi",
            cooldown: 2,
            nivel_desbloqueio: 18,
            passiva: false,
            custo_mana_turno: 750
        },
        {
            nome: "Colosso",
            classe: "Tanker",
            categoria: "Inicial",
            tipo: "Transformação",
            descricao: "Aumenta tamanho do corpo até 10m com buffs.",
            descricao_completa: "O usuário consegue aumentar o tamanho de seu corpo, aumentando sua resistência e força e diminuindo sua agilidade no processo. Enquanto transformado, o usuário pode manter 3 estágios de tamanho: 3 metros de altura, 5 metros e 10 metros, cada um com seu respectivo gasto e bônus. Ao escolher essa técnica, o usuário libera apenas o primeiro estágio; para alcançar os outros dois, precisa gastar mais um slot de técnica. Enquanto transformado, o usuário triplica o tamanho de técnicas como Pele de Golias, Escudo do Guardião e Aura do Defensor e seus efeitos também são triplicados.",
            custo_mana: 1000,
            custo_qi: 5120,
            custo_qi_formatado: "5120 Qi",
            cooldown: 5,
            nivel_desbloqueio: 20,
            passiva: false,
            custo_mana_turno: 250,
            estagios: ["3m (30% FOR/RES)", "5m (50% FOR/RES)", "10m (100% FOR/RES)"]
        },
        {
            nome: "Resistente (Passivo)",
            classe: "Tanker",
            categoria: "Inicial",
            tipo: "Passiva",
            descricao: "Venenos demoram mais para fazer efeito.",
            descricao_completa: "Venenos demoram a fazer efeito no corpo do usuário, demorando 1 turno para surtir efeito. A cada 50 de resistência, o usuário ganha mais um turno de resistência. Caso o veneno ou o adversário que envenenou o alvo seja de um Rank inferior ao do usuário, ganha mais 1 turno de resistência para cada Rank acima do adversário.",
            custo_mana: 0,
            custo_qi: 10240,
            custo_qi_formatado: "10240 Qi",
            cooldown: 0,
            nivel_desbloqueio: 23,
            passiva: true
        },
        {
            nome: "Duro na Queda",
            classe: "Tanker",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Resiste a dano letal sacrificando 50% de resistência.",
            descricao_completa: "Uma vez por combate, consegue sacrificar 50% de sua resistência para resistir a um dano letal. Durante todo o combate, o usuário estará com uma penalidade de 50% da resistência total e poderá sacrificar os outros 50% para resistir a outro dano letal.",
            custo_mana: 2000,
            custo_qi: 20480,
            custo_qi_formatado: "20480 Qi",
            cooldown: 0,
            nivel_desbloqueio: 25,
            passiva: false
        },
        {
            nome: "Muralha Redirecionada",
            classe: "Tanker",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Atrai todos projéteis em 25m² e aumenta resistência.",
            descricao_completa: "Uma vez por combate, o usuário atrai todas as técnicas conjuradas, físicas ou mágicas, que sejam projéteis dentro do raio de 25m², para o seu corpo e aumenta sua resistência em 25%.",
            custo_mana: 1000,
            custo_qi: 40960,
            custo_qi_formatado: "40960 Qi",
            cooldown: 0,
            nivel_desbloqueio: 28,
            passiva: false
        },
        {
            nome: "Invencível",
            classe: "Tanker",
            categoria: "Inicial",
            tipo: "Defesa",
            descricao: "Ignora maldições e ilusões por até 3 turnos.",
            descricao_completa: "Usando sua alta resistência e força de vontade, consegue ignorar qualquer maldição ou ilusão aplicada a si por apenas um turno. Após o turno de uso, o usuário volta ao efeito da maldição ou ilusão caso ainda tenha turnos restantes. Pode prolongar o uso por até três turnos.",
            custo_mana: 2000,
            custo_qi: 81920,
            custo_qi_formatado: "81920 Qi",
            cooldown: 1,
            nivel_desbloqueio: 30,
            passiva: false,
            custo_mana_turno: 2000
        }
    ]
};

module.exports = tanker;