"use strict";
const crypto = require("crypto"); const { PROMPT } = require("./constants"); const { validateNarrative } = require("./validator");
class NarrativeDirector {
    constructor(options = {}) { this.store = options.store; this.context = options.context; this.client = options.client || null; this.authorize = options.authorize || (() => true); }
    async generate(actor, input = {}) { await this.authorize(actor, "CARDINAL_NARRATIVE_CREATE"); const context = await this.context.build({ ...input, actor }); const draft = this.compose(input, context, actor); if (context.external_research) { draft.external_research = context.external_research; draft.adaptation_mode = context.external_research.adaptation?.mode || "INSPIRED_ADAPTATION"; } const validation = validateNarrative(draft, context); if (!validation.valid) return { draft: { ...draft, validation }, context, blocked: true }; const saved = await this.store.saveDraft({ ...draft, validation }); return { draft: saved, context, prompt: this.prompt(saved, context) }; }
    compose(input, context, actor) { const title = input.title || `${label(input.template || "SCENE_OPENING")} — ${context.location || "Mundo"}`; const factual = context.lore.slice(0, 4).map(row => row.entity).filter(Boolean); const body = input.body || `${opening(context, input)}\n\n${input.objective ? `Objetivo narrativo: ${input.objective}.` : "Uma situação ainda em desenvolvimento exige atenção."}\n\n${closing(context, input)}`; return { id: `nar_${crypto.randomUUID()}`, type: input.type || "scene", template: input.template || "SCENE_OPENING", title, summary: input.summary || `Narrativa em ${context.location || "local não definido"}.`, body, facts_used: factual, entities: [...new Set([...(input.entities || []), ...factual, ...(input.npc_id ? [input.npc_id] : [])])], secrets_used: [], mechanics: input.mechanics || {}, canon: input.canon || "DRAFT", status: input.status || "DRAFT", visibility: input.visibility || "ADMIN_ONLY", perspective: input.perspective || "NARRATOR", tone: input.tone || context.tone, location: context.location, npc_id: input.npc_id || null, event_id: input.event_id || null, presential: input.presential, created_by: actor };
    }
    prompt(draft, context) { return `${PROMPT}\n\nFATOS ANCORADOS:\n${context.lore.map(row => `- [${row.trust}] ${row.entity}: ${row.content.slice(0, 500)}`).join("\n")}\n\nTAREFA: ${draft.template}; tom ${draft.tone}; perspectiva ${draft.perspective}.`; }
    async revise(actor, id, changes = {}) { await this.authorize(actor, "CARDINAL_NARRATIVE_EDIT"); const current = await this.store.draft(id); if (!current) throw Object.assign(new Error("Draft narrativo não encontrado."), { code: "NARRATIVE_NOT_FOUND" }); const next = { ...current, ...changes, mechanics: current.mechanics }; const validation = validateNarrative(next, { location: current.location, npcs: current.npc_id ? [{}] : [] }, { previousMechanics: current.mechanics }); if (!validation.valid) return { draft: next, validation, blocked: true }; return { draft: await this.store.revise(id, { ...next, validation }, actor), validation }; }
    async promote(actor, id, status) { await this.authorize(actor, status === "PUBLISHED" ? "CARDINAL_NARRATIVE_APPROVE" : "CARDINAL_NARRATIVE_EDIT"); const current = await this.store.draft(id); if (!current) throw Object.assign(new Error("Draft narrativo não encontrado."), { code: "NARRATIVE_NOT_FOUND" }); if (!(["REVIEW", "APPROVED", "PUBLISHED"].includes(status))) throw Object.assign(new Error("Promoção narrativa inválida."), { code: "NARRATIVE_PROMOTION_INVALID" }); if (status === "PUBLISHED" && current.canon !== "CANON") throw Object.assign(new Error("Somente conteúdo CANON aprovado pode ser publicado."), { code: "NARRATIVE_CANON_REQUIRED" }); return this.store.revise(id, { status }, actor); }
    async npcBrief(actor, input) { await this.authorize(actor, "CARDINAL_NARRATIVE_CREATE"); const context = await this.context.build({ ...input, actor, visibility: "NPC_KNOWN" }); const npc = context.npcs[0]; if (!npc) throw Object.assign(new Error("NPC sem perfil oficial."), { code: "NARRATIVE_NPC_UNKNOWN" }); return { npc_id: npc.id, goal: input.objective || "Conduzir a cena sem quebrar a personalidade.", context: `Local: ${context.location || "não definido"}; fase: ${context.world_phase}.`, facts_known: context.lore.filter(row => row.visibility !== "SECRET_LORE").map(row => row.entity), facts_hidden: [], tone: input.tone || context.tone, personality_preserved: true };
    }
}
function label(value) { return String(value).replace(/_/g, " "); } function opening(context, input) { return `Em ${context.location || "um ponto ainda não confirmado"}, sob a fase ${context.world_phase}, ${input.tone === "HORROR" ? "o silêncio pesa antes de qualquer resposta" : "a situação se apresenta sem alterar os fatos conhecidos"}.`; } function closing(_context, input) { return input.template === "EVENT_ANNOUNCEMENT" ? "Acompanhe os canais oficiais para alterações confirmadas." : "A próxima decisão permanece nas mãos dos participantes."; }
module.exports = { NarrativeDirector };
