"use strict";
const fs = require("fs"), path = require("path"), crypto = require("crypto"), sqlite3 = require("sqlite3").verbose();
class NarrativeStore {
    constructor(file) { this.file = file; fs.mkdirSync(path.dirname(file), { recursive: true }); this.db = new sqlite3.Database(file); }
    run(sql, params = []) { return new Promise((resolve, reject) => this.db.run(sql, params, function(error) { error ? reject(error) : resolve({ lastID: this.lastID, changes: this.changes }); })); }
    get(sql, params = []) { return new Promise((resolve, reject) => this.db.get(sql, params, (error, row) => error ? reject(error) : resolve(row || null))); }
    all(sql, params = []) { return new Promise((resolve, reject) => this.db.all(sql, params, (error, rows) => error ? reject(error) : resolve(rows || []))); }
    exec(sql) { return new Promise((resolve, reject) => this.db.exec(sql, error => error ? reject(error) : resolve())); }
    close() { return new Promise((resolve, reject) => this.db.close(error => error ? reject(error) : resolve())); }
    async init() { await this.exec("PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS narrative_drafts(id TEXT PRIMARY KEY,type TEXT,title TEXT,status TEXT,canon TEXT,visibility TEXT,perspective TEXT,tone TEXT,payload_json TEXT,mechanics_json TEXT,created_by TEXT,created_at TEXT,updated_at TEXT);CREATE TABLE IF NOT EXISTS narrative_versions(id TEXT PRIMARY KEY,draft_id TEXT,version INTEGER,payload_json TEXT,created_at TEXT,created_by TEXT);CREATE TABLE IF NOT EXISTS narrative_arcs(id TEXT PRIMARY KEY,title TEXT,status TEXT,payload_json TEXT,created_at TEXT,updated_at TEXT);CREATE TABLE IF NOT EXISTS narrative_chronicle(id TEXT PRIMARY KEY,title TEXT,body TEXT,source_json TEXT,created_at TEXT);CREATE TABLE IF NOT EXISTS narrative_secrets(id TEXT PRIMARY KEY,label TEXT,visibility TEXT,who_knows_json TEXT,reveal_condition TEXT,status TEXT,payload_json TEXT,created_at TEXT);"); }
    async saveDraft(draft) { const id = draft.id || `nar_${crypto.randomUUID()}`, now = new Date().toISOString(), payload = JSON.stringify(draft); await this.run("INSERT INTO narrative_drafts VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)", [id, draft.type, draft.title, draft.status, draft.canon, draft.visibility, draft.perspective, draft.tone, payload, JSON.stringify(draft.mechanics || {}), draft.created_by || "CARDINAL", now, now]); await this.run("INSERT INTO narrative_versions VALUES(?,?,?,?,?,?)", [`narv_${crypto.randomUUID()}`, id, 1, payload, now, draft.created_by || "CARDINAL"]); return { ...draft, id, version: 1, created_at: now }; }
    async draft(id) { const row = await this.get("SELECT * FROM narrative_drafts WHERE id=?", [id]); return row ? { ...JSON.parse(row.payload_json), id: row.id, version: (await this.get("SELECT MAX(version) AS value FROM narrative_versions WHERE draft_id=?", [id]))?.value || 1 } : null; }
    async revise(id, payload, actor) { const current = await this.draft(id); if (!current) return null; const version = current.version + 1, now = new Date().toISOString(), next = { ...current, ...payload, id, version, updated_at: now }; await this.run("UPDATE narrative_drafts SET title=?,status=?,canon=?,visibility=?,perspective=?,tone=?,payload_json=?,mechanics_json=?,updated_at=? WHERE id=?", [next.title,next.status,next.canon,next.visibility,next.perspective,next.tone,JSON.stringify(next),JSON.stringify(next.mechanics || {}),now,id]); await this.run("INSERT INTO narrative_versions VALUES(?,?,?,?,?,?)", [`narv_${crypto.randomUUID()}`,id,version,JSON.stringify(next),now,actor]); return next; }
    async list(filters = {}) { const rows = await this.all("SELECT * FROM narrative_drafts ORDER BY updated_at DESC LIMIT ?", [Math.min(Number(filters.limit) || 50, 100)]); return rows.map(row => JSON.parse(row.payload_json)).filter(row => !filters.status || row.status === filters.status); }
    async saveArc(arc) { const id = arc.id || `arc_${crypto.randomUUID()}`, now = new Date().toISOString(), payload = JSON.stringify({ ...arc, id, status: arc.status || "DRAFT" }); await this.run("INSERT INTO narrative_arcs VALUES(?,?,?,?,?,?)", [id, arc.title, arc.status || "DRAFT", payload, now, now]); return JSON.parse(payload); }
    async arcs() { const rows = await this.all("SELECT payload_json FROM narrative_arcs ORDER BY updated_at DESC"); return rows.map(row => JSON.parse(row.payload_json)); }
    async addChronicle(entry) { const id = entry.id || `chronicle_${crypto.randomUUID()}`, now = new Date().toISOString(); await this.run("INSERT INTO narrative_chronicle VALUES(?,?,?,?,?)", [id, entry.title, entry.body, JSON.stringify(entry.sources || []), now]); return { ...entry, id, created_at: now }; }
    async chronicle(limit = 50) { const rows = await this.all("SELECT * FROM narrative_chronicle ORDER BY created_at DESC LIMIT ?", [Math.min(Number(limit), 100)]); return rows.map(row => ({ id: row.id, title: row.title, body: row.body, sources: JSON.parse(row.source_json), created_at: row.created_at })); }
    async saveSecret(secret) { const id = secret.id || `secret_${crypto.randomUUID()}`, now = new Date().toISOString(); await this.run("INSERT INTO narrative_secrets VALUES(?,?,?,?,?,?,?,?)", [id,secret.label,secret.visibility || "SECRET_LORE",JSON.stringify(secret.who_knows || []),secret.reveal_condition || null,secret.status || "HIDDEN",JSON.stringify(secret),now]); return { ...secret, id, created_at: now }; }
}
module.exports = { NarrativeStore };
