"use strict";
const fs = require("fs/promises"); const path = require("path"); const { spawn } = require("child_process"); const { DeveloperError, CODES } = require("../errors");
const ALLOWED_EXECUTABLES = Object.freeze(["git", "npm", "npx", "node", "python", "pytest", "pnpm"]);
const BLOCKED = Object.freeze(["powershell", "cmd", "bash", "sh", "curl", "wget", "ssh", "scp", "reg", "shutdown", "format"]);
const SAFE_SCRIPTS = Object.freeze({ cardinal_test: { cwd: ".", command: "npm", args: ["run", "cardinal:test"], kind: "test" }, bot_test: { cwd: "apps/bot", command: "npm", args: ["test"], kind: "test" }, site_lint: { cwd: "apps/site", command: "npm", args: ["run", "lint"], kind: "lint" }, site_build: { cwd: "apps/site", command: "npm", args: ["run", "build"], kind: "build" } });
class SafeRunner {
    constructor(root) { this.root = root; }
    async detect() { const read = async file => { try { return JSON.parse(await fs.readFile(path.join(this.root, file), "utf8")).scripts || {}; } catch { return {}; } }; return { root: await read("package.json"), bot: await read("apps/bot/package.json"), site: await read("apps/site/package.json"), tests: ["node:test", "bot npm test"], lint: (await read("apps/site/package.json")).lint ? "ESLint" : null, build: (await read("apps/site/package.json")).build ? "Next.js" : null }; }
    run(tool, options = {}) { const spec = SAFE_SCRIPTS[tool]; if (!spec) throw new DeveloperError(CODES.COMMAND_BLOCKED, `Runner não permitido: ${tool}.`); return new Promise(resolve => { let executable = spec.command, args = spec.args; if (process.platform === "win32" && spec.command === "npm") { executable = process.execPath; args = [path.join(path.dirname(process.execPath), "node_modules/npm/bin/npm-cli.js"), ...spec.args]; } const child = spawn(executable, args, { cwd: path.join(this.root, spec.cwd), shell: false, windowsHide: true, env: { ...process.env, CI: "1" } }); let stdout = "", stderr = "", settled = false; const finish = (code, error) => { if (settled) return; settled = true; clearTimeout(timer); resolve({ tool, kind: spec.kind, command: [spec.command, ...spec.args].join(" "), success: code === 0, exitCode: code, output: (stdout + stderr + (error ? `\n${error.message}` : "")).slice(-30000) }); }; child.stdout.on("data", chunk => stdout += chunk); child.stderr.on("data", chunk => stderr += chunk); const timer = setTimeout(() => { child.kill(); finish(null, new Error("Tempo limite excedido.")); }, options.timeout || 120000); child.on("error", error => finish(null, error)); child.on("close", code => finish(code)); }); }
}
module.exports = { SafeRunner, SAFE_SCRIPTS, ALLOWED_EXECUTABLES, BLOCKED };
