const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');const sqlite3=require('../node_modules/sqlite3');
async function fixture(t){const sqlite=new sqlite3.Database(':memory:');let tail=Promise.resolve();const db={run(sql,args=[]){return new Promise((resolve,reject)=>sqlite.run(sql,args,function(e){e?reject(e):resolve({changes:this.changes,lastID:this.lastID});}));},get(sql,args=[]){return new Promise((resolve,reject)=>sqlite.get(sql,args,(e,row)=>e?reject(e):resolve(row)));},all(sql,args=[]){return new Promise((resolve,reject)=>sqlite.all(sql,args,(e,rows)=>e?reject(e):resolve(rows)));},transaction(work){const task=tail.then(async()=>{await db.run('BEGIN');try{const r=await work(db);await db.run('COMMIT');return r;}catch(e){await db.run('ROLLBACK');throw e;}});tail=task.catch(()=>{});return task;}};t.after(()=>new Promise(resolve=>sqlite.close(resolve)));
for(const sql of ['CREATE TABLE jogadores(id INTEGER PRIMARY KEY,nome TEXT,won INTEGER)','INSERT INTO jogadores VALUES(1,"Player",1000000)','CREATE TABLE itens(id INTEGER PRIMARY KEY,nome TEXT,categoria TEXT,tier TEXT,preco INTEGER,valor INTEGER,descricao TEXT,arma INTEGER,armadura INTEGER,escudo INTEGER,acessorio INTEGER,consumivel INTEGER,forca_bonus INTEGER,resistencia_bonus INTEGER,velocidade_bonus INTEGER,sentidos_bonus INTEGER,inteligencia_bonus INTEGER,poder_magico_bonus INTEGER,efeito TEXT)','INSERT INTO itens(id,nome,categoria) VALUES(1,"Ferro","Material de Forja")','CREATE TABLE inventario_jogador(id INTEGER PRIMARY KEY,jogador_id INTEGER,item_id INTEGER,quantidade INTEGER,equipado INTEGER,item_inicial INTEGER)','INSERT INTO inventario_jogador VALUES(1,1,1,2,0,0)','CREATE TABLE forja_sessoes(id INTEGER PRIMARY KEY,jogador_id INTEGER,npc_nome TEXT,etapa TEXT,combinacao_resultado TEXT,custo INTEGER,item_resultado_id INTEGER)','CREATE TABLE npc_afinidade(jogador_id INTEGER,npc_nome TEXT,afinidade INTEGER,itens_forjados INTEGER,forja_nacional_disponivel INTEGER,data_ultima_forja TEXT,UNIQUE(jogador_id,npc_nome))','CREATE TABLE transacoes(jogador_id INTEGER,valor INTEGER,tipo TEXT,motivo TEXT,data TEXT)','CREATE TABLE forja_historico(jogador_id INTEGER,npc_nome TEXT,materiais_usados TEXT,item_nome TEXT,item_categoria TEXT,item_rank TEXT,custo INTEGER,tipo_forja TEXT,data TEXT)'])await db.run(sql);
db.ensurePlayerHistorySchema=async()=>{};db.registrarHistoricoFichaComQuery=async(q,e)=>q.run('INSERT INTO recibos VALUES(?,?,?)',[e.jogadorId,e.recurso,e.quantidade]);await db.run('CREATE TABLE recibos(jogador INTEGER,recurso TEXT,quantidade INTEGER)');
const recipe={rank:'E',custo:100,materiais_necessarios:{Ferro:1},itemCatalogo:{slot:'Arma 1'}};await db.run('INSERT INTO forja_sessoes VALUES(1,1,?,?,?,100,NULL)',['Bilac','aguardando_confirmacao',JSON.stringify(recipe)]);
const inventory={SLOT_CAPACIDADE:{'Arma 1':2,'Arma 2':1,Corpo:1},getSlotDoItem:i=>i.categoria};const m={exports:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../src/systems/forjaTransactionService'),'utf8'),{module:m,console,require:name=>name.endsWith('/reward-receipt')?require('../../../packages/database/reward-receipt'):name.endsWith('/config')?{provider:'sqlite'}:name==='./inventorySystem'?inventory:db});
const item=()=>({nome:'Espada',categoria:'Arma 1',rank:'E',descricao:'Teste',isArma:1,isArmadura:0,isEscudo:0,isAcessorio:0,bonus:{forca:11},efeito:'Teste'});const F={calcularCustoFinal:(v)=>v,gerarItemDoCatalogo:item,gerarItemNacional:item};return {db,service:m.exports,F};}
test('forja simultanea entrega uma vez com saldo, materiais e historico corretos',async t=>{const {db,service,F}=await fixture(t);const r=await Promise.all([service.forge(F,1,'Bilac',1),service.forge(F,1,'Bilac',1)]);assert.equal(r.filter(x=>x.sucesso).length,1);assert.equal((await db.get('SELECT won FROM jogadores')).won,999900);assert.equal((await db.get('SELECT quantidade FROM inventario_jogador WHERE item_id=1')).quantidade,1);assert.equal((await db.get('SELECT COUNT(*) AS n FROM forja_historico')).n,1);assert.equal((await db.get('SELECT forca_bonus FROM itens WHERE id=2')).forca_bonus,11);});
test('erro depois do consumo desfaz saldo, materiais e criacao',async t=>{const {db,service,F}=await fixture(t);await db.run('DROP TABLE forja_historico');assert.ok((await service.forge(F,1,'Bilac',1)).erro);assert.equal((await db.get('SELECT won FROM jogadores')).won,1000000);assert.equal((await db.get('SELECT quantidade FROM inventario_jogador')).quantidade,2);assert.equal((await db.get('SELECT COUNT(*) AS n FROM itens')).n,1);assert.equal((await db.get('SELECT etapa FROM forja_sessoes')).etapa,'aguardando_confirmacao');});
test('equipamento e slot bloqueado nao sao usados na forja',async t=>{const {db,service,F}=await fixture(t);assert.equal(service.materialMatches({nome:'Espada de Ferro',categoria:'Arma 1'},'Ferro'),false);await db.run('UPDATE inventario_jogador SET equipado=1');assert.ok((await service.forge(F,1,'Bilac',1)).erro);await db.run('UPDATE inventario_jogador SET equipado=0');await db.run('INSERT INTO itens(id,nome,categoria) VALUES(2,"Arma pesada","Arma 2")');await db.run('INSERT INTO inventario_jogador VALUES(2,1,2,1,1,0)');assert.ok((await service.forge(F,1,'Bilac',1)).erro);assert.equal((await db.get('SELECT quantidade FROM inventario_jogador WHERE id=1')).quantidade,2);});
test('forja nacional consome direito apenas uma vez',async t=>{const {db,service,F}=await fixture(t);await db.run('INSERT INTO npc_afinidade VALUES(1,"Vysache",100,100,1,NULL)');const results=await Promise.all([service.forge(F,1,'Vysache',null,true),service.forge(F,1,'Vysache',null,true)]);assert.equal(results.filter(r=>r.sucesso).length,1);assert.equal((await db.get('SELECT won FROM jogadores')).won,500000);assert.equal((await db.get('SELECT forja_nacional_disponivel FROM npc_afinidade')).forja_nacional_disponivel,0);});
test('parser rejeita zero e soma materiais repetidos; nucleo antigo segue a cor do rank',()=>{const m={exports:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../src/systems/forjaSystem'),'utf8'),{module:m,console,require:name=>name.endsWith('/reward-receipt')?require('../../../packages/database/reward-receipt'):name.endsWith('/config')?{provider:'sqlite'}:{}});const F=m.exports;assert.throws(()=>F.parsearMateriais('Material: Ferro\nQuantidade: 0'));assert.throws(()=>F.parsearMateriais('Material: Ferro\nQuantidade: 2abc'));assert.equal(F.parsearMateriais('Material: Ferro\nQuantidade: 2\nMaterial: Ferro\nQuantidade: 3').Ferro,5);assert.equal(F.buscarMaterial({'Nucleo de Monstro Rank C':1},'Nucleo Verde').quantidade,1);});

test('falha no recibo desfaz a entrega e o pagamento',async t=>{const {db,service,F}=await fixture(t);await db.run('DROP TABLE recibos');assert.ok((await service.forge(F,1,'Bilac',1)).erro);assert.equal((await db.get('SELECT won FROM jogadores')).won,1000000);assert.equal((await db.get('SELECT COUNT(*) AS n FROM itens')).n,1);assert.equal((await db.get('SELECT quantidade FROM inventario_jogador')).quantidade,2);assert.equal((await db.get('SELECT etapa FROM forja_sessoes')).etapa,'aguardando_confirmacao');});
