const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const sqlite3=require('../node_modules/sqlite3');
async function fixture(t){
 const sqlite=new sqlite3.Database(':memory:');let tail=Promise.resolve();
 const db={run(sql,args=[]){return new Promise((resolve,reject)=>sqlite.run(sql,args,function(e){e?reject(e):resolve({changes:this.changes});}));},get(sql,args=[]){return new Promise((resolve,reject)=>sqlite.get(sql,args,(e,row)=>e?reject(e):resolve(row)));},all(sql,args=[]){return new Promise((resolve,reject)=>sqlite.all(sql,args,(e,rows)=>e?reject(e):resolve(rows)));},transaction(work){const task=tail.then(async()=>{await db.run('BEGIN');try{const r=await work(db);await db.run('COMMIT');return r;}catch(e){await db.run('ROLLBACK');throw e;}});tail=task.catch(()=>{});return task;}};
 t.after(()=>new Promise(resolve=>sqlite.close(resolve)));
 for(const sql of ['CREATE TABLE jogadores(id INTEGER PRIMARY KEY,won INTEGER)','INSERT INTO jogadores VALUES(1,100)','CREATE TABLE itens(id INTEGER PRIMARY KEY,nome TEXT,preco INTEGER,valor INTEGER)','INSERT INTO itens VALUES(1,"Espada",0,1000)','CREATE TABLE inventario_jogador(id INTEGER PRIMARY KEY,jogador_id INTEGER,item_id INTEGER,quantidade INTEGER,equipado INTEGER)','INSERT INTO inventario_jogador VALUES(1,1,1,2,0)','CREATE TABLE vendas_pendentes(id INTEGER PRIMARY KEY,jogador_id INTEGER,item_nome TEXT,quantidade INTEGER,valor_total INTEGER,data TEXT)','CREATE TABLE transacoes(jogador_id INTEGER,valor INTEGER,tipo TEXT,motivo TEXT,data TEXT)'])await db.run(sql);
 await db.run('INSERT INTO vendas_pendentes VALUES(1,1,?,?,?,?)',['Espada',2,1000,new Date().toISOString()]);
 const m={exports:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../src/systems/vendaTransactionService'),'utf8'),{module:m,console,require:name=>name.endsWith('/config')?{provider:'sqlite'}:db});
 return {db,sell:m.exports.sell,calculate:(item,q)=>Math.floor(Number(item.preco||item.valor)*.5)*q};
}
test('quantidade textual confirma uma unica vez e remove pendencia junto do credito',async t=>{const {db,sell,calculate}=await fixture(t);const results=await Promise.all([sell(1,'Espada','2',calculate,1),sell(1,'Espada','2',calculate,1)]);assert.equal(results.filter(r=>r.sucesso).length,1);assert.equal((await db.get('SELECT won FROM jogadores')).won,1100);assert.equal(await db.get('SELECT * FROM inventario_jogador'),undefined);assert.equal(await db.get('SELECT * FROM vendas_pendentes'),undefined);});
test('preco alterado e item equipado preservam item, saldo e pendencia',async t=>{const {db,sell,calculate}=await fixture(t);await db.run('UPDATE itens SET valor=2000');assert.equal((await sell(1,'Espada',2,calculate,1)).sucesso,false);await db.run('UPDATE itens SET valor=1000');await db.run('UPDATE inventario_jogador SET equipado=1');assert.equal((await sell(1,'Espada',2,calculate,1)).sucesso,false);assert.equal((await db.get('SELECT won FROM jogadores')).won,100);assert.equal((await db.get('SELECT quantidade FROM inventario_jogador')).quantidade,2);assert.ok(await db.get('SELECT * FROM vendas_pendentes'));});
test('falha ao registrar transacao desfaz retirada e credito',async t=>{const {db,sell,calculate}=await fixture(t);await db.run('DROP TABLE transacoes');assert.equal((await sell(1,'Espada',2,calculate,1)).sucesso,false);assert.equal((await db.get('SELECT won FROM jogadores')).won,100);assert.equal((await db.get('SELECT quantidade FROM inventario_jogador')).quantidade,2);});
