"use strict";
const normalize=value=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
class MemoryRetriever{constructor(options){this.store=options.store;this.maxItems=options.maxItems||8;this.maxChars=options.maxChars||12000;}
score(memory,query,context={}){let score=0;if(memory.importance==="PINNED")score+=100;else if(memory.importance==="HIGH")score+=35;else if(memory.importance==="NORMAL")score+=15;if(memory.session_id&&memory.session_id===context.session_id)score+=80;if(memory.task_id&&memory.task_id===context.task_id)score+=65;if(memory.draft_id&&memory.draft_id===context.draft_id)score+=65;if(memory.workflow_id&&memory.workflow_id===context.workflow_id)score+=65;if(memory.entity_id&&memory.entity_id===context.entity_id)score+=55;const words=normalize(query).split(/\W+/).filter(x=>x.length>2),haystack=normalize(`${memory.summary} ${memory.content}`);score+=words.filter(w=>haystack.includes(w)).length*12;const ageDays=Math.max(0,(Date.now()-new Date(memory.updated_at).getTime())/86400000);if(memory.importance!=="PINNED")score+=Math.max(0,20-Math.log2(ageDays+1)*5);return score;}
async relevant(actor,query,context={},permissions={}){const rows=await this.store.search(actor,"",{limit:100},permissions),ranked=rows.filter(x=>!context.conversation_id||x.conversation_id===context.conversation_id||x.scope!=="CONVERSATION").map(memory=>({...memory,relevance:this.score(memory,query,context)})).sort((a,b)=>b.relevance-a.relevance);const selected=[];let chars=0;for(const row of ranked){const size=String(row.summary||row.content).length;if(selected.length>=this.maxItems||chars+size>this.maxChars)continue;selected.push(row);chars+=size;}return selected;}
async resolve(actor,reference,context={},permissions={}){const kind=/espada|arma|item/i.test(reference)?"draft":/evento|workflow/i.test(reference)?"workflow":null;const rows=await this.relevant(actor,reference,context,permissions),matches=rows.filter(x=>!kind||x.entity_type===kind||x[`${kind}_id`]);if(!matches.length)return{status:"NOT_FOUND",matches:[]};const top=matches[0],second=matches[1];if(second&&Math.abs(top.relevance-second.relevance)<15)return{status:"AMBIGUOUS",matches:matches.slice(0,5).map(publicRef)};return{status:"RESOLVED",match:publicRef(top)};}
}
function publicRef(m){return{memory_id:m.memory_id,label:m.summary||m.content,entity_type:m.entity_type||m.type.toLowerCase(),entity_id:m.entity_id||m.draft_id||m.workflow_id||m.task_id,updated_at:m.updated_at};}
module.exports={MemoryRetriever,publicRef};
