"use strict";
const fs=require("fs"),fsp=require("fs/promises"),path=require("path"),crypto=require("crypto"),sqlite3=require("sqlite3").verbose();const {redact,safeContent}=require("./security");
class MemoryStore{constructor(file,auditFile){this.file=file;this.auditFile=auditFile||path.join(path.dirname(file),"memory-audit.jsonl");fs.mkdirSync(path.dirname(file),{recursive:true});this.db=new sqlite3.Database(file);}run(sql,p=[]){return new Promise((res,rej)=>this.db.run(sql,p,function(e){e?rej(e):res({lastID:this.lastID,changes:this.changes});}));}get(sql,p=[]){return new Promise((res,rej)=>this.db.get(sql,p,(e,row)=>e?rej(e):res(row||null)));}all(sql,p=[]){return new Promise((res,rej)=>this.db.all(sql,p,(e,rows)=>e?rej(e):res(rows||[])));}exec(sql){return new Promise((res,rej)=>this.db.exec(sql,e=>e?rej(e):res()));}close(){return new Promise((res,rej)=>this.db.close(e=>e?rej(e):res()));}
async initialize(){await this.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA synchronous=NORMAL;
CREATE TABLE IF NOT EXISTS memory_sessions(session_id TEXT PRIMARY KEY,actor_id TEXT NOT NULL,conversation_id TEXT,channel_id TEXT,started_at TEXT NOT NULL,last_activity TEXT NOT NULL,expires_at TEXT NOT NULL,closed_at TEXT,active_draft TEXT,active_workflow TEXT,active_task TEXT,last_entity_type TEXT,last_entity_id TEXT,context_json TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS memories(memory_id TEXT PRIMARY KEY,scope TEXT NOT NULL,actor_id TEXT,session_id TEXT,conversation_id TEXT,task_id TEXT,workflow_id TEXT,draft_id TEXT,entity_type TEXT,entity_id TEXT,type TEXT NOT NULL,content TEXT NOT NULL,summary TEXT,importance TEXT NOT NULL,trust TEXT NOT NULL,confidence REAL,version INTEGER NOT NULL DEFAULT 1,active INTEGER NOT NULL DEFAULT 1,shared INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,expires_at TEXT,metadata_json TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS conversations(conversation_id TEXT PRIMARY KEY,actor_id TEXT NOT NULL,title TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE',summary_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,archived_at TEXT);
CREATE TABLE IF NOT EXISTS conversation_messages(message_id TEXT PRIMARY KEY,conversation_id TEXT NOT NULL,actor_id TEXT NOT NULL,role TEXT NOT NULL,content TEXT NOT NULL,created_at TEXT NOT NULL,expires_at TEXT,FOREIGN KEY(conversation_id) REFERENCES conversations(conversation_id));
CREATE TABLE IF NOT EXISTS memory_decision_versions(decision_key TEXT NOT NULL,version INTEGER NOT NULL,memory_id TEXT NOT NULL,content TEXT NOT NULL,created_at TEXT NOT NULL,replaced_by TEXT,PRIMARY KEY(decision_key,version));
CREATE INDEX IF NOT EXISTS idx_memory_actor ON memories(actor_id,active,updated_at);CREATE INDEX IF NOT EXISTS idx_memory_conversation ON memories(conversation_id,active);CREATE INDEX IF NOT EXISTS idx_memory_task ON memories(task_id,active);CREATE INDEX IF NOT EXISTS idx_memory_entity ON memories(entity_type,entity_id,active);CREATE INDEX IF NOT EXISTS idx_memory_workflow ON memories(workflow_id,active);CREATE INDEX IF NOT EXISTS idx_memory_type_date ON memories(type,created_at);CREATE INDEX IF NOT EXISTS idx_sessions_actor ON memory_sessions(actor_id,last_activity);CREATE INDEX IF NOT EXISTS idx_messages_conversation ON conversation_messages(conversation_id,created_at);`);}
async audit(action,actor,details={}){const row=redact({at:new Date().toISOString(),action,actor:String(actor),...details});await fsp.mkdir(path.dirname(this.auditFile),{recursive:true});await fsp.appendFile(this.auditFile,JSON.stringify(row)+"\n","utf8");return row;}
async createSession(actor,input={},ttl=86400000){const now=new Date(),id=input.session_id||`session_${crypto.randomUUID()}`,conversation=input.conversation_id||await this.createConversation(actor,input.title);await this.run("INSERT INTO memory_sessions(session_id,actor_id,conversation_id,channel_id,started_at,last_activity,expires_at,context_json) VALUES(?,?,?,?,?,?,?,?)",[id,String(actor),conversation,input.channel_id||null,now.toISOString(),now.toISOString(),new Date(now.getTime()+ttl).toISOString(),"{}"]);return this.getSession(actor,id);}
async createConversation(actor,title="Nova conversa"){const id=`conversation_${crypto.randomUUID()}`,now=new Date().toISOString();await this.run("INSERT INTO conversations(conversation_id,actor_id,title,created_at,updated_at) VALUES(?,?,?,?,?)",[id,String(actor),String(title||"Nova conversa").slice(0,120),now,now]);return id;}
async getSession(actor,id){const row=await this.get("SELECT * FROM memory_sessions WHERE session_id=? AND actor_id=? AND closed_at IS NULL AND expires_at>?",[id,String(actor),new Date().toISOString()]);return row?hydrate(row):null;}
async currentSession(actor,channelId=null){const row=await this.get("SELECT * FROM memory_sessions WHERE actor_id=? AND closed_at IS NULL AND expires_at>? AND (? IS NULL OR channel_id=?) ORDER BY last_activity DESC LIMIT 1",[String(actor),new Date().toISOString(),channelId,channelId]);return row?hydrate(row):null;}
async touchSession(actor,id,patch={},ttl=86400000){const allowed=["active_draft","active_workflow","active_task","last_entity_type","last_entity_id"],sets=["last_activity=?","expires_at=?"],params=[new Date().toISOString(),new Date(Date.now()+ttl).toISOString()];for(const key of allowed)if(key in patch){sets.push(`${key}=?`);params.push(patch[key]);}if(patch.context){sets.push("context_json=?");params.push(JSON.stringify(redact(patch.context)));}params.push(id,String(actor));await this.run(`UPDATE memory_sessions SET ${sets.join(",")} WHERE session_id=? AND actor_id=?`,params);return this.getSession(actor,id);}
async save(input){const now=new Date().toISOString(),id=input.memory_id||`memory_${crypto.randomUUID()}`,content=safeContent(input.content);if(!content)throw Object.assign(new Error("Memória vazia não pode ser salva."),{code:"MEMORY_INVALID"});const expires=input.importance==="PINNED"?null:input.expires_at||null,metadata=redact(input.metadata||{});await this.run(`INSERT INTO memories(memory_id,scope,actor_id,session_id,conversation_id,task_id,workflow_id,draft_id,entity_type,entity_id,type,content,summary,importance,trust,confidence,version,active,shared,created_at,updated_at,expires_at,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,input.scope||"SESSION",input.actor_id==null?null:String(input.actor_id),input.session_id||null,input.conversation_id||null,input.task_id||null,input.workflow_id||null,input.draft_id||null,input.entity_type||null,input.entity_id||null,input.type||"CONVERSATION",content,safeContent(input.summary||content).slice(0,1000),input.importance||"NORMAL",input.trust||"CONVERSATION",input.confidence??null,input.version||1,1,input.shared?1:0,now,now,expires,JSON.stringify(metadata)]);await this.audit("MEMORY_SAVED",input.actor_id||"system",{memory_id:id,type:input.type,scope:input.scope});return this.getById(input.actor_id,id,{memoryAdmin:true});}
async getById(actor,id,permissions={}){const row=await this.get("SELECT * FROM memories WHERE memory_id=?",[id]);if(!row)return null;this.assertAccess(actor,row,permissions);return hydrate(row);}
assertAccess(actor,row,p={}){if(row.shared||String(row.actor_id)===String(actor)||p.memoryAdmin)return true;throw Object.assign(new Error("Memória privada de outro administrador."),{code:"MEMORY_ACCESS_DENIED"});}
async search(actor,query="",filters={},permissions={}){const where=["active=1","(expires_at IS NULL OR expires_at>?)"],params=[new Date().toISOString()];if(!permissions.memoryAdmin){where.push("(actor_id=? OR shared=1)");params.push(String(actor));}for(const [field,value] of Object.entries({type:filters.type,conversation_id:filters.conversation_id,task_id:filters.task_id,workflow_id:filters.workflow_id,draft_id:filters.draft_id,entity_type:filters.entity_type,entity_id:filters.entity_id}))if(value){where.push(`${field}=?`);params.push(value);}if(filters.since){where.push("created_at>=?");params.push(filters.since);}if(query){where.push("(content LIKE ? OR summary LIKE ? OR entity_id LIKE ?)");params.push(...Array(3).fill(`%${String(query).slice(0,200)}%`));}params.push(Math.min(Number(filters.limit)||50,100));return(await this.all(`SELECT * FROM memories WHERE ${where.join(" AND ")} ORDER BY CASE importance WHEN 'PINNED' THEN 4 WHEN 'HIGH' THEN 3 WHEN 'NORMAL' THEN 2 ELSE 1 END DESC,updated_at DESC LIMIT ?`,params)).map(hydrate);}
async addMessage(actor,conversationId,role,content,retentionDays=14){const conversation=await this.get("SELECT * FROM conversations WHERE conversation_id=?",[conversationId]);if(!conversation||String(conversation.actor_id)!==String(actor))throw Object.assign(new Error("Conversa não encontrada."),{code:"MEMORY_ACCESS_DENIED"});const id=`message_${crypto.randomUUID()}`,now=new Date(),expires=new Date(now.getTime()+retentionDays*86400000).toISOString();await this.run("INSERT INTO conversation_messages(message_id,conversation_id,actor_id,role,content,created_at,expires_at) VALUES(?,?,?,?,?,?,?)",[id,conversationId,String(actor),role,safeContent(content),now.toISOString(),expires]);await this.run("UPDATE conversations SET updated_at=? WHERE conversation_id=?",[now.toISOString(),conversationId]);return{id,conversation_id:conversationId};}
async messages(actor,conversationId,limit=12){const conversation=await this.get("SELECT actor_id,status FROM conversations WHERE conversation_id=?",[conversationId]);if(!conversation||String(conversation.actor_id)!==String(actor))throw Object.assign(new Error("Conversa não encontrada."),{code:"MEMORY_ACCESS_DENIED"});if(conversation.status==="ARCHIVED")return[];return this.all("SELECT role,content,created_at FROM conversation_messages WHERE conversation_id=? AND (expires_at IS NULL OR expires_at>?) ORDER BY created_at DESC LIMIT ?",[conversationId,new Date().toISOString(),limit]).then(rows=>rows.reverse());}
async updateConversationSummary(actor,id,summary){const row=await this.get("SELECT actor_id FROM conversations WHERE conversation_id=?",[id]);if(!row||String(row.actor_id)!==String(actor))throw new Error("Conversa não encontrada.");await this.run("UPDATE conversations SET summary_json=?,updated_at=? WHERE conversation_id=?",[JSON.stringify(redact(summary)),new Date().toISOString(),id]);return summary;}
async conversations(actor,{archived=false,limit=50}={}){return this.all("SELECT * FROM conversations WHERE actor_id=? AND status=? ORDER BY updated_at DESC LIMIT ?",[String(actor),archived?"ARCHIVED":"ACTIVE",limit]);}
async archiveConversation(actor,id){await this.run("UPDATE conversations SET status='ARCHIVED',archived_at=?,updated_at=? WHERE conversation_id=? AND actor_id=?",[new Date().toISOString(),new Date().toISOString(),id,String(actor)]);await this.audit("CONVERSATION_ARCHIVED",actor,{conversation_id:id});}
async saveDecision(actor,input){const key=input.decision_key||`${input.scope||"TASK"}:${input.task_id||input.workflow_id||input.draft_id||input.entity_id||"project"}:${input.topic||"general"}`,previous=await this.get("SELECT * FROM memory_decision_versions WHERE decision_key=? ORDER BY version DESC LIMIT 1",[key]),version=(previous?.version||0)+1;if(previous)await this.run("UPDATE memories SET active=0,updated_at=? WHERE memory_id=?",[new Date().toISOString(),previous.memory_id]);const memory=await this.save({...input,actor_id:actor,type:"DECISION",trust:"DECISION",importance:input.importance||"HIGH",version});await this.run("INSERT INTO memory_decision_versions(decision_key,version,memory_id,content,created_at) VALUES(?,?,?,?,?)",[key,version,memory.memory_id,memory.content,new Date().toISOString()]);if(previous)await this.run("UPDATE memory_decision_versions SET replaced_by=? WHERE decision_key=? AND version=?",[memory.memory_id,key,previous.version]);await this.audit("DECISION_VERSIONED",actor,{decision_key:key,version,memory_id:memory.memory_id,previous:previous?.memory_id});return{...memory,decision_key:key,version};}
async forget(actor,id,permissions={}){const row=await this.get("SELECT * FROM memories WHERE memory_id=?",[id]);if(!row)return false;this.assertAccess(actor,row,permissions);await this.run("DELETE FROM memories WHERE memory_id=?",[id]);await this.audit("MEMORY_FORGOTTEN",actor,{memory_id:id});return true;}
async pin(actor,id,pinned=true,permissions={}){const row=await this.get("SELECT * FROM memories WHERE memory_id=?",[id]);if(!row)throw new Error("Memória não encontrada.");this.assertAccess(actor,row,permissions);await this.run("UPDATE memories SET importance=?,expires_at=?,updated_at=? WHERE memory_id=?",[pinned?"PINNED":"NORMAL",pinned?null:row.expires_at,new Date().toISOString(),id]);await this.audit(pinned?"MEMORY_PINNED":"MEMORY_UNPINNED",actor,{memory_id:id});return this.getById(actor,id,permissions);}
async forgetConversation(actor,id){const row=await this.get("SELECT actor_id FROM conversations WHERE conversation_id=?",[id]);if(!row||String(row.actor_id)!==String(actor))throw Object.assign(new Error("Conversa não encontrada."),{code:"MEMORY_ACCESS_DENIED"});await this.run("DELETE FROM conversation_messages WHERE conversation_id=?",[id]);await this.run("DELETE FROM memories WHERE conversation_id=?",[id]);await this.run("DELETE FROM conversations WHERE conversation_id=?",[id]);await this.audit("CONVERSATION_FORGOTTEN",actor,{conversation_id:id});return true;}
async cleanup(now=new Date()){const iso=now.toISOString();const sessions=await this.run("UPDATE memory_sessions SET closed_at=? WHERE closed_at IS NULL AND expires_at<=?",[iso,iso]),messages=await this.run("DELETE FROM conversation_messages WHERE expires_at IS NOT NULL AND expires_at<=?",[iso]),memories=await this.run("DELETE FROM memories WHERE importance<>'PINNED' AND expires_at IS NOT NULL AND expires_at<=?",[iso]);await this.audit("MEMORY_CLEANUP","system",{sessions:sessions.changes,messages:messages.changes,memories:memories.changes});return{sessions:sessions.changes,messages:messages.changes,memories:memories.changes};}
async health(){try{await this.get("SELECT 1 AS ok");return{status:"ONLINE",file:this.file};}catch{return{status:"DEGRADED",code:"CARDINAL_MEMORY_DEGRADED"};}}
}
function hydrate(row){if(!row)return row;const output={...row,active:Boolean(row.active),shared:Boolean(row.shared)};for(const key of ["metadata_json","context_json","summary_json"])if(key in output){try{output[key.replace("_json","")]=JSON.parse(output[key]||"{}");}catch{output[key.replace("_json","")]={};}delete output[key];}return output;}
module.exports={MemoryStore,hydrate};
