"use strict";
const fs = require("fs/promises"); const path = require("path"); const os = require("os"); const { performance } = require("perf_hooks");
async function httpHealth(url, timeout = 3000) { const started = performance.now(), controller = new AbortController(), timer = setTimeout(() => controller.abort(), timeout); try { const response = await fetch(url, { signal: controller.signal }); return { online: response.ok, status: response.ok ? "ONLINE" : "DEGRADED", http_status: response.status, latency_ms: Math.round(performance.now() - started) }; } catch (e) { return { online: false, status: "OFFLINE", error: e.name === "AbortError" ? "timeout" : "connection_failed", latency_ms: Math.round(performance.now() - started) }; } finally { clearTimeout(timer); } }
class HealthService {
    constructor(options) { Object.assign(this, options); this.db = options.database; delete this.database; }
    async service(id) { const config = this.registry[id]; if (!config) throw new Error(`Serviço não registrado: ${id}.`); const state = await this.adapters[id].status(); if (config.health === "http") { const health = await httpHealth(config.url); return { ...state, ...health, status: health.status }; } return state; }
    async database() { const started = performance.now(); try { await this.db.get("SELECT 1 AS ok"); return { status: "ONLINE", latency_ms: Math.round(performance.now() - started) }; } catch { return { status: "OFFLINE", code: "CARDINAL_DEGRADED_DATABASE_OFFLINE" }; } }
    async knowledge() { try { const stat = await fs.stat(path.join(this.root, "cardinal/cache/knowledge.db")); return { status: "ONLINE", size: stat.size, updated_at: stat.mtime.toISOString() }; } catch { return { status: "OFFLINE" }; } }
    async memory() { try { const stat = await fs.stat(path.join(this.root, "cardinal/cache/memory.db")); return { status: "ONLINE", size: stat.size, updated_at: stat.mtime.toISOString() }; } catch { return { status: "DEGRADED", code: "CARDINAL_MEMORY_DEGRADED" }; } }
    async system() { const disk = await fs.statfs(this.root), free = disk.bavail * disk.bsize; return { uptime_s: Math.round(os.uptime()), cpu_count: os.cpus().length, memory_total: os.totalmem(), memory_free: os.freemem(), disk_free: free, disk_free_mb: Math.floor(free / 1048576) }; }
    async world() { try { const { WorldDirector } = require("../../world"); return await new WorldDirector({ root: this.root, database: this.db }).health(); } catch { return { world_director:"DEGRADED", scheduler:"OFFLINE", world_state:"DEGRADED" }; } }
    async all() { const [qwen, bot, site, database, knowledge, memory, world, system] = await Promise.all([this.service("qwen"), this.service("bot"), this.service("site"), this.database(), this.knowledge(), this.memory(), this.world(), this.system()]); return { qwen, knowledge, memory, world, database, bot, site, forge: { status: "ONLINE" }, publisher: { status: "ONLINE" }, developer: { status: process.env.CARDINAL_DEVELOPER_ENABLED === "true" ? "ONLINE" : "DISABLED" }, operations: { status: process.env.CARDINAL_OPERATIONS_ENABLED === "true" ? "ONLINE" : "READ_ONLY" }, system }; }
}
module.exports = { HealthService, httpHealth };
