"use strict";

const { AdminError, CODES } = require("./errors");
const { createPlan } = require("../forge/planner");
const { validatePlan } = require("../forge/service");
const { qualityGate } = require("../balance");

class CardinalPublisher {
    constructor(options = {}) { this.drafts = options.draftStore; this.validator = options.validator; this.balance = options.balance || null; this.provider = options.provider || "sqlite"; }
    async publish(ctx, draftId) {
        const draft = await this.drafts.getDraft(draftId); if (draft.status !== "VALID") throw new AdminError(CODES.PUBLISH_FAILED, "Somente drafts VALID podem ser publicados.");
        const schemaValidation = await this.validator.validate(draft.type, draft.content);
        const validation = validatePlan(createPlan(draft.request, draft.type), draft.content, schemaValidation);
        if (!validation.valid) throw new AdminError(CODES.PUBLISH_FAILED, "O draft falhou na validação atual.", validation);
        const balanceCheck = this.balance ? await qualityGate({ engine: this.balance, type: draft.type, content: draft.content }) : null; const balance = balanceCheck?.report || null; if (balanceCheck && !balanceCheck.passed && process.env.CARDINAL_BLOCK_CRITICAL_BALANCE_ISSUES !== "false") throw new AdminError(CODES.PUBLISH_FAILED, "O draft possui risco crítico de Balance/QA.", balanceCheck);
        const target = targetFor(draft.type); if (!target) throw new AdminError(CODES.UNSUPPORTED, `Publicação de ${draft.type} não possui estrutura oficial segura.`);
        const existing = await ctx.query.get(`SELECT id,nome FROM ${target.table} WHERE LOWER(nome)=LOWER(?)`, [draft.content.nome]); if (existing) throw new AdminError(CODES.DUPLICATE, `Já existe ${draft.content.nome} em ${target.table}.`, { id: existing.id });
        const published = await target.insert(ctx.query, draft.content, this.provider, ctx.dryRun); const entity = { type: draft.type, table: target.table, id: published.id || null, name: draft.content.nome };
        return { entity, before: null, after: draft.content, result: { success: true, draft_id: draftId, published: !ctx.dryRun, target: target.table, balance_report: balance?.id || null }, rollback: published.id ? { kind: "delete-published", table: target.table, id: published.id, draft_id: draftId } : null, _postCommit: ctx.dryRun ? null : () => this.drafts.markStatus(draftId, "PUBLISHED", ctx.admin.number) };
    }
}
function returning(provider) { return provider === "postgres" ? " RETURNING id" : ""; }
async function insert(query, provider, table, fields, values, dryRun) { if (dryRun) return { id: null }; const marks = fields.map(() => "?").join(","); const row = await query.run(`INSERT INTO ${table}(${fields.join(",")}) VALUES(${marks})${returning(provider)}`, values); return { id: Number(row.lastID) }; }
function itemTarget(flag) { return { table: "itens", async insert(q, c, p, dry) { const fields = ["nome", "categoria", "slot", "tier", "descricao", "forca_bonus", "resistencia_bonus", "velocidade_bonus", "sentidos_bonus", "inteligencia_bonus", "poder_magico_bonus", "efeito", "habilidade", "classe_requerida", "estilo_requerido", "preco", "item_unico"]; const values = [c.nome, c.categoria, c.slot || null, c.tier, c.descricao, c.forca_bonus || 0, c.resistencia_bonus || 0, c.velocidade_bonus || 0, c.sentidos_bonus || 0, c.inteligencia_bonus || 0, c.poder_magico_bonus || 0, c.efeito || null, c.habilidade || null, c.classe_requerida || "Nenhuma", c.estilo_requerido || "Nenhum", c.preco || 0, 1]; if (flag) { fields.push(flag); values.push(1); } return insert(q, p, "itens", fields, values, dry); } }; }
function rareTarget(kind) { const base = itemTarget(null); return { table: "itens", async insert(q, c, p, dry) { const row = await base.insert(q, { ...c, slot: "Item de Apoio", tier: c.rank, efeito: `${c.efeito}\nCondição: ${c.condicao}` }, p, dry); if (!dry) await q.run("INSERT INTO banner_rare_items(item_id,tipo,criado_por) VALUES(?,?,?)", [row.id, kind, "CARDINAL"]); return row; } }; }
const TARGETS = {
    weapon: itemTarget("arma"), armor: itemTarget("armadura"), accessory: itemTarget("acessorio"), consumable: itemTarget("consumivel"), material: itemTarget(null), equipment: itemTarget("equipamento"),
    technique: { table: "tecnicas", insert: (q, c, p, dry) => insert(q, p, "tecnicas", ["nome", "classe", "categoria", "tipo", "descricao", "descricao_completa", "custo_mana", "custo_qi", "custo_maestria", "cooldown", "nivel_desbloqueio", "rank", "passiva"], [c.nome, c.classe, c.categoria, c.tipo, c.descricao, c.descricao_completa, c.custo_mana || 0, c.custo_qi || 0, c.custo_maestria || 0, c.cooldown || 0, c.nivel_desbloqueio, c.rank, c.passiva || 0], dry) },
    passive: rareTarget("PASSIVA"), title: rareTarget("TITULO"),
    mission: { table: "missoes", insert: (q, c, p, dry) => insert(q, p, "missoes", ["jogador_id", "nome", "descricao", "tipo", "progresso", "objetivo", "recompensa_xp", "recompensa_won", "status", "data"], [null, c.nome, c.descricao, c.tipo, 0, c.objetivo, c.recompensa_xp, c.recompensa_won, "rascunho", new Date().toISOString()], dry) },
    banner: { table: "gacha_banners", async insert(q, c, p, dry) { for (const reward of c.pool) { if (!reward.reward_type || reward.referencia_id == null || !Number.isFinite(reward.peso) || reward.peso <= 0) throw new AdminError(CODES.PUBLISH_FAILED, `Recompensa ${reward.nome || "sem nome"} não possui reward_type, referencia_id e peso publicáveis.`); const table = ["TECNICA"].includes(reward.reward_type) ? "tecnicas" : "itens"; if (!await q.get(`SELECT id FROM ${table} WHERE id=?`, [reward.referencia_id])) throw new AdminError(CODES.ENTITY_NOT_FOUND, `Referência do pool não encontrada: ${reward.referencia_id}.`); } const banner = await insert(q, p, "gacha_banners", ["nome", "descricao", "ativo", "permanente", "inicio_em", "fim_em", "status"], [c.nome, c.descricao, 0, c.permanente ? 1 : 0, c.inicio_em || null, c.fim_em || null, "DRAFT"], dry); if (!dry) for (const reward of c.pool) await q.run("INSERT INTO gacha_banner_rewards(banner_id,reward_type,referencia_id,quantidade,peso,raridade,grande_premio,exclusivo_banner,ativo,unica,duplicate_fragment_value) VALUES(?,?,?,?,?,?,?,?,?,?,?)", [banner.id, reward.reward_type, reward.referencia_id, reward.quantidade || 1, reward.peso, reward.raridade || null, reward.grande_premio ? 1 : 0, reward.exclusivo_banner ? 1 : 0, 1, reward.unica ? 1 : 0, reward.duplicate_fragment_value || null]); return banner; } },
    event: { table: "eventos", insert: (q, c, p, dry) => insert(q, p, "eventos", ["nome", "descricao", "recompensa", "ativo"], [c.nome, c.descricao, c.recompensa, 0], dry) },
    dungeon: { table: "dungeons", insert: (q, c, p, dry) => insert(q, p, "dungeons", ["nome", "rank", "andar", "descricao", "boss", "recompensa_xp", "recompensa_won"], [c.nome, c.rank, c.andar, c.descricao, c.boss, c.recompensa_xp, c.recompensa_won], dry) },
    guild: { table: "guildas", insert: (q, c, p, dry) => insert(q, p, "guildas", ["nome", "lider", "nivel", "valor", "territorio", "membros", "passivas", "criada"], [c.nome, "CARDINAL_MODEL", c.nivel, c.valor, c.territorio, c.membros, c.passivas, 0], dry) },
    set: { table: "equipment_sets", async insert(q, c, p, dry) { if (dry) return { id: null }; const base = await insert(q, p, "equipment_sets", ["nome", "descricao", "rank", "ativo"], [c.nome, c.descricao, c.rank, 0], false); for (const item of c.itens) { const found = await q.get("SELECT id FROM itens WHERE LOWER(nome)=LOWER(?)", [item.nome || item]); if (!found) throw new AdminError(CODES.ENTITY_NOT_FOUND, `Item do conjunto não encontrado: ${item.nome || item}.`); await q.run("INSERT INTO equipment_set_items(set_id,item_id) VALUES(?,?)", [base.id, found.id]); } for (const stage of c.estagios) await q.run("INSERT INTO equipment_set_bonuses(set_id,required_pieces,forca,resistencia,velocidade,sentidos,inteligencia,poder_magico,efeito_futuro) VALUES(?,?,?,?,?,?,?,?,?)", [base.id, stage.pecas, stage.forca || 0, stage.resistencia || 0, stage.velocidade || 0, stage.sentidos || 0, stage.inteligencia || 0, stage.poder_magico || 0, stage.descricao || null]); return base; } }
};
function targetFor(type) { return TARGETS[type] || null; }
module.exports = { CardinalPublisher, TARGETS, targetFor };
