"use strict";
const { AdminError, CODES } = require("./errors");
const PERMISSIONS = Object.freeze(["CARDINAL_READ", "CARDINAL_WEB_SEARCH", "CARDINAL_FORGE", "CARDINAL_PUBLISH", "CARDINAL_ECONOMY", "CARDINAL_BALANCE_READ", "CARDINAL_BALANCE_RUN", "CARDINAL_QA_RUN", "CARDINAL_NARRATIVE_READ", "CARDINAL_NARRATIVE_CREATE", "CARDINAL_NARRATIVE_EDIT", "CARDINAL_NARRATIVE_APPROVE", "CARDINAL_LORE_ADMIN", "CARDINAL_SECRET_LORE", "CARDINAL_PLAYER_ADMIN", "CARDINAL_SCENE_ADMIN", "CARDINAL_MISSION_ADMIN", "CARDINAL_BANNER_ADMIN", "CARDINAL_DUNGEON_ADMIN", "CARDINAL_GUILD_ADMIN", "CARDINAL_DEVELOPER", "CARDINAL_DEVELOPER_APPROVE", "CARDINAL_OPS_READ", "CARDINAL_OPS_RESTART", "CARDINAL_OPS_DEPLOY", "CARDINAL_OPS_BACKUP", "CARDINAL_OPS_RESTORE", "CARDINAL_OPS_CRITICAL", "CARDINAL_MEMORY_READ", "CARDINAL_MEMORY_WRITE", "CARDINAL_MEMORY_DELETE", "CARDINAL_MEMORY_ADMIN", "CARDINAL_WORLD_READ", "CARDINAL_WORLD_DUNGEONS", "CARDINAL_WORLD_EVENTS", "CARDINAL_WORLD_NPCS", "CARDINAL_WORLD_BANNERS", "CARDINAL_WORLD_TERRITORIES", "CARDINAL_WORLD_SCHEDULE", "CARDINAL_WORLD_ADMIN", "CARDINAL_CRITICAL"]);
const ROLE_PERMISSIONS = Object.freeze({ evaluator: ["CARDINAL_READ", "CARDINAL_SCENE_ADMIN", "CARDINAL_OPS_READ", "CARDINAL_MEMORY_READ", "CARDINAL_NARRATIVE_READ"], content_admin: ["CARDINAL_READ", "CARDINAL_WEB_SEARCH", "CARDINAL_FORGE", "CARDINAL_PUBLISH", "CARDINAL_BALANCE_READ", "CARDINAL_BALANCE_RUN", "CARDINAL_QA_RUN", "CARDINAL_NARRATIVE_READ", "CARDINAL_NARRATIVE_CREATE", "CARDINAL_NARRATIVE_EDIT", "CARDINAL_MISSION_ADMIN", "CARDINAL_BANNER_ADMIN", "CARDINAL_DUNGEON_ADMIN", "CARDINAL_GUILD_ADMIN", "CARDINAL_DEVELOPER", "CARDINAL_OPS_READ", "CARDINAL_MEMORY_READ", "CARDINAL_MEMORY_WRITE", "CARDINAL_MEMORY_DELETE"], economy_admin: ["CARDINAL_READ", "CARDINAL_ECONOMY", "CARDINAL_BALANCE_READ", "CARDINAL_BALANCE_RUN", "CARDINAL_QA_RUN", "CARDINAL_PLAYER_ADMIN", "CARDINAL_OPS_READ", "CARDINAL_MEMORY_READ", "CARDINAL_MEMORY_WRITE", "CARDINAL_MEMORY_DELETE"], superadmin: PERMISSIONS.filter(value => !["CARDINAL_CRITICAL", "CARDINAL_DEVELOPER_APPROVE", "CARDINAL_SECRET_LORE"].includes(value)), owner: PERMISSIONS });
function roleFrom(admin, ownerNumber) { if (ownerNumber && String(admin?.numero) === String(ownerNumber)) return "owner"; if (Number(admin?.nivel) >= 3) return "superadmin"; const permission = String(admin?.permissao || "").toLowerCase(); if (permission === "admin" || permission.includes("superadmin")) return "superadmin"; if (permission.includes("econom")) return "economy_admin"; if (permission.includes("conte")) return "content_admin"; return "evaluator"; }
class Rbac {
    constructor(options = {}) { this.database = options.database; this.ownerNumber = options.ownerNumber ?? process.env.CARDINAL_OWNER_NUMBER; }
    async identity(actor) { const admin = await this.database.get("SELECT numero,nome,nivel,permissao FROM administradores WHERE numero=?", [actor]); if (!admin) throw new AdminError(CODES.PERMISSION_DENIED, "Acesso restrito a administradores registrados."); const role = roleFrom(admin, this.ownerNumber); return { ...admin, role, permissions: ROLE_PERMISSIONS[role] }; }
    async authorize(actor, permission) { const identity = await this.identity(actor); if (!identity.permissions.includes(permission)) throw new AdminError(CODES.PERMISSION_DENIED, `O administrador não possui ${permission}.`); return identity; }
}
module.exports = { PERMISSIONS, ROLE_PERMISSIONS, roleFrom, Rbac };
