"use strict";

const { AdminError, CODES } = require("./errors");
const { RISK } = require("./risk");
const { EntityResolver } = require("./resolver");

function positiveInteger(value) { const amount = Number(value); if (!Number.isSafeInteger(amount) || amount <= 0) throw new AdminError(CODES.INVALID_AMOUNT, "O valor deve ser um inteiro positivo seguro."); return amount; }
function tool(definition) { return { risk: RISK.LOW, input_schema: { type: "object", additionalProperties: false }, ...definition }; }
function resourceTool(name, column, permission) { return tool({ name, permission, risk: RISK.MEDIUM, input_schema: { required: ["player", "amount"] }, async execute(ctx, params) { const amount = positiveInteger(params.amount); const resolver = new EntityResolver(ctx.query); const player = await resolver.resolve("jogadores", params.player); const before = Number(player[column] || 0); const after = before + amount; if (!Number.isSafeInteger(after)) throw new AdminError(CODES.INVALID_AMOUNT, "A operação excede o limite inteiro seguro."); if (!ctx.dryRun) await ctx.query.run(`UPDATE jogadores SET ${column}=? WHERE id=?`, [after, player.id]); return { entity: { type: "player", id: player.id, name: player.nome }, before: { [column]: before }, after: { [column]: after }, result: { success: true, delta: amount }, rollback: { kind: "set-field", table: "jogadores", id: player.id, field: column, value: before } }; } }); }
function decreaseTool(name, column, permission) { return tool({ name, permission, risk: RISK.HIGH, input_schema: { required: ["player", "amount"] }, async execute(ctx, params) { const amount = positiveInteger(params.amount), player = await new EntityResolver(ctx.query).resolve("jogadores", params.player), before = Number(player[column] || 0); if (before < amount) throw new AdminError(CODES.INVALID_AMOUNT, "O saldo não pode ficar negativo."); const after = before - amount; if (!ctx.dryRun) await ctx.query.run(`UPDATE jogadores SET ${column}=? WHERE id=?`, [after, player.id]); return { entity: { type: "player", id: player.id, name: player.nome }, before: { [column]: before }, after: { [column]: after }, result: { success: true, delta: -amount }, rollback: { kind: "set-field", table: "jogadores", id: player.id, field: column, value: before } }; } }); }
function setResourceTool(name, column, permission) { return tool({ name, permission, risk: RISK.HIGH, input_schema: { required: ["player", "amount"] }, async execute(ctx, params) { const amount = Number(params.amount); if (!Number.isSafeInteger(amount) || amount < 0) throw new AdminError(CODES.INVALID_AMOUNT, "O valor deve ser um inteiro não negativo seguro."); const player = await new EntityResolver(ctx.query).resolve("jogadores", params.player), before = Number(player[column] || 0); if (!ctx.dryRun) await ctx.query.run(`UPDATE jogadores SET ${column}=? WHERE id=?`, [amount, player.id]); return { entity: { type: "player", id: player.id, name: player.nome }, before: { [column]: before }, after: { [column]: amount }, result: { success: true }, rollback: { kind: "set-field", table: "jogadores", id: player.id, field: column, value: before } }; } }); }

function registerCoreTools(registry, dependencies = {}) {
    registry.register(resourceTool("give_wons", "won", "CARDINAL_ECONOMY")); registry.register(resourceTool("give_crystals", "cristais", "CARDINAL_ECONOMY")); registry.register(resourceTool("give_xp", "experiencia", "CARDINAL_PLAYER_ADMIN")); registry.register(resourceTool("give_mastery", "maestria", "CARDINAL_PLAYER_ADMIN"));
    registry.register(decreaseTool("remove_wons", "won", "CARDINAL_ECONOMY")); registry.register(decreaseTool("remove_crystals", "cristais", "CARDINAL_ECONOMY")); registry.register(setResourceTool("set_wons", "won", "CARDINAL_ECONOMY")); registry.register(setResourceTool("set_crystals", "cristais", "CARDINAL_ECONOMY"));
    registry.register(tool({ name: "get_player", permission: "CARDINAL_READ", input_schema: { required: ["player"] }, async execute(ctx, params) { const player = await new EntityResolver(ctx.query).resolve("jogadores", params.player); return { entity: { type: "player", id: player.id, name: player.nome }, before: null, after: null, result: { player }, rollback: null }; } }));
    registry.register(tool({ name: "give_item", permission: "CARDINAL_PLAYER_ADMIN", risk: RISK.MEDIUM, input_schema: { required: ["player", "item", "quantity"] }, async execute(ctx, params) { const quantity = positiveInteger(params.quantity), resolver = new EntityResolver(ctx.query); const player = await resolver.resolve("jogadores", params.player), item = await resolver.resolve("itens", params.item); const current = await ctx.query.get("SELECT * FROM inventario_jogador WHERE jogador_id=? AND item_id=? ORDER BY id LIMIT 1", [player.id, item.id]); const before = Number(current?.quantidade || 0), after = before + quantity; if (!Number.isSafeInteger(after)) throw new AdminError(CODES.INVALID_AMOUNT, "Quantidade excede o limite seguro."); if (!ctx.dryRun) { if (current) await ctx.query.run("UPDATE inventario_jogador SET quantidade=? WHERE id=?", [after, current.id]); else await ctx.query.run("INSERT INTO inventario_jogador(jogador_id,item_id,quantidade,equipado,item_inicial) VALUES(?,?,?,0,0)", [player.id, item.id, after]); } return { entity: { type: "inventory", player_id: player.id, item_id: item.id, name: item.nome }, before: { quantity: before }, after: { quantity: after }, result: { success: true, quantity }, rollback: { kind: "inventory-quantity", player_id: player.id, item_id: item.id, value: before } }; } }));
    registry.register(tool({ name: "remove_item", permission: "CARDINAL_PLAYER_ADMIN", risk: RISK.HIGH, input_schema: { required: ["player", "item", "quantity"] }, async execute(ctx, params) { const quantity = positiveInteger(params.quantity), resolver = new EntityResolver(ctx.query), player = await resolver.resolve("jogadores", params.player), item = await resolver.resolve("itens", params.item), current = await ctx.query.get("SELECT * FROM inventario_jogador WHERE jogador_id=? AND item_id=? ORDER BY id LIMIT 1", [player.id, item.id]); const before = Number(current?.quantidade || 0); if (before < quantity) throw new AdminError(CODES.INVALID_AMOUNT, "Quantidade insuficiente no inventário."); const after = before - quantity; if (!ctx.dryRun) { if (after) await ctx.query.run("UPDATE inventario_jogador SET quantidade=? WHERE id=?", [after, current.id]); else await ctx.query.run("DELETE FROM inventario_jogador WHERE id=?", [current.id]); } return { entity: { type: "inventory", player_id: player.id, item_id: item.id, name: item.nome }, before: { quantity: before }, after: { quantity: after }, result: { success: true, delta: -quantity }, rollback: { kind: "inventory-quantity", player_id: player.id, item_id: item.id, value: before } }; } }));
    registry.register(tool({ name: "adjust_rank", permission: "CARDINAL_PLAYER_ADMIN", risk: RISK.HIGH, input_schema: { required: ["player", "rank"] }, async execute(ctx, params) { const rank = String(params.rank).toUpperCase(); if (!["E", "D", "C", "B", "A", "S"].includes(rank)) throw new AdminError(CODES.INVALID_INPUT, "Rank inválido."); const player = await new EntityResolver(ctx.query).resolve("jogadores", params.player); if (!ctx.dryRun) await ctx.query.run("UPDATE jogadores SET rank=? WHERE id=?", [rank, player.id]); return { entity: { type: "player", id: player.id, name: player.nome }, before: { rank: player.rank }, after: { rank }, result: { success: true }, rollback: { kind: "fields", table: "jogadores", id: player.id, values: { rank: player.rank } } }; } }));
    registry.register(tool({ name: "activate_banner", permission: "CARDINAL_BANNER_ADMIN", input_schema: { required: ["banner"] }, async execute(ctx, params) { const banner = await new EntityResolver(ctx.query).resolve("gacha_banners", params.banner); const before = { ativo: Number(banner.ativo || 0), status: banner.status }; if (!ctx.dryRun) await ctx.query.run("UPDATE gacha_banners SET ativo=1,status='ativo',atualizado_em=CURRENT_TIMESTAMP WHERE id=?", [banner.id]); return { entity: { type: "banner", id: banner.id, name: banner.nome }, before, after: { ativo: 1, status: "ativo" }, result: { success: true }, rollback: { kind: "banner-state", id: banner.id, ...before } }; } }));
    registry.register(tool({ name: "deactivate_banner", permission: "CARDINAL_BANNER_ADMIN", risk: RISK.HIGH, input_schema: { required: ["banner"] }, async execute(ctx, params) { const banner = await new EntityResolver(ctx.query).resolve("gacha_banners", params.banner); const before = { ativo: Number(banner.ativo || 0), status: banner.status }; if (!ctx.dryRun) await ctx.query.run("UPDATE gacha_banners SET ativo=0,status='inativo',atualizado_em=CURRENT_TIMESTAMP WHERE id=?", [banner.id]); return { entity: { type: "banner", id: banner.id, name: banner.nome }, before, after: { ativo: 0, status: "inativo" }, result: { success: true }, rollback: { kind: "banner-state", id: banner.id, ...before } }; } }));
    registry.register(tool({ name: "update_dungeon", permission: "CARDINAL_DUNGEON_ADMIN", risk: RISK.HIGH, input_schema: { required: ["dungeon", "changes"] }, async execute(ctx, params) { const dungeon = await new EntityResolver(ctx.query).resolve("dungeons", params.dungeon); const allowed = ["descricao", "recompensa_xp", "recompensa_won", "andar", "boss"]; const changes = Object.fromEntries(Object.entries(params.changes || {}).filter(([key]) => allowed.includes(key))); if (!Object.keys(changes).length || Object.keys(changes).length !== Object.keys(params.changes || {}).length) throw new AdminError(CODES.INVALID_INPUT, "Alteração de Dungeon contém campos não permitidos."); for (const key of ["recompensa_xp", "recompensa_won", "andar"]) if (changes[key] != null && (!Number.isSafeInteger(changes[key]) || changes[key] < (key === "andar" ? 1 : 0))) throw new AdminError(CODES.INVALID_INPUT, `${key} inválido.`); if (!ctx.dryRun) for (const [key, value] of Object.entries(changes)) await ctx.query.run(`UPDATE dungeons SET ${key}=? WHERE id=?`, [value, dungeon.id]); return { entity: { type: "dungeon", id: dungeon.id, name: dungeon.nome }, before: Object.fromEntries(Object.keys(changes).map(key => [key, dungeon[key]])), after: changes, result: { success: true }, rollback: { kind: "fields", table: "dungeons", id: dungeon.id, values: Object.fromEntries(Object.keys(changes).map(key => [key, dungeon[key]])) } }; } }));
    registry.register(editTool("update_mission", "missoes", "mission", "CARDINAL_MISSION_ADMIN", ["descricao", "recompensa_xp", "recompensa_won", "objetivo", "status"], RISK.HIGH));
    registry.register(editTool("edit_guild", "guildas", "guild", "CARDINAL_GUILD_ADMIN", ["nivel", "valor", "territorio", "passivas"], RISK.HIGH));
    registry.register(editTool("edit_banner", "gacha_banners", "banner", "CARDINAL_BANNER_ADMIN", ["descricao", "inicio_em", "fim_em"], RISK.HIGH));
    registry.register(tool({ name: "approve_scene", permission: "CARDINAL_SCENE_ADMIN", risk: RISK.MEDIUM, input_schema: { required: ["scene_id"] }, async execute() { throw new AdminError(CODES.UNSUPPORTED, "O RPG não possui tabela oficial de cenas pendentes que possa ser aprovada por ID."); } }));
    if (dependencies.publisher) registry.register(tool({ name: "publish_draft", permission: "CARDINAL_PUBLISH", input_schema: { requiredAny: ["draft_id", "draft_name"] }, async execute(ctx, params) { let id = params.draft_id; if (!id) { const found = await dependencies.draftStore.findByName(params.draft_name); if (!found.id) throw new AdminError(found.matches.length ? CODES.AMBIGUOUS_TARGET : CODES.ENTITY_NOT_FOUND, `Draft não resolvido de forma única: ${params.draft_name}.`, found); id = found.id; } return dependencies.publisher.publish(ctx, id); } }));
    return registry;
}
function editTool(name, table, targetKey, permission, allowed, risk) { return tool({ name, permission, risk, input_schema: { required: [targetKey, "changes"] }, async execute(ctx, params) { const row = await new EntityResolver(ctx.query).resolve(table, params[targetKey]), entries = Object.entries(params.changes || {}); if (!entries.length || entries.some(([key]) => !allowed.includes(key))) throw new AdminError(CODES.INVALID_INPUT, `Campos permitidos: ${allowed.join(", ")}.`); for (const [key, value] of entries) { if (["nivel", "valor", "territorio", "recompensa_xp", "recompensa_won", "objetivo"].includes(key) && (!Number.isSafeInteger(value) || value < 0)) throw new AdminError(CODES.INVALID_INPUT, `${key} inválido.`); if (table === "guildas" && key === "nivel" && (value < 1 || value > 10)) throw new AdminError(CODES.INVALID_INPUT, "Nível da guilda deve ficar entre 1 e 10."); } if (!ctx.dryRun) for (const [key, value] of entries) await ctx.query.run(`UPDATE ${table} SET ${key}=? WHERE id=?`, [value, row.id]); const before = Object.fromEntries(entries.map(([key]) => [key, row[key]])), after = Object.fromEntries(entries); return { entity: { type: targetKey, id: row.id, name: row.nome }, before, after, result: { success: true }, rollback: { kind: "fields", table, id: row.id, values: before } }; } }); }
module.exports = { registerCoreTools, positiveInteger, resourceTool, decreaseTool, setResourceTool, editTool };
