"use strict";
const fs = require("fs/promises"); const path = require("path"); const { execFile } = require("child_process"); const { promisify } = require("util"); const run = promisify(execFile); const { DeveloperError, CODES } = require("../errors");
function slug(value) { return String(value || "change").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48) || "change"; }
class GitManager {
    constructor(root, worktreeRoot) { this.root = path.resolve(root); this.worktreeRoot = path.resolve(worktreeRoot); }
    async git(args, cwd = this.root) { const result = await run("git", args, { cwd, maxBuffer: 10_000_000 }); return result.stdout.trim(); }
    async inspect() { try { const top = await this.git(["rev-parse", "--show-toplevel"]), branch = await this.git(["branch", "--show-current"]), status = await this.git(["status", "--porcelain=v1"]), branches = await this.git(["branch", "--format=%(refname:short)"]); const main = ["main", "master", "production"].find(name => branches.split(/\r?\n/).includes(name)) || branch; return { root: path.resolve(top), branch, main, dirty: Boolean(status), status: status.split(/\r?\n/).filter(Boolean) }; } catch (e) { throw new DeveloperError(CODES.GIT_REQUIRED, "O projeto precisa ser um repositório Git válido.", e.message); } }
    async createIsolation(task) { const info = await this.inspect(), kind = task.plan.classification.toLowerCase(), branch = `cardinal/${kind}/${slug(task.plan.target)}-${task.task_id.slice(0, 8)}`, worktree = path.join(this.worktreeRoot, task.task_id); if (path.resolve(worktree) === this.root) throw new DeveloperError(CODES.MAIN_PROTECTED, "Worktree não pode ser a raiz ativa."); await fs.mkdir(this.worktreeRoot, { recursive: true }); await this.git(["worktree", "add", "-b", branch, worktree, "HEAD"]); const baseCommit = await this.git(["rev-parse", "HEAD"], worktree); return { branch, worktree, baseCommit, sourceBranch: info.branch, mainBranch: info.main, sourceDirty: info.dirty }; }
    async assertIsolated(worktree) { const info = await this.inspect(), target = path.resolve(worktree); if (target === this.root || info.branch === info.main && target === info.root) throw new DeveloperError(CODES.MAIN_PROTECTED, "Edição direta da branch principal bloqueada."); const branch = await this.git(["branch", "--show-current"], target); if (!branch.startsWith("cardinal/")) throw new DeveloperError(CODES.MAIN_PROTECTED, "A branch não pertence ao namespace Cardinal."); return branch; }
    status(worktree) { return this.git(["status", "--porcelain=v1"], worktree); }
    diff(worktree) { return this.git(["diff", "--binary", "--no-ext-diff"], worktree); }
    async commit(worktree, message) { await this.assertIsolated(worktree); if (!/^(feat|fix|ui|docs|style|refactor|test|chore|security|db)\([a-z0-9-]+\): .{3,}$/i.test(message)) throw new Error("Mensagem de commit fora do padrão semântico."); await this.git(["add", "--all"], worktree); await this.git(["commit", "-m", message], worktree); return this.git(["rev-parse", "HEAD"], worktree); }
    async merge(branch, mainBranch) { const info = await this.inspect(); if (info.branch !== mainBranch || info.dirty) throw new DeveloperError(CODES.MAIN_PROTECTED, "Merge exige a branch principal limpa e selecionada."); if (!String(branch).startsWith("cardinal/")) throw new DeveloperError(CODES.MAIN_PROTECTED, "Somente branches Cardinal podem ser mescladas."); await this.git(["merge", "--no-ff", branch]); return this.git(["rev-parse", "HEAD"]); }
    async removeWorktree(worktree, branch) { const target = path.resolve(worktree); if (!target.startsWith(this.worktreeRoot + path.sep)) throw new DeveloperError(CODES.INVALID_PATH, "Worktree fora da área Cardinal."); await this.git(["worktree", "remove", "--force", target]); if (branch?.startsWith("cardinal/")) await this.git(["branch", "-D", branch]); }
    async revertMerged(commit, mainBranch) { const info = await this.inspect(); if (info.branch !== mainBranch || info.dirty) throw new DeveloperError(CODES.MAIN_PROTECTED, "Revert exige a branch principal limpa e selecionada."); await this.git(["revert", "--no-edit", commit]); return this.git(["rev-parse", "HEAD"]); }
}
module.exports = { GitManager, slug };
