"use strict";
const fs = require("fs"); const fsp = require("fs/promises"); const path = require("path"); const { spawn } = require("child_process");
function alive(pid) { if (!Number.isInteger(pid) || pid <= 0) return false; try { process.kill(pid, 0); return true; } catch { return false; } }
class LocalServiceAdapter {
    constructor(service) { this.service = service; }
    async pid() { try { const pid = Number((await fsp.readFile(this.service.pidFile, "utf8")).trim()); return alive(pid) ? pid : null; } catch { return null; } }
    async status() { const pid = await this.pid(), started = pid ? (await fsp.stat(this.service.pidFile)).mtimeMs : null; return { service: this.service.id, status: pid ? "ONLINE" : "OFFLINE", pid, uptime_ms: started ? Math.max(0, Date.now() - started) : null, port: this.service.port || null }; }
    command() { if (this.service.kind === "node") return { executable: this.service.executable, args: this.service.args }; if (this.service.kind === "npm") { const npmCli = process.platform === "win32" ? path.join(path.dirname(process.execPath), "node_modules/npm/bin/npm-cli.js") : null; return process.platform === "win32" ? { executable: process.execPath, args: [npmCli, "run", this.service.script] } : { executable: "npm", args: ["run", this.service.script] }; } if (this.service.kind === "llama") { const executable = path.join(this.service.cwd, "cardinal/runtime/llama.cpp/llama-server.exe"); if (!fs.existsSync(executable)) throw new Error("llama-server local autorizado não encontrado."); if (!this.service.modelPath || !fs.existsSync(this.service.modelPath) || !/\.gguf$/i.test(this.service.modelPath)) throw new Error("Modelo GGUF autorizado não encontrado."); if (!new Set(["127.0.0.1", "localhost", "::1"]).has(this.service.host) || this.service.contextSize > 8192) throw new Error("Configuração do modelo viola host local/limite de VRAM."); return { executable, args: ["-m", this.service.modelPath, "--no-mmproj", "-c", String(this.service.contextSize), "-ngl", String(this.service.gpuLayers), "--host", this.service.host, "--port", String(this.service.port)] }; } throw new Error("Tipo de serviço não registrado."); }
    async start() { const current = await this.status(); if (current.pid) return { ...current, duplicate: true }; await fsp.mkdir(path.dirname(this.service.pidFile), { recursive: true }); await fsp.mkdir(path.dirname(this.service.logFile), { recursive: true }); const cmd = this.command(), out = fs.openSync(this.service.logFile, "a"), child = spawn(cmd.executable, cmd.args, { cwd: this.service.cwd, detached: true, windowsHide: true, shell: false, stdio: ["ignore", out, out] }); child.unref(); await fsp.writeFile(this.service.pidFile, String(child.pid), "utf8"); return { service: this.service.id, status: "STARTING", pid: child.pid }; }
    async stop() { const pid = await this.pid(); if (!pid) return { service: this.service.id, status: "OFFLINE", alreadyStopped: true }; process.kill(pid, "SIGTERM"); const until = Date.now() + 5000; while (alive(pid) && Date.now() < until) await new Promise(resolve => setTimeout(resolve, 100)); if (alive(pid)) throw new Error("Shutdown limpo não foi concluído; encerramento forçado não é permitido."); await fsp.rm(this.service.pidFile, { force: true }); return { service: this.service.id, status: "OFFLINE", pid: null }; }
}
module.exports = { LocalServiceAdapter, alive };
