"use strict";
const {response}=require("../dto");const {label,printable,date,number}=require("../formatters");
const fields=object=>Object.entries(object||{}).filter(([k])=>!/password|token|secret|reasoning/i.test(k)).map(([k,v])=>({label:label(k),value:printable(v,k)})); const simple=(type,data={})=>response({type,module:data.module||"CORE",title:data.title||"CARDINAL",status:data.status||type,summary:data.summary||"",sections:data.sections||[],actions:data.actions||[],meta:data.meta||{}}); const info=data=>simple("INFO",data),success=data=>simple("SUCCESS",data),warning=data=>simple("WARNING",data),error=data=>simple("ERROR",{title:"CARDINAL INDISPONÍVEL",...data}),denied=()=>error({title:"CARDINAL",status:"DENIED",summary:"Acesso negado.",sections:[{title:"Permissão",lines:["Você não possui autorização para executar esta função."],fields:[]}],meta:{code:"CARDINAL_PERMISSION_DENIED"}});
function confirmation(data={}){return simple("CONFIRM",{module:data.module||"ADMIN",title:data.title||"ATENÇÃO — CARDINAL",status:data.risk||"HIGH",summary:data.summary||"Esta operação exige confirmação.",sections:[{title:"Impacto",fields:fields(data.impact),lines:data.lines||[]},{title:"Validade",fields:[{label:"Expira em",value:date(data.expiresAt)}],lines:[]}],actions:data.actions||[]});}
function forgeResult(draft={}){const entity=draft.draft||draft,content=entity.content||{},validation=entity.validation||{valid:false,errors:[],warnings:[]};return simple("FORGE_RESULT",{module:"FORGE",title:String(content.nome||entity.type||"ENTIDADE").toUpperCase(),status:validation.valid?"VALID":"INVALID",summary:`${entity.type||"Conteúdo"} • Draft ${entity.id||"—"}`,sections:[{title:"Ficha oficial",fields:fields(Object.fromEntries(Object.entries(content).filter(([k])=>k!=="nome"))),lines:[]},{title:"Validação",fields:[],lines:[validation.valid?"✓ Estrutura aprovada":"× Estrutura inválida",...(validation.errors||[]).map(e=>`× ${e.message||e}`),...(validation.warnings||[]).map(e=>`! ${e.message||e}`)]}],meta:{draftId:entity.id}});}
function adminResult(result={}){const before=result.before||{},after=result.after||{},change={};for(const key of new Set([...Object.keys(before),...Object.keys(after)])){const numeric=[before[key],after[key]].every(v=>v==null||Number.isFinite(Number(v)));change[label(key)]=numeric?`${number(before[key])} → ${number(after[key])}`:`${printable(before[key],key)} → ${printable(after[key],key)}`;}return simple("ADMIN_RESULT",{module:"ADMIN",title:String(result.entity?.name||result.entity?.id||"OPERAÇÃO").toUpperCase(),status:result.dry_run?"WARNING":"SUCCESS",summary:result.dry_run?"Simulação concluída; nada foi persistido.":"Operação concluída.",sections:[{title:"Operação",fields:[{label:"Ação",value:label(result.intent)},{label:"Transação",value:result.operation_id||"—"}],lines:[]},{title:"Alterações",fields:fields(change),lines:[]}],meta:{transactionId:result.operation_id}});}
function workflow(wf={}){const tasks=wf.tasks||[],done=tasks.filter(t=>["SUCCESS","COMPLETED"].includes(t.status)).length,total=tasks.length,progress=total?Math.round(done/total*100):0;return simple("WORKFLOW",{module:"WORKFLOW",title:wf.goal||"WORKFLOW CARDINAL",status:wf.status||"WAITING",summary:`Progresso ${progress}% (${done}/${total} etapas reais)`,sections:[{title:"Etapas",fields:[],lines:tasks.map(t=>`${["SUCCESS","COMPLETED"].includes(t.status)?"✓":t.status==="RUNNING"?"◉":"○"} ${t.name||t.id}: ${label(t.status)}`)},{title:"Controle",fields:[{label:"Workflow",value:wf.workflow_id||"—"},{label:"Risco",value:wf.risk||"—"}],lines:[]}],meta:{progress,workflowId:wf.workflow_id}});}
function developerChange(data={}){return simple("DEVELOPER_CHANGE",{module:"DEVELOPER",title:data.title||"ALTERAÇÃO DE CÓDIGO",status:data.status||"WAITING",summary:data.request||data.summary||"",sections:[{title:"Resumo",fields:[{label:"Branch",value:data.branch||"—"},{label:"Arquivos",value:(data.files||[]).length},{label:"Testes",value:data.tests||"—"},{label:"Build",value:data.build||"—"}],lines:(data.files||[]).slice(0,20)}],meta:{taskId:data.task_id}});}
function operationsStatus(data={}){const services=data.services||data.statuses||data;return simple("OPERATIONS_STATUS",{module:"OPERATIONS",title:"ESTADO DO SISTEMA",status:"INFO",summary:"Diagnóstico atual dos serviços.",sections:[{title:"Serviços",fields:Object.entries(services||{}).filter(([,v])=>typeof v!=="object"||v?.status).map(([k,v])=>({label:label(k),value:String(v?.status||v).toUpperCase()})),lines:[]}],meta:{checkedAt:data.checked_at}});}
function incident(data={}){return simple("INCIDENT",{module:"INCIDENTE",title:data.title||`${data.service||"SERVIÇO"} INDISPONÍVEL`,status:data.severity||"HIGH",summary:data.summary||"Uma falha operacional foi detectada.",sections:[{title:"Incidente",fields:fields({severidade:data.severity,detectado:data.detected_at,tentativas:data.attempts,status:data.status}),lines:[]}],meta:{incidentId:data.id}});}
function knowledgeResult(data={}){return simple("KNOWLEDGE_RESULT",{module:"KNOWLEDGE",title:"CONSULTA CARDINAL",status:data.status||"SUCCESS",summary:data.answer||data.summary||"",sections:[{title:"Pergunta",fields:[],lines:[data.question||"—"]},...(data.rule?[{title:"Regra oficial",fields:[],lines:[data.rule]}]:[])],meta:data.debug?{sources:data.sources||[]}:{}});}
module.exports={info,success,warning,error,denied,confirmation,forgeResult,adminResult,workflow,developerChange,operationsStatus,incident,knowledgeResult,fields};
