"use strict";
const TYPES = Object.freeze(["DOCS", "STYLE", "UI", "BUGFIX", "FEATURE", "REFACTOR", "DATABASE", "SECURITY", "INFRASTRUCTURE", "DEPLOYMENT"]);
function normalize(value) { return String(value || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); }
function classify(request) { const text = normalize(request); if (/deploy|producao|publicar servidor/.test(text)) return "DEPLOYMENT"; if (/segur|vulnerab|permiss/.test(text)) return "SECURITY"; if (/banco|tabela|coluna|schema|migration/.test(text)) return "DATABASE"; if (/bug|erro|quebrad|corrij|nao funciona/.test(text)) return "BUGFIX"; if (/refator|reestrutur/.test(text)) return "REFACTOR"; if (/pagina|layout|botao|responsiv|interface/.test(text)) return "UI"; if (/css|cor|fonte|estilo/.test(text)) return "STYLE"; if (/descri|texto|mensagem|tooltip|label|readme|document/.test(text)) return "DOCS"; return "FEATURE"; }
function targetOf(text) { const domains = ["banner", "inventario", "equipamento", "guilda", "dungeon", "missao", "jogador", "site", "bot", "comando", "banco"]; return domains.find(x => normalize(text).includes(x)) || "project"; }
function riskFor(type, request) { if (["SECURITY", "DEPLOYMENT"].includes(type) || /drop table|drop column|truncate|apagar tabela/i.test(request)) return "CRITICAL"; if (["DATABASE", "INFRASTRUCTURE"].includes(type)) return "HIGH"; if (["FEATURE", "REFACTOR", "BUGFIX"].includes(type)) return "MEDIUM"; return "LOW"; }
function large(request) { return String(request).length > 500 || /todo|inteiro|completo|reformule|reestruture.*sistema/i.test(request); }
function createDeveloperPlan(request, discoveries = {}) { const type = classify(request), target = targetOf(request), isLarge = large(request); return { intent: type.toLowerCase(), classification: type, target, request: String(request).trim(), files_expected: discoveries.files || [], database_change: type === "DATABASE", frontend_change: /site|pagina|layout|botao|inventario|equipamento/i.test(request), backend_change: !["DOCS", "STYLE"].includes(type), risk: riskFor(type, request), diagnosis_required: type === "BUGFIX", large_request: isLarge, stages: isLarge ? ["analysis", "database", "backend", "commands", "site", "tests", "documentation"] : ["analysis", "edit", "validation", "review"] }; }
module.exports = { TYPES, classify, riskFor, createDeveloperPlan };
