"use strict";
const fs = require("fs/promises"); const path = require("path"); const { execFile } = require("child_process"); const { promisify } = require("util"); const run = promisify(execFile); const { relativeSafe } = require("./protection");
class CodeSearch {
    constructor(root, options = {}) { this.root = root; this.limit = options.limit || 40; this.maxChars = options.maxChars || 24000; }
    async search(query, options = {}) { const pattern = String(query || "").trim(); if (!pattern || pattern.length > 200) throw new Error("Busca inválida."); const args = ["--json", "--hidden", "--glob", "!.git/**", "--glob", "!node_modules/**", "--glob", "!.next/**", "--glob", "!.env*", "--glob", "!*.gguf", "--glob", "!backups/**", "--glob", "!cardinal/cache/**", "--glob", "!cardinal/logs/**", pattern, "."]; try { const { stdout } = await run("rg", args, { cwd: this.root, maxBuffer: 2_000_000 }); return stdout.trim().split(/\r?\n/).filter(Boolean).map(JSON.parse).filter(x => x.type === "match").slice(0, options.limit || this.limit).map(x => ({ file: x.data.path.text.replace(/\\/g, "/").replace(/^\.\//, ""), line: x.data.line_number, text: x.data.lines.text.trim().slice(0, 500) })); } catch (e) { if (e.code === 1) return []; throw e; } }
    async findFiles(name) { const value = String(name || "").toLowerCase(); const { stdout } = await run("rg", ["--files", "--hidden", "-g", "!.git/**", "-g", "!node_modules/**", "-g", "!.next/**", "-g", "!.env*", "-g", "!*.gguf", "-g", "!backups/**"], { cwd: this.root, maxBuffer: 2_000_000 }); return stdout.split(/\r?\n/).filter(file => file.toLowerCase().includes(value)).slice(0, this.limit); }
    async findSymbol(symbol) { return this.search(`(?:function|class|const|let|var|interface|type)\\s+${String(symbol).replace(/[^\w$]/g, "") }\\b`); }
    async read(file, start = 1, lines = 160) { const safe = relativeSafe(this.root, file); if (/^\.env(?:\.|$)|credential|secret|token\.json|\.gguf$|(?:^|\/)backups?(?:\/|$)/i.test(safe.relative)) throw new Error(`Leitura de arquivo protegido bloqueada: ${safe.relative}.`); const content = await fs.readFile(safe.absolute, "utf8"), rows = content.split(/\r?\n/), count = Math.min(Math.max(Number(lines) || 160, 1), 300); return { file: safe.relative, start: Math.max(Number(start) || 1, 1), content: rows.slice(Math.max(start - 1, 0), Math.max(start - 1, 0) + count).join("\n").slice(0, this.maxChars) }; }
}
module.exports = { CodeSearch };
