"use strict";
const path = require("path"); const { loadDeveloperConfig } = require("./config"); const { DeveloperError, CODES } = require("./errors"); const { TaskStore } = require("./task-store"); const { DeveloperAudit } = require("./audit"); const { ProjectMap } = require("./project-map"); const { CodeSearch } = require("./search"); const { createDeveloperPlan } = require("./planner"); const { analyzeImpact } = require("./analyzer"); const { ControlledEditor } = require("./editor"); const { GitManager } = require("./git/manager"); const { SafeRunner } = require("./testing/runner"); const { DeveloperReviewer } = require("./review/reviewer"); const { DeveloperTools } = require("./tools");
function commitMessage(plan) { const prefix = { FEATURE: "feat", BUGFIX: "fix", UI: "ui", DOCS: "docs", STYLE: "style", REFACTOR: "refactor", DATABASE: "db", SECURITY: "security" }[plan.classification] || "chore"; return `${prefix}(${plan.target.replace(/[^a-z0-9-]/gi, "-").toLowerCase()}): ${plan.request.slice(0, 70)}`; }
class CardinalDeveloperService {
    constructor(options = {}) { this.config = loadDeveloperConfig(options); this.store = options.store || new TaskStore(this.config.statePath); this.audit = options.audit || new DeveloperAudit(this.config.auditPath); this.projectMap = options.projectMap || new ProjectMap(this.config.root, this.config.projectMapPath); this.rootSearch = options.search || new CodeSearch(this.config.root, { maxChars: this.config.maxContextChars }); this.git = options.git || new GitManager(this.config.root, this.config.worktreeRoot); this.reviewer = options.reviewer || new DeveloperReviewer(); this.authorize = options.authorize || (async () => true); this.reindex = options.reindex || null; this.knowledge = options.knowledge || null; }
    async plan(actor, request) { await this.authorize(actor, "CARDINAL_DEVELOPER"); const map = await this.projectMap.read(), target = createDeveloperPlan(request).target, hits = await this.rootSearch.search(target), files = [...new Set(hits.map(hit => hit.file))].slice(0, 12); let rpgSources = []; try { if (this.knowledge) rpgSources = (await this.knowledge.searchKnowledge(target, { limit: 5 })).map(item => ({ id: item.id, file: item.file, category: item.category, entity: item.entity })); } catch {} const basePlan = createDeveloperPlan(request, { files }), plan = { ...basePlan, impact: analyzeImpact(basePlan, files), code_knowledge: files, rpg_knowledge: rpgSources }; const task = await this.store.create({ actor, request, plan, files_consulted: files, project_map_generated_at: map.generated_at, fix_attempts: 0, bug_report: plan.diagnosis_required ? { issue: request, cause: null, affected_files: files, fix: null, tests: [] } : null }); await this.audit.record({ action: "plan", actor, task_id: task.task_id, request, plan, files_consulted: files }); return task; }
    async start(actor, id) { this.assertEnabled(); await this.authorize(actor, "CARDINAL_DEVELOPER"); const task = await this.store.get(id); if (task.status !== "PLANNED") throw new DeveloperError(CODES.INVALID_STATE, "A tarefa não está em PLANNED."); const isolation = await this.git.createIsolation(task), updated = await this.store.update(id, { ...isolation, status: "EDITING" }); await this.audit.record({ action: "start", actor, task_id: id, ...isolation }); return updated; }
    async edit(actor, id, patch) { this.assertEnabled(); await this.authorize(actor, "CARDINAL_DEVELOPER"); const task = await this.store.get(id); if (!task.worktree || !["EDITING", "FAILED"].includes(task.status)) throw new DeveloperError(CODES.INVALID_STATE, "Tarefa não está pronta para edição."); if (task.plan.diagnosis_required && !task.bug_report?.cause && !patch.diagnosis) throw new DeveloperError(CODES.VALIDATION_FAILED, "Bugfix exige diagnóstico da causa antes do patch."); const attempts = Number(task.fix_attempts || 0) + (task.status === "FAILED" ? 1 : 0); if (attempts > this.config.maxFixAttempts) throw new DeveloperError(CODES.VALIDATION_FAILED, "Limite de auto-fix atingido."); await this.git.assertIsolated(task.worktree); const editor = new ControlledEditor(task.worktree); let file; if (patch.operation === "create") file = await editor.create(patch.file, patch.content); else if (patch.operation === "rename") file = (await editor.rename(patch.file, patch.to)).to; else file = await editor.replace(patch.file, patch.expected, patch.replacement); const files = [...new Set([...(task.files || []), file])], bugReport = task.bug_report ? { ...task.bug_report, cause: task.bug_report.cause || patch.diagnosis, fix: patch.fix || `Patch localizado em ${file}` } : null, updated = await this.store.update(id, { files, status: "EDITING", fix_attempts: attempts, bug_report: bugReport }); await this.audit.record({ action: "edit", actor, task_id: id, operation: patch.operation || "replace", files_modified: [file], diagnosis: patch.diagnosis || null }); return updated; }
    async test(actor, id, requested) { await this.authorize(actor, "CARDINAL_DEVELOPER"); const task = await this.store.get(id); if (!task.worktree) throw new DeveloperError(CODES.INVALID_STATE, "Tarefa sem worktree."); await this.store.update(id, { status: "TESTING" }); const runner = new SafeRunner(task.worktree), detected = await runner.detect(), selected = requested?.length ? requested : this.selectChecks(task, detected), results = []; for (const tool of selected) results.push(await runner.run(tool)); const failed = results.some(result => !result.success), updated = await this.store.update(id, { status: failed ? "FAILED" : "TESTING", tests: [...(task.tests || []), ...results], detected }); await this.audit.record({ action: "test", actor, task_id: id, commands: results.map(x => x.command), tests: results.map(x => ({ tool: x.tool, success: x.success, exitCode: x.exitCode })) }); return updated; }
    selectChecks(task) { const checks = ["cardinal_test"]; if (task.plan.frontend_change) checks.push("site_lint", "site_build"); else if (/apps\/bot/.test((task.files || []).join(" "))) checks.push("bot_test"); return checks; }
    async review(actor, id) { await this.authorize(actor, "CARDINAL_DEVELOPER"); const task = await this.store.get(id); if (!task.worktree || !["TESTING", "READY_FOR_REVIEW", "FAILED"].includes(task.status)) throw new DeveloperError(CODES.INVALID_STATE, "Execute os testes antes da revisão."); const diff = await this.git.diff(task.worktree), review = this.reviewer.review(task, diff, task.tests || []), status = review.passed ? "READY_FOR_REVIEW" : "FAILED", updated = await this.store.update(id, { status, diff, diff_hash: review.diff_hash, review }); await this.audit.record({ action: "review", actor, task_id: id, diff_hash: review.diff_hash, files_modified: task.files, review }); return updated; }
    async approve(actor, id) { await this.authorize(actor, "CARDINAL_DEVELOPER_APPROVE"); let task = await this.store.get(id); if (task.status !== "READY_FOR_REVIEW" || !task.review?.passed) throw new DeveloperError(CODES.REVIEW_FAILED, "A mudança não está pronta para aprovação."); task = await this.store.update(id, { status: "APPROVED", approved_by: actor, approved_at: new Date().toISOString() }); let commit = task.commit; if (this.config.autoCommit) { commit = await this.git.commit(task.worktree, commitMessage(task.plan)); task = await this.store.update(id, { commit }); } if (this.config.autoMerge && ["LOW", "MEDIUM"].includes(task.risk) && commit) { const mergeCommit = await this.git.merge(task.branch, task.mainBranch); task = await this.store.update(id, { status: "MERGED", merge_commit: mergeCommit }); if (this.reindex) await this.reindex(task.files); } await this.audit.record({ action: "approve", actor, task_id: id, commit, merged: task.status === "MERGED", diff_hash: task.diff_hash }); return task; }
    async commit(actor, id) { await this.authorize(actor, "CARDINAL_DEVELOPER_APPROVE"); let task = await this.store.get(id); if (task.status !== "APPROVED") throw new DeveloperError(CODES.INVALID_STATE, "A tarefa precisa estar APPROVED."); const commit = await this.git.commit(task.worktree, commitMessage(task.plan)); task = await this.store.update(id, { commit }); await this.audit.record({ action: "commit", actor, task_id: id, commit }); return task; }
    async rollback(actor, id) { await this.authorize(actor, "CARDINAL_DEVELOPER_APPROVE"); let task = await this.store.get(id); if (task.status === "MERGED") { const revert = await this.git.revertMerged(task.merge_commit, task.mainBranch); task = await this.store.update(id, { status: "ROLLED_BACK", revert_commit: revert }); } else { if (task.worktree) await this.git.removeWorktree(task.worktree, task.branch); task = await this.store.update(id, { status: "ROLLED_BACK", worktree: null }); } await this.audit.record({ action: "rollback", actor, task_id: id, revert_commit: task.revert_commit || null }); return task; }
    async status(actor, id) { await this.authorize(actor, "CARDINAL_DEVELOPER"); return this.store.get(id); } async history(actor) { await this.authorize(actor, "CARDINAL_DEVELOPER"); return this.store.all(); } async diff(actor, id) { await this.authorize(actor, "CARDINAL_DEVELOPER"); const task = await this.store.get(id); return task.worktree ? this.git.diff(task.worktree) : task.diff || ""; }
    toolsFor(worktree = null) { const root = worktree || this.config.root, isolated = worktree && path.resolve(worktree).startsWith(this.config.worktreeRoot + path.sep); return new DeveloperTools({ search: new CodeSearch(root, { maxChars: this.config.maxContextChars }), projectMap: this.projectMap, git: this.git, editor: isolated ? new ControlledEditor(worktree) : null, runner: new SafeRunner(root) }); }
    assertEnabled() { if (!this.config.enabled) throw new DeveloperError(CODES.DISABLED, "Cardinal Developer está desabilitado. Ative CARDINAL_DEVELOPER_ENABLED=true conscientemente."); }
}
module.exports = { CardinalDeveloperService, commitMessage };
